---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: discordsh-n8n-hmac
    namespace: n8n
spec:
    encryptedData:
        N8N_HMAC_SECRET: AgAQkbZvy7vEbV5ZMVr2QTwUnqxYYp1VlIf/baXOlasebMCxtSeFTDUkcc4o0ZJcS7tyu1KRCB9yeFPje0fp5CZpMa5WAsEK4VqSuXU67BQtSK6lOkj2Yb7kW2pxLyzgDvTkOyLcorUjv+vyLbQVs9axEWHwRTBrkVu4QkUtS3DQrJbdbfNxJSsWFA7NWK4PNPWw37Mh0M1YpcmFMeYiuwMiuOtAKSJqYLj6IlAXBl2+A+Frw7GWM10RFtui52eSRSF81D1Teb78AIlamBThw47KEnNTpEnhjikp1MmhxWuXRvVSfNGMoNxDtaxRCzrwgDCDXUBF/9HixA5pEKxz3/A0wXwf22GuBxA6bLGas6d6MY2SV0G1iY+jS15NHFsRfgVNnQq2D2w7gRnlbDFFBqa7IZiFnpGGnzbgbMc592i2ox4urkTj4kcybWFUVRM+xhuwCE83lSyRUpEqlIEe+sxfY/raaShQhuBefsMRtjtc22/83T/pE0T8qY0EGktwuovTRvP7tz0nSEQiCQZI0MA2BjZOQGnphMsBAbnJt6j96yC6l9MI73MG2NqqDMVrVkMn6GYICtxPh8/dKl/CFvAfn7bymF4tTb/M0kkW7Jar6TkzY+pjsTzM9+/Sc8BmJKf8xiNA3lyT2ziJjUJopRBVztL0vra0lC9SwqPz10X5pmWOR5jB+A0cNXe8KsaQStHpYWLcyy7GZkS/8OowQnytkTA/rE1EvsTd93V1L9Lm22H4sJ3wFFHhJN4rVJKOai4XaG9d7g6KrIsNDzDHCZgt
    template:
        metadata:
            name: discordsh-n8n-hmac
            namespace: n8n
