---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: n8n-encryption-secret
    namespace: n8n
spec:
    encryptedData:
        encryption-key: AgCVpAHyel21qOr2VtjUWY5zpRgyxlHzlpRT1R15g4vyknTqoBnAnt6tRTF+yfSKSQJhiRDeuzlNHIZMDgMveLxr7LjPBPV/AY5xQVbd0NgWAZ8sEsEJ5z3b0eEBvsr6ccDcc01t4RBeHc6R9NdJore4XHkhGHUNXO6VpuaD/Vn7dvC8eY2QgN3CGpVheTBQuvIwUKJObyE/TJP7FkD99w8AXIPYldFys5r5FbQZ4wZfwGQQjGuM2gn5qrL338jQBH3UGBdeU4MsRlHGgunS4BP9RvoxmHND5Z7NEoM+SR3v+PVe1E4jGXXZyeiWvQMkPVS7WahMn/994pHtN1HD+Ci5JD90zivXCJGOdssX6gSwhBvA8MZZUOr/GS0TxzyLUjzBj+5K6H0cUHeUsWKMsN4BjK+055nu5pFvpQ/s7vRLXI1L3vwhj72tfynHgbI4oZqrksOv3qtEoJrbmAGqUZhbUPQaKcU9m+SQix0eKlXLWv8K5pOZN/9ydFZy9+VzXqvnYiWv1HTNVNuUYz73Wb7FtnXfy4dbbI9Wo5G+gKN1yq87pSRwSXftbFdo25eR3Am8ltbAOki2d1d7SFiKgsDubjh2VtbhNrp1cMy4FGDj+rpPx7OrxA+dBkF4LuRCuu4iJk8zNSXtXD0p0EgXMdjKNvqOOMfm4n+JCCZikv8GU7g+JB8jEu8T6lK+pgmRYQFPlrDNmaarz241WvdXS+WIeWHniS2fOs1IQF0BbJtI6A99EHHqNAOgGLATiqDssRaH+kZgCS3XunfUDm5qsvpA8A==
    template:
        metadata:
            name: n8n-encryption-secret
            namespace: n8n
