apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
    name: n8n-redis-trigger-auth
    namespace: n8n
spec:
    secretTargetRef:
        - parameter: password
          name: valkey-auth
          key: valkey-password
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
    name: n8n-worker-scaledobject
    namespace: n8n
    labels:
        app: n8n-worker
spec:
    scaleTargetRef:
        name: n8n-worker
    pollingInterval: 15
    cooldownPeriod: 300
    minReplicaCount: 1
    maxReplicaCount: 5
    triggers:
        - type: redis
          metadata:
              address: valkey.valkey.svc.cluster.local:6379
              listName: 'n8n-bull:jobs:wait'
              listLength: '5'
              activationListLength: '1'
              databaseIndex: '2'
              enableTLS: 'false'
          authenticationRef:
              name: n8n-redis-trigger-auth
