apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kbve
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KBVE/kbve
    targetRevision: HEAD
    path: apps/kube/kbve/manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: kbve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true