import os

import unreal

# Imports the rigged weapon FBX and its texture set from Art/Weapons/, builds the
# materials that sample them, and assigns them to the skeletal mesh. The source
# files live outside Content/ so the editor does not see them as loose files next
# to the assets they produced.
#
# Re-runnable: importing over an existing asset reimports it, and the materials
# are rebuilt from scratch each run, so this file -- not the binary uasset -- is
# the thing to edit.
#
# The FBX is generated by rig_weapon.py rather than authored; see the moon task
# `import-weapons` for the whole chain.
#
# Headless:
#   UnrealEditor-Cmd <project> -run=pythonscript -script="<abs path to this file>"

ASSET_TOOLS = unreal.AssetToolsHelpers.get_asset_tools()
EAL = unreal.EditorAssetLibrary
MEL = unreal.MaterialEditingLibrary

WEAPON_DIR = "/Game/Weapons"
TEXTURE_DIR = "/Game/Textures/Weapons"

STEM = "SK_Rifle_BoltAction762"

# suffix -> (sRGB, compression, sampler type)
MAPS = {
    "D": (
        True,
        unreal.TextureCompressionSettings.TC_DEFAULT,
        unreal.MaterialSamplerType.SAMPLERTYPE_COLOR,
    ),
    "N": (
        False,
        unreal.TextureCompressionSettings.TC_NORMALMAP,
        unreal.MaterialSamplerType.SAMPLERTYPE_NORMAL,
    ),
    "ORM": (
        False,
        unreal.TextureCompressionSettings.TC_MASKS,
        unreal.MaterialSamplerType.SAMPLERTYPE_MASKS,
    ),
    "Acc_D": (
        True,
        unreal.TextureCompressionSettings.TC_DEFAULT,
        unreal.MaterialSamplerType.SAMPLERTYPE_COLOR,
    ),
    "Acc_N": (
        False,
        unreal.TextureCompressionSettings.TC_NORMALMAP,
        unreal.MaterialSamplerType.SAMPLERTYPE_NORMAL,
    ),
    "Acc_ORM": (
        False,
        unreal.TextureCompressionSettings.TC_MASKS,
        unreal.MaterialSamplerType.SAMPLERTYPE_MASKS,
    ),
    "Acc_A": (
        False,
        unreal.TextureCompressionSettings.TC_MASKS,
        unreal.MaterialSamplerType.SAMPLERTYPE_MASKS,
    ),
}

# Material slot name on the imported mesh -> the material built for it. The names
# come from the Blender source, misspelling included: matching what the FBX
# actually carries matters more than spelling it correctly here.
SLOT_MATERIALS = {
    "bolt_action_rifle_7_62": f"{WEAPON_DIR}/M_Rifle762_Body",
    "bolt_action_rifle_7_62_accesories": f"{WEAPON_DIR}/M_Rifle762_Acc",
    "bolt_action_rifle_7_62_accesories_glass": f"{WEAPON_DIR}/M_Rifle762_Glass",
}


def source_dir():
    project = unreal.Paths.convert_relative_path_to_full(
        unreal.Paths.project_content_dir()
    )
    return os.path.join(project, os.pardir, "Art", "Weapons")


def import_texture(suffix):
    name = f"{STEM}_{suffix}"
    srgb, compression, _ = MAPS[suffix]
    png = os.path.join(source_dir(), name + ".png")
    if not os.path.isfile(png):
        unreal.log_error(f"missing source texture: {png}")
        return None

    task = unreal.AssetImportTask()
    task.filename = png
    task.destination_path = TEXTURE_DIR
    task.destination_name = name
    task.automated = True
    task.replace_existing = True
    task.save = True
    ASSET_TOOLS.import_asset_tasks([task])

    tex = EAL.load_asset(f"{TEXTURE_DIR}/{name}")
    if not isinstance(tex, unreal.Texture2D):
        unreal.log_error(f"import produced no Texture2D for {name}")
        return None

    tex.set_editor_property("srgb", srgb)
    tex.set_editor_property("compression_settings", compression)
    # A weapon is held at arm's length and aimed down; it is not a world surface
    # and should not share the world group's aggressive distance bias.
    tex.set_editor_property("lod_group", unreal.TextureGroup.TEXTUREGROUP_WEAPON)
    # Already flipped during ingest; flipping again would undo it.
    if compression == unreal.TextureCompressionSettings.TC_NORMALMAP:
        tex.set_editor_property("flip_green_channel", False)
    EAL.save_asset(f"{TEXTURE_DIR}/{name}")
    unreal.log(f"imported {name} (srgb={srgb})")
    return tex


def import_mesh():
    fbx = os.path.join(source_dir(), f"{STEM}.fbx")
    if not os.path.isfile(fbx):
        unreal.log_error(f"missing rigged mesh: {fbx}")
        return None

    options = unreal.FbxImportUI()
    options.set_editor_property("import_mesh", True)
    options.set_editor_property("import_as_skeletal", True)
    options.set_editor_property("import_animations", True)
    options.set_editor_property("import_materials", False)
    options.set_editor_property("import_textures", False)
    options.set_editor_property(
        "mesh_type_to_import", unreal.FBXImportType.FBXIT_SKELETAL_MESH
    )
    # Convex bodies around the weapon's own parts, built by the engine.
    #
    # The support hand needs something to close against, and every attempt to
    # supply that by hand has been a set of measured numbers per weapon -- a
    # fore-end modelled as an ellipse, its width, height and centre dialled in
    # against one rifle and wrong for the next. A physics asset is the same
    # information taken off the mesh, in the mesh's own frame, for any weapon
    # that imports. Nothing simulates: it is geometry to query.
    options.set_editor_property("create_physics_asset", True)

    mesh_data = options.skeletal_mesh_import_data
    # The source is metric at scale 1.0 and the FBX carries its own unit scale,
    # so nothing is rescaled here. Overriding it is how a rifle arrives either
    # a hundred times too big or a hundred times too small.
    mesh_data.set_editor_property("import_uniform_scale", 1.0)
    mesh_data.set_editor_property("convert_scene", True)
    mesh_data.set_editor_property("import_morph_targets", False)
    # Every vertex belongs to one bone at weight 1: a firearm has no deformation,
    # and normals computed from the source beat normals recomputed across the
    # hard edges a machined surface is mostly made of.
    mesh_data.set_editor_property(
        "normal_import_method",
        unreal.FBXNormalImportMethod.FBXNIM_IMPORT_NORMALS_AND_TANGENTS,
    )

    anim_data = options.anim_sequence_import_data
    anim_data.set_editor_property("import_bone_tracks", True)
    anim_data.set_editor_property(
        "animation_length", unreal.FBXAnimationLengthImportType.FBXALIT_EXPORTED_TIME
    )

    task = unreal.AssetImportTask()
    task.filename = fbx
    task.destination_path = WEAPON_DIR
    task.destination_name = STEM
    task.automated = True
    task.replace_existing = True
    task.save = True
    task.options = options
    ASSET_TOOLS.import_asset_tasks([task])

    mesh = EAL.load_asset(f"{WEAPON_DIR}/{STEM}")
    if not isinstance(mesh, unreal.SkeletalMesh):
        unreal.log_error(f"import produced no SkeletalMesh for {STEM}")
        return None
    unreal.log(f"imported {STEM}")
    return mesh


def expr(mat, cls, x, y):
    return MEL.create_material_expression(mat, cls, x, y)


def build_material(path, textures, prefix, masked):
    if EAL.does_asset_exist(path):
        EAL.delete_asset(path)

    pkg_dir, pkg_name = path.rsplit("/", 1)
    mat = ASSET_TOOLS.create_asset(
        pkg_name, pkg_dir, unreal.Material, unreal.MaterialFactoryNew()
    )

    def sample(suffix, y):
        name = f"{STEM}_{suffix}"
        s = expr(mat, unreal.MaterialExpressionTextureSampleParameter2D, -400, y)
        s.set_editor_property("parameter_name", name)
        s.set_editor_property("texture", textures[suffix])
        s.set_editor_property("sampler_type", MAPS[suffix][2])
        return s

    diff = sample(f"{prefix}D", -200)
    norm = sample(f"{prefix}N", 100)
    orm = sample(f"{prefix}ORM", 400)

    MEL.connect_material_property(diff, "RGB", unreal.MaterialProperty.MP_BASE_COLOR)
    MEL.connect_material_property(norm, "RGB", unreal.MaterialProperty.MP_NORMAL)
    # Packed as ambient occlusion, roughness, metallic -- one sample for three
    # inputs rather than three textures.
    MEL.connect_material_property(
        orm, "R", unreal.MaterialProperty.MP_AMBIENT_OCCLUSION
    )
    MEL.connect_material_property(orm, "G", unreal.MaterialProperty.MP_ROUGHNESS)
    MEL.connect_material_property(orm, "B", unreal.MaterialProperty.MP_METALLIC)

    # A material is refused by a skeletal mesh unless it says it expects to be
    # used on one, and the refusal is a warning rather than an error: the mesh
    # silently renders with the default grey instead. Every other check passes
    # -- the graph is wired, the textures are bound -- so the asset looks
    # correct everywhere except on screen.
    mat.set_editor_property("used_with_skeletal_mesh", True)

    if masked:
        # The sling and the scope housing share a sheet with cutout regions, so
        # this set is masked rather than opaque. Opaque would fill the gaps in
        # the strap with stretched texture.
        mat.set_editor_property("blend_mode", unreal.BlendMode.BLEND_MASKED)
        alpha = sample(f"{prefix}A", 700)
        MEL.connect_material_property(
            alpha, "R", unreal.MaterialProperty.MP_OPACITY_MASK
        )

    MEL.recompile_material(mat)
    EAL.save_asset(path)
    unreal.log(f"built {path}")
    return mat


def build_glass(path):
    if EAL.does_asset_exist(path):
        EAL.delete_asset(path)

    pkg_dir, pkg_name = path.rsplit("/", 1)
    mat = ASSET_TOOLS.create_asset(
        pkg_name, pkg_dir, unreal.Material, unreal.MaterialFactoryNew()
    )

    # The source ships no maps for the lens, so this is authored rather than
    # sampled: a dark, near-mirror surface, which is what a coated objective
    # reads as from outside. The view through it is not modelled.
    mat.set_editor_property("blend_mode", unreal.BlendMode.BLEND_TRANSLUCENT)
    mat.set_editor_property("two_sided", False)
    # See build_material: without this the scope lens renders as default grey.
    mat.set_editor_property("used_with_skeletal_mesh", True)

    base = expr(mat, unreal.MaterialExpressionConstant3Vector, -400, -200)
    base.set_editor_property("constant", unreal.LinearColor(0.02, 0.03, 0.05, 1.0))
    rough = expr(mat, unreal.MaterialExpressionConstant, -400, 100)
    rough.set_editor_property("r", 0.05)
    metal = expr(mat, unreal.MaterialExpressionConstant, -400, 250)
    metal.set_editor_property("r", 1.0)
    opacity = expr(mat, unreal.MaterialExpressionConstant, -400, 400)
    opacity.set_editor_property("r", 0.85)

    MEL.connect_material_property(base, "", unreal.MaterialProperty.MP_BASE_COLOR)
    MEL.connect_material_property(rough, "", unreal.MaterialProperty.MP_ROUGHNESS)
    MEL.connect_material_property(metal, "", unreal.MaterialProperty.MP_METALLIC)
    MEL.connect_material_property(opacity, "", unreal.MaterialProperty.MP_OPACITY)

    MEL.recompile_material(mat)
    EAL.save_asset(path)
    unreal.log(f"built {path}")
    return mat


def assign_materials(mesh):
    """Match built materials to the mesh's slots by the slot names the FBX carries."""
    materials = []
    for slot in mesh.get_editor_property("materials"):
        name = str(slot.get_editor_property("material_slot_name"))
        path = SLOT_MATERIALS.get(name)
        loaded = EAL.load_asset(path) if path else None
        if loaded is None:
            unreal.log_warning(f"no material built for slot {name}")
            materials.append(slot)
            continue
        slot.set_editor_property("material_interface", loaded)
        materials.append(slot)
        unreal.log(f"slot {name} -> {path}")
    mesh.set_editor_property("materials", materials)
    EAL.save_asset(f"{WEAPON_DIR}/{STEM}")


def main():
    textures = {}
    for suffix in MAPS:
        tex = import_texture(suffix)
        if tex is None:
            raise RuntimeError(f"texture import failed for {suffix}")
        textures[suffix] = tex

    mesh = import_mesh()
    if mesh is None:
        raise RuntimeError("mesh import failed")

    build_material(SLOT_MATERIALS["bolt_action_rifle_7_62"], textures, "", False)
    build_material(
        SLOT_MATERIALS["bolt_action_rifle_7_62_accesories"], textures, "Acc_", True
    )
    build_glass(SLOT_MATERIALS["bolt_action_rifle_7_62_accesories_glass"])

    assign_materials(mesh)
    unreal.log("weapon import complete")


main()
