apiVersion: v1
kind: ServiceAccount
metadata:
    name: nd-server-external-secrets
    namespace: nexus-defense
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
    name: kilobase-remote-secret-store
    namespace: nexus-defense
spec:
    provider:
        kubernetes:
            remoteNamespace: kilobase
            auth:
                serviceAccount:
                    name: nd-server-external-secrets
                    namespace: nexus-defense
            server:
                url: https://kubernetes.default.svc
                caProvider:
                    type: ConfigMap
                    name: kube-root-ca.crt
                    key: ca.crt
                    namespace: kube-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: nd-server-irc-bot
    namespace: nexus-defense
    labels:
        app.kubernetes.io/part-of: nexus-defense
spec:
    refreshInterval: 1h
    secretStoreRef:
        kind: SecretStore
        name: kilobase-remote-secret-store
    target:
        name: nd-server-irc-bot
        creationPolicy: Owner
        template:
            engineVersion: v2
            data:
                IRC_OPER_PASSWORD: '{{ .password }}'
    data:
        - secretKey: password
          remoteRef:
              key: irc-game-relay
              property: nd-bot-password
