apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      targetRevision: 1.9.1
      chart: longhorn
      helm:
        releaseName: longhorn
        valueFiles:
          - $values/apps/kube/storage/manifests/values.yaml
    - repoURL: https://github.com/kbve/kbve
      targetRevision: main
      ref: values
    - repoURL: https://github.com/kbve/kbve
      targetRevision: main
      path: apps/kube/storage/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true