[package]
name = "kilobase"
version = "17.4.1"
edition = "2021"
rust-version = "1.96"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg17"]
pg17 = ["pgrx/pg17", "pgrx-tests/pg17" ]
pg18 = ["pgrx/pg18", "pgrx-tests/pg18" ]
pg19 = ["pgrx/pg19", "pgrx-tests/pg19" ]
pg_test = []

[dependencies]
thiserror = "2.0.12"
pgrx = { version = "=0.19.2", default-features = false }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
pgrx-tests = "=0.19.2"
