apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 21.2.13
      chart: redis
      helm:
        releaseName: redis
        valueFiles:
          - $values/apps/kube/redis/manifests/values.yaml
    - repoURL: https://github.com/kbve/kbve
      targetRevision: main
      ref: values
    - repoURL: https://github.com/kbve/kbve
      targetRevision: main
      path: apps/kube/redis/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true