---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
    creationTimestamp: null
    name: cloudflare-api-token-secret
    namespace: cert-manager
spec:
    encryptedData:
        api-token: AgDLsUm7hMcZeJWdzu5O/+12MFggiOXkwbfp7N32ZekImQzupzMimVlgKJfYwcatWsDstMvtlq9reMpHVZ2cmRqJboV+neJYh7aFCBokxmRwboV/xMIRBVlkX2q6mqEygikwPA6LW3nYszSJY8dDPiMjbYZVlkfP7OSSbHM6pmCSRZN7WbuBP5p3mpgkBDYXSR4Bg0z6+2bUBoJzUdBUwyKxZkng6nTU6DOAFXjromVzrJCcZ9hIUFh1tMBgYYXMkwF2IWFPmE+TFvZTZMcDQCZf8MT+E5F3aV1XycfY9jPyy+ElqvwAc9PWv4TjkYteWs/Zml4mkOKsjMsawzOFvZPQWtd2FuJu1dh42sqrOuwF+G+FWjPUK8OG4VaZt3tiPLhHCa/4kdcosAz3SkYIzLs1nbTm/75pfO167vI8aapSnELq69EBH0cioeoLF77u6bHOwBZDQOc2h48i1G862JWg8QsRMNehIRMrqIqebpqPA1CU6oFgetPUAdJDRDlSGQGJRTdd+nSFY+NSXymXDAHyDUWaULCMNDewgyeWGvI8hPo5VgEPueLosrB70FpVoZKfPuFHj7AQLdeEBuxas8IW21XbzHl1vMfg7Zq6ZE0+8MZ4sVCCsjUONp82zA2eEbthpuc/kp9OQu81BdIAPRodJmY76VzXqfnhzkFgqQzzIf/rZTq6eWanXVxyovqffieIAIabssdLt1s6i+kJQjCGF8lpTF3sD9CnoxMPwuR49u7LgcPRPPnY
    template:
        metadata:
            annotations:
                sealedsecrets.bitnami.com/namespace-wide: 'true'
            creationTimestamp: null
            name: cloudflare-api-token-secret
            namespace: cert-manager
        type: Opaque
