/**
 * Generated by packages/data/codegen/gen-openapi-types.mjs
 * DO NOT EDIT — regenerate via:
 *   npx tsx packages/data/codegen/gen-openapi-types.mjs
 *
 * Source: packages/data/openapi/openapi.json (emit via
 *   `npx nx run axum-kbve:emit-openapi`)
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/status': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['api_status'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/game-token': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['game_token_handler'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/forum/c/{comment_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * DELETE /api/v1/forum/c/{comment_id} — staff remove.
		 *     axum checks staff at the JWT layer first, then forwards to the
		 *     `service_staff_remove_comment` RPC which re-checks at the SQL layer.
		 */
		delete: operations['api_remove_comment'];
		options?: never;
		head?: never;
		/**
		 * PATCH /api/v1/forum/c/{comment_id} — author edit-own.
		 *     SQL `service_edit_comment` re-checks author ownership.
		 */
		patch: operations['api_edit_comment'];
		trace?: never;
	};
	'/api/v1/forum/c/{comment_id}/moderate': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** PATCH /api/v1/forum/c/{comment_id}/moderate — staff overwrite body. */
		patch: operations['api_staff_edit_comment'];
		trace?: never;
	};
	'/api/v1/forum/spaces': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * GET /api/v1/forum/spaces — JSON list of active spaces.
		 *     Drives the astro-kbve build-time spaces.json artifact.
		 */
		get: operations['api_list_spaces'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/forum/t/{slug_or_id}/comments': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** POST /api/v1/forum/t/{slug_or_id}/comments — Bearer-authed comment. */
		post: operations['api_create_comment'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/forum/tags': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * GET /forum/tags — popularity-sorted tag listing.
		 *     GET /api/v1/forum/tags — JSON list of popularity-sorted tags.
		 *     Drives the astro-kbve build-time top-tags fetch.
		 */
		get: operations['api_list_tags'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/forum/threads': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * POST /api/v1/forum/threads — Bearer-authed thread creation.
		 *     Body: `{ space_slug, title, body, thread_type }`.
		 */
		post: operations['api_create_thread'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/mc/players': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * MC players API endpoint - returns online player list with UUIDs and skin URLs.
		 *     GET /api/v1/mc/players
		 * @description Data is cached and refreshed every 15s via RCON background task.
		 */
		get: operations['mc_players_handler'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/mc/textures/{hash}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * MC texture proxy - fetches skin PNGs from textures.minecraft.net.
		 *     GET /api/v1/mc/textures/{hash}
		 * @description Hash must be 60-64 hex characters. Responses are immutably cached (24h).
		 */
		get: operations['mc_texture_handler'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * GET /api/v1/me — Bearer-authed identity probe. Returns
		 *     `{user_id, username, is_staff}`. Used by the compose page to
		 *     gate the form (signed-in + has-username before submit) and by
		 *     any client surface that needs to mirror user state.
		 */
		get: operations['api_me'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/me/staff': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['api_me_staff'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/osrs/{item_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * OSRS API endpoint - returns item price data as JSON.
		 *     GET /api/v1/osrs/{item_id}
		 * @description Supports both numeric IDs (21012) and item names (dragon_hunter_crossbow).
		 *     Returns current GE prices from the cache (refreshed every 60s).
		 */
		get: operations['osrs_api_handler'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/profile/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Authenticated profile endpoint - returns the current user's profile.
		 *     GET /api/v1/profile/me
		 * @description Requires Bearer token in Authorization header.
		 */
		get: operations['profile_me_handler'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/profile/username': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Set username endpoint - creates username for authenticated user.
		 *     POST /api/v1/profile/username
		 * @description Requires Bearer token in Authorization header.
		 *     Body: { "username": "desired_username" }
		 *
		 *     Validates username at multiple levels:
		 *     1. Client-side validation (Handy app)
		 *     2. Axum-level validation (this endpoint)
		 *     3. Database-level validation (proxy_add_username RPC)
		 */
		post: operations['set_username_handler'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/profile/{username}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Profile API endpoint - returns user profile data as JSON.
		 *     GET /api/v1/profile/{username}
		 * @description Returns the user's profile data including connected accounts (Discord, GitHub, Twitch)
		 *     and enriched data from external APIs when available.
		 */
		get: operations['profile_api_handler'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/telemetry/report': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['report_handler'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['health'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ClientEvent: {
			/** @description Optional structured context (max 2KB serialized, depth <= 4). */
			context?: Record<string, never> | null;
			/** @description "warn" or "error" — INFO is rejected. */
			level: string;
			/** @description Human-readable message (max 512 chars). */
			message: string;
			/** @description Anonymous session id (alphanumeric, max 64 chars). */
			session_id?: string | null;
			/** @description Optional JS/WASM stack trace (max 4KB). */
			stack?: string | null;
		};
		CommentRow: {
			author_id: string;
			body: string;
			created_at: string;
			/** Format: int32 */
			depth: number;
			id: string;
			parent_comment_id?: string | null;
			/** Format: int64 */
			score: number;
			status: string;
			thread_id: string;
		};
		CreateCommentBody: {
			body: string;
			parent_comment_id?: string | null;
		};
		CreateThreadBody: {
			body: string;
			space_slug: string;
			thread_type?: string;
			title: string;
		};
		/** @description Discord-specific information extracted from provider data */
		DiscordInfo: {
			avatar_url?: string | null;
			/** @description User's nickname in the KBVE guild (if set) */
			guild_nickname?: string | null;
			id: string;
			/** @description Whether the user is boosting the server */
			is_boosting?: boolean | null;
			/** @description Whether the user is a member of the KBVE Discord guild */
			is_guild_member?: boolean | null;
			/** @description When the user joined the KBVE guild (ISO8601 timestamp) */
			joined_at?: string | null;
			/** @description Role IDs the user has in the KBVE guild */
			role_ids: string[];
			/** @description Role names resolved from role IDs (cached on server startup) */
			role_names: string[];
			username?: string | null;
		};
		EditCommentBody: {
			body: string;
			/**
			 * @description Optional moderator reason — only honored on the staff-edit /
			 *     staff-remove paths. Inline text, sanitized as a title-like field.
			 */
			reason?: string | null;
		};
		FeedRow: {
			author_id: string;
			body: string;
			/** Format: int32 */
			comment_count: number;
			created_at: string;
			/** Format: int64 */
			downvote_count: number;
			id: string;
			last_activity_at?: string | null;
			nsfw: boolean;
			pinned: boolean;
			/** Format: int64 */
			score: number;
			slug?: string | null;
			space_id: string;
			status: string;
			thread_type: string;
			title: string;
			/** Format: int64 */
			upvote_count: number;
			/** Format: int64 */
			view_count: number;
		};
		/** @description GitHub-specific information extracted from provider data */
		GithubInfo: {
			avatar_url?: string | null;
			id: string;
			username?: string | null;
		};
		HealthResponse: {
			status: string;
			version: string;
		};
		/** @description Appearance customization */
		RentEarthAppearance: {
			/** Format: int32 */
			body_height: number;
			/** Format: int32 */
			body_type: number;
			/** Format: int32 */
			eye_color: number;
			/** Format: int32 */
			eye_shape: number;
			/** Format: int32 */
			eyebrow_color: number;
			/** Format: int32 */
			eyebrow_style: number;
			/** Format: int32 */
			face_shape: number;
			/** Format: int32 */
			facial_hair_color: number;
			/** Format: int32 */
			facial_hair_style: number;
			/** Format: int32 */
			hair_color: number;
			/** Format: int32 */
			hair_style: number;
			/** Format: int32 */
			mouth_style: number;
			/** Format: int32 */
			nose_style: number;
			/** Format: int32 */
			scar_style: number;
			/** Format: int32 */
			skin_color: number;
			/** Format: int32 */
			tattoo_style: number;
			/** Format: int32 */
			voice_type: number;
		};
		/** @description Full character data (summary + details) */
		RentEarthCharacterFull: {
			appearance: components['schemas']['RentEarthAppearance'];
			core_stats: components['schemas']['RentEarthCoreStats'];
			derived_stats: components['schemas']['RentEarthDerivedStats'];
			position: components['schemas']['RentEarthPosition'];
			summary: components['schemas']['RentEarthCharacterSummary'];
		};
		/** @description Character summary from database (for character select display) */
		RentEarthCharacterSummary: {
			/** Format: int64 */
			archetype_flags: number;
			created_at?: string | null;
			current_zone: string;
			display_name: string;
			/** Format: int64 */
			experience: number;
			first_name: string;
			/** Format: int64 */
			gold: number;
			/** Format: int32 */
			health_current: number;
			/** Format: int32 */
			health_max: number;
			id: string;
			last_login_at?: string | null;
			/** Format: int32 */
			level: number;
			/** Format: int32 */
			slot: number;
			/** Format: int64 */
			total_playtime_seconds?: number | null;
			/** Format: int32 */
			visual_type: number;
		};
		/** @description Core stats (8 DND-inspired attributes) */
		RentEarthCoreStats: {
			/** Format: int32 */
			agility: number;
			/** Format: int32 */
			charisma: number;
			/** Format: int32 */
			constitution: number;
			/** Format: int32 */
			faith: number;
			/** Format: int32 */
			intelligence: number;
			/** Format: int32 */
			luck: number;
			/** Format: int32 */
			strength: number;
			/** Format: int32 */
			unspent_skill_points: number;
			/** Format: int32 */
			wisdom: number;
		};
		/** @description Derived stats (computed from core + equipment) */
		RentEarthDerivedStats: {
			/** Format: int32 */
			attack_power: number;
			/** Format: int32 */
			combat_rating: number;
			/** Format: float */
			crit_chance: number;
			/** Format: float */
			crit_damage: number;
			/** Format: int32 */
			defense: number;
			/** Format: int32 */
			health_current: number;
			/** Format: int32 */
			health_max: number;
			/** Format: int32 */
			magic_resist: number;
			/** Format: int32 */
			mana_current: number;
			/** Format: int32 */
			mana_max: number;
			/** Format: float */
			speed: number;
			/** Format: int32 */
			spell_power: number;
			/** Format: int32 */
			stamina_current: number;
			/** Format: int32 */
			stamina_max: number;
		};
		/** @description Position data */
		RentEarthPosition: {
			/** Format: float */
			rotation_yaw: number;
			/** Format: float */
			world_x: number;
			/** Format: float */
			world_y: number;
			/** Format: float */
			world_z: number;
		};
		/** @description Complete RentEarth profile for a user */
		RentEarthProfile: {
			active_character?:
				| null
				| components['schemas']['RentEarthCharacterFull'];
			characters: components['schemas']['RentEarthCharacterSummary'][];
			last_activity_at?: string | null;
			/** Format: int64 */
			total_playtime_seconds?: number | null;
		};
		/** @description Request body for setting username */
		SetUsernameRequest: {
			username: string;
		};
		SpaceRow: {
			description?: string | null;
			id: string;
			name: string;
			slug: string;
			status: string;
		};
		StatusResponse: {
			status: string;
			/** Format: int64 */
			uptime_seconds: number;
			version: string;
		};
		TagRow: {
			description?: string | null;
			/** Format: int32 */
			id: number;
			name: string;
			slug: string;
			/** Format: int64 */
			thread_count: number;
		};
		ThreadRow: {
			author_id: string;
			body: string;
			/** Format: int32 */
			comment_count: number;
			created_at: string;
			id: string;
			last_activity_at?: string | null;
			locked: boolean;
			nsfw: boolean;
			pinned: boolean;
			/** Format: int64 */
			score: number;
			slug?: string | null;
			space_id: string;
			status: string;
			thread_type: string;
			title: string;
		};
		TokenRequest: {
			/** @description Supabase JWT. Empty or absent for guest access. */
			jwt?: string | null;
			/**
			 * @description Preferred transport: "webtransport" or "websocket".
			 *     Controls the order of server addresses in the ConnectToken so
			 *     the Netcode handshake tries the right port first. Defaults to
			 *     "webtransport" for backward compatibility (Chrome prefers WT).
			 */
			transport?: string | null;
		};
		TokenResponse: {
			/** @description SHA-256 certificate digest (hex, 64 chars). Empty if using a trusted cert. */
			cert_digest: string;
			/**
			 * @description Certificate type: "trusted" (CA-signed, no hash pinning) or "self-signed"
			 *     (must use serverCertificateHashes with cert_digest). Empty if WT disabled.
			 */
			cert_type: string;
			/** @description The WebSocket URL the client should connect to. */
			server_url: string;
			/** @description The WebTransport (HTTPS/QUIC) URL. Empty if WT is not available. */
			server_wt_url: string;
			/** @description Base64-encoded ConnectToken (2048 bytes decoded). */
			token: string;
		};
		/** @description Twitch-specific information extracted from provider data */
		TwitchInfo: {
			avatar_url?: string | null;
			id: string;
			/** @description Whether the user is currently live streaming */
			is_live?: boolean | null;
			username?: string | null;
		};
		/** @description Aggregated user profile with all providers */
		UserProfile: {
			discord?: null | components['schemas']['DiscordInfo'];
			github?: null | components['schemas']['GithubInfo'];
			providers: components['schemas']['UserProvider'][];
			rentearth?: null | components['schemas']['RentEarthProfile'];
			twitch?: null | components['schemas']['TwitchInfo'];
			user_id: string;
			username: string;
		};
		/** @description User provider information from get_user_all_providers RPC */
		UserProvider: {
			avatar_url?: string | null;
			email?: string | null;
			identity_data?: Record<string, never> | null;
			last_sign_in_at?: string | null;
			linked_at?: string | null;
			provider: string;
			provider_id: string;
			username?: string | null;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	api_status: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service status with uptime */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StatusResponse'];
				};
			};
		};
	};
	game_token_handler: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['TokenRequest'];
			};
		};
		responses: {
			/** @description Netcode ConnectToken issued */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TokenResponse'];
				};
			};
			/** @description JWT invalid */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Token generation / DNS resolution failed */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	api_remove_comment: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Comment UUID */
				comment_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['EditCommentBody'];
			};
		};
		responses: {
			/** @description Removed — `{action_id, comment_id}` */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description RPC validation error */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Missing / invalid bearer token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Caller is not staff */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Upstream staff check error */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forum service not configured */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	api_edit_comment: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Comment UUID */
				comment_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['EditCommentBody'];
			};
		};
		responses: {
			/** @description Edit applied — `{comment_id}` */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description RPC validation / author mismatch */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Missing / invalid bearer token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forum service not configured */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	api_staff_edit_comment: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Comment UUID */
				comment_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['EditCommentBody'];
			};
		};
		responses: {
			/** @description Moderation edit applied — `{action_id, comment_id}` */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description RPC validation error */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Missing / invalid bearer token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Caller is not staff */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Upstream staff check error */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forum service not configured */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	api_list_spaces: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Active forum spaces */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Upstream forum DB error */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forum service not configured */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	api_create_comment: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Thread slug or UUID */
				slug_or_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateCommentBody'];
			};
		};
		responses: {
			/** @description Comment created — `{comment_id, thread_id}` */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description RPC validation error */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Missing / invalid bearer token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Thread not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Upstream forum DB error */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forum service not configured */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	api_list_tags: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Popularity-sorted tag list */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Upstream forum DB error */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forum service not configured */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	api_create_thread: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateThreadBody'];
			};
		};
		responses: {
			/** @description Thread created — `{thread_id}` */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description RPC validation error (title length / username required / etc) */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Missing / invalid bearer token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Space slug not found or inactive */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Upstream forum DB error */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Forum service not configured */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	mc_players_handler: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Currently-online Minecraft players (UUID + skin URL) */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description MC player service not configured (RCON env not set) */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	mc_texture_handler: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description 60-64 character hex texture hash from Mojang */
				hash: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description PNG skin texture */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'image/png': unknown;
				};
			};
			/** @description Invalid hash format */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Texture not found upstream */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description MC service not configured */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	api_me: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Caller identity probe (user_id, username, is_staff) */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Missing / invalid bearer token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	api_me_staff: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Staff role bundle for caller */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Missing / invalid bearer token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Upstream forum DB error */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	osrs_api_handler: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Numeric OSRS item id or kebab-case item name (e.g. `21012` or `dragon-hunter-crossbow`) */
				item_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current Grand Exchange price snapshot */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Item not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description OSRS price service unavailable */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	profile_me_handler: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Caller's profile (or basic auth info if no profile yet) */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Missing / invalid / expired token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Auth or profile service unavailable */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	set_username_handler: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SetUsernameRequest'];
			};
		};
		responses: {
			/** @description Username set successfully */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Invalid username format / body */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Missing / invalid / expired token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Username already taken */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Auth or profile service unavailable */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	profile_api_handler: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Public username (3-24 chars, alphanumeric + underscore, must start with letter) */
				username: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User profile with provider enrichment */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UserProfile'];
				};
			};
			/** @description Invalid username format */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Profile not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	report_handler: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ClientEvent'];
			};
		};
		responses: {
			/** @description Event accepted (no body) */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid level / message / encoding / nesting */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Payload too large (>8KB) */
			413: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Rate limited (>120 events/min globally) */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	health: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service liveness probe */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HealthResponse'];
				};
			};
		};
	};
}
