apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: argocd
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: argocd
    annotations:
        kbve.com/source-path: kube/argocd
        kbve.com/manifest-path: apps/kube/argocd/manifests
        kbve.com/application-file: kube/argocd/application.yaml
        kbve.com/managed-by: argocd
        kbve.com/schema-version: v1
        kbve.com/category: infrastructure
        kbve.com/stack: core
spec:
    project: default
    source:
        repoURL: https://github.com/kbve/kbve
        targetRevision: main
        path: apps/kube/argocd/manifests
    destination:
        server: https://kubernetes.default.svc
        namespace: argocd
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
        syncOptions:
            - CreateNamespace=true
            - ApplyOutOfSyncOnly=true
            - ServerSideApply=true
            - PruneLast=true
            - RespectIgnoreDifferences=true
    ignoreDifferences:
        - group: apps
          kind: Deployment
          name: argocd-server
          namespace: argocd
          jsonPointers:
              - /spec/template/spec/containers/0/image
