apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-management
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kbve/kbve
    targetRevision: main
    path: apps/kube/namespace/manifests
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false