export type ClipCategory =
	| 'Locomotion'
	| 'Combat'
	| 'Idle'
	| 'Emote'
	| 'Interact'
	| 'Other';

export interface ClipInfo {
	name: string;
	duration: number;
	category: ClipCategory;
}

export const CLIP_CATEGORIES: ClipCategory[] = [
	'Locomotion',
	'Combat',
	'Idle',
	'Emote',
	'Interact',
	'Other',
];

export const CLIPS: ClipInfo[] = [
	{ name: 'Chest_Open', duration: 1.38, category: 'Interact' },
	{ name: 'ClimbUp_1m_RM', duration: 0.67, category: 'Locomotion' },
	{ name: 'Consume', duration: 1.33, category: 'Interact' },
	{ name: 'Crouch_Fwd_Loop', duration: 2.5, category: 'Locomotion' },
	{ name: 'Crouch_Idle_Loop', duration: 3.67, category: 'Locomotion' },
	{ name: 'Dance_Loop', duration: 1.25, category: 'Emote' },
	{ name: 'Death_D', duration: 2.17, category: 'Combat' },
	{ name: 'Driving_Loop', duration: 2.08, category: 'Interact' },
	{ name: 'Farm_Harvest', duration: 2.33, category: 'Interact' },
	{ name: 'Farm_PlantSeed', duration: 2.79, category: 'Interact' },
	{ name: 'Farm_Watering', duration: 3.83, category: 'Interact' },
	{ name: 'Fixing_Kneeling', duration: 6.5, category: 'Interact' },
	{ name: 'Hit_Chest', duration: 0.42, category: 'Interact' },
	{ name: 'Hit_Head', duration: 0.54, category: 'Combat' },
	{ name: 'Hit_Knockback', duration: 0.83, category: 'Combat' },
	{ name: 'Hit_Knockback_RM', duration: 0.63, category: 'Combat' },
	{ name: 'Idle_FoldArms_Loop', duration: 2.5, category: 'Emote' },
	{ name: 'Idle_Lantern_Loop', duration: 2.5, category: 'Idle' },
	{ name: 'Idle_Loop', duration: 2.5, category: 'Idle' },
	{ name: 'Idle_No_Loop', duration: 2.5, category: 'Idle' },
	{ name: 'Idle_Rail_Call', duration: 2.5, category: 'Locomotion' },
	{ name: 'Idle_Rail_Loop', duration: 2.5, category: 'Locomotion' },
	{ name: 'Idle_Shield_Break', duration: 1.08, category: 'Combat' },
	{ name: 'Idle_Shield_Loop', duration: 2.0, category: 'Combat' },
	{ name: 'Idle_Talking_Loop', duration: 3.67, category: 'Emote' },
	{ name: 'Idle_TalkingPhone_Loop', duration: 2.92, category: 'Emote' },
	{ name: 'Idle_Torch_Loop', duration: 1.58, category: 'Idle' },
	{ name: 'Interact', duration: 2.5, category: 'Interact' },
	{ name: 'Jog_Fwd_Loop', duration: 0.93, category: 'Locomotion' },
	{ name: 'Jump_Land', duration: 1.27, category: 'Locomotion' },
	{ name: 'Jump_Loop', duration: 2.5, category: 'Locomotion' },
	{ name: 'Jump_Start', duration: 1.33, category: 'Locomotion' },
	{ name: 'LayToIdle', duration: 1.5, category: 'Locomotion' },
	{ name: 'Melee_Hook', duration: 0.37, category: 'Combat' },
	{ name: 'Melee_Hook_Rec', duration: 0.47, category: 'Combat' },
	{ name: 'NinjaJump_Idle_Loop', duration: 2.0, category: 'Locomotion' },
	{ name: 'NinjaJump_Land', duration: 1.25, category: 'Locomotion' },
	{ name: 'NinjaJump_Start', duration: 0.96, category: 'Locomotion' },
	{ name: 'OverhandThrow', duration: 1.33, category: 'Interact' },
	{ name: 'PickUp_Table', duration: 1.04, category: 'Interact' },
	{ name: 'Pistol_Aim_Down', duration: 0.21, category: 'Combat' },
	{ name: 'Pistol_Aim_Neutral', duration: 0.21, category: 'Combat' },
	{ name: 'Pistol_Aim_Up', duration: 0.21, category: 'Combat' },
	{ name: 'Pistol_Idle_Loop', duration: 2.08, category: 'Combat' },
	{ name: 'Pistol_Reload', duration: 2.08, category: 'Combat' },
	{ name: 'Pistol_Shoot', duration: 0.79, category: 'Combat' },
	{ name: 'Punch_Cross', duration: 1.0, category: 'Combat' },
	{ name: 'Punch_Jab', duration: 0.87, category: 'Combat' },
	{ name: 'Push_Loop', duration: 3.33, category: 'Interact' },
	{ name: 'Roll', duration: 1.83, category: 'Locomotion' },
	{ name: 'Roll_RM', duration: 1.83, category: 'Locomotion' },
	{ name: 'Shield_Dash_RM', duration: 1.08, category: 'Combat' },
	{ name: 'Shield_OneShot', duration: 0.83, category: 'Combat' },
	{ name: 'Sitting_Enter', duration: 1.63, category: 'Emote' },
	{ name: 'Sitting_Exit', duration: 1.29, category: 'Emote' },
	{ name: 'Sitting_Idle_Loop', duration: 2.08, category: 'Emote' },
	{ name: 'Sitting_Talking_Loop', duration: 3.67, category: 'Emote' },
	{ name: 'Slide_Exit', duration: 0.5, category: 'Locomotion' },
	{ name: 'Slide_Loop', duration: 2.0, category: 'Locomotion' },
	{ name: 'Slide_Start', duration: 0.83, category: 'Locomotion' },
	{ name: 'Spell_Simple_Enter', duration: 0.67, category: 'Combat' },
	{ name: 'Spell_Simple_Exit', duration: 0.54, category: 'Combat' },
	{ name: 'Spell_Simple_Idle_Loop', duration: 2.67, category: 'Combat' },
	{ name: 'Spell_Simple_Shoot', duration: 0.63, category: 'Combat' },
	{ name: 'Sprint_Loop', duration: 0.67, category: 'Locomotion' },
	{ name: 'Swim_Fwd_Loop', duration: 1.67, category: 'Locomotion' },
	{ name: 'Swim_Idle_Loop', duration: 4.17, category: 'Locomotion' },
	{ name: 'Sword_Attack', duration: 1.53, category: 'Combat' },
	{ name: 'Sword_Attack_RM', duration: 1.92, category: 'Combat' },
	{ name: 'Sword_Block', duration: 1.0, category: 'Combat' },
	{ name: 'Sword_Dash_RM', duration: 1.58, category: 'Combat' },
	{ name: 'Sword_Idle', duration: 1.67, category: 'Combat' },
	{ name: 'Sword_Regular_A', duration: 0.46, category: 'Combat' },
	{ name: 'Sword_Regular_A_Rec', duration: 0.96, category: 'Combat' },
	{ name: 'Sword_Regular_B', duration: 0.54, category: 'Combat' },
	{ name: 'Sword_Regular_B_Rec', duration: 1.0, category: 'Combat' },
	{ name: 'Sword_Regular_C', duration: 1.67, category: 'Combat' },
	{ name: 'Sword_Regular_C_RM', duration: 1.67, category: 'Combat' },
	{ name: 'Sword_Regular_Combo', duration: 2.96, category: 'Combat' },
	{ name: 'TreeChopping_Loop', duration: 0.96, category: 'Interact' },
	{ name: 'Walk_Carry_Loop', duration: 2.0, category: 'Locomotion' },
	{ name: 'Walk_Formal_Loop', duration: 1.67, category: 'Locomotion' },
	{ name: 'Walk_Loop', duration: 1.33, category: 'Locomotion' },
	{ name: 'Yes', duration: 2.5, category: 'Emote' },
	{ name: 'Zombie_Idle_Loop', duration: 1.33, category: 'Combat' },
	{ name: 'Zombie_Scratch', duration: 1.79, category: 'Combat' },
	{ name: 'Zombie_Walk_Fwd_Loop', duration: 1.33, category: 'Combat' },
];
