apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: supabase-vector
  namespace: kilobase
  labels:
    app: supabase-vector
    component: vector
spec:
  selector:
    matchLabels:
      app: supabase-vector
  template:
    metadata:
      labels:
        app: supabase-vector
        component: vector
    spec:
      serviceAccountName: vector
      containers:
      - name: vector
        image: timberio/vector:0.48.0-alpine
        ports:
        - containerPort: 9001
          name: api
        env:
        - name: VECTOR_SELF_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: LOGFLARE_PUBLIC_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: logflare-config
              key: public-access-token
        command: ["/usr/local/bin/vector", "--config", "/etc/vector/vector.yml"]
        volumeMounts:
        - name: vector-config
          mountPath: /etc/vector
          readOnly: true
        - name: var-log-pods
          mountPath: /var/log/pods
          readOnly: true
        - name: var-lib-docker-containers
          mountPath: /var/lib/docker/containers
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: 9001
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "6000m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      
      restartPolicy: Always
      volumes:
      - name: vector-config
        configMap:
          name: vector-config
      - name: var-log-pods
        hostPath:
          path: /var/log/pods
      - name: var-lib-docker-containers
        hostPath:
          path: /var/lib/docker/containers

---
apiVersion: v1
kind: Service
metadata:
  name: vector
  namespace: kilobase
  labels:
    app: supabase-vector
    component: vector
spec:
  type: ClusterIP
  ports:
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: api
  selector:
    app: supabase-vector