apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: supabase-vector
  namespace: vector
  labels:
    app: supabase-vector
    component: vector
spec:
  selector:
    matchLabels:
      app: supabase-vector
  template:
    metadata:
      labels:
        app: supabase-vector
        component: vector
    spec:
      serviceAccountName: vector
      containers:
      - name: vector
        image: timberio/vector:0.48.0-alpine
        ports:
        - containerPort: 9001
          name: api
        env:
        - name: VECTOR_SELF_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: VECTOR_SELF_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VECTOR_SELF_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROCFS_ROOT
          value: "/host/proc"
        - name: SYSFS_ROOT
          value: "/host/sys"
        - name: LOGFLARE_PUBLIC_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: logflare-config
              key: public-access-token
        args:
        - --config-dir
        - /etc/vector/
        volumeMounts:
        - name: vector-config
          mountPath: /etc/vector/
          readOnly: true
        - name: data
          mountPath: /vector-data-dir
        - name: var-log
          mountPath: /var/log/
          readOnly: true
        - name: var-lib
          mountPath: /var/lib
          readOnly: true
        - name: procfs
          mountPath: /host/proc
          readOnly: true
        - name: sysfs
          mountPath: /host/sys
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "6000m"
        securityContext:
          runAsUser: 0
          privileged: true
        livenessProbe:
          httpGet:
            path: /health
            port: 9001
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: vector-config
        projected:
          sources:
          - configMap:
              name: vector-config
      - name: data
        hostPath:
          path: /var/lib/vector
          type: DirectoryOrCreate
      - name: var-log
        hostPath:
          path: /var/log/
      - name: var-lib
        hostPath:
          path: /var/lib/
      - name: procfs
        hostPath:
          path: /proc
      - name: sysfs
        hostPath:
          path: /sys

---
apiVersion: v1
kind: Service
metadata:
  name: vector
  namespace: vector
  labels:
    app: supabase-vector
    component: vector
spec:
  type: ClusterIP
  ports:
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: api
  selector:
    app: supabase-vector