---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector
  namespace: vector
  labels:
    app: supabase-vector
    component: vector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-logs-reader
  labels:
    app: supabase-vector
    component: vector
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - namespaces
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-logs-reader
  labels:
    app: supabase-vector
    component: vector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector-logs-reader
subjects:
- kind: ServiceAccount
  name: vector
  namespace: vector