---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: reel-api
  namespace: reel
spec:
  encryptedData:
    REEL_API_TOKEN: AgByk6ZfbGB+b1CU/iFl01gK/rn0ZtM0JStlS8G2t7Ezy2UbepiRsQ85RrI6kKpbzg1LUN6WBJ0Z4ke5vVYNguNEgat5NG1pRlH9agSZXwnSnASAg3VWrqT0koG/0mnJTfwHoLkgFGPDM9A63UCzxz+PtRfinZlvyPelXsdC1jaV26zautFCXDPQdFKv5IvB9J9n5e7sLeGH8HUVs+JarYKUwAbn3xETtuOpFAU4szNZHOzH/A5X2B2Y/uIs5OI6+RGHwAPznBH/nkQHzF6JhF9rRb9ngw/UdRBWAi9H78WreNDLtmQQeCeODqcqFdRdSDZGAY0fkzXMXGEqV/H10UGb3/zbsgszlJLCsj7RAGDfocELDk/0318qKV2s2By+mv2zjbB05Abms2+pfg18ZvZzMdqhv9rYOEt+UKEA/2+qV7TDr+az2qzhmsXO/GS0eY22rL82kel9ByVE6ExdFMvbcmhxX2wSFFr2xIaVC+qqnjrHcvzy4Rh5KAOWlXM9iSPlsyk98TIcB8smK/K4dV4gZgOroWA0M1vcxH9/k2mUpNnxSDLR8H4wPHW/IaJFq5z+O4f2EBdm/qiJ0JRiSaWXBXH/++hrWL5Bra4l3Fur22XSoWJzG+xU41PJQlHcKYNFb3Liw4fmHJrhlDjQbg/YG4JnUNAQXPfeEFWmiaK4i//WRQ5CifAssa9/jPiu5aqEJYgyuh+qZpDQZK/R2EPOiBMZQLwgJMyMDE3lT21XQ2J50afBiL2shKUM7qvC/Ed67GJRgc3I+Jbp4PbtAueP
  template:
    metadata:
      name: reel-api
      namespace: reel
