---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: reel-vpn
    namespace: reel
spec:
    encryptedData:
        WIREGUARD_PRIVATE_KEY: REPLACE_WITH_KUBESEAL_OUTPUT
        WIREGUARD_ADDRESSES: REPLACE_WITH_KUBESEAL_OUTPUT
        VPN_SERVICE_PROVIDER: REPLACE_WITH_KUBESEAL_OUTPUT
        VPN_TYPE: REPLACE_WITH_KUBESEAL_OUTPUT
    template:
        metadata:
            name: reel-vpn
            namespace: reel
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: reel-api
    namespace: reel
spec:
    encryptedData:
        REEL_API_TOKEN: REPLACE_WITH_KUBESEAL_OUTPUT
    template:
        metadata:
            name: reel-api
            namespace: reel
