apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rows-rentearth-release

resources:
    - namespace.yaml
    - sealed-customer-guid.yaml
    - sealed-encryption-key.yaml
    - sealed-fleet-restart-token.yaml
    - ../../base

labels:
    - pairs:
          app.kubernetes.io/instance: rentearth-release
      includeSelectors: false

patches:
    - target:
          kind: Deployment
          name: rows
      patch: |-
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
                name: OWS_TENANT_SLUG
                value: rentearth-release
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
                name: OWS_ENV
                value: release
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
                name: AGONES_FLEET
                value: rows-rentearth-release
    - target:
          kind: Job
          name: rows-seed
      patch: |-
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
                name: CUSTOMER_NAME
                value: RentEarth
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
                name: CUSTOMER_EMAIL
                value: admin@rentearth.com
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
                name: MAP_NAME
                value: Lvl_Entry
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
                name: ZONE_NAME
                value: Origin
    - target:
          kind: Certificate
          name: rows-api-tls
      patch: |-
          - op: replace
            path: /spec/secretName
            value: rows-rentearth-release-api-tls
          - op: replace
            path: /spec/dnsNames/0
            value: api.rentearth.com
    - target:
          kind: HTTPRoute
          name: ows-api-routes
      patch: |-
          - op: replace
            path: /spec/hostnames/0
            value: api.rentearth.com
