replicaCount: 1

image:
    repository: ghcr.io/cloudnative-pg/cloudnative-pg
    tag: ''
    pullPolicy: IfNotPresent

webhook:
    port: 9443
    mutating:
        create: true
        failurePolicy: Fail
    validating:
        create: true
        failurePolicy: Fail

monitoring:
    enabled: true
    podMonitorEnabled: true
    podMonitor:
        enabled: true
        namespace: monitoring
        labels:
            release: prometheus

resources:
    requests:
        cpu: 100m
        memory: 200Mi
    limits:
        cpu: 500m
        memory: 500Mi

securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    capabilities:
        drop:
            - ALL

podSecurityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001

serviceAccount:
    create: true
    name: ''

config:
    data:
        INHERITED_ANNOTATIONS: ''
        INHERITED_LABELS: ''
        WATCH_NAMESPACE: ''

nodeSelector: {}
affinity: {}
tolerations: []

logLevel: info
