---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: valkey-auth
    namespace: valkey
spec:
    encryptedData:
        valkey-password: AgAwZY3UHO4xUPnbYBokn/fJc2VfB5dBESIjhPqd6PPutPl8dv6ziMYBcugci5+SwrS96qNcBgqT716oeBSyAbTozf6rryRT6j+TZVvu6xNTOv0KwmCD5Qkv4EpjI0kSVYVNqF/BY1dsHPxoSnjy/6ho64F3wUqcKp+bvokH1H4HvZnjmoEcUL2hoClldSIcldFqTjss1f7Dc+t1I+Jn1xfQK45v9NLhVaG2RjtB88S8HXJFIWO5Ac61cqueWDmRIaxdzw2ir/8CjG2+A7Hlg+/76i/TnIzdC/+dAqpG65M92mm0iDliaUZugqXT4DeBys6vTNqYPr2DjX6WCEoETWqMp+1d80ORWIohKM7C6exSESX9okcB80CnUUSJ9bPlHM4WlZtt3v5OqZx1pMW8+J0ptebAJjiNctYP/+vsnsuQIgMJuBNelQ/fcDx1pJ4aEG8lwOgBpmFWGuehoApUvoL3A589AhRldLOV7DFS6g4UhhYNhz9RsJGRiNUeE7lB30rUvuVSJ6sc3agr/JETo30lo+g8pU+KJ9UMzxoCtVQC+cIJDHBpBEV0lbcwjWr4uY3GPvcp5NBr632QOfhyKj5Pgud+iPzFpOM2nWLaXo64DuH7hgT0HIf092t7tvpaiPvR/pKgLGEr6D9ZL3GvnuwFQ6qggGawjam1QPMnV3b6ymiyOOT0ybOxB3YxDQSSRMDSAHsLaPST9vKps+wG2PkVob4WNve2VLfwTG7eFzPFgbCUvQfyJ1zEJ7D8LLVwmjEvgMXzdA0JLtba6QU1ClVn
    template:
        metadata:
            name: valkey-auth
            namespace: valkey
