// <auto-generated/>
// Generated by packages/data/codegen/gen-rareicon-mapdb.mjs
// Source: apps/kbve/astro-kbve/src/content/docs/mapdb/*.mdx
// Regenerate via: npx nx run astro-kbve:sync:rareicon-mapdb
// Do not edit by hand.

namespace RareIcon
{
    /// <summary>FNV-1a 32-bit hashes of each mdx entry's `ref` slug.
    /// Runtime keys for MapdbSingleton + BuildingPrefabRegistry lookups. Burst-friendly (uint, zero allocations).</summary>
    public static class MapdbRefs
    {

        // resource_node (16)
        public const uint AdamantineVein           = 0xFB42BC64u;  // adamantine-vein
        public const uint CoalVein                 = 0x5BF6A1ABu;  // coal-vein
        public const uint CobaltVein               = 0x74695033u;  // cobalt-vein
        public const uint CopperVein               = 0xF9769079u;  // copper-vein
        public const uint GoldVein                 = 0xAD7A1FC0u;  // gold-vein
        public const uint IronVein                 = 0xFAC8EF08u;  // iron-vein
        public const uint JadeCrystal              = 0x9099E1E8u;  // jade-crystal
        public const uint MithrilVein              = 0xFE043B8Bu;  // mithril-vein
        public const uint OakTree                  = 0xB938E0FDu;  // oak-tree
        public const uint QuietSpring              = 0xD4EA7C1Bu;  // quiet-spring
        public const uint RedwoodTree              = 0x28AC4C44u;  // redwood-tree
        public const uint RubyCrystal              = 0x09381CA2u;  // ruby-crystal
        public const uint SaltVein                 = 0xC2A89F6Au;  // salt-vein
        public const uint SapphireCrystal          = 0xAAA8660Cu;  // sapphire-crystal
        public const uint SilverVein               = 0xD8E0DD0Du;  // silver-vein
        public const uint UraniumVein              = 0x8914FA57u;  // uranium-vein

        // building (11)
        public const uint Barracks                 = 0xD1ED70FEu;  // barracks
        public const uint Capital                  = 0xE12037ABu;  // capital
        public const uint Dock                     = 0x40EB5A9Au;  // dock
        public const uint Farm                     = 0xFD902939u;  // farm
        public const uint Furnace                  = 0x42BC02A3u;  // furnace
        public const uint GoblinCave               = 0xFE4B61CCu;  // goblin-cave
        public const uint Inn                      = 0x9BE987D0u;  // inn
        public const uint Lumbercamp               = 0x97ED8E1Fu;  // lumbercamp
        public const uint Market                   = 0xB5F82E71u;  // market
        public const uint MiningPit                = 0x858630A1u;  // mining-pit
        public const uint Outpost                  = 0x4B40DE91u;  // outpost

        // npc_marker (2)
        public const uint DustyBazaar              = 0x53606820u;  // dusty-bazaar
        public const uint WanderersNook            = 0x5E452D56u;  // wanderers-nook

        // settlement (3)
        public const uint DwarvenOutpost           = 0xBFE58B27u;  // dwarven-outpost
        public const uint MushroomBazaar           = 0x9094A889u;  // mushroom-bazaar
        public const uint SunkenMarket             = 0x028AD358u;  // sunken-market

        // landmark (3)
        public const uint MirrorChamber            = 0x7D791549u;  // mirror-chamber
        public const uint TheStillPool             = 0xB1ACAA1Cu;  // the-still-pool
        public const uint WhisperingHall           = 0x4FF76AF5u;  // whispering-hall

        // arena (2)
        public const uint PrismaticThrone          = 0xCCB79FB8u;  // prismatic-throne
        public const uint ShatteredCrown           = 0xB127B5F9u;  // shattered-crown
    }
}
