// <auto-generated/>
// Source: packages/data/codegen/gen-itemdb-atlas.mjs
// Regenerate: npx nx run astro-kbve:sync:itemdb-atlas

using Unity.Mathematics;

namespace RareIcon
{
    public static class ItemSpriteAtlas
    {
        public const int   AtlasSize    = 2048;
        public const int   TileSize     = 64;
        public const int   TilesPerRow  = 32;
        public const float TileNormSize = 0.03125000f;

        public static readonly float4 FallbackUV = new float4(0f, 0f, 0.03125000f, 0.03125000f);

        // Identity mapping: slot index == item key. UV(key) = (key%32, key/32) * TileNormSize.
        public static float4 GetUV(ushort itemId)
        {
            if (itemId == 0 || itemId >= 1024) return FallbackUV;
            int col = itemId % 32;
            int row = itemId / 32;
            return new float4(col * TileNormSize, row * TileNormSize, TileNormSize, TileNormSize);
        }
    }
}
