apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mc-world-data
    namespace: mc
    labels:
        app: mc
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 10Gi
