apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: nginx-ingress
data:
  1935: "restream/restreamer-tcp:1935"
  1936: "restream/restreamer-tcp:1936"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: nginx-ingress
data:
  6000: "restream/restreamer-udp:6000"