apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restreamer-config
  namespace: restream
  labels:
    app: restreamer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restreamer-data
  namespace: restream
  labels:
    app: restreamer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path