apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
    name: elasticsearch
    namespace: elastic-stack
    labels:
        kbve.sh/app: elk
        kbve.sh/component: elasticsearch
    annotations:
        kbve.sh/last-updated: '2026-03-20'
        kbve.sh/rollout-restart: '2026-03-20T00:00:00Z'
spec:
    version: 8.19.13
    nodeSets:
        - name: default
          count: 1
          config:
              node.store.allow_mmap: false
          podTemplate:
              spec:
                  containers:
                      - name: elasticsearch
                        resources:
                            limits:
                                cpu: '2'
                                memory: 4Gi
                            requests:
                                cpu: 500m
                                memory: 2Gi
          volumeClaimTemplates:
              - metadata:
                    name: elasticsearch-data
                spec:
                    accessModes:
                        - ReadWriteOnce
                    resources:
                        requests:
                            storage: 50Gi
                    storageClassName: longhorn
