apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: rentearth
    namespace: argocd
    annotations:
        kbve.com/source-path: kube/rentearth
        kbve.com/manifest-path: apps/kube/rentearth/manifest
        kbve.com/application-file: kube/rentearth/application.yaml
        kbve.com/managed-by: argocd
        kbve.com/schema-version: v1
        kbve.com/category: application
        kbve.com/stack: core
        argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
    project: default
    source:
        repoURL: https://github.com/KBVE/kbve
        targetRevision: HEAD
        path: apps/kube/rentearth/manifest
    destination:
        server: https://kubernetes.default.svc
        namespace: rentearth
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
            - PrunePropagationPolicy=foreground
            - PruneLast=true
            - RespectIgnoreDifferences=true
            - Replace=false
