// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MediaAttachment {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub media_type: i32,
    #[prost(string, tag = "3")]
    pub caption: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Vertical {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub slug: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub label: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub status: i32,
    #[prost(int32, tag = "6")]
    pub sort_order: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Taxonomy {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(uint64, tag = "2")]
    pub vertical_id: u64,
    #[prost(int32, tag = "3")]
    pub kind: i32,
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub label: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub status: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MembershipApplication {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub user_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "3")]
    pub requested_capabilities: i32,
    #[prost(uint64, repeated, tag = "4")]
    pub vertical_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(string, tag = "5")]
    pub statement: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "6")]
    pub portfolio_links: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, tag = "7")]
    pub status: i32,
    #[prost(bytes = "vec", tag = "8")]
    pub reviewed_by: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "9")]
    pub reviewed_at: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub review_notes: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub created_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TalentProfile {
    #[prost(bytes = "vec", tag = "1")]
    pub user_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub headline: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub years_experience: i32,
    #[prost(int32, tag = "4")]
    pub availability: i32,
    #[prost(int64, tag = "5")]
    pub rate_min: i64,
    #[prost(int64, tag = "6")]
    pub rate_max: i64,
    #[prost(string, tag = "7")]
    pub currency: ::prost::alloc::string::String,
    #[prost(uint64, repeated, tag = "8")]
    pub vertical_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag = "9")]
    pub discipline_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag = "10")]
    pub tool_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag = "11")]
    pub skill_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(string, tag = "12")]
    pub updated_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClientProfile {
    #[prost(bytes = "vec", tag = "1")]
    pub user_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub org_name: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub company_size: i32,
    #[prost(string, tag = "4")]
    pub website: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub about: ::prost::alloc::string::String,
    #[prost(uint64, repeated, tag = "6")]
    pub vertical_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(string, tag = "7")]
    pub updated_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PortfolioItem {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub user_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub vertical_id: u64,
    #[prost(string, tag = "4")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub source: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "7")]
    pub media: ::prost::alloc::vec::Vec<MediaAttachment>,
    #[prost(uint64, repeated, tag = "8")]
    pub tag_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(int32, tag = "9")]
    pub sort_order: i32,
    #[prost(string, tag = "10")]
    pub created_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Gig {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub poster_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub vertical_id: u64,
    #[prost(string, tag = "4")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub summary: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub description: ::prost::alloc::string::String,
    #[prost(uint64, repeated, tag = "7")]
    pub discipline_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag = "8")]
    pub tool_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag = "9")]
    pub skill_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(enumeration = "BudgetType", tag = "10")]
    pub budget_type: i32,
    #[prost(int64, tag = "11")]
    pub budget_min: i64,
    #[prost(int64, tag = "12")]
    pub budget_max: i64,
    #[prost(string, tag = "13")]
    pub currency: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub deadline: ::prost::alloc::string::String,
    #[prost(int32, tag = "15")]
    pub location_pref: i32,
    #[prost(int32, tag = "16")]
    pub status: i32,
    #[prost(string, tag = "17")]
    pub published_at: ::prost::alloc::string::String,
    #[prost(string, tag = "18")]
    pub updated_at: ::prost::alloc::string::String,
    #[prost(string, tag = "19")]
    pub created_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Application {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub gig_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub applicant_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub cover_message: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub proposed_rate: i64,
    #[prost(enumeration = "BudgetType", tag = "6")]
    pub proposed_rate_type: i32,
    #[prost(bytes = "vec", repeated, tag = "7")]
    pub portfolio_item_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(int32, tag = "8")]
    pub status: i32,
    #[prost(string, tag = "9")]
    pub created_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Engagement {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub gig_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub poster_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub taker_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "5")]
    pub status: i32,
    #[prost(string, tag = "6")]
    pub started_at: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub completed_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Review {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub engagement_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub reviewer_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub reviewee_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "5")]
    pub rating: i32,
    #[prost(string, tag = "6")]
    pub body: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub created_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Conversation {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub gig_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub created_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConversationParticipant {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub conversation_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub user_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub joined_at: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub left_at: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "6")]
    pub last_read_message_id: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub conversation_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub sender_participant_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub body: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub attachments: ::prost::alloc::vec::Vec<MediaAttachment>,
    #[prost(string, tag = "6")]
    pub created_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Notification {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub user_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "3")]
    pub kind: i32,
    #[prost(bytes = "vec", tag = "4")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "5")]
    pub read_at: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub created_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Report {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub reporter_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "3")]
    pub target_kind: i32,
    #[prost(string, tag = "4")]
    pub target_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub reason: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub status: i32,
    #[prost(string, tag = "7")]
    pub created_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuditLog {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub actor_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub action: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub target_kind: i32,
    #[prost(string, tag = "5")]
    pub target_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "6")]
    pub detail: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "7")]
    pub created_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ById {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ByLookup {
    #[prost(uint64, tag = "1")]
    pub id: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ByUser {
    #[prost(bytes = "vec", tag = "1")]
    pub user_id: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ack {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Capability {
    CapNone = 0,
    CapTaker = 1,
    CapPoster = 2,
    CapAdmin = 4,
}
impl Capability {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::CapNone => "CAP_NONE",
            Self::CapTaker => "CAP_TAKER",
            Self::CapPoster => "CAP_POSTER",
            Self::CapAdmin => "CAP_ADMIN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CAP_NONE" => Some(Self::CapNone),
            "CAP_TAKER" => Some(Self::CapTaker),
            "CAP_POSTER" => Some(Self::CapPoster),
            "CAP_ADMIN" => Some(Self::CapAdmin),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GigStatus {
    GigDraft = 0,
    GigPendingReview = 1,
    GigOpen = 2,
    GigFilled = 4,
    GigClosed = 8,
    GigExpired = 16,
}
impl GigStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::GigDraft => "GIG_DRAFT",
            Self::GigPendingReview => "GIG_PENDING_REVIEW",
            Self::GigOpen => "GIG_OPEN",
            Self::GigFilled => "GIG_FILLED",
            Self::GigClosed => "GIG_CLOSED",
            Self::GigExpired => "GIG_EXPIRED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GIG_DRAFT" => Some(Self::GigDraft),
            "GIG_PENDING_REVIEW" => Some(Self::GigPendingReview),
            "GIG_OPEN" => Some(Self::GigOpen),
            "GIG_FILLED" => Some(Self::GigFilled),
            "GIG_CLOSED" => Some(Self::GigClosed),
            "GIG_EXPIRED" => Some(Self::GigExpired),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ApplicationStatus {
    AppSubmitted = 0,
    AppShortlisted = 1,
    AppAccepted = 2,
    AppDeclined = 3,
    AppWithdrawn = 4,
}
impl ApplicationStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::AppSubmitted => "APP_SUBMITTED",
            Self::AppShortlisted => "APP_SHORTLISTED",
            Self::AppAccepted => "APP_ACCEPTED",
            Self::AppDeclined => "APP_DECLINED",
            Self::AppWithdrawn => "APP_WITHDRAWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "APP_SUBMITTED" => Some(Self::AppSubmitted),
            "APP_SHORTLISTED" => Some(Self::AppShortlisted),
            "APP_ACCEPTED" => Some(Self::AppAccepted),
            "APP_DECLINED" => Some(Self::AppDeclined),
            "APP_WITHDRAWN" => Some(Self::AppWithdrawn),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EngagementStatus {
    EngActive = 0,
    EngCompleted = 1,
    EngCancelled = 2,
}
impl EngagementStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::EngActive => "ENG_ACTIVE",
            Self::EngCompleted => "ENG_COMPLETED",
            Self::EngCancelled => "ENG_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ENG_ACTIVE" => Some(Self::EngActive),
            "ENG_COMPLETED" => Some(Self::EngCompleted),
            "ENG_CANCELLED" => Some(Self::EngCancelled),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BudgetType {
    BudgetUnspecified = 0,
    BudgetFixed = 1,
    BudgetRange = 2,
    BudgetHourly = 3,
}
impl BudgetType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::BudgetUnspecified => "BUDGET_UNSPECIFIED",
            Self::BudgetFixed => "BUDGET_FIXED",
            Self::BudgetRange => "BUDGET_RANGE",
            Self::BudgetHourly => "BUDGET_HOURLY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BUDGET_UNSPECIFIED" => Some(Self::BudgetUnspecified),
            "BUDGET_FIXED" => Some(Self::BudgetFixed),
            "BUDGET_RANGE" => Some(Self::BudgetRange),
            "BUDGET_HOURLY" => Some(Self::BudgetHourly),
            _ => None,
        }
    }
}
