apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: realtime-image-loader
  namespace: kilobase
  labels:
    app: realtime-image-loader
spec:
  selector:
    matchLabels:
      app: realtime-image-loader
  template:
    metadata:
      labels:
        app: realtime-image-loader
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists  # Run on all nodes
      containers:
      - name: image-loader
        image: docker:24-cli
        command:
        - sh
        - -c
        - |
          echo "Waiting for image tar file..."
          while [ ! -f /shared-storage/kbve-realtime.tar ]; do
            echo "Image tar not found, waiting..."
            sleep 10
          done
          
          echo "Loading image into Docker daemon..."
          docker load -i /shared-storage/kbve-realtime.tar
          
          echo "Image loaded successfully!"
          docker images | grep kbve-realtime
          
          echo "Image loader completed on node $(hostname)"
          
          # Keep the pod running
          sleep infinity
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: shared-storage
          mountPath: /shared-storage
        securityContext:
          privileged: true  # Needed to access Docker socket
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: shared-storage
        persistentVolumeClaim:
          claimName: realtime-image-storage