apiVersion: batch/v1
kind: Job
metadata:
  name: realtime-builder
  namespace: kilobase
  labels:
    app: realtime-builder
spec:
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: git-clone
        image: alpine/git:latest
        command:
        - sh
        - -c
        - |
          echo "Cloning KBVE/realtime repository..."
          git clone https://github.com/KBVE/realtime.git /workspace
          echo "Repository cloned successfully"
          ls -la /workspace
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      containers:
      - name: buildah-builder
        image: quay.io/buildah/stable:latest
        command:
        - sh
        - -c
        - |
          echo "Building image with buildah..."
          cd /workspace
          
          # Build the image using buildah (rootless)
          buildah bud --storage-driver vfs -t kbve-realtime:latest .
          
          # Export the image to a tar file
          buildah push --storage-driver vfs kbve-realtime:latest oci-archive:/output/kbve-realtime.tar:kbve-realtime:latest
          
          echo "Image built and exported successfully!"
          ls -la /output/
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: output
          mountPath: /output
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi" 
            cpu: "2000m"
      volumes:
      - name: workspace
        emptyDir: {}
      - name: output
        emptyDir: {}