apiVersion: batch/v1
kind: Job
metadata:
  name: realtime-builder-v3
  namespace: kilobase
  labels:
    app: realtime-builder
spec:
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: git-clone
        image: alpine/git:latest
        command:
        - sh
        - -c
        - |
          echo "Cloning KBVE/realtime repository..."
          git clone https://github.com/KBVE/realtime.git /workspace
          echo "Repository cloned successfully"
          ls -la /workspace
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      containers:
      - name: kaniko-builder
        image: gcr.io/kaniko-project/executor:latest
        args:
        - --dockerfile=/workspace/Dockerfile
        - --context=/workspace
        - --no-push
        - --tarPath=/shared-storage/kbve-realtime.tar
        - --destination=kbve-realtime:latest
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: shared-storage
          mountPath: /shared-storage
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi" 
            cpu: "2000m"
      volumes:
      - name: workspace
        emptyDir: {}
      - name: shared-storage
        persistentVolumeClaim:
          claimName: realtime-image-storage