apiVersion: v1
kind: Service
metadata:
  name: realtime-prod-headless
  namespace: kilobase
  labels:
    app: realtime-prod
    component: websocket
spec:
  clusterIP: None  # This makes it a headless service
  publishNotReadyAddresses: true  # Important for pod discovery during startup
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
    - port: 4369
      targetPort: 4369
      protocol: TCP
      name: epmd  # Erlang Port Mapper Daemon
    - port: 5369
      targetPort: 5369
      protocol: TCP
      name: gen-rpc  # GenRPC for inter-node communication
  selector:
    app: realtime-prod