apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime
  namespace: kilobase
  labels:
    app: realtime
    component: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime
  template:
    metadata:
      labels:
        app: realtime
        component: websocket
    spec:
      containers:
      - name: realtime
        image: supabase/realtime:v2.42.3
        command: ["/bin/sh"]
        args: ["-c", "/app/bin/migrate && /app/bin/realtime eval 'Realtime.Release.seeds(Realtime.Repo)' && /app/bin/server"]
        ports:
        - containerPort: 4000
          name: http
        env:
        - name: PORT
          value: "4000"
        - name: DB_HOST
          value: "supabase-cluster-rw.kilobase.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "supabase_admin"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-superuser
              key: password
        - name: DB_NAME
          value: "supabase"
        - name: DB_AFTER_CONNECT_QUERY
          value: "SET search_path TO _realtime"
        - name: DB_ENC_KEY
          value: "supabaserealtime"
        - name: API_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: realtime-jwt-secret
              key: API_JWT_SECRET
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: realtime-jwt-secret
              key: API_JWT_SECRET
        - name: JWT_CLAIM_VALIDATORS
          value: '{"iss": "supabase"}'
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: realtime-jwt-secret
              key: secret-key-base
        - name: ERL_AFLAGS
          value: "-proto_dist inet_tcp"
        - name: DNS_NODES
          value: "''"
        - name: RLIMIT_NOFILE
          value: "10000"
        - name: APP_NAME
          value: "realtime"
        - name: SEED_SELF_HOST
          value: "true"
        - name: RUN_JANITOR
          value: "true"
        
        # Add ANON_KEY as environment variable for health checks
        - name: ANON_KEY
          valueFrom:
            secretKeyRef:
              name: realtime-jwt-secret
              key: ANON_KEY
        
        # Add Supabase service role key
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: realtime-jwt-secret
              key: SERVICE_KEY
        
        # Add Supabase anon key for public access
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: realtime-jwt-secret
              key: ANON_KEY
        
        # Set the tenant name for realtime - URL compatible name for self-host
        - name: SELF_HOST_TENANT_NAME
          value: "realtime"
        
        # Set TENANT_NAME for seeds script to create realtime tenant
        - name: TENANT_NAME
          value: "realtime"
        
        # Restart trigger for JWT updates
        - name: RESTART_TRIGGER
          value: "jwt-update-2025-08-18-ALPHA"
        
        volumeMounts:
        - name: realtime-seeds
          mountPath: /app/lib/realtime-2.42.3/priv/repo/seeds.exs
          subPath: seeds.exs
        
        livenessProbe:
          tcpSocket:
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          tcpSocket:
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: realtime-seeds
        configMap:
          name: realtime-seeds