apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse-cluster
  namespace: clickhouse
spec:
  configuration:
    users:
      admin/password_sha256_hex: "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92"  # "hello"
      admin/networks/ip:
        - "::/0"
      admin/profile: "default"
      admin/access_management: "1"
    profiles:
      default/max_memory_usage: "10000000000"
      default/use_uncompressed_cache: "0"
      default/load_balancing: "random"
      default/background_pool_size: "32"
      default/background_schedule_pool_size: "16"
      default/background_fetches_pool_size: "8"
      default/background_move_pool_size: "8"
      default/background_common_pool_size: "8"
    quotas:
      default/interval/duration: "3600"
      default/interval/queries: "0"
      default/interval/errors: "0"
      default/interval/result_rows: "0"
      default/interval/read_rows: "0"
      default/interval/execution_time: "0"
    clusters:
      - name: cluster
        layout:
          shardsCount: 2
          replicasCount: 2
        settings:
          # ClickHouse Keeper configuration (instead of ZooKeeper)
          keeper_server/tcp_port: "9181"
          keeper_server/server_id_from_k8s_node_name: "true"
          # Use ClickHouse Keeper service
          zookeeper/nodes/node/host: "clickhouse-keeper-client.clickhouse.svc.cluster.local"
          zookeeper/nodes/node/port: "9181"
          # Performance settings
          max_connections: "4096"
          keep_alive_timeout: "3"
          max_concurrent_queries: "100"
          uncompressed_cache_size: "8589934592"
          mark_cache_size: "5368709120"
          # Replication settings
          max_replica_delay_for_distributed_queries: "300"
          fallback_to_stale_replicas_for_distributed_queries: "1"
          distributed_replica_error_half_life: "60"
          distributed_replica_error_cap: "1000"
          # Metrics and monitoring
          prometheus/endpoint: "/metrics"
          prometheus/port: "9363"
          prometheus/metrics: "true"
          prometheus/events: "true"
          prometheus/errors: "true"
          prometheus/asynchronous_metrics: "true"
  defaults:
    templates:
      dataVolumeClaimTemplate: longhorn-storage
      logVolumeClaimTemplate: longhorn-logs
      podTemplate: clickhouse-pod
      serviceTemplate: clickhouse-service
  templates:
    volumeClaimTemplates:
      - name: longhorn-storage
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: longhorn
      - name: longhorn-logs
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: longhorn
    podTemplates:
      - name: clickhouse-pod
        metadata:
          labels:
            app: clickhouse
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:25.6
              ports:
                - name: http
                  containerPort: 8123
                - name: client
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009
                - name: prometheus
                  containerPort: 9363
              resources:
                requests:
                  memory: "2Gi"
                  cpu: "500m"
                limits:
                  memory: "8Gi"
                  cpu: "2000m"
              readinessProbe:
                httpGet:
                  path: /ping
                  port: 8123
                initialDelaySeconds: 10
                periodSeconds: 5
              livenessProbe:
                httpGet:
                  path: /ping
                  port: 8123
                initialDelaySeconds: 30
                periodSeconds: 30
              volumeMounts:
                - name: longhorn-storage
                  mountPath: /var/lib/clickhouse
                - name: longhorn-logs
                  mountPath: /var/log/clickhouse-server
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
    serviceTemplates:
      - name: clickhouse-service
        metadata:
          labels:
            app: clickhouse
        spec:
          ports:
            - name: http
              port: 8123
              targetPort: 8123
            - name: client
              port: 9000
              targetPort: 9000
            - name: interserver
              port: 9009
              targetPort: 9009
            - name: prometheus
              port: 9363
              targetPort: 9363
          selector:
            app: clickhouse