apiVersion: clickhouse-keeper.altinity.com/v1
kind: ClickHouseKeeperInstallation
metadata:
  name: clickhouse-keeper
  namespace: clickhouse
spec:
  configuration:
    clusters:
      - name: keeper
        layout:
          replicasCount: 3
        settings:
          # Basic Keeper server configuration
          keeper_server/tcp_port: "9181"
          keeper_server/server_id_from_k8s_node_name: "true"
          # Essential coordination settings only
          keeper_server/coordination_settings/operation_timeout_ms: "10000"
          keeper_server/coordination_settings/session_timeout_ms: "30000"
          keeper_server/coordination_settings/election_timeout_lower_bound_ms: "1000"
          keeper_server/coordination_settings/election_timeout_upper_bound_ms: "2000"
          # Metrics
          prometheus/endpoint: "/metrics"
          prometheus/port: "7000"
          prometheus/metrics: "true"
  defaults:
    templates:
      dataVolumeClaimTemplate: longhorn-storage
      podTemplate: clickhouse-keeper-pod
      serviceTemplate: clickhouse-keeper-service
  templates:
    volumeClaimTemplates:
      - name: longhorn-storage
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: longhorn
    podTemplates:
      - name: clickhouse-keeper-pod
        metadata:
          labels:
            app: clickhouse-keeper
        spec:
          containers:
            - name: clickhouse-keeper
              image: clickhouse/clickhouse-keeper:23.8
              ports:
                - name: client
                  containerPort: 9181
                - name: raft
                  containerPort: 9234
                - name: prometheus
                  containerPort: 7000
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
                  cpu: "500m"
              readinessProbe:
                tcpSocket:
                  port: 9181
                initialDelaySeconds: 10
                periodSeconds: 5
              livenessProbe:
                tcpSocket:
                  port: 9181
                initialDelaySeconds: 30
                periodSeconds: 30
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
    serviceTemplates:
      - name: clickhouse-keeper-service
        metadata:
          labels:
            app: clickhouse-keeper
        spec:
          ports:
            - name: client
              port: 9181
              targetPort: 9181
            - name: raft
              port: 9234
              targetPort: 9234
            - name: prometheus
              port: 7000
              targetPort: 7000
          selector:
            app: clickhouse-keeper