apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: clickhouse
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clickhouse-external-secrets-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["supabase-postgres", "supabase-cluster-app", "supabase-superuser"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clickhouse-external-secrets-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clickhouse-external-secrets-reader
subjects:
- kind: ServiceAccount
  name: external-secrets-sa
  namespace: clickhouse
---
# Allow the clickhouse namespace SA to access secrets in kilobase namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-kilobase-secrets
  namespace: kilobase
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: ["supabase-postgres", "supabase-cluster-app", "supabase-superuser"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clickhouse-read-kilobase-secrets
  namespace: kilobase
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-kilobase-secrets
subjects:
- kind: ServiceAccount
  name: external-secrets-sa
  namespace: clickhouse