apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kilobase-remote-secret-store
  namespace: clickhouse
spec:
  provider:
    kubernetes:
      remoteNamespace: kilobase
      auth:
        serviceAccount:
          name: external-secrets-sa
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: default
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clickhouse-postgres-credentials
  namespace: clickhouse
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kilobase-remote-secret-store
    kind: SecretStore
  target:
    name: clickhouse-postgres-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        host: supabase-cluster-rw.kilobase.svc.cluster.local
        database: supabase
  data:
  - secretKey: username
    remoteRef:
      key: supabase-postgres
      property: username
  - secretKey: password
    remoteRef:
      key: supabase-postgres
      property: password
