apiVersion: v1
kind: Service
metadata:
    name: friendslop-game
    namespace: friendslop
    labels:
        app: friendslop-server
        app.kubernetes.io/part-of: friendslop
        kbve.com/category: game-server
        kbve.com/stack: agones
        kbve.com/managed-by: argocd
spec:
    type: ClusterIP
    selector:
        app: friendslop-server
    sessionAffinity: ClientIP
    ports:
        - name: ws
          port: 7980
          targetPort: 7980
          protocol: TCP
