apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: discord

resources:
  - notification-bot-deployment.yaml
  - notification-bot-service.yaml
  - notification-bot-ingress.yaml
  - notification-bot-rbac.yaml
  - notification-bot-externalsecret.yaml