apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-bot
  namespace: discord
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: notification-bot-secrets-reader
  namespace: kilobase
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["supabase-jwt", "supabase-postgres", "supabase-db"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notification-bot-read-kilobase-secrets
  namespace: kilobase
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: notification-bot-secrets-reader
subjects:
- kind: ServiceAccount
  name: notification-bot
  namespace: discord
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: notification-bot-services-reader
  namespace: kilobase
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notification-bot-read-kilobase-services
  namespace: kilobase
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: notification-bot-services-reader
subjects:
- kind: ServiceAccount
  name: notification-bot
  namespace: discord