apiVersion: v1
kind: Service
metadata:
  name: notification-bot
  namespace: kilobase
spec:
  type: ClusterIP
  selector:
    app: notification-bot
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http