import { describe, expect, it } from 'vitest';
import { heightAt, seedFromWorld, HEIGHT_AMPLITUDE } from './heightfield';

// Cross-language parity vectors — generated by
// `cargo test -p simgrid print_height_vectors -- --ignored --nocapture`
// and pinned bit-exactly in packages/rust/simgrid/src/heightfield.rs.
// The JS FastNoiseLite port runs in f64, so agreement here is epsilon-bounded.
const VECTORS: Array<[number, number, number, number]> = [
	[0, 0.0, 0.0, 0.0],
	[0, 1.0, 1.0, 41.39485],
	[0, -1.0, 1.0, 113.86262],
	[0, 100.5, -200.25, -60.05444],
	[-1046127014, 0.0, 0.0, 0.0],
	[-1046127014, 64.0, 64.0, -26.676088],
	[-1046127014, -300.0, 12.0, -299.7108],
	[1, 0.5, 0.5, -13.320968],
	[-1, 1024.0, -1024.0, -125.21937],
	[123456789, 3.25, -7.75, -173.96893],
];

const EPSILON = 0.05;

describe('heightfield', () => {
	it('matches the pinned simgrid vectors within epsilon', () => {
		for (const [seed, x, y, expected] of VECTORS) {
			expect(Math.abs(heightAt(seed, x, y) - expected)).toBeLessThan(
				EPSILON,
			);
		}
	});

	it('is deterministic and bounded', () => {
		const a = heightAt(42, 12.5, -83.25);
		const b = heightAt(42, 12.5, -83.25);
		expect(a).toBe(b);
		expect(Math.abs(a)).toBeLessThanOrEqual(HEIGHT_AMPLITUDE);
	});

	it('truncates world seeds canonically', () => {
		expect(seedFromWorld(0)).toBe(0);
		expect(seedFromWorld(0xc1a55e5a)).toBe(-1046127014);
		expect(seedFromWorld(-1)).toBe(-1);
		expect(seedFromWorld(0x123456789n)).toBe(0x23456789);
	});
});
