import { describe, expect, it } from 'vitest';
import {
	heightAt,
	riverMask,
	makeHeightField,
	seedFromWorld,
	HEIGHT_AMPLITUDE,
	RIVERBED_DEPTH,
	WATER_Z,
} from './heightfield';

// Cross-language parity vectors — generated by
// `cargo test -p simgrid print_height_vectors -- --ignored --nocapture`
// and pinned bit-exactly in packages/rust/simgrid/src/heightfield.rs.
// The JS FastNoiseLite port runs in f64, so agreement here is epsilon-bounded.
const VECTORS: Array<[number, number, number, number]> = [
	[0, 0.0, 0.0, -293.7651],
	[0, 1.0, 1.0, -248.87437],
	[0, -1.0, 1.0, 110.21433],
	[0, 100.5, -200.25, -60.05444],
	[-1046127014, 0.0, 0.0, -220.23637],
	[-1046127014, 64.0, 64.0, -48.45469],
	[-1046127014, -300.0, 12.0, -299.7108],
	[1, 0.5, 0.5, -300.0],
	[-1, 1024.0, -1024.0, -168.0653],
	[123456789, 3.25, -7.75, -174.0908],
];

// Wider than it was before the river landed. The carve divides by a numerically
// estimated gradient, and dividing amplifies the f32-vs-f64 gap between the two
// ports into the channel width; 0.25 uu against a 900 uu amplitude is still
// three parts in ten thousand, and this mirror is for rendering offsets, not for
// anything the server verifies.
const EPSILON = 0.25;

describe('heightfield', () => {
	it('matches the pinned simgrid vectors within epsilon', () => {
		for (const [seed, x, y, expected] of VECTORS) {
			expect(Math.abs(heightAt(seed, x, y) - expected)).toBeLessThan(
				EPSILON,
			);
		}
	});

	it('is deterministic and bounded', () => {
		const a = heightAt(42, 12.5, -83.25);
		const b = heightAt(42, 12.5, -83.25);
		expect(a).toBe(b);
		expect(Math.abs(a)).toBeLessThanOrEqual(
			HEIGHT_AMPLITUDE + RIVERBED_DEPTH + Math.abs(WATER_Z),
		);
	});

	it('carves a river network, not a flood', () => {
		const field = makeHeightField(1337);
		let basin = 0;
		for (let gy = 0; gy < 120; gy++) {
			for (let gx = 0; gx < 120; gx++) {
				if (field.riverMask(gx * 5 - 300, gy * 5 - 300) > 0.98) basin++;
			}
		}
		const frac = basin / (120 * 120);
		expect(frac).toBeGreaterThan(0.005);
		expect(frac).toBeLessThan(0.05);
	});

	it('truncates world seeds canonically', () => {
		expect(seedFromWorld(0)).toBe(0);
		expect(seedFromWorld(0xc1a55e5a)).toBe(-1046127014);
		expect(seedFromWorld(-1)).toBe(-1);
		expect(seedFromWorld(0x123456789n)).toBe(0x23456789);
	});
});
