apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
    name: guacd-scaler
    namespace: angelscript
    labels:
        app: guacd
        component: guacamole
spec:
    scaleTargetRef:
        name: guacd
    pollingInterval: 30
    cooldownPeriod: 300
    idleReplicaCount: 0
    minReplicaCount: 0
    maxReplicaCount: 1
    triggers:
        - type: kubernetes-workload
          metadata:
              podSelector: 'vm.kubevirt.io/name=windows-builder'
              value: '1'
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
    name: guacamole-scaler
    namespace: angelscript
    labels:
        app: guacamole
        component: guacamole
spec:
    scaleTargetRef:
        name: guacamole
    pollingInterval: 30
    cooldownPeriod: 300
    idleReplicaCount: 0
    minReplicaCount: 0
    maxReplicaCount: 1
    triggers:
        - type: kubernetes-workload
          metadata:
              podSelector: 'vm.kubevirt.io/name=windows-builder'
              value: '1'
