apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: valkey
    namespace: argocd
    annotations:
        kbve.com/source-path: kube/valkey
        kbve.com/manifest-path: kube/valkey
        kbve.com/application-file: kube/valkey/application.yaml
        kbve.com/managed-by: argocd
        kbve.com/schema-version: v1
        kbve.com/category: database
        kbve.com/stack: core
        argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
    project: default
    sources:
        - repoURL: https://valkey-io.github.io/valkey-helm/
          targetRevision: 0.9.4
          chart: valkey
          helm:
              releaseName: valkey
              valueFiles:
                  - $values/apps/kube/valkey/manifests/values.yaml
        - repoURL: https://github.com/kbve/kbve
          targetRevision: main
          ref: values
        - repoURL: https://github.com/kbve/kbve
          targetRevision: main
          path: apps/kube/valkey/manifests
    destination:
        server: https://kubernetes.default.svc
        namespace: valkey
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
        syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
