/**
 * Presentational surface re-exported from `@kbve/rn/ui`.
 *
 * Everything here is theme-only: no component in `@kbve/rn/ui` reads the
 * `KbveProvider` auth context, so a Tauri app can render these without
 * standing up a supabase-js client. Auth-bound screens (`@kbve/rn/account`)
 * are deliberately not re-exported — Tauri apps own their session through
 * `@kbve/tauri`'s Rust IPC instead.
 */
export {
	Text,
	Surface,
	Stack,
	Divider,
	Badge,
	Button,
	PressableSurface,
	Screen,
	Gradient,
	AppCard,
	CardList,
	MenuItem,
	MenuList,
	EntityRenderer,
	EmptyState,
	LoadingState,
	ErrorState,
	Footer,
	NavBar,
	NavItem,
	AppBar,
	TabBar,
	NavShell,
	navStore,
	useTab,
	Hero,
	Section,
	SectionHeading,
	FeatureCard,
	FeatureGrid,
	StatStrip,
	ProjectCard,
	ProjectGrid,
	CtaSection,
	ProcessSteps,
	Testimonials,
	LiveFeed,
	PricingTiers,
	FaqAccordion,
	LogoCloud,
	BentoGrid,
	Timeline,
	TabbedFeatures,
	TeamGrid,
	NewsletterCapture,
	useTheme,
	tokens,
} from '@kbve/rn/ui';

export type {
	CardModel,
	CardVariant,
	ActionDescriptor,
	MenuItemModel,
	MenuSectionModel,
	UIEntity,
	BadgeTone,
	TextVariant,
	TextTone,
	ButtonVariant,
	NavLink,
	NavBarProps,
	NavItemProps,
	AppBarProps,
	TabItem,
	TabBarProps,
	NavRoute,
	NavShellProps,
	FooterLink,
	FooterGroup,
	FooterProps,
	HeroProps,
	HeroAction,
	SectionProps,
	SectionHeadingProps,
	FeatureCardProps,
	StatItem,
	ProjectItem,
	StepItem,
	TestimonialItem,
	FeedRow,
	PricingTier,
	FaqItem,
	LogoItem,
	BentoItem,
	TimelineItem,
	FeatureTab,
	TeamMember,
} from '@kbve/rn/ui';
