---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: mc-vt-api-key
    namespace: arc-runners
spec:
    encryptedData:
        VT_API_KEY: AgAfyIc6aHxH2dHi9fZKcHJ1u8U3OaJKXLSWYd9mkQOulWrPRXvPhj/xCb97aiVAvLYoTdNClSkhn8GIYe7/an+SWpry3KLGbMXAsEVuLTDdRAXq6kXHjCLizBSnb7B/MY+0SowtqeCIUFEhlFwzEB4K7PZBlBIvMOc4H2GbuwkHgS1LrLXwJcVHR/jY6usUA3EcyCEVc28wnfgf/FTERhJDR1hZL10KGdqYzL0/LCoiQMyRalSoHheuAtItvPgxE2/mam2MtW5CNy6AimcHBj7OIOa0jTOnPw+fKtt4b1s9WjMb56UPifTQ3bbPdr7+VSw+uKx+E7eMJaUzAJlNGtyoZzSyUdby4b95uxh3pQI7yyv277Mq5hbzzrCic4wRr+ZaoyIjAIMLuUhYClGYh3DPZZ2hYtLtMwBFxjnPJCCKGELdbhLPUWw2Tdm++Rnz84vo0ljGKj2gB1bQzGD9s4a7Wodtpd4NgR8heXR2o6bR6iBqwTI41jKkN83grAjczDsU59I6M511jKFXSTjBxZ+V6zBy5ziXVYfTNuFi//x57wqU/nYrFOkxM31ImAD+Eu2by4CHWXlP5btrWQ7iEsi1in+gPEPbYnh7/7Jjl55D59c+vYufn6FIqliJfZCsIgXHpsWSME38BN/QBsXakGXnPQ1Dez1293DmgfmhUnefCznqT4wYTPrA5mzu+jU/ZuC208ODRTDEpRHdMW6Nqb1yaFaqRbpdybceE1QrWDImIBM2ZxX+UYLlL8Tju3HdOZtHrkAb9sjAVspQis2clSKL
    template:
        metadata:
            name: mc-vt-api-key
            namespace: arc-runners
