---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: arpg-discord-credentials
    namespace: arpg
spec:
    encryptedData:
        client_id: AgAUTmcuqA05LmVrY/unomltUbU/fuNLPOGWPZVnDnTq39hLhOq7s+mLxzoWQL4bX0xWxvDCikeu3RjHwIyIIpQOXdsQeqdk0WSth92wJck1JxD0NM/kq7rOrZZIOWVIva60d4gGXsCFDBaz+dOBB+nSf+THEnKTcO8a/mK1Hf2Ag/+KY6IL7Bk48MjL5VPkvI8IId3XZeiNm3ipODc2ULk0+zeiFuJnNchrYN9q5M7iDZu99Vp4Ogy4nqQPY+Xy8CDPZR9dWteD7G/46h4/nX2kyhPE4CkSTEh0Ud9tBNvypmBmMmTANP75Ppdj6XIVrtvmiEPb8FcQ3ZhUFhPHO3GqEQYE7/i4PuoSpoU6XMTEqnY0O0msh21sXtYVjlbVC+fmmH9+TbrWFF+ngfDBAbQ4tBpCODJAk65gFZMQgkokXv6lOTQJmC8Z89jua4k9XZEeQJp/X2F5yrdPiBeJlfPzL1fkvMrYaRNK69qscw3y1i3sWFSD5txLh4dUQBPxo8SKKai0TOSaxu4Fh7Ij1HVpV/C6rBwJYb938yu67StSLPdO+8bUcGjuBJ+IOBD/zOOuAwB7iOhSaq4P4MpPppNsl/MHrVxiqH+d+ogC4J0ZQWBVhXVzUKMF5UzUvsGQ9gfg9HlyJAQ2fHAYjiUDKEE9YkI8QPmt7siqUXDTyuSTn2m/lwF6kwboLAzSwbY4+/LALYiV48JO8O9fXqego6pMTFUj
        secret_key: AgBXPifBX7V8NZDRsUfw13tJPzgap2jDyziyak8i8JhigpMCr6wroyQyjrIPXveD+18bAtr9XXZ/y9yETkan1dWlEKyS8H5VcWQ0qLgdZxFwQx8l6JS/0Gat8A3gYzS/dWthRbTQ7UdAvuA6/P1Ir8RuZTDd3qo43+f/IbVOS4uhylUmIUOrNGXyIxspFO5KEGLjbILVw/r53P5DJfaHy5qpoG9c4CVqi4B2bVQ9hJe2oMsNWw228YCBNT1r+imgXskF3avqf0CzbVeYgaxjgESwedT+v1cO1LsNVkzrbZTyuV6spDqgl9d8AbkEI8aGrDBkJd8Nr1FYiE5MgHh9KttgnDVfXUn9CGucgWgeFDnlkigkIbeSWyZh4J5qa2oXIgIHc5o+MMZAL45tgbNPALSu34PoflAIFJDbDGKB5qZ5VfoggHu20k0tuHpsAJhjzu84bAvA3NqbhAQ8MgCMadWoRJH3PLjaUAvaZoh1Dn9orjjMBissNmq1p+fSS4hTDjdhiMe3dNGTFS6V23j9t+t7943Mwa+oq0J+zY9YOu4QOGBMpI4kZbeNLNzkyQ2ivRcVXEzWc7PIu09dnFzkrjHTeSbbFeckrrZ+XKxrZy+tlDkSIKJwRtmO/45e0wYdRQzb/KKeJe545Qsx2LKnMZp8mM/R+xbpUpoM7wnhFCuEs9a2vGOnf/Jwmj9/T5BiQ9wsSXZKIIYEN5dH87J/hcPALxb9qVcUUL1uh7YU3Ue2OA==
    template:
        metadata:
            name: arpg-discord-credentials
            namespace: arpg
