local Market = {}

Market.ITEMS = {
	{ item = 'repair-pack', price = 3, count = 5 },
	{ item = 'iron-gear-wheel', price = 4, count = 25 },
	{ item = 'steel-plate', price = 5, count = 10 },
	{ item = 'sulfur', price = 6, count = 10 },
	{ item = 'plastic-bar', price = 8, count = 10 },
	{ item = 'piercing-rounds-magazine', price = 8, count = 10 },
	{ item = 'fast-inserter', price = 10, count = 4 },
	{ item = 'underground-belt', price = 12, count = 4 },
	{ item = 'splitter', price = 15, count = 4 },
	{ item = 'battery', price = 18, count = 5 },
	{ item = 'gun-turret', price = 30, count = 2 },
	{ item = 'stone-wall', price = 4, count = 25 },
	{ item = 'advanced-circuit', price = 25, count = 5 },
	{ item = 'engine-unit', price = 30, count = 2 },
	{ item = 'assembling-machine-2', price = 35, count = 1 },
	{ item = 'fast-transport-belt', price = 4, count = 25 },
	{ item = 'medium-electric-pole', price = 8, count = 4 },
	{ item = 'big-electric-pole', price = 18, count = 4 },
	{ item = 'substation', price = 45, count = 2 },
	{ item = 'electric-engine-unit', price = 80, count = 2 },
	{ item = 'assembling-machine-3', price = 90, count = 1 },
	{ item = 'processing-unit', price = 100, count = 1 },
	{ item = 'laser-turret', price = 150, count = 2 },
	{ item = 'flying-robot-frame', price = 150, count = 1 },
	{ item = 'construction-robot', price = 200, count = 1 },
	{ item = 'logistic-robot', price = 250, count = 1 },
	{ item = 'defender-capsule', price = 40, count = 10 },
	{ item = 'distractor-capsule', price = 150, count = 5 },
	{ item = 'destroyer-capsule', price = 300, count = 5 },
	{ item = 'modular-armor', price = 500, count = 1 },
	{ item = 'roboport', price = 500, count = 1 },
	{ item = 'power-armor', price = 2000, count = 1 },
	{ item = 'power-armor-mk2', price = 5000, count = 1 },
	{ item = 'fusion-reactor-equipment', price = 6000, count = 1 },
}

return Market
