apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: kasm-discord-profile
    namespace: kasm
    labels:
        app: kasm-vpn
        app.kubernetes.io/part-of: kasm
        app.kubernetes.io/component: storage
        kbve.com/category: virtualization
        kbve.com/stack: core
        kbve.com/managed-by: argocd
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 5Gi
