apiVersion: v1
kind: ServiceAccount
metadata:
    name: kasm-init-sa
    namespace: kasm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: kasm-vnc-pw-rotator
    namespace: kasm
rules:
    - apiGroups: ['']
      resources: ['secrets']
      resourceNames: ['kasm-vnc-pw']
      verbs: ['get', 'patch', 'update']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: kasm-init-sa-rotator
    namespace: kasm
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: kasm-vnc-pw-rotator
subjects:
    - kind: ServiceAccount
      name: kasm-init-sa
      namespace: kasm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: kasm-vnc-pw-reader
    namespace: kasm
rules:
    - apiGroups: ['']
      resources: ['secrets']
      resourceNames: ['kasm-vnc-pw']
      verbs: ['get']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: kbve-app-vnc-pw-reader
    namespace: kasm
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: kasm-vnc-pw-reader
subjects:
    - kind: ServiceAccount
      name: kbve-app
      namespace: kbve
