apiVersion: v1
kind: Secret
metadata:
    name: kasm-vnc-pw
    namespace: kasm
    labels:
        app: kasm-vpn
        app.kubernetes.io/part-of: kasm
        app.kubernetes.io/component: vnc-auth
type: Opaque
stringData:
    password: 'placeholder-overwritten-by-init-on-pod-start'
