############
##  [Stage] - 1
############
FROM eclipse-temurin:17-jdk AS jardeps

RUN apt-get update && apt-get install -y git maven

RUN git clone --depth 1 https://github.com/chsami/microbot.git /root/microbot

RUN mkdir /root/.m2

COPY add_dependency.sh /root/add_dependency.sh

RUN chmod +x /root/add_dependency.sh

RUN /root/add_dependency.sh

WORKDIR /root/microbot

RUN mvn -f /root/microbot/pom.xml dependency:go-offline dependency:resolve dependency:resolve-plugins clean package -DskipTests -B
RUN mvn -f /root/microbot/runelite-api/pom.xml dependency:go-offline dependency:resolve dependency:resolve-plugins clean package -DskipTests -B
RUN mvn -f /root/microbot/runelite-jshell/pom.xml dependency:go-offline dependency:resolve dependency:resolve-plugins clean package -DskipTests -B
RUN mvn -f /root/microbot/runelite-client/pom.xml dependency:go-offline dependency:resolve dependency:resolve-plugins -DskipTests -B
RUN mvn -f /root/microbot/runelite-maven-plugin/pom.xml dependency:go-offline dependency:resolve dependency:resolve-plugins clean package -DskipTests -B


############
##  [STAGE] - 1D
############
FROM eclipse-temurin:17-jdk AS jar

RUN apt-get update && apt-get install -y git maven

COPY --from=jardeps /root/microbot /root/microbot
COPY --from=jardeps /root/.m2 /root/.m2

WORKDIR /root/microbot

RUN mkdir -p /root/microbot/runelite-client/src/main/java/net/runelite/client/plugins/microbot/kbve
COPY ./plugin /root/microbot/runelite-client/src/main/java/net/runelite/client/plugins/microbot/kbve

ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
#   RUN mvn clean package -T 1C -DskipTests -Dmaven.test.skip=true -Dparallel=all
RUN mvn clean package -T 1C -DskipTests -Dmaven.test.skip=true -Dparallel=all

############
##  [Stage] - 2
#############
# FROM --platform=linux/amd64 ubuntu:24.04 AS os_builder

# RUN apt-get update && apt-get update && apt-get install -y \
#     wget \ 
#     openjdk-11-jdk

# WORKDIR /tmp

# RUN wget https://go.dev/dl/go1.21.1.linux-amd64.tar.gz

# RUN tar -xvf go1.21.1.linux-amd64.tar.gz
# RUN mv go /usr/local
# RUN GOBIN=/usr/local/bin/ /usr/local/go/bin/go install github.com/canonical/chisel/cmd/chisel@latest
# WORKDIR /rootfs
# RUN chisel cut --release ubuntu-24.04 --root /rootfs \
#         base-files_base \
#         base-files_release-info \
#         ca-certificates_data \
#         libgcc-s1_libs \
#         libc6_libs \
#         openssl_config \
#         liblcms2-2_libs \
#         libjpeg8_libs \
#         openjdk-11-jre-headless_standard


############
##  [Stage] - 3
############
# FROM --platform=linux/amd64 ubuntu:22.04 as desktop

# RUN apt-get update && apt-get install -y xvfb

############
##  [Stage] - 4
############
# FROM ubuntu/jre:17_edge

#COPY --from=desktop /usr/bin/Xvfb /usr/bin/Xvfb
#COPY --from=desktop /usr/lib/x86_64-linux-gnu/libXfont2.so.* /usr/lib/x86_64-linux-gnu/
#COPY --from=desktop /usr/lib/x86_64-linux-gnu/libfontenc.so.* /usr/lib/x86_64-linux-gnu/
FROM ghcr.io/linuxserver/baseimage-kasmvnc:ubuntujammy

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openjdk-11-jre && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

COPY --from=jar /root/microbot/runelite-client/target/*.jar /usr/local/bin/runelite.jar

COPY /raw /

ENV TITLE="Fudster Raw v1.03"
ENV NO_FULL=true

RUN chown -R abc:abc /config

EXPOSE 3000