apiVersion: v1
kind: ConfigMap
metadata:
    name: migrate-script
    namespace: kilobase
    labels:
        app.kubernetes.io/name: kilobase
        app.kubernetes.io/component: migration
        kbve.com/category: application
        kbve.com/stack: core
        kbve.com/managed-by: argocd
data:
    migrate.sh:
        "#!/usr/bin/env sh\necho \"--------------------\"\necho \"Beginning\
        \ migrations\"\n\nset -e\n\nDB_VERSION=\"${1:-17.4.1.014}\"\n\napk upgrade\napk\
        \ add gettext moreutils git curl jq grep\n\nmkdir -p /supasql/db/base\nmkdir -p\
        \ /supasql/db/final\n\ngit clone --depth 1 https://github.com/supabase/postgres.git\
        \ /supasql/postgres && cd /supasql/postgres\ngit checkout -b ${DB_VERSION}\ncp\
        \ -a /supasql/postgres/migrations/db/init-scripts/*.sql /supasql/db/base/\ncp\
        \ -a /supasql/postgres/migrations/db/migrations/*.sql /supasql/db/base/\n\ncp\
        \ /supasql/postgres/ansible/files/pgbouncer_config/pgbouncer_auth_schema.sql /supasql/db/00-schema.sql\n\
        cp /supasql/postgres/ansible/files/stat_extension.sql /supasql/db/00-extension.sql\n\
        \n# not possible with cnpg?\nrm /supasql/db/base/10000000000000_demote-postgres.sql\n\
        \n# profiles with rls\n# curl https://raw.githubusercontent.com/supabase/supabase/refs/heads/master/docker/dev/data.sql\
        \ > migrations/99-z_00-data.sql\n\n# git clone --depth 1 git@github.com:supabase/postgres.git\n\
        for afile in $(curl -s https://api.github.com/repositories/214587193/contents/docker/volumes/db\
        \ | jq -r '.[] | .download_url' - | grep -E '\\.sql$')\ndo\n  curl -s $afile >\
        \ /supasql/db/final/$(basename $afile)\ndone\n\n# build from parts, as the CNPG\
        \ superuser targets \"*\" database.\n# Superuser credentials, and the App DB\n\
        db_uri=\"postgresql://${SUPERUSER_USER}:${SUPERUSER_PASSWORD}@${SUPERUSER_HOST}:${SUPERUSER_PORT}/${POSTGRES_DB}\"\
        \n\necho \"Running base migrations\"\necho\necho \"-----------\"\necho\necho \"\
        Basic pgbouncer & other setup\"\npsql -d $db_uri -f \"/supasql/db/00-schema.sql\"\
        \npsql -d $db_uri -f \"/supasql/db/00-extension.sql\"\n\n# MIGRATION_SCHEMA as\
        \ first search_path so the dbmate migrations table gets created in a seperate\
        \ schema\n# (not polluting the public schema, and not interfering with Realtime's\
        \ schema_migrations table)\ndbmate_uri=\"${db_uri}?search_path=${MIGRATION_SCHEMA},public\"\
        \ndbmate --wait-timeout=300s --url $dbmate_uri --migrations-dir \"/supasql/db/base\"\
        \ --wait --no-dump-schema up\n\necho \"Running final migrations\"\necho \"_supabase.sql\"\
        \npsql -d $db_uri -f \"/supasql/db/final/_supabase.sql\"\necho \"webhooks.sql\"\
        \npsql -d $db_uri -f \"/supasql/db/final/webhooks.sql\"\necho \"realtime.sql\"\
        \npsql -d $db_uri -f \"/supasql/db/final/realtime.sql\"\necho \"roles.sql\"\n\
        psql -d $db_uri -f \"/supasql/db/final/roles.sql\"\necho \"logs.sql\"\npsql -d\
        \ $db_uri -f \"/supasql/db/final/logs.sql\"\necho \"pooler.sql\"\npsql -d $db_uri\
        \ -f \"/supasql/db/final/pooler.sql\"\n\necho \"FIXME: temp personalise database\
        \ name in jwt.sql\"\n# psql -d $db_uri -f \"./db/final/jwt.sql\"\npsql -d $db_uri\
        \ -c \"ALTER DATABASE ${POSTGRES_DB} SET \"app.settings.jwt_secret\" TO '${JWT_SECRET}';\"\
        \ \\\n  \"ALTER DATABASE ${POSTGRES_DB} SET \"app.settings.jwt_exp\" TO '${JWT_EXP}';\"\
        \n\necho \"     Complete\"\necho \"--------------------\"\n"
