---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kilobase-s3-secret
  namespace: kilobase
spec:
  encryptedData:
    accessKey: AgCfJk0AIbOTjq541u8n5VDiAJNmknfagmnsQaXR8f1EQr+cdA+LOebBqEEjrSbfaneFAH1okSwVC6egauHsPwdbje59sRL07QE1pmW9G8mV3TB/ljssrzQEyck+Bvw+OYcMNTHnwT9NsBMgVzdAzUqNn68RfA+oNrxTyIGBfMQeMi1vyHug5EyCmOCUCBJKI/Sn7bb+BuUELA11g17fMjQdscbPUreZ6K3p2M7IwRKUz4CBbsx223DLQfY6GJ7lL5Amo4eXhOufudURBL9jo8YhAczz1jeUQ4ZtILjNYhkYw1Jxc1TRewJuykRcf/BUQmcAUhhvgU7wMfC8FO7pydrDSjxCL559BmYuIKZJzDDYxXyoafoV31HnHdEXIQfIrjEborQlXD0oHOXstAowq82rPFIabGuIeXFigtOM63bOMuNZXqAlNzku9PiyF6h2XYDcn3QKfhT5DLtmTEzQQIvutFMpgu07qYtxmBHTLEXaE1tJFFYOogUWJ+7JG9PdbgcvsN/AHSvUMeBPcxwsS1ITmZ9Uiw6j0wuU6rHtM5AnECFr0XhekzgsKpBvMdxl1md6qTLovR93LiLkPnw3Dzk9NbOyIxKpdQSSa06deZNJLoLR4FP45iPgf7Hp7YBfqjbWMeKDvAaHUdSQtJiT9faRNef9PNGIDPznqmcejsVa9hZ3iIi7vuc7tNhtrsyIypJZiaJbpSJEa8/aZ1uRp4fdeHhX4naVP3sNZIwOraEuUAubf0w0fAeG
    keyId: AgAe6wbPF8tI6cKt21fz6DH0zAS+zgrflueiYn97SuIuJxVR2I/Nvbq4ZP1x5TLdVYzzEP1wTzrWGFnR+pR3SIlQSnBcP+PyQfD8GQjetvPX5b9bmAfDHa7vZVYFGQ5JqAcGem7t4aAv3TSvlCKAeTsfL0LwTnsugVx8NhWPCH2ctYLt5p59XCXQdsAxlKYCCTP6OT+PTH8j6lM5qmVFEo/LdAadU7JNfEhekB86SfykR3fE2I13cWuNfxL2SX81YlR64QuNB//B6A2RGfgxxOtD6hcy8ZIiknU6k8ePBTzwBvKF41vVYeqbKUDBOfY/vvZQ2NjvWoSGxO5fwRXO4n04f4LHy5sp77ZAcnr9skVFMsrx9LVWA7L6aN0qwg8NYM9DmRJwEylnfKQ8mSQty70v8Ldv3WriAAnFta/NGINZLLQb5zt+xGev0S23I6hA2oCF+Ek8fhvI7+lRP4vwCqvCjW47c0L1I+kK5nI1gz41rsaZuAKsvVUjcSNwpauWW6QVOx7lDLTVAJE4GJpkCgGpgnwLtMdlUUZpYHSvJ/B9f8JzEH16WiRj+ReQq3s58bXeRqo2XuDBILvh87tB6pCr2S+0rfH+fviE/1mt8z9w5e69jq8EjUejhY2UtrN4ETW8bp125HyyQUZMJCXLIbakRSOBw1r150lj/5QC+BFnFpdLEqvA55mFcOkxn8cOdlol79JikdF5yFUdAZNZYKQAWVO21g==
  template:
    metadata:
      creationTimestamp: null
      name: kilobase-s3-secret
      namespace: kilobase
    type: Opaque
