---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: forgejo-db-credentials
    namespace: kilobase
spec:
    encryptedData:
        password: AgAWHzR+WLzRDiKjVM0jy8IQiGj0NccrQGLupdKv0qJrxhGyQ1W+SX9WYM0I8yCcuyjxCTvdIpQ26Q9OEybhzA6xy3YQhRCblrWt7+b3uuCJ4X2OAgkuD+MPp/XtuiiszR89Uocu7YAi2wLx1+5oik3fedtmFJRK1NP1ukezomWDkT9SlKehtGC50as9t22DjksIxicqf6J9YByKhX5hT5sAXvPkO4hX4VlwV+LolixWovy/W3eP5b5V4naNq70EHkJZwvz19kV9Ujpr4Uhl77LphebR1kn3tACnyqamR5ZD/wv9NBV26QZbxOuNZ8VQTj/I+162p2T9ndaLnbTFlvKjXnpeAvspEdaCh5hVu9uUoqGicz/+LMyI31hgw68j2vvoF4chnvupe2RASkQlbwkEqhPnonTlKylxhb0qyEqMmDMRJpZj70ygapRs46DvXsM/caUP7BSYJF6grknFCtd89vbWNOx5GktQyygZyU/fXaUM2s3GDcR8WWkWkZoPFb7WvL/KtSFOS8LIJbhQlJcm/XQEJWpKCvq0InLxZM4dXx8CMvSqqvebvh4gTfTZSYQSvdxYxJfu897V/SKcDOXW56D66CXPSu3snp5jgESeEt+u//HmbKrupK/IOV1ZedwK00lKH0McaJQvVg7B4xPGv0NZEPiIooayYEV4Lb5zeuinuZRTG7KZmUFQT0aEz9iIhbatygHZFwXv7FCKZYPnDozoTYmbL05U3lergh49wMaQwLrxdqsX
    template:
        metadata:
            name: forgejo-db-credentials
            namespace: kilobase
