---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-password
  namespace: kilobase
spec:
  encryptedData:
    password: AgAMG7BaCN5YdMhwnad8tBbjEInf2EWwjBi5fdTSE0xYaUKWPt40mxiTVEW4z8WRtSKDmOC/Kc1GHy7R7o5oa18+uFXIh1JHcQPybo/i19+vH0Ih5cETFmk9/JE+AKKtzbB4kxE1PGQdkAuf1hWClCPyoEMs1bUjI2hTa+fXrFJxp0q1BNygwjy4Q+oFLqR0wmhoqSudkUTjneYG1lhx/vY5/BmRnUoZFsZiwzBcQbCs1FrSdvT/UKKlKn5LEivQ0tvhGths0OZpDGNYFvH9SwgRaZ8aYgBwUTgKZm6EQa8vaxxEElYezhJqvVRbEZfk2XwqAHbzeBnruPsiUvPA/Ns7JzR32bt7gdst+yJ9Fp94+bQEvZ84xRagjbszVzdEkdPLBeWQkkWDuTdOk+WxIDKFEXFqzCyWRgYwoe67+VM6p/rW61Nk8jaYec6B41NQHx/MNdKae8oL3WEsegnthyz/ElIQOq5DazjO+lQW5lTBKkr9sxWRrMOTclOQQpOnYPKZ3e3WFEWM/ZdOqI5BCUuLMQiZwfiaJm8XqsRb16rtlk/YNE8bvePfP+zgkyyhctTrjh2BMo9i6rJqIuC+DI/03tGdX1takvQrtgOJKG3W1qwwTkv4FVbRD+69spw3TDOuIzDlatJYu6JOaf8WqCY8RxWUOhf0VDXZdbRAcPCkv2OVYmnYJ0qoQJiBBKiDnPTspcEjGah8DWXF2gowHGbXEPtNWRo7yBCL2LTx1xop39qkIjgB+8Rg
    username: AgCUD0x89LvQgq2JNEWl8Nz/ZqJTmNPn6zU3XjqkmSRwVXMCLnUMe5IsaxIlaq7oQiufw1o7b4Eve53Lpz6dBVjpT7+Hhp6Q3frTEZMR4b1KgD1E3XhEktRgk3zruSyH81u0FnE8TQYZgLXcTYiE9bcyMwvKkNO7Xys9kpwipEY8tN88oVXFin8196Ybk1b1drUwKseGhDJO0p9YdZTsSFwFns28D5lOAVnbflq6jYpTxvRrqFxtGSo3O3M5vHeZu1IVlhT7RQLbLvemKSETtJjRqIg5TO6ZSMFx1E4uHPp4hk4R4sJqpyeJpfhqFO+7C4GgBg9DO+pXPs+pYDFNRCJCMJVYNKEYr2mzfAZVIhM/V1So5Q9+673MiAA0lzv8ourKXxIs8r0ZsXqWBeaRLExrmDJEQnEDJn5ER9f1VpKoUpau8ZTSWlMCDNFHbEl1w9RqL334IcOVml88L48JJ3Dk3TU2cATcqxYoHsCE405sER8ZBxWflTx9QzpxYNll7goWV7j+AgxutDLzp+/ieusw6SEFErwM2vt2O56G+XhCaN0sOHP8sBRH7QnzM/NIcEacf8r0dTqBJ1y/U9Kd53/prlhuDbwXJShiUpGsGieYLK8/1cV+YiEkC26BdYn0vwVKcUpwPRqPZXCTlYVRruv8YcdV5TZtib63LxbsfFBzcNYJrEuTSmN77RDGx8HP9NLZhfhzX4MoGw==
  template:
    metadata:
      name: keycloak-db-password
      namespace: kilobase
    type: kubernetes.io/basic-auth
