apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: mysql-operator-crds
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-wave: '0'
spec:
    project: default
    source:
        repoURL: https://github.com/kbve/kbve
        targetRevision: main
        path: apps/kube/mysql/crds
    destination:
        server: https://kubernetes.default.svc
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
        syncOptions:
            - ServerSideApply=true
            - Replace=true
        retry:
            limit: 3
            backoff:
                duration: 5s
                factor: 2
                maxDuration: 3m
