apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kilobase
    namespace: argocd
    labels:
        app.kubernetes.io/name: kilobase
        app.kubernetes.io/component: database
spec:
    project: default
    source:
        repoURL: https://github.com/kbve/kbve
        targetRevision: main
        path: apps/kube/kilobase/manifests
    destination:
        server: https://kubernetes.default.svc
        namespace: kilobase
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
        syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
            - RespectIgnoreDifferences=true
        retry:
            limit: 3
            backoff:
                duration: 10s
                factor: 2
                maxDuration: 5m
    ignoreDifferences:
        - group: postgresql.cnpg.io
          kind: Cluster
          jsonPointers:
              - /status
              - /metadata/generation
        - group: ''
          kind: Pod
          jsonPointers:
              - /spec/containers/*/resources
              - /metadata/labels/role
              - /metadata/annotations
        - group: ''
          kind: Secret
          jsonPointers:
              - /data
        - group: ''
          kind: Service
          jsonPointers:
              - /spec/selector
        - group: ''
          kind: PersistentVolumeClaim
          jsonPointers:
              - /status
