use crate::models::Character;
use crate::proto::ows::Character as ProtoCharacter;

impl From<&Character> for ProtoCharacter {
    fn from(c: &Character) -> Self {
        ProtoCharacter {
            customer_guid: c.customer_guid.to_string(),
            character_id: c.character_id,
            user_guid: c.user_guid.map(|u| u.to_string()),
            email: c.email.clone(),
            char_name: c.char_name.clone(),
            map_name: c.map_name.clone(),
            x: c.x,
            y: c.y,
            z: c.z,
            rx: c.rx,
            ry: c.ry,
            rz: c.rz,
            perception: c.perception,
            acrobatics: c.acrobatics,
            climb: c.climb,
            stealth: c.stealth,
            spirit: c.spirit,
            magic: c.magic,
            team_number: c.team_number,
            thirst: c.thirst,
            hunger: c.hunger,
            gold: c.gold as f64,
            score: c.score as f64,
            character_level: c.character_level as i32,
            gender: c.gender as i32,
            xp: c.xp as f64,
            hit_die: c.hit_die as i32,
            wounds: c.wounds,
            size: c.size as f64,
            weight: c.weight,
            max_health: c.max_health,
            health: c.health,
            health_regen_rate: c.health_regen_rate,
            max_mana: c.max_mana,
            mana: c.mana,
            mana_regen_rate: c.mana_regen_rate,
            max_energy: c.max_energy,
            energy: c.energy,
            energy_regen_rate: c.energy_regen_rate,
            max_stamina: c.max_stamina,
            stamina: c.stamina,
            stamina_regen_rate: c.stamina_regen_rate,
            strength: c.strength,
            dexterity: c.dexterity,
            constitution: c.constitution,
            intellect: c.intellect,
            wisdom: c.wisdom,
            charisma: c.charisma,
            agility: c.agility,
            base_attack: c.base_attack,
            base_attack_bonus: c.base_attack_bonus,
            attack_power: c.attack_power,
            attack_speed: c.attack_speed,
            crit_chance: c.crit_chance,
            crit_multiplier: c.crit_multiplier,
            defense: c.defense,
            silver: c.silver as f64,
            copper: c.copper as f64,
            free_currency: c.free_currency as f64,
            premium_currency: c.premium_currency as f64,
            fame: c.fame,
            alignment: c.alignment,
            is_admin: c.is_admin,
            is_moderator: c.is_moderator,
            is_internal_network_test_user: false,
            default_pawn_class_path: None,
            base_mesh: None,
            class_name: c.class_id.map(|id| id.to_string()),
        }
    }
}

/// Convert a Vec<Character> to Vec<ProtoCharacter> without cloning the vec.
pub fn to_proto_characters(chars: &[Character]) -> Vec<ProtoCharacter> {
    chars.iter().map(ProtoCharacter::from).collect()
}
