use utoipa::OpenApi;

use crate::error::SuccessResponse;
use crate::models::*;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "ROWS — Rust Open World Server",
        description = "Single-binary game backend (REST + gRPC + WS) replacing the OWS .NET microservices for ChuckRPG. Surfaced through the kbve.com dashboard via a same-origin proxy that injects the tenant X-CustomerGUID header.",
        contact(
            name = "KBVE",
            url = "https://kbve.com",
            email = "support@kbve.com"
        ),
        license(name = "MIT"),
        version = env!("CARGO_PKG_VERSION"),
    ),
    servers(
        (url = "/dashboard/chuckrpg/proxy", description = "Same-origin staff proxy (DASHBOARD_VIEW, X-CustomerGUID injected by axum-kbve)"),
        (url = "http://localhost:4322", description = "Local ROWS (set X-CustomerGUID manually)"),
    ),
    paths(
        crate::rest::root,
        crate::rest::health,
        crate::rest::readiness,
        crate::rest::system::fleet_status,
        crate::rest::system::aggregated_health,
        crate::rest::system::active_players,
        crate::rest::system::instance_log,
        crate::rest::system::deployment_info,
        crate::rest::system::report_build,
        crate::rest::system::restart_game_server,
        crate::rest::system::restart_fleet,
        crate::rest::system::verify_deployment,
        crate::rest::system::fleet_restart_status,
        crate::rest::system::fleet_restart_pending,
        crate::rest::system::fleet_restart_trigger,
        crate::rest::system::fleet_restart_clear,
        crate::rest::auth::login,
        crate::rest::auth::external_login,
        crate::rest::auth::get_user_session,
        crate::rest::auth::get_all_characters,
        crate::rest::auth::get_server_to_connect_to,
        crate::rest::auth::get_char_by_name_public,
        crate::rest::auth::system_status,
        crate::rest::auth::register_user,
        crate::rest::auth::logout,
        crate::rest::auth::create_character,
        crate::rest::auth::remove_character,
        crate::rest::auth::create_char_defaults,
        crate::rest::auth::set_selected_char,
        crate::rest::auth::user_session_set_selected_char,
        crate::rest::auth::get_player_groups,
        crate::rest::auth::get_default_custom_data,
        crate::rest::characters::get_char_by_name,
        crate::rest::characters::get_custom_data,
        crate::rest::characters::update_all_positions,
        crate::rest::characters::add_or_update_custom_data,
        crate::rest::characters::update_character_stats,
        crate::rest::characters::player_logout,
        crate::rest::characters::get_character_statuses,
        crate::rest::abilities::get_character_abilities,
        crate::rest::abilities::add_ability,
        crate::rest::abilities::remove_ability,
        crate::rest::abilities::update_ability,
        crate::rest::abilities::get_ability_bars,
        crate::rest::abilities::get_ability_bars_and_abilities,
        crate::rest::abilities::get_abilities_list,
        crate::rest::instances::set_zone_status,
        crate::rest::instances::get_zone_instances,
        crate::rest::instances::register_launcher,
        crate::rest::instances::start_instance_launcher,
        crate::rest::instances::shut_down_instance_launcher,
        crate::rest::instances::spin_up_server_instance,
        crate::rest::instances::shut_down_server_instance,
        crate::rest::instances::instance_get_server_to_connect_to,
        crate::rest::instances::get_zone_instances_for_zone,
        crate::rest::instances::get_current_world_time,
        crate::rest::instances::update_number_of_players,
        crate::rest::instances::get_zone_instance,
        crate::rest::instances::get_server_instance_from_port,
        crate::rest::instances::get_zone_assignment,
        crate::rest::zones::add_zone,
        crate::rest::global_data::set_global_data,
        crate::rest::global_data::get_global_data,
        crate::rest::management::list_users,
        crate::rest::management::create_user_admin,
        crate::rest::management::edit_user_admin,
    ),
    components(schemas(
        HealthResponse,
        SuccessResponse,
        LoginResult,
        Character,
        UserSession,
        UserSessionWithCharacter,
        ZoneInstance,
        JoinMapResult,
        GlobalData,
        CustomCharacterData,
        CharacterAbility,
        CustomDataRows,
        AbilityBar,
        AbilityBarAbility,
        ServerInstanceInfo,
        CharacterStatus,
        PlayerGroupMembership,
        UserInfo,
        crate::rest::system::InstanceEvent,
        crate::rest::system::FleetRestartStatus,
        crate::rest::system::FleetRestartPending,
    )),
    tags(
        (name = "health", description = "Health and readiness probes"),
        (name = "system", description = "Dashboard endpoints — fleet, health, active players, instance log, deployment metadata, restart + verification ops."),
        (name = "auth", description = "Login, registration, session management"),
        (name = "characters", description = "Character CRUD, stats, custom data"),
        (name = "instances", description = "Server instance lifecycle"),
        (name = "abilities", description = "Character ability management"),
        (name = "zones", description = "Zone management"),
        (name = "global", description = "Global key-value data"),
        (name = "users", description = "Admin user management (list, create, edit)"),
    )
)]
pub struct ApiDoc;
