// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace RareIcon.Native
{
    public static unsafe partial class Uniti
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "uniti";
#endif
        





        /// <summary>
        ///  Create an inventory with the given slot capacity.
        ///  Caller must free with `uniti_inventory_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_inventory_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* uniti_inventory_new(uint max_slots);

        /// <summary>
        ///  Free an inventory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_inventory_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void uniti_inventory_free(void* inv);

        /// <summary>
        ///  Add items to the inventory. Returns overflow count (0 = all fit).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_inventory_add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint uniti_inventory_add(void* inv, ushort item_id, uint quantity);

        /// <summary>
        ///  Remove items from the inventory. Returns amount actually removed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_inventory_remove", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint uniti_inventory_remove(void* inv, ushort item_id, uint quantity);

        /// <summary>
        ///  Count total quantity of an item kind.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_inventory_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint uniti_inventory_count(void* inv, ushort item_id);

        /// <summary>
        ///  Number of occupied slots.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_inventory_slot_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint uniti_inventory_slot_count(void* inv);

        /// <summary>
        ///  Read a specific slot. Returns FfiSlot with valid=0 if out of bounds.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_inventory_get_slot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiSlot uniti_inventory_get_slot(void* inv, uint index);

        /// <summary>
        ///  Check if the inventory has room for a quantity of an item.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_inventory_has_room", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte uniti_inventory_has_room(void* inv, ushort item_id, uint quantity);

        /// <summary>
        ///  Swap two slots. Returns 1 on success, 0 on failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_inventory_swap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte uniti_inventory_swap(void* inv, uint a, uint b);

        /// <summary>
        ///  Split a stack. Returns 1 on success, 0 on failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_inventory_split", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte uniti_inventory_split(void* inv, uint slot, uint quantity);

        /// <summary>
        ///  Merge slot `from` into slot `to`. Returns items moved.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_inventory_merge", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint uniti_inventory_merge(void* inv, uint from, uint to);

        /// <summary>
        ///  Compact fragmented stacks.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_inventory_compact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void uniti_inventory_compact(void* inv);

        /// <summary>
        ///  Clear all items.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_inventory_clear", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void uniti_inventory_clear(void* inv);

        /// <summary>
        ///  Create an empty grid. Caller must free with `uniti_grid_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_grid_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* uniti_grid_new(int origin_x, int origin_z, uint width, uint depth);

        /// <summary>
        ///  Set a cell in the grid.
        ///
        ///  `surface_kind`: 0=Blocked, 1=Solid, 2=Slow, 3=Hazard
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_grid_set", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void uniti_grid_set(void* grid, int x, int z, int height, byte surface_kind);

        /// <summary>
        ///  Check if a cell is walkable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_grid_is_walkable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte uniti_grid_is_walkable(void* grid, int x, int z);

        /// <summary>
        ///  Free a grid allocated by `uniti_grid_new`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_grid_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void uniti_grid_free(void* grid);

        /// <summary>
        ///  Compute a flow field toward the given goals.
        ///
        ///  `goals_ptr` is a flat array of `[x0, z0, x1, z1, ...]` with `goal_count` pairs.
        ///  Caller must free the result with `uniti_flow_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_flow_compute", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* uniti_flow_compute(void* grid, int* goals_ptr, uint goal_count);

        /// <summary>
        ///  Compute a flee field (away from sources).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_flow_compute_flee", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* uniti_flow_compute_flee(void* grid, int* sources_ptr, uint source_count);

        /// <summary>
        ///  Query the direction at a cell.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_flow_direction", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiDirection uniti_flow_direction(void* field, int x, int z);

        /// <summary>
        ///  Query the BFS distance to the nearest goal. Returns u32::MAX if unreachable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_flow_distance", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint uniti_flow_distance(void* field, int x, int z);

        /// <summary>
        ///  Free a flow field allocated by `uniti_flow_compute` or `uniti_flow_compute_flee`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_flow_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void uniti_flow_free(void* field);

        /// <summary>
        ///  Create a new world store. Spawns a background tick thread immediately.
        ///  Returns an opaque handle the caller must eventually pass to
        ///  `uniti_world_free`. Returns null only if thread spawn fails.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_world_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* uniti_world_new();

        /// <summary>
        ///  Drop the store. Stops the background thread and frees all chunk state.
        ///  Calling this twice on the same handle is undefined behavior.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_world_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void uniti_world_free(void* world);

        /// <summary>
        ///  Returns 1 if any state is stored for the chunk that owns this hex.
        ///  Cheap fast-path for chunk-load: skip the per-hex queries entirely if 0.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_world_has_chunk", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte uniti_world_has_chunk(void* world, int cx, int cy);

        /// <summary>
        ///  Read the saved override for a hex. `valid=0` means no override exists
        ///  (caller falls back to deterministic gen).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_world_get_hex", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiHexLookup uniti_world_get_hex(void* world, int q, int r);

        /// <summary>
        ///  Save a hex's resource state. Caller is responsible for only calling
        ///  this on hexes that actually diverged from the gen-time roll.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_world_save_hex", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void uniti_world_save_hex(void* world, int q, int r, FfiHexResources res);

        /// <summary>
        ///  Push a ghost unit into the store. Chunk is derived from unit position.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_world_save_unit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void uniti_world_save_unit(void* world, FfiGhostUnit unit);

        /// <summary>
        ///  Drain all ghost units in a chunk into the caller's buffer.
        ///  Returns the number of units written. Units that fit are removed from
        ///  the store; if `cap` is too small, the unwritten ones stay (and the
        ///  caller can call again with a bigger buffer to drain the rest).
        ///
        ///  `out_buf` must be a valid pointer to an array of at least `cap`
        ///  `FfiGhostUnit` values.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_world_take_units_in_chunk", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint uniti_world_take_units_in_chunk(void* world, int cx, int cy, FfiGhostUnit* out_buf, uint cap);

        /// <summary>
        ///  How many ghost units are stored for a chunk. Useful for sizing the
        ///  buffer before `uniti_world_take_units_in_chunk`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_world_unit_count_in_chunk", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint uniti_world_unit_count_in_chunk(void* world, int cx, int cy);


    }

    /// <summary>
    ///  Slot data returned to C#.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct FfiSlot
    {
        public ushort item_id;
        public uint quantity;
        public byte valid;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct FfiDirection
    {
        public int dx;
        public int dz;
        public byte valid;
    }

    /// <summary>
    ///  Per-hex resource amounts, mirrors the C# HexResources struct exactly.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct FfiHexResources
    {
        public byte wood;
        public byte stone;
        public byte berries;
        public byte mushrooms;
        public byte herbs;
        public byte cactus;
        public byte cactus_variant;
    }

    /// <summary>
    ///  Result of `uniti_world_get_hex` — `valid=0` means "no override stored,
    ///  caller should fall back to deterministic gen".
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct FfiHexLookup
    {
        public byte valid;
        public FfiHexResources res;
    }

    /// <summary>
    ///  A ghost unit — abstract state of a unit that lived in an unloaded chunk.
    ///  Position is in hex-axial coords; the chunk it belongs to is derived by
    ///  the caller (currently `chunk = floor(q / 32), floor(r / 32)`).
    ///
    ///  Inventory carries the first 4 slots only — matches the HUD snapshot
    ///  shape and keeps the FFI struct flat (~50 bytes per unit).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct FfiGhostUnit
    {
        public byte unit_type;
        public int q;
        public int r;
        public float health;
        public float max_health;
        public ushort inv0_id;
        public ushort inv0_qty;
        public ushort inv1_id;
        public ushort inv1_qty;
        public ushort inv2_id;
        public ushort inv2_qty;
        public ushort inv3_id;
        public ushort inv3_qty;
    }



}
