// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace RareIcon.Native
{
    public static unsafe partial class Uniti
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "uniti";
#endif
        





        /// <summary>
        ///  Create an empty grid. Caller must free with `uniti_grid_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_grid_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* uniti_grid_new(int origin_x, int origin_z, uint width, uint depth);

        /// <summary>
        ///  Set a cell in the grid.
        ///
        ///  `surface_kind`: 0=Blocked, 1=Solid, 2=Slow, 3=Hazard
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_grid_set", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void uniti_grid_set(void* grid, int x, int z, int height, byte surface_kind);

        /// <summary>
        ///  Check if a cell is walkable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_grid_is_walkable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte uniti_grid_is_walkable(void* grid, int x, int z);

        /// <summary>
        ///  Free a grid allocated by `uniti_grid_new`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_grid_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void uniti_grid_free(void* grid);

        /// <summary>
        ///  Compute a flow field toward the given goals.
        ///
        ///  `goals_ptr` is a flat array of `[x0, z0, x1, z1, ...]` with `goal_count` pairs.
        ///  Caller must free the result with `uniti_flow_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_flow_compute", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* uniti_flow_compute(void* grid, int* goals_ptr, uint goal_count);

        /// <summary>
        ///  Compute a flee field (away from sources).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_flow_compute_flee", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* uniti_flow_compute_flee(void* grid, int* sources_ptr, uint source_count);

        /// <summary>
        ///  Query the direction at a cell.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_flow_direction", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern FfiDirection uniti_flow_direction(void* field, int x, int z);

        /// <summary>
        ///  Query the BFS distance to the nearest goal. Returns u32::MAX if unreachable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_flow_distance", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint uniti_flow_distance(void* field, int x, int z);

        /// <summary>
        ///  Free a flow field allocated by `uniti_flow_compute` or `uniti_flow_compute_flee`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "uniti_flow_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void uniti_flow_free(void* field);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct FfiDirection
    {
        public int dx;
        public int dz;
        public byte valid;
    }



}
