apiVersion: v1
kind: ConfigMap
metadata:
  name: disoxide-config
  namespace: disoxide
  labels:
    app: disoxide
data:
  PUBLIC_SUPABASE_URL: "https://api.kbve.com"
  PUBLIC_SUPABASE_ANON_KEY: "placeholder-anon-key"
  PUBLIC_API_URL: "https://api.kbve.com"
  PUBLIC_WS_URL: "wss://ws.kbve.com"
  PUBLIC_DISCORD_CLIENT_ID: "placeholder-discord-client-id"
  PUBLIC_ENV: "production"