---
apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: kilobase
  labels:
    app: kong-alias
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 80
    protocol: TCP
    name: http

---
apiVersion: v1
kind: Endpoints
metadata:
  name: kong
  namespace: kilobase
subsets:
- addresses:
  - ip: "10.99.61.11"  # kong-kong-proxy service IP
  ports:
  - port: 80
    name: http