# Kong Gateway Configuration
image:
  repository: kong
  tag: "3.9.1"
  
# Deployment configuration
replicaCount: 2

# Environment variables
env:
  # Database mode - using DB-less mode for simplicity
  database: "off"
  
  # Use declarative config
  declarative_config: "/kong/kong.yml"
  
  # Admin API configuration
  admin_api_uri: "http://kong-admin.kilobase.svc.cluster.local:8001"
  admin_gui_url: "http://kong-manager.kilobase.svc.cluster.local:8002"
  
  # Proxy configuration
  proxy_url: "http://kong.kilobase.svc.cluster.local"
  
  # Plugins
  plugins: "bundled,cors,rate-limiting,jwt,oauth2,acl,request-transformer,response-transformer"
  
  # Logging
  log_level: "info"

# Map secret keys to environment variables Kong expects
extraEnvFrom:
- secretRef:
    name: supabase-jwt
  
# Service configuration  
proxy:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 80
    containerPort: 8000
  tls:
    enabled: true
    servicePort: 443
    containerPort: 8443

# Admin API
admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001

# Manager (GUI)
manager:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8002
    containerPort: 8002

# Portal (Developer Portal)
portal:
  enabled: false

# Status API
status:
  enabled: true
  http:
    enabled: true
    containerPort: 8100

# Ingress configuration - disabled since we're using nginx ingress
ingressController:
  enabled: false

# Resource limits
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

# Init containers for config templating
initContainers:
- name: config-templater
  image: busybox:1.36
  command: ["sh", "-c"]
  args:
  - |
    envsubst < /kong-template/kong.yml > /kong/kong.yml
  env:
  - name: anon_key
    valueFrom:
      secretKeyRef:
        name: supabase-jwt
        key: anon-key
  - name: service_key
    valueFrom:
      secretKeyRef:
        name: supabase-jwt
        key: service-key
  - name: secret
    valueFrom:
      secretKeyRef:
        name: supabase-jwt
        key: secret
  volumeMounts:
  - name: kong-config-template
    mountPath: /kong-template
  - name: kong-config-processed
    mountPath: /kong

# Volume mounts for Kong configuration
extraConfigMaps:
- name: kong-config
  mountPath: /kong-template

extraVolumes:
- name: kong-config-processed
  emptyDir: {}

extraVolumeMounts:
- name: kong-config-processed
  mountPath: /kong

# Monitoring
serviceMonitor:
  enabled: true
  labels:
    app: kong