---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: factorio-credentials
    namespace: factorio
spec:
    encryptedData:
        token: AgBvr24xbLdcAdOVB4TxT09HBUXZ0kIsiuQ8aKDZPHH3MlnGxUUNF4/HTUA9Riz23nxaFYOLu7uC0bqkl2DFZcgRzakZ70ilHOsKxpiJfs8Oi1vjtaYa4q9W8TItA7yX9Ut+fuEog376dVU/3LIFMtZBpqMnyrazhHVXwryZtvvxTqYOE2KWGyCfeORQVh72zkrJNg9QrJzFYeBOwf5gPWXoWH6kkUO5hZdDghOzHp4zpO1n1VOm1xZKEbNXcj7+FA0U9xObPnrZC2IhLk/of6Z+YMPGrb+4pvq7Dfo22qKzpt4XbxZGvT0KW7tVmcPfmw3HOAGVCBpgo8mP2RG4HyZWDaFfjidJNik5oWDRR769tvULty3dqrth1ZbxpkH11Ns+lotW2ykhRlnNg6vAF97cRnLjKPZ0Jry1nLxnlq0L/eA6mxLgwhZn2ByyawpEdWe5+WKr2FXXS+NqOzPe0zEOUSJ25ed9mfZ0OgFaWK1OJx7Z2sXASl2K3by+enFinoaXyeq3CL44Nm9YeoApEeAaAzA0ReZgMqPGVlERj9HyUkY1Gbl7QzqW4Zenhc6a0bqJPxhxGCY69LhWSzusAP4DaBBDNbEnsfsaWC5slz6tWtfd/GF2i5yywDY5ocYy1aB3keSc4jQ39eXlkiPKJv0XBosLKFEOmKPmfK4zYJ3SYe6yrJXwfmR8DAjz19HW2N1gVqc4x0pYeX5xM2zncgVUW5kzHrcyVYZUII6fAPQ=
        username: AgB9rRmTVKXkfNq+4/c17QFkuxCcH/NyrZYvO+h9G7ahAVQT27XBhTOG36y9t7F2QVwFFUfSXjKihATS2hjLQA3kO4lIyZj6hkchb7kr4u4n3kZfNV7UDBWsMkYbySD1S4wjFsrE2AEsmSc+dFViJFT4i0CoJO0TpZDmzm0n9Tq+6tqcsItIRNM/8zYRFfekExBriT+90FDxnTB+VuclDmd5mwGr56axpR4UYr47SS17oXJSNUr7piAzgBj1n9DEKJEVZpLms7/fBSuGputm7Yk73Wx7tPIUBPxapEB9EbuGrxrXGLMcsp0WbNLElRE5uRGuex3pU/1AwnF/8lJoOQyFE7WSf4S0VDZ1S6aprSkGvPQlnSd7WsG1e6OWTVarxSd9OsQhgxP8eq88trdh/MX5qeqpQT0WRVXdQxwM0rExmGI8EGM6NptSIitO/vYWpZqy5Xo2mG2BKPia7/AREiEszC6ifFiAgMkFq3MpR6GtFZqu94S8dc8sVYHZCAz6OyV1wyJhLPcAG3PHynqJG+5ic2i838pHg3ZFB8RJlcjbrg2zylrsN2HjiIAIP6AejxsPXf0G1VNr6IldHTecw3WqomnAiqcePXgdXEUXlmHebalWsUFcH1MoOcI/537Q7s3UyeyXY/mDENMH/zN329J8UEG4YD7EHO4mCAyW+i2jlyXwOqxUty3ADZtegtc7WVvB/l1/DWMjrA==
    template:
        metadata:
            name: factorio-credentials
            namespace: factorio
