---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: factorio-rcon
    namespace: factorio
spec:
    encryptedData:
        rcon_password: AgDFpss85/jF6PvnKNDOgeKoEMTDXp9/8rczADvJDs6W4TU6umos3+ywI9kBmCXjo6zI6LIlIebLtYusuXR3sp7mHBUMGOtvDA2EO6aQqgBi8kdgqpFZwGxLXfUTuNuH/QtPDNgaSxm4uCkcdX9hU8cMLbY1aiLmGLmjJQGPKfC7u/rvpr8Xwqu2L2M5CjAKK8rCdIpoDVZTTDGSN5cYTLRSjUPCTJu00dtgiqGFE/8QWyKh/y9OBaw77yGSES1jl1oiYzKfqIyUBIy1OTiiFKt0WOOUkrF2wRtP2UK6oyT1VbM26Vk2C0jHYMV7AsKDwpIpqkbNYHJ2ehObtJW1ljpj9rzPgpZmLN+NnfVkhisu5uThygc/wTUD79vrOQOyI4OFsy0P9b4N5ENHxzsoHsGONSMIqrwMadLWhjnPHlrE1IMaDrCXELNdIPonEOQ0WBzlB+X9XD/VajM3feqpsgLHQY5V7xEj/lPsimWqzxPhcU4Dnwx24E1uMKeAd6Mj/mVprHQYYJqbSCHKoyYsXRjS+rcg79+1hqCKudvWL5znatx+ExG8PX/9bDdHTaRflQnNOUCK6GqUrqS0mXeqoDRPll5j3QRG3xP7kW9qSglZ8YmBCF0jnRvj71ihqD0u7OfNvQF8rTh4rkCQu1Y7dmUVzLQIpT39ij1lGBqTwgUWEyJSEM6VxeJq2bw/jrACULgbzbiGGuqECr9qRE4JiYZOLKB926O6H6JZ/C0StfaEPFmnf53cZnC9jOFQDruYQaA=
    template:
        metadata:
            name: factorio-rcon
            namespace: factorio
