apiVersion: v1
kind: Service
metadata:
  name: rest
  namespace: kilobase
  labels:
    app: postgrest
    component: rest
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: postgrest