apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: elk-stack
    namespace: argocd
    labels:
        kbve.sh/app: elk
        kbve.sh/component: stack
    annotations:
        argocd.argoproj.io/sync-wave: '3'
        kbve.sh/last-updated: '2026-03-20'
spec:
    project: default
    sources:
        - repoURL: https://github.com/kbve/kbve
          targetRevision: main
          path: apps/kube/elk/manifests
    destination:
        server: https://kubernetes.default.svc
        namespace: elastic-stack
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
        syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
