apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: kilobase
  labels:
    app: storage-api
    component: storage
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: storage-api