[package]
name = "axum-herbmail"
authors = ["kbve", "h0lybyte"]
version = "0.1.2"
edition = "2021"
rust-version.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
thiserror = "2"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tower = { workspace = true, features = ["util", "timeout", "load-shed", "limit"] }
tower-http = { workspace = true, features = ["compression-full", "limit", "trace", "fs", "cors", "set-header"] }
tokio = { workspace = true, features = ["default", "full", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["default", "env-filter"] }
axum = { version = "0.8.5", features = ["ws", "macros"] }
axum-extra = { workspace = true, features = ["cookie"] }
askama = "0.15.4"
socket2 = { workspace = true }
num_cpus = { workspace = true }
dotenvy = { workspace = true }

# Workspace path dependencies
jedi = { path = "../../../packages/rust/jedi" }
kbve = { path = "../../../packages/rust/kbve" }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { workspace = true, optional = true }

[dev-dependencies]
serial_test = { workspace = true }
http-body-util = { workspace = true }

[features]
default = []
jemalloc = ["dep:tikv-jemallocator"]

[package.metadata.askama]
dirs = ["templates"]
