use std::fs;
use std::path::Path;
use std::process::Command;

/// Proto module names that src/proto/mod.rs expects via include!()
const PROTO_MODULES: &[&str] = &[
    "kbve.common",
    "kbve.enums",
    "kbve.snapshot",
    "kbve.pool",
    "kbve.schema",
    "kbve.osrs",
    "kbve.rcon",
];

fn protoc_available() -> bool {
    Command::new("protoc")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Write empty stubs so `include!(concat!(env!("OUT_DIR"), "/kbve.X.rs"))` compiles
fn write_proto_stubs(out_dir: &str) {
    for module in PROTO_MODULES {
        let path = Path::new(out_dir).join(format!("{module}.rs"));
        if !path.exists() {
            let _ = fs::write(
                &path,
                "// proto stub — protoc was not available at build time\n",
            );
        }
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = std::env::var("OUT_DIR").unwrap();

    // Proto file locations docker/CI: /proto/kbve/ and Monorepo local dev: ../../../packages/data/proto/kbve/
    let docker_proto_dir = Path::new("/proto/kbve");
    let local_proto_dir = Path::new("../../../packages/data/proto/kbve");

    let (proto_dir, include_dir) = if docker_proto_dir.exists() {
        (docker_proto_dir, Path::new("/proto"))
    } else if local_proto_dir.exists() {
        (local_proto_dir, Path::new("../../../packages/data/proto"))
    } else {
        println!("cargo:warning=Proto directory not found, skipping protobuf compilation");
        write_proto_stubs(&out_dir);
        return Ok(());
    };

    if !protoc_available() {
        println!("cargo:warning=protoc not found, skipping protobuf compilation");
        write_proto_stubs(&out_dir);
        return Ok(());
    }

    let proto_files = vec![
        proto_dir.join("common.proto"),
        proto_dir.join("enums.proto"),
        proto_dir.join("snapshot.proto"),
        proto_dir.join("pool.proto"),
        proto_dir.join("schema.proto"),
        proto_dir.join("osrs.proto"),
        proto_dir.join("rcon.proto"),
    ];

    for proto in &proto_files {
        if !proto.exists() {
            println!("cargo:warning=Proto file not found: {:?}", proto);
            write_proto_stubs(&out_dir);
            return Ok(());
        }
    }

    prost_build::Config::new().compile_protos(
        &proto_files.iter().map(|p| p.as_path()).collect::<Vec<_>>(),
        &[include_dir],
    )?;

    for proto in &proto_files {
        println!("cargo:rerun-if-changed={}", proto.display());
    }

    generate_osrs_family_redirects(&out_dir)?;

    Ok(())
}

/// Codegen the OSRS family redirect table from the committed
/// `osrs_family_redirects.json` (produced by the Python resolver). The JSON
/// lives inside the crate, so it is always present in the build context; the
/// generated `OSRS_FAMILY_REDIRECTS` slice is written to OUT_DIR and pulled in
/// via include!() from src/transport/osrs_family_redirects.rs.
fn generate_osrs_family_redirects(out_dir: &str) -> Result<(), Box<dyn std::error::Error>> {
    let json_path = Path::new("src/transport/osrs_family_redirects.json");
    println!("cargo:rerun-if-changed={}", json_path.display());

    let routes: Vec<(String, String)> = if json_path.exists() {
        let raw = fs::read_to_string(json_path)?;
        let parsed: serde_json::Value = serde_json::from_str(&raw)?;
        parsed
            .get("routes")
            .and_then(|r| r.as_array())
            .map(|arr| {
                arr.iter()
                    .filter_map(|pair| {
                        let a = pair.get(0)?.as_str()?.to_string();
                        let b = pair.get(1)?.as_str()?.to_string();
                        Some((a, b))
                    })
                    .collect()
            })
            .unwrap_or_default()
    } else {
        println!("cargo:warning=osrs_family_redirects.json missing; empty redirect table");
        Vec::new()
    };

    let mut out = String::from(
        "// @generated by build.rs from osrs_family_redirects.json. DO NOT EDIT.\n\
         /// Member-page URLs that permanently redirect to their family page.\n\
         pub static OSRS_FAMILY_REDIRECTS: &[(&str, &str)] = &[\n",
    );
    for (src, dst) in &routes {
        out.push_str(&format!("    ({src:?}, {dst:?}),\n"));
    }
    out.push_str("];\n");

    fs::write(Path::new(out_dir).join("osrs_family_redirects.rs"), out)?;
    Ok(())
}
