apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-secret-store
  namespace: kilobase
spec:
  provider:
    kubernetes:
      remoteNamespace: kilobase
      auth:
        serviceAccount:
          name: external-secrets-sa
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: kube-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgrest-db-uri
  namespace: kilobase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secret-store
    kind: SecretStore
  target:
    name: postgrest-db-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PGRST_DB_URI: |
          postgres://authenticator:{{ .password }}@supabase-cluster-rw.kilobase.svc.cluster.local:5432/postgres?sslmode=disable
  data:
  - secretKey: password
    remoteRef:
      key: supabase-cluster-app
      property: password