apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kubevirt-autologon
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-wave: '4'
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    project: default
    source:
        repoURL: https://github.com/KBVE/kbve
        targetRevision: main
        path: apps/kube/kubevirt/autologon
    destination:
        server: https://kubernetes.default.svc
        namespace: angelscript
    syncPolicy:
        automated:
            prune: true
            selfHeal: false
        syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
        retry:
            limit: 3
            backoff:
                duration: 30s
                factor: 2
                maxDuration: 10m
    revisionHistoryLimit: 3
