use std::collections::HashMap;

use bevy::prelude::{Commands, Local, Res, ResMut};
use bevy_items::{StatusEffectKind, UseEffect, UseEffectType};
use simgrid::arpg_dungeon;
use simgrid::proto::{StatusKind, Tile};
use simgrid::{
    AggroSpec, BuffEffects, BuffSpec, ConsumableEffects, EnvOpts, HazardZone, HealAura,
    KindRegistry, NpcSpec, SIM_TICK_HZ, SimConfig, Stairs, WalkableMap, ground_item_bundle,
    spawn_env_object, spawn_npc_from_spec,
};

pub const MAX_PLAYERS: usize = 32;

// Endless dungeon shared with the client. The seed MUST equal the client's
// DUNGEON_SEED (isometric-arpg/config.ts) so server collision matches the tiles
// the client predicts. Collision is computed on demand from the seed — nothing
// is stored, so the world is unbounded. PATH_WINDOW only caps find_path's BFS
// frontier (an open grid needs a search bound); movement itself has no edges.
pub const DUNGEON_SEED: u32 = 0x5eed1;
pub const PATH_WINDOW: i32 = 96;

pub const PLAYER_HP: i32 = 100;
pub const PLAYER_ATTACK: i32 = 5;
pub const PLAYER_TICKS_PER_TILE: u8 = 3;
// Aim spawn near the client's debug spawn tile; snap to the nearest floor so a
// player never drops into rock.
pub const PLAYER_SPAWN_HINT: Tile = Tile::new(12, 12);
pub const PLAYER_SAFE_RADIUS: i32 = 6;

pub const NPC_RESPAWN_TICKS: u32 = SIM_TICK_HZ * 30;

pub const GOBLIN_REF: &str = "goblin";
pub const GOBLIN_COUNT: i32 = 6;
pub const GOBLIN_LOOT_REF: &str = "coin";

// Descending the stairs to a deeper floor needs a dungeon key the player must
// find/loot. Ascending is always free.
pub const STAIR_KEY_REF: &str = "dungeon-key";
pub const GOBLIN_HP: i32 = 24;
pub const GOBLIN_DAMAGE: i32 = 3;
pub const GOBLIN_DEFENSE: i32 = 0;
pub const GOBLIN_TICKS_PER_TILE: u8 = 6;
pub const HOSTILE_AGGRO_RANGE: i32 = 6;

// Campfire: a placed env object near spawn. Blocks its tile, heals players in the
// adjacent ring, and burns anything forced onto the tile. Tuning is hardcoded
// here for the MVP; #12972 will read it from the `campfire` itemdb entry.
pub const CAMPFIRE_REF: &str = "campfire";
pub const CAMPFIRE_HEAL_RANGE: i32 = 2;
pub const CAMPFIRE_HEAL_AMOUNT: i32 = 3;
pub const CAMPFIRE_BURN_AMOUNT: i32 = 8;
pub const CAMPFIRE_PERIOD_TICKS: u32 = SIM_TICK_HZ;

/// Ground floor — players spawn here; stairs descend to deeper floors.
pub const SPAWN_FLOOR: i32 = 0;

/// Player spawn snapped onto a real floor tile of the ground floor.
pub fn player_spawn() -> Tile {
    let (x, y) = arpg_dungeon::nearest_floor(
        DUNGEON_SEED,
        SPAWN_FLOOR,
        PLAYER_SPAWN_HINT.x,
        PLAYER_SPAWN_HINT.y,
        arpg_dungeon::CHUNK_SIZE,
    );
    Tile::new(x, y)
}

/// Nearest floor tile to a hint on the ground floor — keeps spawns out of rock.
fn floor_near(hint: Tile) -> Tile {
    let (x, y) = arpg_dungeon::nearest_floor(
        DUNGEON_SEED,
        SPAWN_FLOOR,
        hint.x,
        hint.y,
        arpg_dungeon::CHUNK_SIZE,
    );
    Tile::new(x, y)
}

pub fn registry() -> KindRegistry {
    let mut reg = KindRegistry::new();
    reg.register_npc(GOBLIN_REF);
    reg.register_item(GOBLIN_LOOT_REF);
    reg.register_item(STAIR_KEY_REF);
    reg.register_env(CAMPFIRE_REF);
    reg
}

/// Full itemdb registry, embedded from the canonical proto binary
/// (`itemdb-data.binpb`, an `item.ItemRegistry`). Carries every item's data —
/// names, prices, use_effects/status_effect, food/regen — so server systems
/// resolve any ref without a DB round-trip. Regenerated by `sync:itemdb`.
pub fn item_db() -> bevy_items::ItemDb {
    bevy_items::ItemDb::from_bytes(include_bytes!(
        "../../../../../packages/data/codegen/generated/itemdb-data.binpb"
    ))
    .expect("embedded itemdb-data.binpb decodes as item.ItemRegistry")
}

/// FullHeal has no amount on the wire — use a large heal; `use_item` clamps to
/// max_hp.
const FULL_HEAL: i32 = 9_999;

/// Map an itemdb `StatusEffectKind` onto the three runtime `StatusKind`s the sim
/// supports. Burning collapses to Poison (both periodic damage); unsupported
/// effects return `None` so the item simply grants no buff.
fn map_status(raw: i32) -> Option<StatusKind> {
    match StatusEffectKind::try_from(raw).ok()? {
        StatusEffectKind::StatusEffectRegen => Some(StatusKind::Regen),
        StatusEffectKind::StatusEffectHaste => Some(StatusKind::Haste),
        StatusEffectKind::StatusEffectPoison | StatusEffectKind::StatusEffectBurning => {
            Some(StatusKind::Poison)
        }
        _ => None,
    }
}

/// Fold one itemdb `UseEffect` into the consumable-heal / status-buff maps.
fn ingest_effect(
    ref_id: &str,
    ue: &UseEffect,
    heals: &mut HashMap<String, i32>,
    buffs: &mut HashMap<String, BuffSpec>,
) {
    match UseEffectType::try_from(ue.r#type) {
        Ok(UseEffectType::UseEffectHeal) => {
            if let Some(a) = ue.amount {
                heals.entry(ref_id.to_string()).or_insert(a);
            }
        }
        Ok(UseEffectType::UseEffectFullHeal) => {
            heals.entry(ref_id.to_string()).or_insert(FULL_HEAL);
        }
        Ok(UseEffectType::UseEffectApplyEffect) => {
            if let Some(kind) = ue.status_effect.and_then(map_status) {
                let turns = ue.turns.unwrap_or(8).max(1) as u32;
                let magnitude = ue.amount.or(ue.stacks).unwrap_or(2).max(1);
                // Haste is a flat move-speed modifier (no periodic tick); damage
                // and regen tick about once per second.
                let period_ticks = if kind == StatusKind::Haste {
                    0
                } else {
                    SIM_TICK_HZ
                };
                buffs.entry(ref_id.to_string()).or_insert(BuffSpec {
                    kind,
                    magnitude,
                    period_ticks,
                    duration_ticks: turns.saturating_mul(SIM_TICK_HZ),
                });
            }
        }
        _ => {}
    }
}

/// Derive consumable heals + status buffs from the itemdb so `UseItem` resolves
/// real effects instead of being a no-op. Reads each item's `use_effects` and
/// `food.buff_effects` / `food.heals`. This is the data-driven path (#12972) —
/// editing the MDX + `sync:itemdb` changes in-game item behavior with no code.
pub fn item_effects(db: &bevy_items::ItemDb) -> (ConsumableEffects, BuffEffects) {
    let mut heals: HashMap<String, i32> = HashMap::new();
    let mut buffs: HashMap<String, BuffSpec> = HashMap::new();
    for (_, item) in db.iter() {
        let ref_id = item.r#ref.as_str();
        for ue in &item.use_effects {
            ingest_effect(ref_id, ue, &mut heals, &mut buffs);
        }
        if let Some(food) = &item.food {
            for ue in &food.buff_effects {
                ingest_effect(ref_id, ue, &mut heals, &mut buffs);
            }
            if let Some(h) = food.heals
                && h > 0
            {
                heals.entry(ref_id.to_string()).or_insert(h);
            }
        }
    }
    (ConsumableEffects(heals), BuffEffects(buffs))
}

/// Endless dungeon stairs: two seed-derived stairs per floor (down + up).
/// Descending is gated on the dungeon key; ascending is free.
pub fn stairs() -> Stairs {
    Stairs::Dungeon {
        seed: DUNGEON_SEED,
        descend_key: Some(STAIR_KEY_REF.to_string()),
    }
}

pub fn config() -> SimConfig {
    SimConfig {
        player_kind: 0,
        player_hp: PLAYER_HP,
        player_attack: PLAYER_ATTACK,
        spawn: player_spawn(),
        ticks_per_tile: PLAYER_TICKS_PER_TILE,
        safe_radius: PLAYER_SAFE_RADIUS,
    }
}

pub fn walkable_map() -> WalkableMap {
    WalkableMap::arpg_dungeon(DUNGEON_SEED, PATH_WINDOW)
}

fn goblin_spec(registry: &KindRegistry, origin: Tile) -> Option<NpcSpec> {
    let kind = registry.kind_of(GOBLIN_REF)?;
    Some(NpcSpec {
        kind,
        origin,
        ticks_per_tile: GOBLIN_TICKS_PER_TILE,
        max_hp: GOBLIN_HP,
        level: 1,
        defense: GOBLIN_DEFENSE,
        wander: Some((8, 25)),
        aggro: Some(AggroSpec {
            range: HOSTILE_AGGRO_RANGE,
            damage: GOBLIN_DAMAGE,
            period_ticks: SIM_TICK_HZ,
            poison: None,
        }),
        loot: Some(GOBLIN_LOOT_REF.to_string()),
        respawn_ticks: NPC_RESPAWN_TICKS,
    })
}

pub fn spawn_world(
    mut done: Local<bool>,
    registry: Res<KindRegistry>,
    mut walkable: ResMut<WalkableMap>,
    mut commands: Commands,
) {
    if *done {
        return;
    }
    *done = true;

    // Seed a few goblins around the spawn room, each snapped to a floor tile so
    // none start embedded in rock. They wander/respawn within their own bounds,
    // so the sim only ticks this populated pocket of the endless dungeon.
    let spawn = player_spawn();
    for i in 0..GOBLIN_COUNT {
        let hint = Tile::new(spawn.x + 4 + (i % 3) * 2, spawn.y + 4 + (i / 3) * 2);
        let origin = floor_near(hint);
        if let Some(spec) = goblin_spec(&registry, origin) {
            spawn_npc_from_spec(&mut commands, &spec);
        }
    }

    // One starter loot pile near spawn.
    let coin = floor_near(Tile::new(spawn.x + 2, spawn.y + 1));
    if let Some(bundle) = ground_item_bundle(&registry, GOBLIN_LOOT_REF, 5, coin) {
        commands.spawn(bundle);
    }

    // A dungeon key on the ground floor so a fresh player can reach the stairs
    // down. Deeper floors gate their own keys via loot later.
    let key_tile = floor_near(Tile::new(spawn.x - 2, spawn.y + 2));
    if let Some(bundle) = ground_item_bundle(&registry, STAIR_KEY_REF, 1, key_tile) {
        commands.spawn(bundle);
    }

    // A campfire near spawn: blocks its tile, heals the adjacent ring, burns
    // anything forced onto it. Snap to a floor tile distinct from the player
    // spawn so no one starts trapped on it.
    let fire = floor_near(Tile::new(spawn.x + 3, spawn.y - 1));
    if fire != spawn
        && spawn_env_object(
            &mut commands,
            &registry,
            CAMPFIRE_REF,
            fire,
            EnvOpts {
                blocker: true,
                heal_aura: Some(HealAura {
                    range: CAMPFIRE_HEAL_RANGE,
                    magnitude: CAMPFIRE_HEAL_AMOUNT,
                    period_ticks: CAMPFIRE_PERIOD_TICKS,
                }),
                hazard: Some(HazardZone {
                    magnitude: CAMPFIRE_BURN_AMOUNT,
                    period_ticks: CAMPFIRE_PERIOD_TICKS,
                }),
                floor: SPAWN_FLOOR,
            },
        )
        .is_some()
    {
        walkable.block_tile_z(SPAWN_FLOOR, fire);
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn itemdb_embeds_and_decodes() {
        let db = super::item_db();
        assert!(
            db.len() >= 100,
            "embedded itemdb decoded {} items",
            db.len()
        );
        assert!(
            db.get_by_ref("campfire-kit").is_some(),
            "campfire-kit present"
        );
    }

    #[test]
    fn itemdb_effects_map_heal_and_buff() {
        let db = super::item_db();
        let (heals, buffs) = super::item_effects(&db);
        // potion: use_effects [{ HEAL, amount 15 }]
        assert_eq!(heals.0.get("potion").copied(), Some(15));
        // elixir: use_effects [{ FULL_HEAL }]
        assert_eq!(heals.0.get("elixir").copied(), Some(super::FULL_HEAL));
        // mana-potion: food.buff_effects [{ APPLY_EFFECT, REGEN }]
        let mana = buffs.0.get("mana-potion").expect("mana-potion buff");
        assert_eq!(mana.kind, super::StatusKind::Regen);
        assert!(!heals.0.is_empty() && !buffs.0.is_empty());
    }
}
