# ServiceAccount + RBAC for OWS Instance Launcher to create Agones GameServerAllocations
apiVersion: v1
kind: ServiceAccount
metadata:
    name: ows-instancelauncher
    namespace: ows
---
# Allow creating GameServerAllocations in arc-runners namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: agones-allocator-for-ows
    namespace: arc-runners
rules:
    - apiGroups: ['allocation.agones.dev']
      resources: ['gameserverallocations']
      verbs: ['create']
    - apiGroups: ['agones.dev']
      resources: ['gameservers']
      verbs: ['get', 'list', 'watch', 'delete']
    - apiGroups: ['agones.dev']
      resources: ['fleets', 'fleets/scale']
      verbs: ['get', 'patch', 'update']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: ows-launcher-agones-allocator
    namespace: arc-runners
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: agones-allocator-for-ows
subjects:
    - kind: ServiceAccount
      name: ows-instancelauncher
      namespace: ows
