apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: chuckrpg-tls
    namespace: chuckrpg
spec:
    secretName: chuckrpg-tls
    dnsNames:
        - chuckrpg.com
    issuerRef:
        name: letsencrypt-http
        kind: ClusterIssuer
        group: cert-manager.io
