---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: chuckrpg-secrets
    namespace: chuckrpg
spec:
    encryptedData:
        ITCH_API: AgArA+hJKKsDyEADfiIbG1Ppy4uiV1E6mVNgPtdMVGvZ2aa8VDGxY2PNmVpIG3R8yEWYJcwysaFY5/kLK7dCr4t28Bt/V4P9RwmMQ2HtekoHvujWAoyLxiV+J8gHXo4VuDkT0Eq2Ngo/VvBPa1i/PnFFPzCsA9Q1XFasqfY62oqhRRMLcKK1qq8gZU0ZZVEMS4m1QZFXvamU/1LAXPjtvl1Ev7WH9p8KCLy8ssWsLow9fsJLNo9mgwpAMuMVR7+Z5IL7A9rXqbyLL+h1h1SWG2R6X2RRoY8m+sKboa2Me0P5C5YUD+UiMZdnD5TjPckytmXbsjhpC5fnxleXo/gvozdYcty5aCVAlZskhlDsPEPui2RNYufAtAjhKrh9+fKOcg8UtDgWv4lIGTRrJ+8Lb8VdA4E+dlWtQPX2JepeQP8dJPdJ2O01NWtvJZGo+3PCzHXyFGqIW/3ojZUoVzZos6bqEg0R2d3p/8t9ZidqM6uCIjKCUzJL9dDRMcaarFPXtt52LN0Lfx2/nve8TrXB/P3VayI+DvOwe7Igbubn6BpBQ3HPBBcXdMO5Okm6WHJdcwnAYdriciUWcV4UpiIXJ6eeotchlQfD6XN/KcGGqpynspRGmH4EYOEkPj8OrG3vGy6xchuR2GmN9Grx2luKr1kRH246bhkbE+IQXXv8Re5U1h7CgkXSNF3va4RT4ZmHq0hG51sPZFkNjSmLEsK+2K1DCkKYJVfS4kBY4sybZEZsozzclPlbBFUt
    template:
        metadata:
            name: chuckrpg-secrets
            namespace: chuckrpg
