---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    creationTimestamp: null
    name: github-oauth-config
    namespace: kilobase
spec:
    encryptedData:
        client-id: AgB9NHmhlOysMMRmPIudYDQoey0uS/CHFrQwojHDgyRnehOuy6VhWUul1b6WCPeqHKbM4z4cSn9wDpKfzgEV1tNl7mRkSzV7a1/WoihRTUsmp9GN0j4Lb2m0X00M+sLM5Af/ONXDD3pc8DXbAzRD6ka45nAAPhMxSqpxbDBGHXWqlUYudN1tm1i7ILU9v7xJ9EyLP4C75BYR1x8Wj95OAw0P6a7xgAdWwdhV74k00P1HebmE5c/HNHSrPwurrrThVAvW08tUyz2pYzvBUeFBBm62vORqWh7E51eTi0Qu6ccn+fECJk335FeCNJmWwrIMf+pc/JxoMpwh5uQAPSwTibzO8Mg3A2vJbRN6BkouGju1NTOme6hqZU8LDGpKmH2rO9A9n4oe+OUhMInZo5EgkPAmaHc2Q7Agf0gvJ8Ij9ky5lGQf9Nrx5aImIzH9iQUj3I/6uTQPRC1DFab3D61Ew3+WJBC7el1X47tewRQk8Zh+D3QeCLaLRPkoGkL8h3zfAKbdV0PF2dPDRiMhzTW92GiIebQ2UuiriJsFnr3H1+ifF8ZEOM60ESSzRYPN7kz0mgUZl4wTm4lEsDlbULxQblvRCjPUivUPw7MBQKRZBiyRomGP4q8cgys2bA7AxnsZYCSLMkS5emr/W71wBJ8HAclP8yRw4Djhz7boTNUZDOVbtCEEcIZLygtpZQ9HlcEWK1L0C9OMbAU6nRJxjCjozl2X8720ug==
        client-secret: AgAxhZC2B3j/qpmSza5JLKUEeVDstf3rIRLCbcEkXcC/2DdYhcLw+T1F17aG/PYntbuGHycrj9w6cLUZ4EuXg8Y7zUXjCzdz6e5LRMO8m2Oed9F6AvialtN38JnsDsA0c2eYJB45fnRCG0tzTMcMgqukD0CpFjuJo1h8S/uCuoLNio2ldVycDblo9EwhelDPxGBhQQR92huEfOPp+c9tIPl/dkBuVTsEcLgB0J6YXwOy1jjXup494g9T8CYRnTErPvoQXmanYWOYgmeTp9AvxMvGapVPjYtTMosGAsoC54RWFvBrsAI5y9tiBiVMadqTHbg0TIqQwdvgmwKMCHFOz+JI5BitAbG325mX9YXIArdm5Ud+DKTxdXtxgiNQNvFwRFpaNcCgFfsDlVp+odBpcageunK5LdsjZxhQCTF9Z8sKj9Z1D3A7opo6oRZ/Oq9v4HDia/6EOiuhLOJoRZQGzYUn8mI1huO53iy5cRD0ByNe3nqhxpWTbf/5PuaHO339uYCs3Z3FTNPVmDTD+4IAffRLr76qg0KWYeuoClG/WbjPwulv5m8jMi1k8Zn1+ilyOqq2kJLwY0G49gCpAosbbVZbXu3m5kdFIa5APxTgs5wdbOS7Oibz0QZ0NH+Bol2oXZZwTVAj7E4Pd8xBTziF7ORYOkVXn0G1ASbxrkaxTmIOAC6VhvLqez9CevzpzlSzv4r1rFb74C2lGRKjiiOUCQYTfA8210Cdi1TwzEjL2mdZsqPn6dQZEv3r
    template:
        metadata:
            creationTimestamp: null
            name: github-oauth-config
            namespace: kilobase
        type: Opaque
