apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-authserver
  namespace: ac
  labels:
    app: azerothcore
    component: authserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azerothcore
      component: authserver
  template:
    metadata:
      labels:
        app: azerothcore
        component: authserver
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z azerothcore-mariadb.ac.svc.cluster.local 3306; do echo waiting for database; sleep 2; done;']
      
      containers:
      - name: authserver
        image: acore/ac-wotlk-authserver:master
        imagePullPolicy: Always
        ports:
        - containerPort: 3724
          name: auth
          protocol: TCP
        env:
        - name: AC_LOGS_DIR
          value: "/azerothcore/env/dist/logs"
        - name: AC_TEMP_DIR
          value: "/azerothcore/env/dist/temp"
        - name: AC_LOGIN_DATABASE_INFO
          value: "azerothcore-mariadb.ac.svc.cluster.local;3306;acore;$(DB_PASSWORD);acore_auth"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: azerothcore-mariadb-user
              key: password
        
        volumeMounts:
        - name: logs
          mountPath: /azerothcore/env/dist/logs
        - name: temp
          mountPath: /azerothcore/env/dist/temp
        - name: config
          mountPath: /azerothcore/env/dist/etc
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        livenessProbe:
          tcpSocket:
            port: 3724
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          tcpSocket:
            port: 3724
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
      
      volumes:
      - name: logs
        emptyDir: {}
      - name: temp
        emptyDir: {}
      - name: config
        configMap:
          name: ac-authserver-config
          optional: true