apiVersion: v1
kind: Service
metadata:
  name: ac-authserver
  namespace: ac
  labels:
    app: azerothcore
    component: authserver
spec:
  type: LoadBalancer
  selector:
    app: azerothcore
    component: authserver
  ports:
  - port: 3724
    targetPort: 3724
    protocol: TCP
    name: auth