/**
 * Assembles the final TypeScript output string from processed schemas.
 */

import type { DescMessage, DescEnum } from '@bufbuild/protobuf';
import type {
	ProtoZodConfig,
	ConstArrayConfig,
	TypeGuardConfig,
	HelperConfig,
	PostambleConfig,
} from './types.js';
import { mapField, mapOneof } from './field-mapper.js';
import { emitConstArray } from './enum-mapper.js';

export interface EmitOptions {
	sortedMessages: DescMessage[];
	enums: Map<string, DescEnum>;
	config: ProtoZodConfig;
	zodImport: string;
	protoSource?: string;
	configSource?: string;
	/** Type names that need z.lazy() due to circular references */
	lazyRefs?: Set<string>;
}

/** Get the schema const name for a message */
function getSchemaName(typeName: string, config: ProtoZodConfig): string {
	if (config.schemaNames?.[typeName]) {
		return config.schemaNames[typeName];
	}
	const shortName = typeName.split('.').pop() ?? typeName;
	return `${shortName}Schema`;
}

/** Get the type name for a message */
function getTypeName(typeName: string, config: ProtoZodConfig): string {
	if (config.typeNames?.[typeName]) {
		return config.typeNames[typeName];
	}
	return typeName.split('.').pop() ?? typeName;
}

/** Get the renamed field name or original */
function getFieldName(
	parentFqn: string,
	fieldName: string,
	config: ProtoZodConfig,
): string {
	const fqn = `${parentFqn}.${fieldName}`;
	return config.renames?.[fqn] ?? fieldName;
}

/** Emit a single message schema + type */
function emitSchema(
	msg: DescMessage,
	config: ProtoZodConfig,
	lazyRefs?: Set<string>,
): string[] {
	const schemaName = getSchemaName(msg.typeName, config);
	const typeName = getTypeName(msg.typeName, config);
	const usePassthrough = config.passthrough?.includes(msg.typeName) ?? false;

	const lines: string[] = [];

	// Schema const
	lines.push(`export const ${schemaName} = z`);
	lines.push('\t.object({');

	// Check for rename conflicts (two fields mapping to the same output name)
	const outputNames = new Set<string>();
	for (const member of msg.members) {
		let name: string;
		if (member.kind === 'oneof') {
			name =
				config.renames?.[`${msg.typeName}.${member.name}`] ??
				member.name;
		} else {
			if (member.oneof) continue;
			name = getFieldName(msg.typeName, member.name, config);
		}
		if (outputNames.has(name)) {
			throw new Error(
				`Rename conflict in ${msg.typeName}: multiple fields map to "${name}"`,
			);
		}
		outputNames.add(name);
	}

	// Proto fields and oneofs (via members for correct ordering)
	for (const member of msg.members) {
		if (member.kind === 'oneof') {
			// Emit oneof as a single union field named after the oneof group
			const oneofName =
				config.renames?.[`${msg.typeName}.${member.name}`] ??
				member.name;
			const expr = mapOneof(member, msg.typeName, config, lazyRefs);
			lines.push(`\t\t${oneofName}: ${expr},`);
		} else {
			// Regular field — skip if it belongs to a oneof (handled above)
			if (member.oneof) continue;
			const name = getFieldName(msg.typeName, member.name, config);
			const expr = mapField(member, msg.typeName, config, lazyRefs);
			lines.push(`\t\t${name}: ${expr},`);
		}
	}

	// Extra fields (MDX-only)
	const extras = config.extraFields?.[msg.typeName];
	if (extras) {
		for (const extra of extras) {
			const comment = extra.comment ? ` // ${extra.comment}` : '';
			lines.push(`\t\t${extra.name}: ${extra.zodExpr},${comment}`);
		}
	}

	lines.push('\t})');

	if (usePassthrough) {
		lines.push('\t.passthrough();');
	} else {
		// Replace trailing line to close with semicolon
		lines[lines.length - 1] = lines[lines.length - 1] + ';';
	}

	lines.push('');

	// Type export
	lines.push(`export type ${typeName} = z.infer<typeof ${schemaName}>;`);

	return lines;
}

/** Emit a type guard function */
function emitTypeGuard(guard: TypeGuardConfig): string[] {
	const lines: string[] = [];
	const paramType = guard.inputType;
	const retType = guard.returnType;

	lines.push(`export function ${guard.name}(`);
	lines.push(`\titem: ${paramType},`);
	lines.push(`): ${retType} {`);

	// Indent body lines
	for (const bodyLine of guard.body.split('\n')) {
		lines.push(`\t${bodyLine}`);
	}

	lines.push('}');
	return lines;
}

/**
 * Assemble the complete output file.
 */
export function emit(options: EmitOptions): string {
	const { sortedMessages, enums, config, zodImport, lazyRefs } = options;
	const lines: string[] = [];

	// Header
	lines.push('/**');
	lines.push(' * AUTO-GENERATED by proto-to-zod — DO NOT EDIT');
	lines.push(' *');
	if (options.protoSource) {
		lines.push(` * Source: ${options.protoSource}`);
	}
	if (options.configSource) {
		lines.push(` * Config: ${options.configSource}`);
	}
	lines.push(` * Generated: ${new Date().toISOString()}`);
	lines.push(' */');
	lines.push('');

	// Import
	lines.push(`import { z } from '${zodImport}';`);
	lines.push('');

	// Preamble (hand-written schemas)
	if (config.preamble) {
		for (const block of config.preamble) {
			lines.push(block);
			lines.push('');
		}
	}

	// Const arrays from enums
	if (config.constArrays) {
		for (const ca of config.constArrays) {
			const enumDesc = enums.get(ca.sourceEnum);
			if (enumDesc) {
				const enumConfig = config.enums?.[ca.sourceEnum];
				lines.push(...emitConstArray(ca, enumDesc, enumConfig));
			}
		}
	}

	// Generated schemas (in topo order)
	for (const msg of sortedMessages) {
		lines.push(`// ${msg.typeName.split('.').pop() ?? msg.typeName}`);
		lines.push(...emitSchema(msg, config, lazyRefs));
		lines.push('');
	}

	// Postamble schemas (depend on generated schemas)
	if (config.postamble) {
		for (const pa of config.postamble) {
			lines.push(pa.code);
			lines.push('');
		}
	}

	// Type guards
	if (config.typeGuards && config.typeGuards.length > 0) {
		lines.push(
			'// ============================================================================',
		);
		lines.push('// Type Guards');
		lines.push(
			'// ============================================================================',
		);
		lines.push('');
		for (const guard of config.typeGuards) {
			lines.push(...emitTypeGuard(guard));
			lines.push('');
		}
	}

	// Helper functions
	if (config.helpers) {
		for (const helper of config.helpers) {
			lines.push(helper.code);
			lines.push('');
		}
	}

	return lines.join('\n');
}
