// This file is @generated by prost-build.
/// A single quest objective
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuestObjective {
    /// Unique within quest (e.g. "kill_spiders")
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Human-readable objective text
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(enumeration = "ObjectiveType", tag = "3")]
    pub r#type: i32,
    /// ULIDs — NPC, item, zone, or tile refs
    #[prost(string, repeated, tag = "4")]
    pub target_refs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// How many (default: 1)
    #[prost(int32, tag = "5")]
    pub required_amount: i32,
    /// Bonus objective (not required for completion)
    #[prost(bool, optional, tag = "6")]
    pub optional: ::core::option::Option<bool>,
    /// Revealed only when conditions met
    #[prost(bool, optional, tag = "7")]
    pub hidden: ::core::option::Option<bool>,
    /// Trigger expression that unhides this objective
    #[prost(string, optional, tag = "8")]
    pub reveal_trigger: ::core::option::Option<::prost::alloc::string::String>,
    /// Sequential ordering (0 = can be done in parallel)
    #[prost(int32, optional, tag = "9")]
    pub order: ::core::option::Option<i32>,
    /// Zone/area where objective must be completed
    #[prost(string, optional, tag = "10")]
    pub zone_ref: ::core::option::Option<::prost::alloc::string::String>,
}
/// Item reward entry
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuestItemReward {
    /// ULID or item slug
    #[prost(string, tag = "1")]
    pub item_ref: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub item_name: ::core::option::Option<::prost::alloc::string::String>,
    /// default: 1
    #[prost(int32, tag = "3")]
    pub amount: i32,
}
/// Achievement / platform integration
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct AchievementMeta {
    /// Platform achievement ID (e.g. "ACH_AUTO_COOKER")
    #[prost(string, tag = "1")]
    pub api_name: ::prost::alloc::string::String,
    /// Display name
    #[prost(string, optional, tag = "2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// Icon path when unlocked
    #[prost(string, optional, tag = "4")]
    pub icon_achieved: ::core::option::Option<::prost::alloc::string::String>,
    /// Icon path when locked
    #[prost(string, optional, tag = "5")]
    pub icon_unachieved: ::core::option::Option<::prost::alloc::string::String>,
    /// % of players who earned it (0.0–100.0)
    #[prost(float, optional, tag = "6")]
    pub global_percent: ::core::option::Option<f32>,
    /// Hidden until earned
    #[prost(bool, optional, tag = "7")]
    pub hidden: ::core::option::Option<bool>,
    /// Progress tracking min
    #[prost(int32, optional, tag = "8")]
    pub min_value: ::core::option::Option<i32>,
    /// Progress tracking max
    #[prost(int32, optional, tag = "9")]
    pub max_value: ::core::option::Option<i32>,
}
/// Rewards granted on quest completion
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct QuestRewards {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<QuestItemReward>,
    /// Gold / base currency
    #[prost(int32, optional, tag = "2")]
    pub currency: ::core::option::Option<i32>,
    /// Experience points
    #[prost(int32, optional, tag = "3")]
    pub xp: ::core::option::Option<i32>,
    /// Arbitrary stat bonuses (e.g. "cookingSpeed": 5)
    #[prost(map = "string, double", tag = "4")]
    pub bonuses: ::std::collections::HashMap<::prost::alloc::string::String, f64>,
    #[prost(message, optional, tag = "5")]
    pub achievement: ::core::option::Option<AchievementMeta>,
    /// Unlocks a recipe, area, feature, etc.
    #[prost(string, optional, tag = "6")]
    pub unlock_ref: ::core::option::Option<::prost::alloc::string::String>,
    /// Quest IDs unlocked on completion
    #[prost(string, repeated, tag = "7")]
    pub unlock_quest_refs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Faction rep gained
    #[prost(int32, optional, tag = "8")]
    pub reputation_amount: ::core::option::Option<i32>,
    /// Which faction
    #[prost(string, optional, tag = "9")]
    pub reputation_faction: ::core::option::Option<::prost::alloc::string::String>,
}
/// A single dialogue choice within a quest step
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuestChoice {
    /// Unique within step
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Button / option text
    #[prost(string, tag = "2")]
    pub label: ::prost::alloc::string::String,
    /// Tooltip or expanded text
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "ChoiceConsequenceType", tag = "4")]
    pub consequence: i32,
    /// Target ref (quest ID, item ref, zone ref, etc.)
    #[prost(string, optional, tag = "5")]
    pub consequence_ref: ::core::option::Option<::prost::alloc::string::String>,
    /// Magnitude (rep amount, damage, etc.)
    #[prost(int32, optional, tag = "6")]
    pub consequence_value: ::core::option::Option<i32>,
    /// Override: jump to specific step instead of sequential
    #[prost(string, optional, tag = "7")]
    pub next_step_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Items player must have to pick this choice
    #[prost(string, repeated, tag = "8")]
    pub required_item_refs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Class restriction (e.g. "rogue", "cleric")
    #[prost(string, optional, tag = "9")]
    pub required_class: ::core::option::Option<::prost::alloc::string::String>,
    /// Which QuestOutcome this choice leads to
    #[prost(string, optional, tag = "10")]
    pub outcome_id: ::core::option::Option<::prost::alloc::string::String>,
    /// World-state flags set when chosen
    #[prost(string, repeated, tag = "11")]
    pub set_flags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Jump to a dialogue node (in NPC dialogue tree)
    #[prost(string, optional, tag = "12")]
    pub dialogue_node_ref: ::core::option::Option<::prost::alloc::string::String>,
}
/// Branching quest outcome — different endings with different rewards/chains
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct QuestOutcome {
    /// Unique within quest (e.g. "saved_village", "betrayed")
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Narrative text for this ending
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    /// Rewards specific to this outcome
    #[prost(message, optional, tag = "3")]
    pub rewards: ::core::option::Option<QuestRewards>,
    /// Chain continues differently per outcome
    #[prost(string, optional, tag = "4")]
    pub next_quest_ref: ::core::option::Option<::prost::alloc::string::String>,
    /// World-state flags set permanently
    #[prost(string, repeated, tag = "5")]
    pub consequence_flags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// e.g. "good", "neutral", "evil", "secret"
    #[prost(string, optional, tag = "6")]
    pub ending_type: ::core::option::Option<::prost::alloc::string::String>,
    /// Is this the "canon" ending for lore purposes
    #[prost(bool, optional, tag = "7")]
    pub canonical: ::core::option::Option<bool>,
}
/// Dialogue hooks — references into NPC dialogue trees at quest transition points.
/// Dialogue content lives in NPC proto; quests only store entry-point references.
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuestDialogueHooks {
    /// Dialogue node when quest is offered/accepted
    #[prost(string, optional, tag = "1")]
    pub accept_ref: ::core::option::Option<::prost::alloc::string::String>,
    /// Dialogue node while quest is active
    #[prost(string, optional, tag = "2")]
    pub in_progress_ref: ::core::option::Option<::prost::alloc::string::String>,
    /// Dialogue node when objectives done, awaiting turn-in
    #[prost(string, optional, tag = "3")]
    pub complete_ref: ::core::option::Option<::prost::alloc::string::String>,
    /// Dialogue node on turn-in / reward claim
    #[prost(string, optional, tag = "4")]
    pub turn_in_ref: ::core::option::Option<::prost::alloc::string::String>,
    /// Dialogue node if quest fails
    #[prost(string, optional, tag = "5")]
    pub fail_ref: ::core::option::Option<::prost::alloc::string::String>,
    /// Dialogue node if player drops quest
    #[prost(string, optional, tag = "6")]
    pub abandon_ref: ::core::option::Option<::prost::alloc::string::String>,
}
/// Repeat reward policy — different rewards on subsequent completions
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct RepeatRewards {
    /// Full rewards on first completion
    #[prost(message, optional, tag = "1")]
    pub first_time: ::core::option::Option<QuestRewards>,
    /// Reduced rewards on subsequent completions
    #[prost(message, optional, tag = "2")]
    pub repeat: ::core::option::Option<QuestRewards>,
}
/// A quest step — one stage in the quest progression
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct QuestStep {
    /// Unique within quest
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Step title (e.g. "Find the missing parts")
    #[prost(string, optional, tag = "2")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    /// Narrative text shown to player
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// NPC ref who speaks this step
    #[prost(string, optional, tag = "5")]
    pub speaker_ref: ::core::option::Option<::prost::alloc::string::String>,
    /// What to do in this step
    #[prost(message, repeated, tag = "6")]
    pub objectives: ::prost::alloc::vec::Vec<QuestObjective>,
    /// Branching options (if any)
    #[prost(message, repeated, tag = "7")]
    pub choices: ::prost::alloc::vec::Vec<QuestChoice>,
    /// Default next step (linear progression)
    #[prost(string, optional, tag = "8")]
    pub next_step_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Intermediate rewards on step completion
    #[prost(message, optional, tag = "9")]
    pub step_rewards: ::core::option::Option<QuestRewards>,
    /// Event fired when step begins
    #[prost(string, optional, tag = "10")]
    pub trigger_on_start: ::core::option::Option<::prost::alloc::string::String>,
    /// Event fired when step ends
    #[prost(string, optional, tag = "11")]
    pub trigger_on_complete: ::core::option::Option<::prost::alloc::string::String>,
    /// Step behavior
    ///
    /// Objectives can be done in any order (vs sequential)
    #[prost(bool, optional, tag = "12")]
    pub parallel: ::core::option::Option<bool>,
    /// Step advances automatically when objectives met
    #[prost(bool, optional, tag = "13")]
    pub auto_complete: ::core::option::Option<bool>,
    /// Step not shown until previous step completes
    #[prost(bool, optional, tag = "14")]
    pub hidden: ::core::option::Option<bool>,
    /// Player can skip this step
    #[prost(bool, optional, tag = "15")]
    pub skippable: ::core::option::Option<bool>,
    /// Failure handling
    #[prost(enumeration = "FailurePolicy", optional, tag = "16")]
    pub failure_policy: ::core::option::Option<i32>,
    /// Per-step timeout (independent of quest timeout)
    #[prost(int32, optional, tag = "17")]
    pub step_time_limit_secs: ::core::option::Option<i32>,
    /// Dialogue hooks for this step
    #[prost(message, optional, tag = "18")]
    pub dialogue_hooks: ::core::option::Option<QuestDialogueHooks>,
}
/// Quest prerequisite — what must be true before quest is available
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuestPrerequisite {
    /// Minimum player level
    #[prost(int32, optional, tag = "1")]
    pub level_requirement: ::core::option::Option<i32>,
    /// Quests that must be completed
    #[prost(string, repeated, tag = "2")]
    pub quest_refs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Required faction membership
    #[prost(string, optional, tag = "3")]
    pub faction_ref: ::core::option::Option<::prost::alloc::string::String>,
    /// Minimum faction rank
    #[prost(int32, optional, tag = "4")]
    pub faction_rank: ::core::option::Option<i32>,
    /// Items player must possess
    #[prost(string, repeated, tag = "5")]
    pub item_refs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Required player class
    #[prost(string, optional, tag = "6")]
    pub class_ref: ::core::option::Option<::prost::alloc::string::String>,
    /// Custom trigger expression
    #[prost(string, optional, tag = "7")]
    pub trigger: ::core::option::Option<::prost::alloc::string::String>,
}
/// Time constraints for the quest
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuestTimeLimits {
    /// Fail if not completed within N seconds
    #[prost(int32, optional, tag = "1")]
    pub time_limit_secs: ::core::option::Option<i32>,
    /// ISO 8601 date — quest appears after this date
    #[prost(string, optional, tag = "2")]
    pub available_after: ::core::option::Option<::prost::alloc::string::String>,
    /// ISO 8601 date — quest disappears after this date
    #[prost(string, optional, tag = "3")]
    pub available_until: ::core::option::Option<::prost::alloc::string::String>,
    /// Repeatable quest cooldown between completions
    #[prost(int32, optional, tag = "4")]
    pub cooldown_secs: ::core::option::Option<i32>,
    /// UTC hour for daily quest reset (0-23)
    #[prost(int32, optional, tag = "5")]
    pub daily_reset_hour: ::core::option::Option<i32>,
}
/// Generic extension slot
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct QuestExtension {
    /// Namespace, e.g. "discordsh.dungeon_depth"
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(oneof = "quest_extension::Value", tags = "2, 3, 4, 5, 6")]
    pub value: ::core::option::Option<quest_extension::Value>,
}
/// Nested message and enum types in `QuestExtension`.
pub mod quest_extension {
    #[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "2")]
        StringValue(::prost::alloc::string::String),
        #[prost(int64, tag = "3")]
        IntValue(i64),
        #[prost(double, tag = "4")]
        FloatValue(f64),
        #[prost(bool, tag = "5")]
        BoolValue(bool),
        #[prost(bytes, tag = "6")]
        BytesValue(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct Quest {
    /// Identity
    ///
    /// ULID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// URL-safe identifier, e.g. "auto-cooker-9000"
    #[prost(string, tag = "2")]
    pub slug: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// Extended backstory / flavor text
    #[prost(string, optional, tag = "5")]
    pub lore: ::core::option::Option<::prost::alloc::string::String>,
    /// Classification
    #[prost(enumeration = "QuestCategory", tag = "6")]
    pub category: i32,
    /// Free-form tags for filtering
    #[prost(string, repeated, tag = "7")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Visual
    ///
    /// Quest icon path
    #[prost(string, optional, tag = "8")]
    pub icon: ::core::option::Option<::prost::alloc::string::String>,
    /// Banner / splash image
    #[prost(string, optional, tag = "9")]
    pub img: ::core::option::Option<::prost::alloc::string::String>,
    /// Map marker icon
    #[prost(string, optional, tag = "10")]
    pub marker_icon: ::core::option::Option<::prost::alloc::string::String>,
    /// Requirements
    #[prost(message, optional, tag = "11")]
    pub prerequisites: ::core::option::Option<QuestPrerequisite>,
    /// Behavior flags
    ///
    /// Not shown in quest log until triggered
    #[prost(bool, optional, tag = "12")]
    pub hidden: ::core::option::Option<bool>,
    /// Can be completed multiple times
    #[prost(bool, optional, tag = "13")]
    pub repeatable: ::core::option::Option<bool>,
    /// Starts automatically when prerequisites met
    #[prost(bool, optional, tag = "14")]
    pub auto_accept: ::core::option::Option<bool>,
    /// Completes automatically when objectives done
    #[prost(bool, optional, tag = "15")]
    pub auto_complete: ::core::option::Option<bool>,
    /// Can be shared with party members
    #[prost(bool, optional, tag = "16")]
    pub shareable: ::core::option::Option<bool>,
    /// Player can drop (default: true)
    #[prost(bool, optional, tag = "17")]
    pub abandonable: ::core::option::Option<bool>,
    /// Show on HUD / active tracker by default
    #[prost(bool, optional, tag = "18")]
    pub tracked: ::core::option::Option<bool>,
    /// Time constraints
    #[prost(message, optional, tag = "19")]
    pub time_limits: ::core::option::Option<QuestTimeLimits>,
    /// Steps — ordered quest progression
    #[prost(message, repeated, tag = "20")]
    pub steps: ::prost::alloc::vec::Vec<QuestStep>,
    /// Quest chain
    ///
    /// ULID of the next quest in the chain
    #[prost(string, optional, tag = "21")]
    pub next_quest_ref: ::core::option::Option<::prost::alloc::string::String>,
    /// Quest chain / storyline this belongs to
    #[prost(string, optional, tag = "22")]
    pub chain_ref: ::core::option::Option<::prost::alloc::string::String>,
    /// NPC linkage
    ///
    /// NPCs that offer this quest
    #[prost(string, repeated, tag = "23")]
    pub giver_npc_refs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// NPCs that accept completion
    #[prost(string, repeated, tag = "24")]
    pub turn_in_npc_refs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Zone / location
    ///
    /// Zones where this quest takes place
    #[prost(string, repeated, tag = "25")]
    pub zone_refs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Suggested player level
    #[prost(int32, optional, tag = "26")]
    pub recommended_level: ::core::option::Option<i32>,
    /// Suggested party size
    #[prost(int32, optional, tag = "27")]
    pub recommended_party_size: ::core::option::Option<i32>,
    /// Rewards (on final completion — used when no outcomes defined)
    #[prost(message, optional, tag = "28")]
    pub rewards: ::core::option::Option<QuestRewards>,
    /// Branching outcomes — multiple possible endings
    #[prost(message, repeated, tag = "33")]
    pub outcomes: ::prost::alloc::vec::Vec<QuestOutcome>,
    /// Repeat reward policy (first-time vs subsequent)
    #[prost(message, optional, tag = "34")]
    pub repeat_rewards: ::core::option::Option<RepeatRewards>,
    /// Reward distribution in party
    #[prost(enumeration = "RewardPolicy", optional, tag = "35")]
    pub reward_policy: ::core::option::Option<i32>,
    /// Failure handling (quest-level default, steps can override)
    #[prost(enumeration = "FailurePolicy", optional, tag = "36")]
    pub failure_policy: ::core::option::Option<i32>,
    /// Dialogue hooks — references into NPC dialogue trees
    #[prost(message, optional, tag = "37")]
    pub dialogue_hooks: ::core::option::Option<QuestDialogueHooks>,
    /// Triggers — event expressions that activate/progress the quest
    ///
    /// e.g. "player:level:5", "area:kitchen-zone"
    #[prost(string, repeated, tag = "29")]
    pub triggers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// World-state conditions — flags that must be set/unset for quest availability
    ///
    /// Flags that must be set
    #[prost(string, repeated, tag = "38")]
    pub required_flags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Flags that prevent quest (e.g. "betrayed_village")
    #[prost(string, repeated, tag = "39")]
    pub blocked_by_flags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Extensions — game-specific key-value pairs
    #[prost(message, repeated, tag = "30")]
    pub extensions: ::prost::alloc::vec::Vec<QuestExtension>,
    /// Metadata
    #[prost(string, optional, tag = "31")]
    pub credits: ::core::option::Option<::prost::alloc::string::String>,
    /// Hidden from production
    #[prost(bool, optional, tag = "32")]
    pub drafted: ::core::option::Option<bool>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct QuestChain {
    /// ULID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub slug: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// Ordered list of quest IDs in this chain
    #[prost(string, repeated, tag = "5")]
    pub quest_refs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub icon: ::core::option::Option<::prost::alloc::string::String>,
    /// Bonus rewards for completing entire chain
    #[prost(message, optional, tag = "7")]
    pub chain_rewards: ::core::option::Option<QuestRewards>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct QuestRegistry {
    #[prost(message, repeated, tag = "1")]
    pub quests: ::prost::alloc::vec::Vec<Quest>,
    #[prost(message, repeated, tag = "2")]
    pub chains: ::prost::alloc::vec::Vec<QuestChain>,
}
/// Quest category — narrative weight and reset behavior
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
    Hash,
    PartialOrd,
    Ord,
    ::prost::Enumeration,
)]
#[repr(i32)]
pub enum QuestCategory {
    /// Primary storyline
    Main = 0,
    /// Optional side content
    Side = 1,
    /// Resets daily
    Daily = 2,
    /// Seasonal / limited-time
    Event = 3,
    /// Skill / achievement challenge
    Challenge = 4,
    /// Onboarding / new player
    Tutorial = 5,
    /// Repeatable kill/collect bounties
    Bounty = 6,
    /// Faction/guild-specific
    Guild = 7,
}
impl QuestCategory {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Main => "QUEST_CATEGORY_MAIN",
            Self::Side => "QUEST_CATEGORY_SIDE",
            Self::Daily => "QUEST_CATEGORY_DAILY",
            Self::Event => "QUEST_CATEGORY_EVENT",
            Self::Challenge => "QUEST_CATEGORY_CHALLENGE",
            Self::Tutorial => "QUEST_CATEGORY_TUTORIAL",
            Self::Bounty => "QUEST_CATEGORY_BOUNTY",
            Self::Guild => "QUEST_CATEGORY_GUILD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "QUEST_CATEGORY_MAIN" => Some(Self::Main),
            "QUEST_CATEGORY_SIDE" => Some(Self::Side),
            "QUEST_CATEGORY_DAILY" => Some(Self::Daily),
            "QUEST_CATEGORY_EVENT" => Some(Self::Event),
            "QUEST_CATEGORY_CHALLENGE" => Some(Self::Challenge),
            "QUEST_CATEGORY_TUTORIAL" => Some(Self::Tutorial),
            "QUEST_CATEGORY_BOUNTY" => Some(Self::Bounty),
            "QUEST_CATEGORY_GUILD" => Some(Self::Guild),
            _ => None,
        }
    }
}
/// Objective type — what the player must do
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
    Hash,
    PartialOrd,
    Ord,
    ::prost::Enumeration,
)]
#[repr(i32)]
pub enum ObjectiveType {
    /// Gather N of item
    ObjectiveCollect = 0,
    /// Defeat N of NPC/enemy
    ObjectiveKill = 1,
    /// Reach a location / tile / zone
    ObjectiveVisit = 2,
    /// Talk to NPC, use object, trigger event
    ObjectiveInteract = 3,
    /// Protect/follow an NPC to a destination
    ObjectiveEscort = 4,
    /// Survive N waves / protect an object
    ObjectiveDefend = 5,
    /// Craft N of item
    ObjectiveCraft = 6,
    /// Discover N tiles / reveal map area
    ObjectiveExplore = 7,
    /// Game-specific logic (check via trigger)
    ObjectiveCustom = 8,
}
impl ObjectiveType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ObjectiveCollect => "OBJECTIVE_COLLECT",
            Self::ObjectiveKill => "OBJECTIVE_KILL",
            Self::ObjectiveVisit => "OBJECTIVE_VISIT",
            Self::ObjectiveInteract => "OBJECTIVE_INTERACT",
            Self::ObjectiveEscort => "OBJECTIVE_ESCORT",
            Self::ObjectiveDefend => "OBJECTIVE_DEFEND",
            Self::ObjectiveCraft => "OBJECTIVE_CRAFT",
            Self::ObjectiveExplore => "OBJECTIVE_EXPLORE",
            Self::ObjectiveCustom => "OBJECTIVE_CUSTOM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OBJECTIVE_COLLECT" => Some(Self::ObjectiveCollect),
            "OBJECTIVE_KILL" => Some(Self::ObjectiveKill),
            "OBJECTIVE_VISIT" => Some(Self::ObjectiveVisit),
            "OBJECTIVE_INTERACT" => Some(Self::ObjectiveInteract),
            "OBJECTIVE_ESCORT" => Some(Self::ObjectiveEscort),
            "OBJECTIVE_DEFEND" => Some(Self::ObjectiveDefend),
            "OBJECTIVE_CRAFT" => Some(Self::ObjectiveCraft),
            "OBJECTIVE_EXPLORE" => Some(Self::ObjectiveExplore),
            "OBJECTIVE_CUSTOM" => Some(Self::ObjectiveCustom),
            _ => None,
        }
    }
}
/// Quest status — runtime tracking (not baked into definition)
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
    Hash,
    PartialOrd,
    Ord,
    ::prost::Enumeration,
)]
#[repr(i32)]
pub enum QuestStatus {
    /// Prerequisites not met
    Locked = 0,
    /// Can be accepted
    Available = 1,
    /// In progress
    Active = 2,
    /// All objectives done, awaiting turn-in
    Complete = 3,
    /// Rewards claimed
    TurnedIn = 4,
    /// Failed (timed out, wrong choice, etc.)
    Failed = 5,
    /// Player dropped the quest
    Abandoned = 6,
}
impl QuestStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Locked => "QUEST_STATUS_LOCKED",
            Self::Available => "QUEST_STATUS_AVAILABLE",
            Self::Active => "QUEST_STATUS_ACTIVE",
            Self::Complete => "QUEST_STATUS_COMPLETE",
            Self::TurnedIn => "QUEST_STATUS_TURNED_IN",
            Self::Failed => "QUEST_STATUS_FAILED",
            Self::Abandoned => "QUEST_STATUS_ABANDONED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "QUEST_STATUS_LOCKED" => Some(Self::Locked),
            "QUEST_STATUS_AVAILABLE" => Some(Self::Available),
            "QUEST_STATUS_ACTIVE" => Some(Self::Active),
            "QUEST_STATUS_COMPLETE" => Some(Self::Complete),
            "QUEST_STATUS_TURNED_IN" => Some(Self::TurnedIn),
            "QUEST_STATUS_FAILED" => Some(Self::Failed),
            "QUEST_STATUS_ABANDONED" => Some(Self::Abandoned),
            _ => None,
        }
    }
}
/// Dialogue choice consequence type
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
    Hash,
    PartialOrd,
    Ord,
    ::prost::Enumeration,
)]
#[repr(i32)]
pub enum ChoiceConsequenceType {
    ConsequenceNone = 0,
    /// Progress to next step
    ConsequenceAdvanceQuest = 1,
    /// Fail the quest
    ConsequenceFailQuest = 2,
    /// Fork to a different quest
    ConsequenceBranchQuest = 3,
    /// Player receives item
    ConsequenceGiveItem = 4,
    /// Player loses item
    ConsequenceTakeItem = 5,
    /// Faction reputation change
    ConsequenceReputation = 6,
    /// Trigger combat encounter
    ConsequenceSpawnEnemy = 7,
    /// Move player to location
    ConsequenceTeleport = 8,
    /// Unlock area / feature / recipe
    ConsequenceUnlock = 9,
    /// Set a world-state flag
    ConsequenceSetFlag = 10,
    /// Clear a world-state flag
    ConsequenceClearFlag = 11,
    /// Change NPC attitude toward player
    ConsequenceNpcDisposition = 12,
}
impl ChoiceConsequenceType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ConsequenceNone => "CONSEQUENCE_NONE",
            Self::ConsequenceAdvanceQuest => "CONSEQUENCE_ADVANCE_QUEST",
            Self::ConsequenceFailQuest => "CONSEQUENCE_FAIL_QUEST",
            Self::ConsequenceBranchQuest => "CONSEQUENCE_BRANCH_QUEST",
            Self::ConsequenceGiveItem => "CONSEQUENCE_GIVE_ITEM",
            Self::ConsequenceTakeItem => "CONSEQUENCE_TAKE_ITEM",
            Self::ConsequenceReputation => "CONSEQUENCE_REPUTATION",
            Self::ConsequenceSpawnEnemy => "CONSEQUENCE_SPAWN_ENEMY",
            Self::ConsequenceTeleport => "CONSEQUENCE_TELEPORT",
            Self::ConsequenceUnlock => "CONSEQUENCE_UNLOCK",
            Self::ConsequenceSetFlag => "CONSEQUENCE_SET_FLAG",
            Self::ConsequenceClearFlag => "CONSEQUENCE_CLEAR_FLAG",
            Self::ConsequenceNpcDisposition => "CONSEQUENCE_NPC_DISPOSITION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CONSEQUENCE_NONE" => Some(Self::ConsequenceNone),
            "CONSEQUENCE_ADVANCE_QUEST" => Some(Self::ConsequenceAdvanceQuest),
            "CONSEQUENCE_FAIL_QUEST" => Some(Self::ConsequenceFailQuest),
            "CONSEQUENCE_BRANCH_QUEST" => Some(Self::ConsequenceBranchQuest),
            "CONSEQUENCE_GIVE_ITEM" => Some(Self::ConsequenceGiveItem),
            "CONSEQUENCE_TAKE_ITEM" => Some(Self::ConsequenceTakeItem),
            "CONSEQUENCE_REPUTATION" => Some(Self::ConsequenceReputation),
            "CONSEQUENCE_SPAWN_ENEMY" => Some(Self::ConsequenceSpawnEnemy),
            "CONSEQUENCE_TELEPORT" => Some(Self::ConsequenceTeleport),
            "CONSEQUENCE_UNLOCK" => Some(Self::ConsequenceUnlock),
            "CONSEQUENCE_SET_FLAG" => Some(Self::ConsequenceSetFlag),
            "CONSEQUENCE_CLEAR_FLAG" => Some(Self::ConsequenceClearFlag),
            "CONSEQUENCE_NPC_DISPOSITION" => Some(Self::ConsequenceNpcDisposition),
            _ => None,
        }
    }
}
/// Failure behavior — what happens when a quest or step fails
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
    Hash,
    PartialOrd,
    Ord,
    ::prost::Enumeration,
)]
#[repr(i32)]
pub enum FailurePolicy {
    /// Cannot retry, quest locked forever
    FailurePermanent = 0,
    /// Restart current step, keep prior progress
    FailureRetryStep = 1,
    /// Restart entire quest from beginning
    FailureRetryQuest = 2,
    /// Mark failed but allow re-acceptance later
    FailureSoftFail = 3,
}
impl FailurePolicy {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::FailurePermanent => "FAILURE_PERMANENT",
            Self::FailureRetryStep => "FAILURE_RETRY_STEP",
            Self::FailureRetryQuest => "FAILURE_RETRY_QUEST",
            Self::FailureSoftFail => "FAILURE_SOFT_FAIL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FAILURE_PERMANENT" => Some(Self::FailurePermanent),
            "FAILURE_RETRY_STEP" => Some(Self::FailureRetryStep),
            "FAILURE_RETRY_QUEST" => Some(Self::FailureRetryQuest),
            "FAILURE_SOFT_FAIL" => Some(Self::FailureSoftFail),
            _ => None,
        }
    }
}
/// Reward distribution policy for party quests
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
    Hash,
    PartialOrd,
    Ord,
    ::prost::Enumeration,
)]
#[repr(i32)]
pub enum RewardPolicy {
    /// Each player gets full rewards independently
    RewardIndividual = 0,
    /// Rewards split across party members
    RewardShared = 1,
    /// Only quest owner / party leader gets rewards
    RewardLeader = 2,
}
impl RewardPolicy {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::RewardIndividual => "REWARD_INDIVIDUAL",
            Self::RewardShared => "REWARD_SHARED",
            Self::RewardLeader => "REWARD_LEADER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REWARD_INDIVIDUAL" => Some(Self::RewardIndividual),
            "REWARD_SHARED" => Some(Self::RewardShared),
            "REWARD_LEADER" => Some(Self::RewardLeader),
            _ => None,
        }
    }
}
