//! Default Nexus Defense match zone, expressed as a `bevy_mapdb::map::Zone`.
//!
//! Lives in Rust today; a follow-up PR lifts this into an MDX entry under
//! `apps/kbve/astro-kbve/src/content/docs/mapdb/` once the gen-mapdb-data
//! pipeline learns how to route `type: "zone"` records into
//! `MapRegistry.zones[]`. Until then, this constructor is the source of
//! truth and keeps the proto shape stable across the cutover.
//!
//! The zone is **mode-agnostic** — only existing mapdb primitives are
//! used (no `tower_defense` proto extension). Any future TD-style game
//! (or co-op survival, or PvE arena) can load a zone via `bevy_mapdb`
//! and walk:
//!
//! - `objects[]` — pre-placed defensive buildings (uses
//!   `WorldObjectPlacement.grid_pos = {x: q, y: r}`).
//! - `spawn_points[]` — enemy spawn endpoints with
//!   `category = SPAWN_CATEGORY_ENEMY`.
//! - `pois[]` — landmark positions (nexus, waypoints, etc).
//! - `extensions[]` — typed key/value pacing knobs
//!   (`prepare_seconds`, `enemies_per_wave`).

use bevy_mapdb::map;
use bevy_npc::{Npc, NpcDb};

/// Extension keys honoured by the server. Use the `nexus_defense.` prefix
/// so co-existing mapdb consumers can scope their own knobs without
/// stepping on TD pacing.
pub const EXT_PREPARE_SECONDS: &str = "nexus_defense.prepare_seconds";
pub const EXT_ENEMIES_PER_WAVE: &str = "nexus_defense.enemies_per_wave";

pub const ZONE_REF: &str = "nexus-defense-default";

pub const DEFAULT_PREPARE_SECONDS: i64 = 6;
pub const DEFAULT_ENEMIES_PER_WAVE: i64 = 10;

pub const STARTER_TOWER_REF: &str = "nd-tower-basic";
pub const ENEMY_REF: &str = "nd-enemy-runner";

/// Canonical mapdb registry binary baked into the binary at compile time.
/// Generated by `nx run astro-kbve:sync:mapdb` from MDX under
/// `apps/kbve/astro-kbve/src/content/docs/mapdb/`. Lookup-only at
/// runtime — no fallback to disk so the deployed image carries the
/// same data the code was tested against.
pub const MAPDB_BINPB: &[u8] =
    include_bytes!("../../../../data/codegen/generated/mapdb-data.binpb");

/// Canonical npc registry binary. Generated by
/// `nx run astro-kbve:sync:npcdb` from the npcdb MDX directory and
/// consumed for per-enemy combat stats.
pub const NPCDB_BINPB: &[u8] =
    include_bytes!("../../../../data/codegen/generated/npcdb-data.binpb");

fn grid(q: i32, r: i32) -> map::GridPos {
    map::GridPos { x: q, y: r }
}

fn placement(object_def_ref: &str, q: i32, r: i32) -> map::WorldObjectPlacement {
    map::WorldObjectPlacement {
        object_def_ref: object_def_ref.to_string(),
        grid_pos: Some(grid(q, r)),
        position: None,
        rotation_y: None,
        scale_override: None,
        seed: None,
    }
}

fn extension_int(key: &str, value: i64) -> map::MapExtension {
    map::MapExtension {
        key: key.to_string(),
        value: Some(map::map_extension::Value::IntValue(value)),
    }
}

/// Build the default Nexus Defense zone. The fields populated here are
/// the only ones the server currently reads; everything else stays at
/// proto defaults so the zone serializes compactly.
pub fn default_zone() -> map::Zone {
    map::Zone {
        r#ref: ZONE_REF.to_string(),
        name: "Nexus Defense — Default".to_string(),
        description: Some(
            "Single-lane horizontal track. Spawn on the left, nexus on the right, \
             two starter towers flanking the path."
                .to_string(),
        ),
        r#type: map::ZoneType::Arena as i32,
        biome: map::Biome::Grassland as i32,
        objects: vec![
            placement(STARTER_TOWER_REF, -4, 0),
            placement(STARTER_TOWER_REF, 4, 0),
        ],
        spawn_points: vec![map::SpawnPoint {
            id: "spawn-west".to_string(),
            category: map::SpawnCategory::Enemy as i32,
            entity_ref: Some(ENEMY_REF.to_string()),
            grid_pos: Some(grid(-6, 0)),
            group_min: Some(1),
            group_max: Some(1),
            ..Default::default()
        }],
        pois: vec![map::PointOfInterest {
            id: "nexus-east".to_string(),
            r#ref: "nexus".to_string(),
            name: "Nexus".to_string(),
            r#type: map::PoiType::PoiTower as i32,
            grid_pos: Some(grid(6, 0)),
            ..Default::default()
        }],
        extensions: vec![
            extension_int(EXT_PREPARE_SECONDS, DEFAULT_PREPARE_SECONDS),
            extension_int(EXT_ENEMIES_PER_WAVE, DEFAULT_ENEMIES_PER_WAVE),
        ],
        ..Default::default()
    }
}

/// Read an int64 extension value by key, or `None` if absent / wrong type.
pub fn read_int_extension(zone: &map::Zone, key: &str) -> Option<i64> {
    zone.extensions
        .iter()
        .find(|ext| ext.key == key)
        .and_then(|ext| match ext.value.as_ref()? {
            map::map_extension::Value::IntValue(v) => Some(*v),
            _ => None,
        })
}

/// Combat stats pulled from a `WorldObjectDef`'s `RangedAttackSpec` +
/// `max_health`. Wraps the raw proto so the rest of the server doesn't
/// need to depend on the mapdb crate's types.
#[derive(Clone, Copy, Debug)]
pub struct BuildingStats {
    pub max_hp: f32,
    pub range: f32,
    pub fire_interval_secs: f32,
    pub damage_per_shot: f32,
    pub projectile_speed: f32,
    pub projectile_lifetime_secs: f32,
}

impl BuildingStats {
    /// Numbers that match the previously-hardcoded constants in
    /// `nexus_defense_server::mod`. Used when a WorldObjectDef lookup
    /// misses (mapdb missing the ref, or `ranged_attack` block omitted).
    pub const FALLBACK_TOWER: Self = Self {
        max_hp: 200.0,
        range: 140.0,
        fire_interval_secs: 0.4,
        damage_per_shot: 18.0,
        projectile_speed: 320.0,
        projectile_lifetime_secs: 1.875, // 600 / 320
    };

    pub fn max_range(&self) -> f32 {
        self.projectile_speed * self.projectile_lifetime_secs
    }
}

/// Combat + economy stats for an enemy archetype. Sourced from a
/// `bevy_npc::Npc` (NpcStats.max_hp / speed + LootTable.gold_min). The
/// `speed` field is reinterpreted as **pixels per second** for the
/// Nexus Defense lane sim; other npcdb consumers may treat it as a
/// turn-based RPG stat without conflict.
#[derive(Clone, Copy, Debug)]
pub struct EnemyStats {
    pub max_hp: f32,
    pub speed: f32,
    pub bounty_gold: i32,
}

impl EnemyStats {
    /// Numbers that match the previously-hardcoded constants in
    /// `nexus_defense_server::mod`. Used when an npcdb lookup misses.
    pub const FALLBACK_RUNNER: Self = Self {
        max_hp: 50.0,
        speed: 60.0,
        bounty_gold: 8,
    };
}

/// Pull combat stats out of an npcdb `Npc`. Falls back to
/// `EnemyStats::FALLBACK_RUNNER` for any field the entry omits.
pub fn enemy_stats_from_npc(npc: &Npc) -> EnemyStats {
    let fallback = EnemyStats::FALLBACK_RUNNER;
    let (max_hp, speed) = npc
        .stats
        .as_ref()
        .map(|s| {
            let hp_src = if s.max_hp > 0 { s.max_hp } else { s.hp };
            (
                if hp_src > 0 {
                    hp_src as f32
                } else {
                    fallback.max_hp
                },
                if s.speed > 0 {
                    s.speed as f32
                } else {
                    fallback.speed
                },
            )
        })
        .unwrap_or((fallback.max_hp, fallback.speed));
    let bounty_gold = npc
        .loot
        .as_ref()
        .and_then(|l| l.gold_min)
        .filter(|v| *v > 0)
        .unwrap_or(fallback.bounty_gold);
    EnemyStats {
        max_hp,
        speed,
        bounty_gold,
    }
}

/// Resolve `ENEMY_REF` against the embedded npcdb. Falls back to
/// `EnemyStats::FALLBACK_RUNNER` when the entry is missing.
pub fn runner_stats_from_db(db: &NpcDb) -> EnemyStats {
    db.get_by_ref(ENEMY_REF)
        .map(enemy_stats_from_npc)
        .unwrap_or(EnemyStats::FALLBACK_RUNNER)
}

/// Pull combat stats out of a mapdb `WorldObjectDef`. Falls back to
/// `BuildingStats::FALLBACK_TOWER` for any field the def omits so a
/// half-authored entry still produces a playable tower.
pub fn building_stats_from_def(def: &map::WorldObjectDef) -> BuildingStats {
    let fallback = BuildingStats::FALLBACK_TOWER;
    let max_hp = def
        .max_health
        .filter(|v| *v > 0)
        .map(|v| v as f32)
        .unwrap_or(fallback.max_hp);
    let (range, cooldown_secs, damage, proj_speed, proj_life) = def
        .ranged_attack
        .as_ref()
        .map(|ra| {
            (
                if ra.range > 0.0 {
                    ra.range
                } else {
                    fallback.range
                },
                if ra.cooldown_secs > 0.0 {
                    ra.cooldown_secs
                } else {
                    fallback.fire_interval_secs
                },
                if ra.damage_per_shot > 0.0 {
                    ra.damage_per_shot
                } else {
                    fallback.damage_per_shot
                },
                if ra.projectile_speed > 0.0 {
                    ra.projectile_speed
                } else {
                    fallback.projectile_speed
                },
                if ra.projectile_lifetime > 0.0 {
                    ra.projectile_lifetime
                } else {
                    fallback.projectile_lifetime_secs
                },
            )
        })
        .unwrap_or((
            fallback.range,
            fallback.fire_interval_secs,
            fallback.damage_per_shot,
            fallback.projectile_speed,
            fallback.projectile_lifetime_secs,
        ));
    BuildingStats {
        max_hp,
        range,
        fire_interval_secs: cooldown_secs,
        damage_per_shot: damage,
        projectile_speed: proj_speed,
        projectile_lifetime_secs: proj_life,
    }
}
