apiVersion: v1
kind: Service
metadata:
    name: functions
    namespace: kilobase
    labels:
        kbve.com/category: application
        kbve.com/stack: supabase
        kbve.com/managed-by: argocd
spec:
    type: ClusterIP
    selector:
        app: functions
    ports:
        - port: 9000
          targetPort: 9000
          protocol: TCP
          name: edge-runtime
