apiVersion: v1
kind: Service
metadata:
  name: functions
  namespace: kilobase
spec:
  type: ClusterIP
  selector:
    app: functions
  ports:
  - port: 54321
    targetPort: 54321
    protocol: TCP
    name: edge-runtime