apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: functions-supabase-secrets
  namespace: kilobase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secret-store
    kind: SecretStore
  target:
    name: supabase-shared
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        jwt-secret: "{{ .jwtsecret }}"
        anon-key: "{{ .anonkey }}"
        service-role-key: "{{ .servicekey }}"
        db-url: "postgres://postgres:{{ .dbpassword }}@supabase-cluster-rw.kilobase.svc.cluster.local:5432/supabase"
  data:
  - secretKey: jwtsecret
    remoteRef:
      key: supabase-jwt
      property: secret
  - secretKey: anonkey
    remoteRef:
      key: supabase-jwt
      property: anon-key
  - secretKey: servicekey
    remoteRef:
      key: supabase-jwt
      property: service-key
  - secretKey: dbpassword
    remoteRef:
      key: supabase-postgres
      property: password