apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rows-chuckrpg-dev

resources:
    - namespace.yaml
    - sealed-customer-guid.yaml
    - sealed-encryption-key.yaml
    - sealed-fleet-restart-token.yaml
    - ../../base

labels:
    - pairs:
          app.kubernetes.io/instance: chuckrpg-dev
      includeSelectors: false

patches:
    - target:
          kind: Deployment
          name: rows
      patch: |-
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
                name: OWS_TENANT_SLUG
                value: chuckrpg-dev
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
                name: OWS_ENV
                value: dev
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
                name: AGONES_FLEET
                value: rows-chuckrpg-dev
    - target:
          kind: Job
          name: rows-seed
      patch: |-
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
                name: CUSTOMER_NAME
                value: ChuckRPG Dev
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
                name: CUSTOMER_EMAIL
                value: admin@chuckrpg.com
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
                name: MAP_NAME
                value: greenshire
          - op: add
            path: /spec/template/spec/containers/0/env/-
            value:
                name: ZONE_NAME
                value: MainWorld
    - target:
          kind: Certificate
          name: rows-api-tls
      patch: |-
          - op: replace
            path: /spec/secretName
            value: rows-chuckrpg-dev-api-tls
          - op: replace
            path: /spec/dnsNames/0
            value: api-dev.chuckrpg.com
    - target:
          kind: HTTPRoute
          name: ows-api-routes
      patch: |-
          - op: replace
            path: /spec/hostnames/0
            value: api-dev.chuckrpg.com
