persistence:
  defaultClass: true
  defaultClassReplicaCount: 1

csi:
  kubeletRootDir: /var/lib/kubelet

defaultSettings:
  defaultDataPath: "/var/lib/longhorn"
  replicaSoftAntiAffinity: false
  storageOverProvisioningPercentage: 200
  storageMinimalAvailablePercentage: 25
  upgradeChecker: false
  defaultReplicaCount: 1
  defaultLonghornStaticStorageClass: "longhorn"
  backupstorePollInterval: 300
  taintToleration: "node-role.kubernetes.io/control-plane:NoSchedule"
  systemManagedComponentsNodeSelector: ""
  priorityClass: ""
  autoSalvage: true
  autoDeletePodWhenVolumeDetachedUnexpectedly: true
  disableSchedulingOnCordonedNode: true
  replicaZoneSoftAntiAffinity: false
  nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
  allowNodeDrainWithLastHealthyReplica: false
  mkfsExt4Parameters: "-O ^metadata_csum,^64bit"
  disableSnapshotPurge: false

longhornManager:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

longhornDriver:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule