//! The generated types, under the names this crate has always used for them.
//!
//! These used to be produced by a build script in this crate, from schemas that
//! lived in another repository, into ten files committed under `src/proto`.
//! That arrangement compiled without protoc and without the schemas, which is
//! also why nothing noticed when the two drifted apart.
//!
//! They now come from `packages/proto`, generated by `moon run protobuf:build`
//! for every language at once. This module is the seam: the paths below are the
//! ones the rest of the crate already imports, so moving the schemas did not
//! have to become a rename of every call site.
//!
//! `github` and `forgejo` were separate protobuf packages and are now one
//! `kbve.git.v1`, beside the primitives they already shared. Both names are
//! kept pointing at it -- a GitHub type and a Forgejo type are still different
//! types, and saying which forge a call is about is worth more than the two
//! aliases cost.

pub use kbve_proto::kbve::clickhouse::v1 as clickhouse;
pub use kbve_proto::kbve::git::v1 as forgejo;
pub use kbve_proto::kbve::git::v1 as git;
pub use kbve_proto::kbve::git::v1 as github;
pub use kbve_proto::kbve::groq::v1 as groq;
pub use kbve_proto::kbve::jedi::v1 as jedi;
pub use kbve_proto::kbve::redis::v1 as redis;
pub use kbve_proto::kbve::staff::v1 as staff;
#[cfg(feature = "twitch")]
pub use kbve_proto::kbve::twitch::v1 as twitch;

/// The gRPC clients and servers, when the `grpc` feature is on.
///
/// These used to arrive as part of `redis` and `clickhouse` above, because the
/// build script generated them into the same file as the messages. They are a
/// separate module in kbve-proto now, so that a crate wanting an item
/// definition does not compile an HTTP/2 stack to get one. Nothing in this
/// workspace calls them yet -- the frozen copy this crate carried had a client
/// and a server for both services and no caller for either.
#[cfg(feature = "grpc")]
pub mod grpc {
    pub use kbve_proto::grpc::{clickhouse, redis};
}
