---
# SecretStore: pull secrets from cert-manager namespace
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
    name: certmanager-remote-secret-store
    namespace: kbve
spec:
    provider:
        kubernetes:
            remoteNamespace: cert-manager
            auth:
                serviceAccount:
                    name: kbve-external-secrets
                    namespace: kbve
            server:
                url: https://kubernetes.default.svc
                caProvider:
                    type: ConfigMap
                    name: kube-root-ca.crt
                    key: ca.crt
                    namespace: kube-system
---
# ExternalSecret: sync Cloudflare API token into kbve namespace
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: kbve-cloudflare-cache-purge
    namespace: kbve
spec:
    refreshInterval: 24h
    secretStoreRef:
        name: certmanager-remote-secret-store
        kind: SecretStore
    target:
        name: cloudflare-cache-purge
        creationPolicy: Owner
        template:
            engineVersion: v2
            data:
                api-token: '{{ .apitoken }}'
    data:
        - secretKey: apitoken
          remoteRef:
              key: cloudflare-api-token-secret
              property: api-token
