---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBEKotIjum0kxtrFbu4V6HOMR9nIIXu0sBoDDh9aSgwQZjWQMRTSCu+ACsQUVzM1ipBSsEHaNf1SG5NgmV7FU3xi57uKOCq3RNeBb2Eq6NrfJwVH7piLLYyrbfZhON0p/kwcRi6UYVJDXGPO7WyKUpAJZ0vZ2v3O+AWhCp0zUuSUn2heELFTsdlkz834LQeO0AaXF0OfygDuW61l+yCC3iDoOqiMRCE6SK//kQkJ2vrYv5H7w/jGX1+HvxASKkMHWGX7kpkBxYTUv9tAHgFAPP0RZUR05uzW26FfbgarEjoV1yEkdetmu4cgQn12ooS+rhD4XT+2tlxY57r8rkQ51c+mi7renYHEhtpa/Y07E0bsk5FCUbJCY3rFtP2a2nMUpHVMPIFv6vy5SD0hPzZp2CkROsuDg86twoBPxe8qAdAoK+7J1SQusiJyb9YsAyfMQwl7RaxVSyHHCCY6dtbuFyVCAln7FmCxpFPgPl3Zu9MjLV6B0uC/BcU0aJgleFGuaP8+IYYdPvAWi4DSxm0pCO52KA87h7bzB+NMwji5c7C21+3Cn4VR/kFT/whmKdNtAUDtMk3X1x00VMRAbdcOLK303DR7snMhSOIlKz9qWaAToEMp0kI1cBHcE+8Gr3Jp4T1Qg89hN8QLbQK/o1UKZ4s5B2X92JW0K4w7LrpjFRfjevDIZeljfpC2ESIagxkIaHIbeA8vZrvv4zTqoMQLrMM
    admin-user: AgCSjkPTCfKDdqDLKSyLqy2Jp3JeYXRSantDu3v9o34WtFRd4Cq7MewD/fFYjE5wLXIeXsCwaS5nWh45u5kLukeELfoKNwpX/FXjd/dEQ7H0jrCZtXPkI8fYHgfjlMhTcNj4v0ieHIn5cgknWrH8fQ9g0ERXGUx7TbeLQqA55dx4yrOUJz2ZBzqOBEvGhH7rDgGrPQnPTXpDo5Ouzwiue3NBbfIgx8bwKS1I54zbnUfOcHmwGJ28jZCWgSshB8TGnYSf6ch+2JG0Obcj5SATlLiTgHXA4Jn7z+O+at2WkMzGYnmZcETjQsVFdZU/RqqOrnAouyUFB4703yI42zvfBccS8JV+0iIWGSFbFDxccFWDyz5sIer2vOwpcsphUIFOPgYFlv3rHzYtPJTvYuV/3UXKLKfofv/1SvwrwwtSwDoMzEjfub2eCCeOne60Z8kLuZE3+0NoJ7ngFGjkabsA0XbFJ1tTJoTKzG71L1WdcX9w7rpZYU6ABl9x4XFqigK7EDFYonXIzp28eR0zlL2opg/OGdvhcHicuY39U5yYJxNqSFFOa3DXGwKnmntewJNJMBg/iaWSuXEJIGG7cDQdvSapXBSAnpH+E5CIyjgsyHXFp3mja0seE/S0RPfYJjNZg71N43iDb4D+tSuQp3d1YafJHQh72OBasj7M5o4/G3d8zXWZA+IrNbZ4N8olsGcHpxcNclU1vg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
