---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: grafana-admin
    namespace: monitoring
spec:
    encryptedData:
        admin-password: AgArQL5QeNxKbVMf79KMZGvnQLJ2phpSY4dgty01vDoTTu2gZ5tHL6hAi3xEyD84vTM3tZ+92nqqT2khH0JBt9aniMLQJ5XhkR2Ou+kktjjAz3/pFCPZrdgOsXHSYxI+pffHT43/9wZjHQ0Bhq4gJWyGTESDz9Tt9u5RdQaZZ7x9nWpT6qLh7H0QacefvR4n8EJOKX35OT1AzcWT6zjRZsinQTTmm$
        admin-user: AgBfXezuQ/SaneMl4Jn6i1uK/GUDbW2svcp/fbJ5f957GC3Nn03R2K8ItjPt+FkmhT34oH5o6UdaEuDH344lWEpxEmzJd8flLorvQOZAHCbuygjlvEm+k+WHqg5Lb/0+T68MKh/MnJWmrjZs39iGv8ku7gZyrJ8zY8N9/KuDaJVvvTSd2tSzHmQIBLkSPd8mn/A+Rd+9Xwc9xApZ4h9Msw56Cq3oLHT3o$
    template:
        metadata:
            name: grafana-admin
            namespace: monitoring
