---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    creationTimestamp: null
    name: grafana-admin
    namespace: monitoring
spec:
    encryptedData:
        admin-password: AgBEKotIjum0kxtrFbu4V6HOMR9nIIXu0sBoDDh9aSgwQZjWQMRTSCu+ACsQUVzM1ipBSsEHaNf1SG5NgmV7FU3xi57uKOCq3RNeBb2Eq6NrfJwVH7piLLYyrbfZhON0p/kwcRi6UYVJDXGPO7WyKUpAJZ0vZ2v3O+AWhCp0zUuSUn2heELFTsdlkz834LQeO0AaXF0OfygDuW61l+yCC3iDoOqiM$
        admin-user: AgCSjkPTCfKDdqDLKSyLqy2Jp3JeYXRSantDu3v9o34WtFRd4Cq7MewD/fFYjE5wLXIeXsCwaS5nWh45u5kLukeELfoKNwpX/FXjd/dEQ7H0jrCZtXPkI8fYHgfjlMhTcNj4v0ieHIn5cgknWrH8fQ9g0ERXGUx7TbeLQqA55dx4yrOUJz2ZBzqOBEvGhH7rDgGrPQnPTXpDo5Ouzwiue3NBbfIgx8bwK$
    template:
        metadata:
            creationTimestamp: null
            name: grafana-admin
            namespace: monitoring
        type: Opaque
