---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: grafana-admin
    namespace: monitoring
spec:
    encryptedData:
        admin-password: AgC/mktJXRQMkzTn52u2ITZjYgldm4Zm+ssKB7msZ8eJw8odx5/2ORsm2G0zbrujv/bpdMz6072Z5A9Xx98p4ThgUUBHoniDbtAMoWD+3mr3++RSTe9bsH6IR+hKQ2v3kKHihoCqG5JlJpJl65u13mCeM2OBoAs9vjwOuNvhuOfr1uFytWFHoXHc0WYckabRcrbb1DAIPPhxYBG1ymQE4Vz4Du66W$
        admin-user: AgCrP/c0n8V3ww9PGYdVmSR0rFA31Q23YDd81X8D/VGVVI6tnA6qthtWFHeP1bVfGDaiDXKne02LX3bTJruRGCpq8Y3P6H3tRqIGSnfv6tnY8qks8Du27z2N8RE6Idq999TMPyz4B2qzF+7jaWAsCEc+YinbLwiNWaj+ifVpOrqLREKC9o+FiHLFj9pWwRIs3cdVGZJobxTndiBBS1QrYaAqgvke27z/z$
    template:
        metadata:
            name: grafana-admin
            namespace: monitoring
