---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    creationTimestamp: null
    name: grafana-admin
    namespace: monitoring
spec:
    encryptedData:
        admin-password: AgBhoRt0dgS+EirkBXte6e/FYaPDhFkbjd+6TftytUFLaT1XfvP001c2P//YVJHenS5UHe1H6c6kycWOG/rH39kGJ3FvgTkFwei8vzMyMNvfev9K5h0skNL4GhPbXfOMgNiHsoxlDfCWDhu9WBzg0t0HK5iKc9IYYFhUV/fmjTrkxF3m16qGXEEK+afyyyXNgiBEP+hYNB6bRuYQX2NadU2hpgfd8$
        admin-user: AgAaIgKiLNEChbmjkmy1O8+COIv7fEInVmU8IPpHQJeh1C8u50rCW2jQIA4vKXMkQGDJwGgt9745QwfBCH+LrrKUBo2HHCct2bYeaR6JeOw6lAA0N1uYPvN6Cyw0YXtqYjpvlRyN3UQ9lp8OlcLFUpvscmD17hQ1G3t4BOnzpWYimJds9giFU8jFfpCt5Vgd1m0F+4u9yuB7iCJntKXHsQkDgTXnCYNNW$
    template:
        metadata:
            creationTimestamp: null
            labels:
                app.kubernetes.io/name: grafana
            name: grafana-admin
            namespace: monitoring
        type: Opaque
