apiVersion: v1
kind: Service
metadata:
    name: ergo-irc-service
    namespace: irc
spec:
    type: ClusterIP
    selector:
        app: ergo-irc
    ports:
        - name: irc
          port: 6667
          targetPort: 6667
          protocol: TCP
        - name: ircs
          port: 6697
          targetPort: 6697
          protocol: TCP
        - name: websocket
          port: 8080
          targetPort: 8080
          protocol: TCP
        - name: metrics
          port: 6060
          targetPort: 6060
          protocol: TCP