apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: thelounge-data-pvc
    namespace: irc
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 2Gi