apiVersion: v1
kind: ConfigMap
metadata:
  name: thelounge-config
  namespace: irc
data:
  config.js: |
    "use strict";

    module.exports = {
      // Set to 'false' to enable public mode
      public: true,
      
      // Default server settings for public mode
      defaults: {
        name: "KBVE Network",
        host: "ergo-irc-service",
        port: 6667,
        password: "-",
        tls: false,
        rejectUnauthorized: false,
        nick: "kbve-user-%%",
        username: "kbve-user",
        realname: "KBVE User",
        join: "#general"
      },

      // Disable account registration in public mode
      displayNetwork: false,
      lockNetwork: true,

      // Enable prefetch for better UX
      prefetch: true,
      prefetchStorage: true,
      prefetchTimeout: 5000,
      prefetchMaxImageSize: 2048,

      // File upload (disable for security)
      fileUpload: {
        enable: false
      },

      // Transports
      transports: ["polling", "websocket"],

      // Reverse proxy settings
      reverseProxy: true,

      // Maximum number of push subscriptions per user
      maxHistory: 10000,

      // LDAP (disabled)
      ldap: {
        enable: false
      },

      // Theming
      theme: "default",
      
      // Debug info
      debug: {
        ircFramework: false,
        raw: false
      }
    };