apiVersion: v1
kind: Service
metadata:
    name: mc-lobby-backend
    namespace: arc-runners
    labels:
        app: mc-lobby
        app.kubernetes.io/part-of: mc
        kbve.com/category: game-server
        kbve.com/stack: agones
        kbve.com/managed-by: argocd
spec:
    type: ClusterIP
    selector:
        app: mc-lobby
    ports:
        - name: minecraft
          port: 25565
          targetPort: 25565
          protocol: TCP
        - name: rcon
          port: 25575
          targetPort: 25575
          protocol: TCP
