apiVersion: v1
kind: ConfigMap
metadata:
    name: mc-map-rotation-config
    namespace: arc-runners
    labels:
        app.kubernetes.io/part-of: mc
        kbve.com/category: game-server
        kbve.com/stack: agones
        kbve.com/managed-by: argocd
data:
    CENTER_X: '0'
    CENTER_Z: '0'
    PROTECT_RADIUS: '512'
    RESET_NETHER: 'true'
    RESET_END: 'true'
    RESET_PLAYERDATA: 'false'
