apiVersion: v1
kind: Service
metadata:
    name: mc-fabric-rcon
    namespace: arc-runners
    labels:
        app.kubernetes.io/part-of: mc
        app.kubernetes.io/component: rcon
        kbve.com/category: game-server
        kbve.com/stack: agones
        kbve.com/managed-by: argocd
spec:
    clusterIP: None
    selector:
        app: mc-gameserver
    ports:
        - name: rcon
          port: 25575
          targetPort: 25575
          protocol: TCP
