[package]
name = "kbve-gate"
authors = ["kbve", "h0lybyte"]
version = "0.1.9"
edition = "2021"
rust-version.workspace = true
publish = false

[[bin]]
name = "kbve-gate"
path = "src/main.rs"

[dependencies]
kbve = { path = "../../../packages/rust/kbve", features = ["gate"] }
tokio = { workspace = true, features = ["default", "full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["default", "env-filter"] }
dotenvy = { workspace = true }
