apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: realtime
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kbve/kbve
    targetRevision: HEAD
    path: apps/kube/realtime/manifests
    # Enable Kustomize to generate ConfigMap from files
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: kilobase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true