using Unity.Entities;
using Unity.Physics;
using UnityEngine;
using Unity.Mathematics;
using KBVE.MMExtensions.Orchestrator.DOTS.Common;

namespace KBVE.MMExtensions.Orchestrator.DOTS
{
    public class SoldierAuthoring : MonoBehaviour
    {
        private class SoldierBaker : Baker<SoldierAuthoring>
        {
            public override void Bake(SoldierAuthoring authoring)
            {
                var entity = GetEntity(TransformUsageFlags.Dynamic); // 11-04-2025 Switched from "None" to "Dynamic", but might revert.
                AddComponent<SoldierTag>(entity);
                // MovingTag removed - combatants use Combatant.State for movement control
                // TODO: Debug if we want to use localTransform or switch to WorldPosition , 11-04-2025
                AddComponent<Destination>(entity);
                AddComponent<MoveTimer>(entity);
                AddComponent<SpriteFlipVelocityTag>(entity);
                AddComponent(entity, new MoveSpeed { value = authoring.MoveSpeed });

                // Add universal EntityComponent for hover/selection system
                // Note: Entity ULID will be generated by FactorySystem when instantiated from prefab
                var entityData = new EntityData
                {
                    Ulid = default, // Will be overwritten by FactorySystem with unique ULID
                    Type = EntityType.Monster | EntityType.Unit | EntityType.NPC | EntityType.Interactable | EntityType.Enemy,
                    ActionFlags = EntityActionFlags.CanInteract | EntityActionFlags.CanAttack,
                    WorldPos = authoring.transform.position
                };
                AddComponent(entity, new EntityComponent { Data = entityData });

                // Add Combatant component so bridge systems can detect this as a combatant
                var combatantData = new CombatantData
                {
                    TemplateUlid = default, // Will be set by factory or spawning system
                    Type = CombatantType.Monster,
                    Flags = CombatantFlags.IsHostile,
                    State = CombatantState.Idle,
                    Level = 1,
                    Health = 100,
                    MaxHealth = 100,
                    Mana = 0,
                    MaxMana = 0,
                    AttackDamage = 10,
                    Defense = 5,
                    AttackSpeed = 1f,
                    MoveSpeed = authoring.MoveSpeed,
                    DetectionRange = 10f
                };
                AddComponent(entity, new Combatant { Data = combatantData });

                // Add SpatialIndex so combatants are included in CSR Grid for dynamic queries
                // CRITICAL: Without this, combatants won't appear in spatial queries (attack, pathfinding, etc.)
                AddComponent(entity, new SpatialIndex
                {
                    Radius = combatantData.DetectionRange, // Use detection range as collision radius
                    LayerMask = uint.MaxValue, // Visible to all layers
                    IncludeInQueries = true, // CRITICAL: Must be true for spatial queries
                    Priority = 1 // Higher priority than static resources
                });

                // Add spatial settings for moving units (dynamic entities)
                // UpdateFrequency = 1 means update every frame (combatants move constantly)
                AddComponent(entity, SpatialSettings.MovingUnit);

                // NOTE: PhysicsVelocity is automatically added by Unity.Physics.Authoring.RigidbodyBaker
                // when the GameObject has a Rigidbody component. Do NOT add it manually!
                // The Rigidbody component on the Soldier prefab handles physics baking.

                // Add AttackCooldown component for damage rate limiting
                // PlayerDamageSystem uses this to prevent attacking every frame
                AddComponent(entity, new AttackCooldown { TimeRemaining = 0f });
            }
        }

        public float MoveSpeed;
    }
}
