apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-analytics
  namespace: kilobase
  labels:
    app: supabase-analytics
    component: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-analytics
  template:
    metadata:
      labels:
        app: supabase-analytics
        component: analytics
    spec:
      initContainers:
      - name: url-builder
        image: busybox:1.36
        command: ["sh", "-c"]
        args:
        - |
          echo "postgresql://supabase_admin:$DB_PASSWORD@supabase-cluster-rw:5432/_supabase" > /shared/postgres_backend_url
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-postgres
              key: password
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      containers:
      - name: logflare
        image: supabase/logflare:1.14.2
        ports:
        - containerPort: 4000
          name: http
        env:
        # Basic Logflare configuration
        - name: LOGFLARE_NODE_HOST
          value: "127.0.0.1"
        
        # Database configuration for metadata
        - name: DB_USERNAME
          value: "supabase_admin"
        - name: DB_DATABASE
          value: "_supabase"
        - name: DB_HOSTNAME
          value: "supabase-cluster-rw"
        - name: DB_PORT
          value: "5432"
        - name: DB_SCHEMA
          value: "_analytics"
        
        # Supabase mode configuration
        - name: LOGFLARE_SINGLE_TENANT
          value: "true"
        - name: LOGFLARE_SUPABASE_MODE
          value: "true"
        - name: LOGFLARE_MIN_CLUSTER_SIZE
          value: "1"
        
        # PostgreSQL backend for analytics data
        - name: POSTGRES_BACKEND_SCHEMA
          value: "_analytics"
        - name: LOGFLARE_FEATURE_FLAG_OVERRIDE
          value: "multibackend=true"
        
        # Required encryption key for sensitive data
        - name: LOGFLARE_DB_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: logflare-config
              key: encryption-key
        
        # Password from secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-postgres
              key: password
        
        # PostgreSQL backend URL will be loaded from file by entrypoint script
        command: ["/bin/sh", "-c"]
        args:
        - |
          export POSTGRES_BACKEND_URL=$(cat /shared/postgres_backend_url)
          exec /app/bin/logflare start
              
        # Health check
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          
        volumeMounts:
        - name: shared-data
          mountPath: /shared
          readOnly: true
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
            
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      
      volumes:
      - name: shared-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: analytics
  namespace: kilobase
  labels:
    app: supabase-analytics
    component: analytics
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: supabase-analytics