apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: bugwars
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-kilobase-secrets
  namespace: kilobase
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list', 'watch']
    resourceNames: ['supabase-jwt', 'supabase-postgres']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bugwars-read-kilobase-secrets
  namespace: kilobase
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-kilobase-secrets
subjects:
  - kind: ServiceAccount
    name: external-secrets-sa
    namespace: bugwars
