apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bugwars-supabase-secrets
  namespace: bugwars
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: supabase-shared
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        jwt-secret: "{{ .jwtsecret }}"
        anon-key: "{{ .anonkey }}"
        service-role-key: "{{ .servicekey }}"
        db-url: "postgres://postgres:{{ .dbpassword }}@supabase-cluster-rw.kilobase.svc.cluster.local:5432/supabase"
  dataFrom:
  - find:
      name:
        regexp: "supabase-.*"
      conversionStrategy: Default
    rewrite:
    - regexp:
        source: "supabase-(.*)"
        target: "$1"
  data:
  - secretKey: jwtsecret
    remoteRef:
      key: supabase-jwt
      property: secret
      namespace: kilobase
  - secretKey: anonkey
    remoteRef:
      key: supabase-jwt
      property: anon-key
      namespace: kilobase
  - secretKey: servicekey
    remoteRef:
      key: supabase-jwt
      property: service-key
      namespace: kilobase
  - secretKey: dbpassword
    remoteRef:
      key: supabase-postgres
      property: password
      namespace: kilobase
