#!/bin/bash

echo "[STARTING] : Fudster"
echo "[ACTION] : AutoStart | Home -> $HOME Display -> $DISPLAY"

if [ ! -f $HOME/.Xauthority ]; then
    touch $HOME/.Xauthority
    chown abc:abc $HOME/.Xauthority
fi

export DISPLAY=${DISPLAY:-:1}

java -jar /usr/local/bin/runelite.jar | tee -a runelite.log &
