---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: axum-rentearth-secrets
  namespace: rentearth
spec:
  encryptedData:
    ITCH_API: AgBxIHw+/x9Tt77X3aR8kPXam2UV9VfYyAyVVEWFRKRApvnF7A2vbjd3LSRAXh5Gv+HkGmoPyjvFAE6SZn8/DenXeYZSdtE5bCBUnaUIg88kjULMzN7ACPNi5uJcksbduj80x6aYTO+J8tOeVCTzfHrUvTf7dwU/AOw5zrUAn2WqHGR+2lbYLmXoAVFBu0LDyz9B+9SDqNvU2lBIplxc4ss3ioN6qUnDi5A8jmBHs59c1rdMCV9O/iQij5YZdVoMAt4WJ6ICyYZhMAU9jm7+9RcTOH6Ny8J2RTJknT03MxwDcdwT8KEk6Q/vhd+4eMgqcCw9nqyzd8etHvYunm9kGGlpsVdXZEj0e/2I0kgPTzS2KtIpFIaJ1LdXAijNNLLiAwGM96zrCSpdSxPmz9OM2WcGTxJuj6QyfSiz/Br3kJa0JXxll/gyhUs4D3gOg8CkCsZesaSuki74D3XFalrU2aSzz9s5GIe1MlwMxhLH6Sez0VRjCZXKiwE8XN2GGgfP9ziWYKfzpql49ycxU2btIzc7EtjIWWVCg3SFAUSdNlHmhPXioFD2KadHth3ja6fYYc6jwKxGC8ONQiwFjM/sOZl7bzOCiECz4UZw9DR7FGcEGYoZMBeshTeC8wVEZIMB7EwslC7irfVxYFm8sBiGMFN18nHnzJF3vzX7wfMYA5t3dr4rWeaHDzzBnBF4ZjF6XxKns6klcTIzlJKluvzut0nX7yT99jN0FjGVB923GuZgI4ASwoQTL+5m
  template:
    metadata:
      name: axum-rentearth-secrets
      namespace: rentearth
