apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rentearth

resources:
    - rentearth-serviceaccount.yaml
    - rentearth-externalsecret.yaml
    - axum-rentearth-configmap.yaml
    - axum-rentearth-secrets-sealedsecret.yaml
    - axum-rentearth-deployment.yaml
    - axum-rentearth-httproute.yaml
    - rentearth-reference-grant.yaml
    - rentearth-certificate.yaml
