apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
    name: kilobase-remote-secret-store
    namespace: rentearth
spec:
    provider:
        kubernetes:
            remoteNamespace: kilobase
            auth:
                serviceAccount:
                    name: rentearth-external-secrets
                    namespace: rentearth
            server:
                url: https://kubernetes.default.svc
                caProvider:
                    type: ConfigMap
                    name: kube-root-ca.crt
                    key: ca.crt
                    namespace: kube-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: rentearth-supabase-secrets
    namespace: rentearth
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: kilobase-remote-secret-store
        kind: SecretStore
    target:
        name: supabase-shared
        creationPolicy: Owner
        template:
            engineVersion: v2
            data:
                jwt-secret: '{{ .jwtsecret }}'
                anon-key: '{{ .anonkey }}'
                service-role-key: '{{ .servicekey }}'
                db-url: 'postgres://postgres:{{ .dbpassword }}@supabase-cluster-rw.kilobase.svc.cluster.local:5432/supabase'
    data:
        - secretKey: jwtsecret
          remoteRef:
              key: supabase-jwt
              property: secret
        - secretKey: anonkey
          remoteRef:
              key: supabase-jwt
              property: anon-key
        - secretKey: servicekey
          remoteRef:
              key: supabase-jwt
              property: service-key
        - secretKey: dbpassword
          remoteRef:
              key: supabase-postgres
              property: password
