#!/usr/bin/env python3
"""Parse an NX graph JSON file into a Starlight MDX page.

Usage: nx-graph-to-mdx.py <graph.json> <output.mdx> <timestamp>
"""
import json
import sys


def main():
    if len(sys.argv) != 4:
        print(
            f"Usage: {sys.argv[0]} <graph.json> <output.mdx> <timestamp>", file=sys.stderr)
        sys.exit(1)

    graph_path, output_path, timestamp = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(graph_path) as f:
        data = json.load(f)

    nodes = data["graph"]["nodes"]
    deps = data["graph"]["dependencies"]

    # Group projects by type
    by_type: dict[str, list[str]] = {}
    for name, node in sorted(nodes.items()):
        ptype = node.get("type", "unknown")
        by_type.setdefault(ptype, []).append(name)

    # Build project rows
    rows = []
    for name in sorted(nodes):
        node = nodes[name]
        ptype = node.get("type", "unknown")
        root = node.get("data", {}).get("root", "")
        dep_count = len(deps.get(name, []))
        dependents = sum(
            1 for d_list in deps.values() for d in d_list if d["target"] == name
        )
        rows.append((name, ptype, root, dep_count, dependents))

    # Collect unique edges for mermaid
    mermaid_lines = ["graph LR"]
    seen_edges: set[tuple[str, str]] = set()
    for dep_list in deps.values():
        for d in dep_list:
            edge = (d["source"], d["target"])
            if edge not in seen_edges:
                seen_edges.add(edge)
                src_id = d["source"].replace("-", "_")
                tgt_id = d["target"].replace("-", "_")
                mermaid_lines.append(
                    f"    {src_id}[{d['source']}] --> {tgt_id}[{d['target']}]"
                )

    with open(output_path, "w") as out:
        # Frontmatter
        out.write(
            "---\n"
            "title: NX Dependency Graph\n"
            "description: |\n"
            "    Weekly auto-generated NX project dependency graph for the KBVE monorepo.\n"
            "sidebar:\n"
            "    label: NX Graph\n"
            "    order: 101\n"
            "editUrl: false\n"
            "---\n\n"
        )

        # Header
        out.write("## NX Dependency Graph\n\n")
        out.write(f"> Last generated: **{timestamp}**\n")
        out.write(">\n")
        out.write(
            "> Auto-generated every Tuesday by the `ci-weekly-nx-report` workflow.\n\n"
        )

        # Overview table
        out.write("### Overview\n\n")
        out.write("| Metric | Count |\n|--------|-------|\n")
        out.write(f"| Total Projects | {len(nodes)} |\n")
        out.write(f"| Total Dependencies | {len(seen_edges)} |\n")
        for ptype in sorted(by_type):
            out.write(
                f"| {ptype.capitalize()} Projects | {len(by_type[ptype])} |\n")
        out.write("\n")

        # Mermaid diagram (skip if too many edges)
        if len(seen_edges) <= 200:
            out.write("### Dependency Diagram\n\n")
            out.write("```mermaid\n")
            out.write("\n".join(mermaid_lines))
            out.write("\n```\n\n")
        else:
            out.write(
                "> Dependency diagram omitted — too many edges for inline rendering.\n\n"
            )

        # Project index table
        out.write("### Project Index\n\n")
        out.write(
            "| Project | Type | Root | Deps | Dependents |\n"
            "|---------|------|------|:----:|:----------:|\n"
        )
        for name, ptype, root, dep_count, dependents in rows:
            out.write(
                f"| {name} | {ptype} | `{root}` | {dep_count} | {dependents} |\n"
            )
        out.write("\n")

        # Per-project dependency details (collapsible)
        out.write("### Dependency Details\n\n")
        for name in sorted(nodes):
            dep_list = deps.get(name, [])
            if not dep_list:
                continue
            out.write("<details>\n")
            out.write(
                f"<summary><strong>{name}</strong> ({len(dep_list)} deps)</summary>\n\n"
            )
            out.write("| Target | Type |\n|--------|------|\n")
            for d in sorted(dep_list, key=lambda x: x["target"]):
                out.write(f"| {d['target']} | {d['type']} |\n")
            out.write("\n</details>\n\n")

        out.write("---\n\n")
        out.write(
            "*Auto-generated by "
            "[ci-weekly-nx-report.yml]"
            "(https://github.com/KBVE/kbve/actions/workflows/ci-weekly-nx-report.yml)*\n"
        )

    print(
        f"Generated {output_path} — {len(nodes)} projects, {len(seen_edges)} edges")


if __name__ == "__main__":
    main()
