apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: security-profiles-operator
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-wave: '2'
        kbve.com/source-path: kube/security-profiles-operator
        kbve.com/manifest-path: kube/security-profiles-operator
        kbve.com/application-file: kube/security-profiles-operator/application.yaml
        kbve.com/managed-by: argocd
        kbve.com/schema-version: v1
        kbve.com/category: security
        kbve.com/stack: core
spec:
    project: default
    sources:
        - repoURL: https://github.com/kubernetes-sigs/security-profiles-operator
          targetRevision: v1.0.0
          path: deploy/helm
          helm:
              releaseName: security-profiles-operator
              skipCrds: true
              valueFiles:
                  - $values/apps/kube/security-profiles-operator/manifests/values.yaml
        - repoURL: https://github.com/kbve/kbve
          targetRevision: main
          ref: values
    destination:
        server: https://kubernetes.default.svc
        namespace: security-profiles-operator
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
        managedNamespaceMetadata:
            labels:
                pod-security.kubernetes.io/enforce: privileged
                pod-security.kubernetes.io/audit: privileged
                pod-security.kubernetes.io/warn: privileged
        syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
            - RespectIgnoreDifferences=true
        retry:
            limit: 3
            backoff:
                duration: 30s
                factor: 2
                maxDuration: 3m
