// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GitHubUser {
    #[prost(string, tag = "1")]
    pub login: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GitHubLabel {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// hex without '#', e.g. "d73a4a"
    #[prost(string, tag = "2")]
    pub color: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GitHubIssueType {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub color: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct GitHubIssue {
    #[prost(uint64, tag = "1")]
    pub number: u64,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub state: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub user: ::core::option::Option<GitHubUser>,
    #[prost(message, repeated, tag = "5")]
    pub labels: ::prost::alloc::vec::Vec<GitHubLabel>,
    #[prost(string, tag = "6")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub updated_at: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub html_url: ::prost::alloc::string::String,
    #[prost(bool, tag = "9")]
    pub is_pull_request: bool,
    #[prost(message, repeated, tag = "10")]
    pub assignees: ::prost::alloc::vec::Vec<GitHubUser>,
    #[prost(string, tag = "11")]
    pub body: ::prost::alloc::string::String,
    #[prost(uint64, tag = "12")]
    pub comments: u64,
    #[prost(message, optional, tag = "13")]
    pub issue_type: ::core::option::Option<GitHubIssueType>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateIssueRequest {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub body: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub labels: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "4")]
    pub assignees: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "5")]
    pub issue_type: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateIssueRequest {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub body: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub state: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub labels: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "5")]
    pub assignees: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "6")]
    pub issue_type: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GitHubRef {
    #[prost(string, tag = "1")]
    pub ref_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sha: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct GitHubPull {
    #[prost(uint64, tag = "1")]
    pub number: u64,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub state: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub user: ::core::option::Option<GitHubUser>,
    #[prost(message, optional, tag = "5")]
    pub head: ::core::option::Option<GitHubRef>,
    #[prost(string, tag = "6")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub updated_at: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub html_url: ::prost::alloc::string::String,
    #[prost(bool, tag = "9")]
    pub draft: bool,
    #[prost(message, repeated, tag = "10")]
    pub labels: ::prost::alloc::vec::Vec<GitHubLabel>,
    #[prost(message, repeated, tag = "11")]
    pub assignees: ::prost::alloc::vec::Vec<GitHubUser>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MergePullRequest {
    #[prost(string, tag = "1")]
    pub commit_title: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub commit_message: ::prost::alloc::string::String,
    /// "merge", "squash", or "rebase"
    #[prost(string, tag = "3")]
    pub merge_method: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GitHubMergeResult {
    #[prost(string, tag = "1")]
    pub sha: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub merged: bool,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GitHubCommitAuthor {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub date: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GitHubCommitDetail {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub author: ::core::option::Option<GitHubCommitAuthor>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GitHubCommit {
    #[prost(string, tag = "1")]
    pub sha: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub commit: ::core::option::Option<GitHubCommitDetail>,
    #[prost(string, tag = "3")]
    pub html_url: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GitHubRepo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub full_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub html_url: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub default_branch: ::prost::alloc::string::String,
    #[prost(uint64, tag = "6")]
    pub open_issues_count: u64,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GitHubStatusChecks {
    #[prost(bool, tag = "1")]
    pub strict: bool,
    #[prost(string, repeated, tag = "2")]
    pub contexts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(
    serde::Serialize, serde::Deserialize, Clone, Copy, PartialEq, Eq, Hash, ::prost::Message,
)]
pub struct GitHubEnforceAdmins {
    #[prost(bool, tag = "1")]
    pub enabled: bool,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GitHubBranchProtection {
    #[prost(message, optional, tag = "1")]
    pub required_status_checks: ::core::option::Option<GitHubStatusChecks>,
    #[prost(message, optional, tag = "2")]
    pub enforce_admins: ::core::option::Option<GitHubEnforceAdmins>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GitHubComment {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub body: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub user: ::core::option::Option<GitHubUser>,
    #[prost(string, tag = "4")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub updated_at: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub html_url: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct GitHubSearchResult {
    #[prost(uint64, tag = "1")]
    pub total_count: u64,
    #[prost(bool, tag = "2")]
    pub incomplete_results: bool,
    #[prost(message, repeated, tag = "3")]
    pub items: ::prost::alloc::vec::Vec<GitHubIssue>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GitHubWorkflow {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub state: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub html_url: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct GitHubWorkflowsResponse {
    #[prost(uint64, tag = "1")]
    pub total_count: u64,
    #[prost(message, repeated, tag = "2")]
    pub workflows: ::prost::alloc::vec::Vec<GitHubWorkflow>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct DispatchWorkflowRequest {
    /// file name or numeric ID
    #[prost(string, tag = "1")]
    pub workflow_id: ::prost::alloc::string::String,
    /// git ref (branch, tag, sha)
    #[prost(string, tag = "2")]
    pub r#ref: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub inputs:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(
    serde::Serialize, serde::Deserialize, Clone, Copy, PartialEq, Eq, Hash, ::prost::Message,
)]
pub struct GitHubRateLimit {
    #[prost(uint32, tag = "1")]
    pub remaining: u32,
    #[prost(uint32, tag = "2")]
    pub limit: u32,
    #[prost(uint64, tag = "3")]
    pub reset: u64,
}
