---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: stalwart-hook-secret
    namespace: herbmail
spec:
    encryptedData:
        secret: AgBnT6iuScpalMesppob3tCyhytPSPtCPKkUIvXTy9dJccxiIpGy5U80DTQPo+aLvFBOueT3glcOuLSndGYMDHfUuJJNQoHUai7xVobmCyYh873+bU4ub1mI0PAO7mOF7PIEFddGnH0OjL394UriGulIEkezAtsW85E3aqZ7abqyxfbZlqz5/zAb6qDczGue2Fy3aI77zfONQPbS9vkKiL/to/DnroHHqIOtMLKxcg4jEp74jilWF64QUkcvCRUG1XX7bZCWMGMULSBSIVFHLVPufMBH+ZwrC1LKmABdRmY9BbaLGDeSDajSU6aXKckMP3FeSl/BH6rxgVvWX8wZ+syIxiyQ4kky6JUNZCUO4OEdAj39GqVU3c7pj4Uc5LOSuk5gFEGtzCe7gXZJO5na9O+J2FrAWgW94nsZjDlVxMUvHwfjCqePTsFxRzfoKuClRiIAVPatkaipoeC/tpG8/F+rJPl1IouE/bZWq+IJYbBgQvxBZR6AaZPi2wbQGUcE+lnRFPsA15ZL+MqZaQWKde5mSGGxvfjbC9hDXI24DvMi3Lf+B0gySPzm7YkqAMids7mryMkzDMCKxX7O9B1ynyzxjmuR+/y+HUOXNt4yZwK0rNalj52v0IRJeBUHBrMV9lXWjsQq3DiZOqqSED23SdZocYNHrxHUNYJr3MNpO/bXGqS4KqixBz5z1pXKziyoag71EJnbPeYPqaGoifseQ9Qb3NwurHNwoqUbj9kB/FkXnOKi4Aii+ulP
    template:
        metadata:
            name: stalwart-hook-secret
            namespace: herbmail
