apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: supabase-service-key-reader-for-chuckrpg-dev
    namespace: kilobase
rules:
    - apiGroups: ['']
      resources: ['secrets']
      resourceNames: ['supabase-service-key']
      verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: agones-read-svckey-chuckrpg-dev
    namespace: kilobase
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: supabase-service-key-reader-for-chuckrpg-dev
subjects:
    - kind: ServiceAccount
      name: agones-rows-chuckrpg-dev-secrets
      namespace: arc-runners
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
    name: kilobase-svckey-store-chuckrpg-dev
    namespace: arc-runners
spec:
    provider:
        kubernetes:
            remoteNamespace: kilobase
            auth:
                serviceAccount:
                    name: agones-rows-chuckrpg-dev-secrets
                    namespace: arc-runners
            server:
                url: https://kubernetes.default.svc
                caProvider:
                    type: ConfigMap
                    name: kube-root-ca.crt
                    key: ca.crt
                    namespace: kube-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: ows-service-key-chuckrpg-dev
    namespace: arc-runners
spec:
    refreshInterval: 15m
    secretStoreRef:
        name: kilobase-svckey-store-chuckrpg-dev
        kind: SecretStore
    target:
        name: ows-service-key-chuckrpg-dev
        creationPolicy: Owner
    data:
        - secretKey: service-key
          remoteRef:
              key: supabase-service-key
              property: key
