#include "RareIconPlayerPawn.h"

#include "Components/CapsuleComponent.h"
#include "Animation/AnimSequence.h"
#include "DrawDebugHelpers.h"
#include "Components/SkeletalMeshComponent.h"
#include "Engine/SkeletalMesh.h"
#include "InputAction.h"
#include "InputMappingContext.h"
#include "Components/CapsuleComponent.h"
#include "Engine/Engine.h"
#include "Engine/World.h"
#include "GameFramework/PlayerController.h"
#include "HAL/IConsoleManager.h"
#include "UnrealClient.h"
#include "DefaultMovementSet/CharacterMoverComponent.h"
#include "MoveLibrary/FloorQueryUtils.h"
#include "KBVEFootIKAnimInstance.h"
#include "KBVEWeaponGrip.h"
#include "GameFramework/SpringArmComponent.h"
#include "Camera/CameraComponent.h"
#include "UnrealClient.h"
#include "KBVEWorldHeightfield.h"
#include "KBVEWorldStreamer.h"
#include "KBVEWorldHeightfieldActor.h"
#include "RareIcon.h"
#include "EngineUtils.h"
#include "UObject/ConstructorHelpers.h"

namespace
{
	// Manny ships inside the MoverExamples plugin rather than as engine content,
	// because this install has no feature packs. That makes the player mesh a
	// dependency on an Experimental plugin's sample content -- fine for finding
	// the feel of the game, wrong to ship. Replacing it means changing this path
	// and nothing else.
	const TCHAR* MannyMeshPath = TEXT("/MoverExamples/Characters/Mannequins/Meshes/SKM_Manny_Simple.SKM_Manny_Simple");

	// Epic's Game Animation Sample rifle set, staged and imported by the
	// `import-animations` moon task. Authored on the UE5 mannequin rig, which
	// shares 86 of its 87 bones with this one, so they bind with no retarget.
	//
	// They hold the weapon themselves -- stance, grip and finger pose are all
	// animated -- which is why the procedural weapon hold below is off. A pose
	// an animator authored beats one a solver reconstructs.
	//
	// Individual clips rather than the blendspaces beside them, because playing
	// a blendspace needs an animation graph to evaluate it. Single-node playback
	// is the honest floor: no strafe set and no turn-in-place, both of which are
	// in the source set waiting for a graph that can blend them.
	const TCHAR* IdleAnimPath = TEXT("/Game/Animations/Rifle/A_Rifle_Idle.A_Rifle_Idle");
	const TCHAR* WalkAnimPath = TEXT("/Game/Animations/Rifle/A_Rifle_Walk_F.A_Rifle_Walk_F");
	const TCHAR* RunAnimPath = TEXT("/Game/Animations/Rifle/A_Rifle_Run_F.A_Rifle_Run_F");
	const TCHAR* FallAnimPath = TEXT("/Game/Animations/Rifle/A_Rifle_Jump_Start.A_Rifle_Jump_Start");

	// Generated by the `import-weapons` moon task rather than authored: the
	// PolyHaven source ships as loose rigid parts, and scripts/rig_weapon.py
	// builds the armature from their geometry. See that file for the bolt axis.
	const TCHAR* RifleMeshPath = TEXT("/Game/Weapons/SK_Rifle_BoltAction762.SK_Rifle_BoltAction762");

	// Built by `build-weapon-grips` from scripts/config/weapons.json.
	const TCHAR* RifleGripPath = TEXT("/Game/Weapons/DA_Grip_BoltAction762.DA_Grip_BoltAction762");

	// A second weapon, to find out whether the grip pipeline describes a rifle
	// or just describes the Mosin. Different length, different section, barrel
	// on a different axis in the source -- if the hand lands on both from
	// measurements alone, the data asset is doing its job.
	const TCHAR* SS2MeshPath = TEXT("/Game/Weapons/SK_Rifle_SS2V5.SK_Rifle_SS2V5");
	const TCHAR* SS2GripPath = TEXT("/Game/Weapons/DA_Grip_SS2V5.DA_Grip_SS2V5");

	// Strip the weapon and every pass that touches an arm, leaving the clip.
	//
	// The control this whole grip investigation lacked: if the left wrist still
	// reads as twisted with nothing solving it, the twist is authored into the
	// animation and no solver change was ever going to fix it.
	// A bench for the grip: idle clip, camera parked on the weapon, nothing
	// moving. A day of this was spent launching the editor, entering play and
	// chasing a walking character with a screenshot to judge where a thumb sat.
	// Frozen, not merely idling. The idle clip breathes and sways, which is
	// enough to make a still of a thumb impossible to line up against the last
	// one -- and comparing two stills is the entire point of a bench. Zero holds
	// the first frame; set it to 1 to watch the hold move.
	static float GGripLabRate = 0.0f;
	static FAutoConsoleVariableRef CVarGripLabRate(
		TEXT("rareicon.Grip.LabRate"), GGripLabRate,
		TEXT("Play rate for the held idle clip in the grip lab. 0 freezes it."), ECVF_Default);

	static int32 GGripLab = 0;
	static FAutoConsoleVariableRef CVarGripLab(
		TEXT("rareicon.Grip.Lab"), GGripLab,
		TEXT("1 holds the idle pose and parks the camera on the weapon, for judging a grip."),
		ECVF_Default);

	// Name every bone the grip touches, on screen, with a leader line out to the
	// label. Saying "the wrist looks twisted" and "lower lowerarm_twist_02_l by
	// three degrees" are different sentences, and only one of them is actionable.
	// On by default while the grip is being worked on: the whole point is that
	// nobody should have to remember a console command to see which bone is
	// which. Set to 0 when the hands are settled.
	static int32 GGripBones = 1;
	static FAutoConsoleVariableRef CVarGripBones(
		TEXT("rareicon.Grip.Bones"), GGripBones,
		TEXT("1 labels the support arm and finger roots, 2 labels every finger joint."),
		ECVF_Default);

	// Where the label column sits and how big it reads, live. The camera
	// framing earlier cost a dozen rebuilds to find an angle by trial; this is
	// dialable from the console instead.
	static float GGripBonesSide = -30.0f;
	static float GGripBonesSpread = 3.2f;
	static float GGripBonesText = 2.0f;
	static FAutoConsoleVariableRef CVarGripBonesSide(
		TEXT("rareicon.Grip.BonesSide"), GGripBonesSide,
		TEXT("Sideways offset of the bone label column, cm. Negative puts it clear of the weapon."),
		ECVF_Default);
	static FAutoConsoleVariableRef CVarGripBonesSpread(
		TEXT("rareicon.Grip.BonesSpread"), GGripBonesSpread,
		TEXT("Vertical gap between bone labels, cm."), ECVF_Default);
	static FAutoConsoleVariableRef CVarGripBonesText(
		TEXT("rareicon.Grip.BonesText"), GGripBonesText,
		TEXT("Bone label font scale."), ECVF_Default);

	static int32 GWeaponHide = 0;
	static FAutoConsoleVariableRef CVarWeaponHide(
		TEXT("rareicon.Weapon.Hide"), GWeaponHide,
		TEXT("1 hides the weapon and disables every arm solve, showing the clip alone."),
		ECVF_Default);

	static int32 GWeaponUse = 0;
	static FAutoConsoleVariableRef CVarWeaponUse(
		TEXT("rareicon.Weapon.Use"), GWeaponUse,
		TEXT("0 the bolt-action Mosin, 1 the SS2-V5. Swaps mesh and grip asset live."),
		ECVF_Default);

	template <typename T>
	T* FindAsset(const TCHAR* Path)
	{
		ConstructorHelpers::FObjectFinder<T> Finder(Path);
		return Finder.Succeeded() ? Finder.Object : nullptr;
	}
}

ARareIconPlayerPawn::ARareIconPlayerPawn(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	PrimaryActorTick.bCanEverTick = true;
	if (Mesh)
	{
		if (USkeletalMesh* Manny = FindAsset<USkeletalMesh>(MannyMeshPath))
		{
			Mesh->SetSkeletalMesh(Manny);
			// Manny's origin is at his feet and the capsule's is at its centre,
			// so the mesh has to drop by the half-height or he floats. The yaw
			// is because the skeleton faces -Y and a pawn's forward is +X.
			const float HalfHeight = Capsule ? Capsule->GetUnscaledCapsuleHalfHeight() : 88.0f;
			Mesh->SetRelativeLocationAndRotation(
				FVector(0.0f, 0.0f, -HalfHeight), FRotator(0.0f, -90.0f, 0.0f));
		}

		// A native anim instance rather than an animation blueprint: the one that
		// ships beside this mesh does not compile in 5.8, and this keeps the
		// whole solve in C++ where it shows up in a diff. It plays the one clip
		// the locomotion picks and plants both feet on the ground beneath them.
		Mesh->SetAnimInstanceClass(UKBVEFootIKAnimInstance::StaticClass());
		Mesh->SetAnimationMode(EAnimationMode::AnimationBlueprint);

		// Attached to the chest rather than a hand: the arms are solved onto the
		// weapon, not the other way round. It has no collision of its own -- the
		// capsule is what the world tests against, and a rifle barrel sweeping
		// the geometry would push the character off ledges it stands clear of.
		WeaponMesh = CreateDefaultSubobject<USkeletalMeshComponent>(TEXT("WeaponMesh"));
		WeaponMesh->SetupAttachment(Mesh, WeaponAttachBone);
		WeaponGrip = FindAsset<UKBVEWeaponGrip>(RifleGripPath);
		WeaponMesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);
		WeaponMesh->SetCanEverAffectNavigation(false);
		if (USkeletalMesh* Rifle = FindAsset<USkeletalMesh>(RifleMeshPath))
		{
			WeaponMesh->SetSkeletalMesh(Rifle);
		}
		WeaponMesh->SetRelativeTransform(WeaponAttachOffset);
	}

	InputMappingContext = FindAsset<UInputMappingContext>(TEXT("/Game/Input/IMC_RareIcon.IMC_RareIcon"));
	MoveAction = FindAsset<UInputAction>(TEXT("/Game/Input/IA_Move.IA_Move"));
	LookAction = FindAsset<UInputAction>(TEXT("/Game/Input/IA_Look.IA_Look"));
	JumpAction = FindAsset<UInputAction>(TEXT("/Game/Input/IA_Jump.IA_Jump"));
	SprintAction = FindAsset<UInputAction>(TEXT("/Game/Input/IA_Sprint.IA_Sprint"));
	ZoomAction = FindAsset<UInputAction>(TEXT("/Game/Input/IA_Zoom.IA_Zoom"));
	InteractAction = FindAsset<UInputAction>(TEXT("/Game/Input/IA_Interact.IA_Interact"));
	InventoryAction = FindAsset<UInputAction>(TEXT("/Game/Input/IA_Inventory.IA_Inventory"));

	IdleAnim = FindAsset<UAnimSequence>(IdleAnimPath);
	WalkAnim = FindAsset<UAnimSequence>(WalkAnimPath);
	RunAnim = FindAsset<UAnimSequence>(RunAnimPath);
	FallAnim = FindAsset<UAnimSequence>(FallAnimPath);
}

namespace
{
	// Off by default: this writes a file, and a game that drops a screenshot into
	// Saved/ on every run is a surprise rather than a diagnostic.
	static bool GAutoShot = false;
	// Later than the feet report on purpose: the player start is 1500 units up,
	// so a shot taken as soon as the pawn exists catches it still falling and
	// posed mid-air rather than standing in its idle.
	// Live handles for seating the weapon in the support hand. Both rotate about
	// the trigger-hand grip, because that is the contact that must not move.
	static float GWeaponPitch = 0.0f;
	static float GWeaponRoll = 0.0f;

	// The attach offset, dialable. Pitch and roll were reachable from the
	// console and the three numbers beside them were not, so the one transform
	// that decides where a weapon sits in the hand could only be tried by
	// editing a config, rebuilding the grip assets and restarting -- which is
	// why the second rifle shipped with it unverified. In the hand's own space,
	// which is the frame the offset is written in: X slides the hand along the
	// weapon, Y takes it outboard, Z lifts it.
	static float GWeaponOffsetX = 0.0f;
	static float GWeaponOffsetY = 0.0f;
	static float GWeaponOffsetZ = 0.0f;
	static FAutoConsoleVariableRef CVarWeaponPitch(
		TEXT("rareicon.Weapon.Pitch"), GWeaponPitch,
		TEXT("Extra weapon pitch about the trigger-hand grip, degrees."), ECVF_Default);
	static FAutoConsoleVariableRef CVarWeaponRoll(
		TEXT("rareicon.Weapon.Roll"), GWeaponRoll,
		TEXT("Extra weapon roll about the trigger-hand grip, degrees."), ECVF_Default);

	// Draws the weapon as the hand solver believes it to be: the bore it rolls
	// the wrist around and the fore-end it closes the fingers onto. If this
	// cylinder is not lying inside the rendered barrel then every grip number
	// downstream is being measured against a rifle that is not there, and no
	// amount of finger solving converges.
	// Report the mannequin's weapon-IK bones against the weapon, once a second.
	//
	// Whether these clips animate ik_hand_l decides the whole approach, and it
	// is not a thing to judge by eye: a bone welded to the wrist and a bone
	// authored onto a fore-end can sit a few centimetres apart and look alike
	// through a viewport. Moving over time and sitting near the wood is the
	// answer, and both are numbers.
	static int32 GGripIKReport = 0;
	static FAutoConsoleVariableRef CVarGripIKReport(
		TEXT("rareicon.Grip.IKReport"), GGripIKReport,
		TEXT("Log ik_hand_gun and ik_hand_l against the weapon once a second."), ECVF_Default);

	static int32 GWeaponDrawBore = 0;
	// Frame the support hand and photograph it, so a grip can be looked at
	// instead of inferred from joint angles. Six rounds of this were spent
	// measuring numbers that were all individually correct while the hand
	// still looked wrong, which is a thing only a picture settles.
	static float GGripShotSeconds = -1.0f;
	static float GGripShotYaw = -100.0f;
	static float GGripShotPitch = -15.0f;
	static float GGripShotDist = 42.0f;
	static int32 GGripShotWeapon = 1;
	static FAutoConsoleVariableRef CVarGripShotWeapon(
		TEXT("rareicon.Weapon.GripShotWeapon"), GGripShotWeapon,
		TEXT("1 frames the weapon in world space, 0 frames the support hand in the pawn's frame."),
		ECVF_Default);
	static FAutoConsoleVariableRef CVarGripShotYaw(
		TEXT("rareicon.Weapon.GripShotYaw"), GGripShotYaw,
		TEXT("Camera yaw about the support hand for the grip shot, relative to the pawn."), ECVF_Default);
	static FAutoConsoleVariableRef CVarGripShotPitch(
		TEXT("rareicon.Weapon.GripShotPitch"), GGripShotPitch,
		TEXT("Camera pitch for the grip shot."), ECVF_Default);
	static FAutoConsoleVariableRef CVarGripShotDist(
		TEXT("rareicon.Weapon.GripShotDist"), GGripShotDist,
		TEXT("Camera distance from the support hand for the grip shot, cm."), ECVF_Default);
	static FAutoConsoleVariableRef CVarGripShot(
		TEXT("rareicon.Weapon.GripShot"), GGripShotSeconds,
		TEXT("Seconds to wait, then frame the left hand, screenshot it and quit. -1 off."),
		ECVF_Default);
	static FAutoConsoleVariableRef CVarWeaponOffsetX(
		TEXT("rareicon.Weapon.OffsetX"), GWeaponOffsetX,
		TEXT("Slide the weapon along its own length in the trigger hand, cm."), ECVF_Default);
	static FAutoConsoleVariableRef CVarWeaponOffsetY(
		TEXT("rareicon.Weapon.OffsetY"), GWeaponOffsetY,
		TEXT("Move the weapon outboard in the trigger hand, cm."), ECVF_Default);
	static FAutoConsoleVariableRef CVarWeaponOffsetZ(
		TEXT("rareicon.Weapon.OffsetZ"), GWeaponOffsetZ,
		TEXT("Lift the weapon in the trigger hand, cm."), ECVF_Default);
	static FAutoConsoleVariableRef CVarWeaponDrawBore(
		TEXT("rareicon.Weapon.DrawBore"), GWeaponDrawBore,
		TEXT("Draw the bore and fore-end the grip solver is aiming at."), ECVF_Default);

	static float GAutoShotDelay = 9.0f;
	static FAutoConsoleVariableRef CVarAutoShotDelay(
		TEXT("rareicon.AutoShotDelay"),
		GAutoShotDelay,
		TEXT("Seconds after possession before the automatic screenshot."),
		ECVF_Default);
	static FAutoConsoleVariableRef CVarAutoShot(
		TEXT("rareicon.AutoShot"),
		GAutoShot,
		TEXT("Take one screenshot a few seconds after possession."),
		ECVF_Default);
}

void ARareIconPlayerPawn::BeginPlay()
{
	Super::BeginPlay();

	// Reapplied here as well as in the constructor so that editing the offset on
	// the placed pawn takes effect: the constructor runs once against the class
	// default, and a value changed in the details panel would otherwise never
	// reach the component.
	if (WeaponMesh)
	{
		WeaponMesh->SetRelativeTransform(WeaponAttachOffset);
	}

	// One source of truth for where the weapon is. The component is parented to
	// the chest and the solver places the hands from the same transform, so
	// handing it over here is what keeps the rifle the arms are reaching for and
	// the rifle being drawn in the same place.
	if (UKBVEFootIKAnimInstance* AnimInstance = Mesh ? Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance()) : nullptr)
	{
		// Off, because the rifle clips already hold the weapon. The solver stays
		// in the class for characters without an authored hold; running it over
		// clips that have one would fight them for the same bones.
		AnimInstance->SetHoldWeapon(bUseProceduralWeaponHold);

		// The solver has to find the weapon exactly where the component is, so
		// it is told the same bone and the same offset rather than keeping its
		// own copy that could drift out of step.
		AnimInstance->WeaponHandBone = WeaponAttachBone;
		AnimInstance->WeaponRelativeToHand = WeaponAttachOffset;

		// Without this the grip asset is built and never read, and the support
		// hand keeps whatever fingers the locomotion clip happened to have.
		AnimInstance->WeaponGrip = WeaponGrip;
		StoredLeftHandIKAlpha = AnimInstance->LeftHandIKAlpha;
		StoredFitWeaponToHands = AnimInstance->bFitWeaponToHands;
	}
}

void ARareIconPlayerPawn::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);
	UpdateLocomotionAnimation(DeltaSeconds);

	// A close, fixed view of the support hand, held from the moment play starts
	// so the shot below lands on a settled pose rather than a spawn frame.
	if ((GGripShotSeconds >= 0.0f || GGripLab != 0) && Mesh && CameraBoom)
	{
		// Framed on the weapon in world space, not on a hand in the pawn's own
		// frame. Aiming at hand_l meant the character turned into the shot and
		// occluded the thing being photographed, which cost several rounds of
		// screenshots that showed a torso and a sliver of wood.
		const FVector Target = (GGripShotWeapon != 0 && WeaponMesh)
			? WeaponMesh->Bounds.Origin
			: Mesh->GetSocketLocation(TEXT("hand_l"));
		CameraBoom->SetWorldLocation(Target);

		// Looking from the character's left and slightly below: the grip is on
		// the underside of the fore-end, and the body hides it from anywhere in
		// front. Yaw follows the pawn so the view holds as the character turns.
		CameraBoom->SetWorldRotation(GGripShotWeapon != 0
			? FRotator(GGripShotPitch, GGripShotYaw, 0.0f)
			: FRotator(GGripShotPitch, GetActorRotation().Yaw + GGripShotYaw, 0.0f));
		CameraBoom->TargetArmLength = GGripShotDist;
		CameraBoom->bDoCollisionTest = false;

		// The boom follows the controller by default, which quietly threw away
		// every rotation set above: two bench runs at ninety degrees apart came
		// out pixel for pixel identical, so the one control that frames the
		// weapon did nothing and the shot was whatever the character faced.
		CameraBoom->bUsePawnControlRotation = false;

		GripShotElapsed += DeltaSeconds;
		if (GripShotElapsed >= GGripShotSeconds && !bGripShotTaken)
		{
			bGripShotTaken = true;
			// With the UI, because that is where the debug text lives: bone
			// labels go through the HUD, and asking for a screenshot without
			// the UI strips the labels out of the very shot taken to check them.
			FScreenshotRequest::RequestScreenshot(true);
			UE_LOG(LogTemp, Display, TEXT("grip shot: requested at %.1fs"), GripShotElapsed);
		}
		else if (bGripShotTaken && GripShotElapsed >= GGripShotSeconds + 1.5f)
		{
			FPlatformMisc::RequestExit(false);
		}
	}

	if (GGripIKReport > 0 && Mesh)
	{
		IKReportElapsed += DeltaSeconds;
		if (IKReportElapsed >= 1.0f)
		{
			IKReportElapsed = 0.0f;
			const FTransform Gun = Mesh->GetSocketTransform(TEXT("ik_hand_gun"), RTS_Component);
			const FTransform IKL = Mesh->GetSocketTransform(TEXT("ik_hand_l"), RTS_Component);
			const FTransform HandL = Mesh->GetSocketTransform(TEXT("hand_l"), RTS_Component);
			const FTransform HandR = Mesh->GetSocketTransform(TEXT("hand_r"), RTS_Component);

			// Relative to the gun bone, because that is the frame a hold would
			// be authored in: a constant here means unanimated, whatever the
			// character is doing.
			const FVector RelGun = Gun.InverseTransformPosition(IKL.GetLocation());

			// Reach against requirement, which is the question a miss actually
			// raises: an arm that cannot get there and an arm aimed somewhere
			// wrong both leave the hand off the weapon and look identical.
			const FTransform Shoulder = Mesh->GetSocketTransform(TEXT("upperarm_l"), RTS_Component);
			const FTransform Elbow = Mesh->GetSocketTransform(TEXT("lowerarm_l"), RTS_Component);
			const float ArmLength =
				FVector::Dist(Shoulder.GetLocation(), Elbow.GetLocation())
				+ FVector::Dist(Elbow.GetLocation(), HandL.GetLocation());

			// Against the point the arm was sent to, not the point on the wood.
			//
			// They are deliberately different -- a wrist stands off a rifle by
			// the length of the hand in front of it -- so scoring the wrist
			// against the wood reported a fixed eight-centimetre miss on a grip
			// that had landed exactly, and no amount of solving would ever have
			// cleared it. The standoff is reported beside it as its own figure,
			// because a hand that is not standing off is a different fault.
			FVector SocketAt = FVector::ZeroVector;
			FVector TargetAt = FVector::ZeroVector;
			float NeedReach = 0.0f;
			const UKBVEFootIKAnimInstance* Solved =
				Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance());
			if (Solved && Solved->bResolvedSupportSocketValid && WeaponMesh)
			{
				const FTransform Weapon = WeaponMesh->GetComponentTransform();
				const FTransform ToLocal = Mesh->GetComponentTransform();
				SocketAt = ToLocal.InverseTransformPosition(
					(Solved->ResolvedSupportSocket * Weapon).GetLocation());
				TargetAt = ToLocal.InverseTransformPosition(
					Weapon.TransformPosition(Solved->ResolvedSupportTarget));
				NeedReach = FVector::Dist(Shoulder.GetLocation(), TargetAt);
			}

			UE_LOG(LogTemp, Display,
				TEXT("grip reach: shoulder(%.1f %.1f %.1f) socket(%.1f %.1f %.1f) "
					 "target(%.1f %.1f %.1f) need=%.1f arm=%.1f slack=%+.1f miss=%.1f standoff=%.1f"),
				Shoulder.GetLocation().X, Shoulder.GetLocation().Y, Shoulder.GetLocation().Z,
				SocketAt.X, SocketAt.Y, SocketAt.Z, TargetAt.X, TargetAt.Y, TargetAt.Z,
				NeedReach, ArmLength, ArmLength - NeedReach,
				FVector::Dist(TargetAt, HandL.GetLocation()),
				FVector::Dist(SocketAt, HandL.GetLocation()));

			UE_LOG(LogTemp, Display,
				TEXT("grip ik: gun(%.1f %.1f %.1f) ik_l(%.1f %.1f %.1f) rel_gun(%.2f %.2f %.2f) "
					 "hand_l(%.1f %.1f %.1f) |ik_l-hand_l|=%.2f |gun-hand_r|=%.2f"),
				Gun.GetLocation().X, Gun.GetLocation().Y, Gun.GetLocation().Z,
				IKL.GetLocation().X, IKL.GetLocation().Y, IKL.GetLocation().Z,
				RelGun.X, RelGun.Y, RelGun.Z,
				HandL.GetLocation().X, HandL.GetLocation().Y, HandL.GetLocation().Z,
				FVector::Dist(IKL.GetLocation(), HandL.GetLocation()),
				FVector::Dist(Gun.GetLocation(), HandR.GetLocation()));
		}
	}

	// The support-hand skeleton, named.
	if (GGripBones > 0 && Mesh)
	{
		// The mannequin's own weapon-IK bones, alongside the arm they exist to
		// drive. Manny carries ik_hand_gun and ik_hand_l, which is where a rifle
		// hold is conventionally authored: the weapon mounts to the first and
		// the animator poses the second onto its fore-end, leaving IK to enforce
		// a hold rather than invent one. Whether these clips actually animate
		// them is the question, and drawing them is how it gets answered.
		static const TCHAR* Arm[] = {
			TEXT("lowerarm_l"), TEXT("lowerarm_twist_02_l"), TEXT("lowerarm_twist_01_l"), TEXT("hand_l"),
			TEXT("ik_hand_gun"), TEXT("ik_hand_l"),
		};
		static const TCHAR* Chains[] = {
			TEXT("thumb"), TEXT("index"), TEXT("middle"), TEXT("ring"), TEXT("pinky"),
		};

		TArray<FName, TInlineAllocator<24>> Bones;
		for (const TCHAR* Name : Arm)
		{
			Bones.Add(FName(Name));
		}
		for (const TCHAR* Chain : Chains)
		{
			const int32 Last = GGripBones > 1 ? 3 : 1;
			for (int32 Joint = 1; Joint <= Last; ++Joint)
			{
				Bones.Add(FName(*FString::Printf(TEXT("%s_0%d_l"), Chain, Joint)));
			}
		}

		// Labels stacked in a column beside the hand rather than sitting on the
		// bones: at finger scale the text would overlap into an unreadable pile.
		const FVector Anchor = Mesh->GetSocketLocation(TEXT("hand_l"));

		// Stacked against the camera, not against the character. Offsetting
		// along the actor's right vector puts the column edge-on or behind the
		// hand as the pawn turns, and the lab camera holds a fixed world yaw
		// rather than following the pawn, so the two drift apart immediately.
		FVector Right = GetActorRightVector();
		FVector Up = FVector::UpVector;
		if (FollowCamera)
		{
			const FRotator View = FollowCamera->GetComponentRotation();
			Right = FRotationMatrix(View).GetScaledAxis(EAxis::Y);
			Up = FRotationMatrix(View).GetScaledAxis(EAxis::Z);
		}

		// A hue per finger, dimming toward the fingertip.
		//
		// Every finger drawn the same colour is what makes a bad hold hard to
		// report: the picture says a knuckle is wrong and cannot say which
		// knuckle, so the reply is "it looks bad" and the next guess is blind.
		// Named colours the eye separates at finger scale, and the wrist white
		// because it is the joint every one of these arguments is about.
		auto ChainColour = [](int32 Chain, int32 Joint) -> FColor
		{
			static const FColor Hues[] = {
				FColor(255, 140, 0),    // thumb
				FColor(60, 220, 60),    // index
				FColor(255, 0, 255),    // middle
				FColor(80, 150, 255),   // ring
				FColor(255, 230, 0),    // pinky
			};
			const FColor Hue = Hues[Chain % UE_ARRAY_COUNT(Hues)];
			const float Fade = Joint <= 0 ? 1.0f : (Joint == 1 ? 0.72f : 0.5f);
			return FColor(uint8(Hue.R * Fade), uint8(Hue.G * Fade), uint8(Hue.B * Fade));
		};

		const int32 ArmCount = UE_ARRAY_COUNT(Arm);
		const int32 JointsPerChain = GGripBones > 1 ? 3 : 1;

		for (int32 Index = 0; Index < Bones.Num(); ++Index)
		{
			const int32 BoneIndex = Mesh->GetBoneIndex(Bones[Index]);
			if (BoneIndex == INDEX_NONE)
			{
				continue;
			}
			const FVector At = Mesh->GetBoneLocation(Bones[Index]);
			// By name, not by position in the list. Highlighting the last arm
			// entry marked whichever bone happened to be appended most recently
			// -- which, once the IK bones were added for inspection, was not the
			// wrist at all. The one bone every one of these arguments is about
			// was the one drawn in the wrong colour.
			const bool bArm = Index < ArmCount;
			const bool bWrist = Bones[Index] == FName(TEXT("hand_l"));

			FColor Colour = FColor::White;
			if (!bArm)
			{
				const int32 Finger = Index - ArmCount;
				Colour = ChainColour(Finger / JointsPerChain, Finger % JointsPerChain);
			}
			else if (!bWrist)
			{
				Colour = FColor(0, 190, 190);
			}

			DrawDebugSphere(GetWorld(), At, bWrist ? 1.4f : 0.9f, 10, Colour, false, -1.0f,
				SDPG_Foreground, bWrist ? 0.5f : 0.3f);

			const FVector Label = Anchor
				+ Up * (Bones.Num() * GGripBonesSpread * 0.5f - Index * GGripBonesSpread)
				+ Right * GGripBonesSide;
			DrawDebugLine(GetWorld(), At, Label, Colour, false, -1.0f, SDPG_Foreground, 0.35f);
			DrawDebugString(GetWorld(), Label, Bones[Index].ToString(), nullptr, Colour, 0.0f,
				true, GGripBonesText);
		}

		// The forearm's own line, so a twist reads against something straight.
		const int32 Elbow = Mesh->GetBoneIndex(TEXT("lowerarm_l"));
		if (Elbow != INDEX_NONE)
		{
			DrawDebugLine(GetWorld(), Mesh->GetBoneLocation(TEXT("lowerarm_l")),
				Mesh->GetBoneLocation(TEXT("hand_l")), FColor(0, 190, 190), false, -1.0f,
				SDPG_Foreground, 0.2f);
		}
	}

	// Nothing held, nothing solved: the clip as the animator left it.
	if (Mesh)
	{
		if (WeaponMesh && WeaponMesh->IsVisible() == (GWeaponHide != 0))
		{
			WeaponMesh->SetVisibility(GWeaponHide == 0, true);
		}
		if (UKBVEFootIKAnimInstance* Anim = Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance()))
		{
			const bool bHide = GWeaponHide != 0;
			Anim->LeftHandIKAlpha = bHide ? 0.0f : StoredLeftHandIKAlpha;
			Anim->bFitWeaponToHands = bHide ? false : StoredFitWeaponToHands;
			Anim->SetHoldWeapon(bHide ? false : bUseProceduralWeaponHold);
		}
	}

	// Swapped live rather than at spawn, so two weapons can be compared without
	// a relaunch -- which is the whole point of measuring a grip instead of
	// tuning one.
	if (WeaponMesh && GWeaponUse != AppliedWeapon)
	{
		AppliedWeapon = GWeaponUse;
		const bool bSS2 = GWeaponUse != 0;
		if (USkeletalMesh* Swap = LoadObject<USkeletalMesh>(nullptr, bSS2 ? SS2MeshPath : RifleMeshPath))
		{
			WeaponMesh->SetSkeletalMesh(Swap);
		}
		WeaponGrip = LoadObject<UKBVEWeaponGrip>(nullptr, bSS2 ? SS2GripPath : RifleGripPath);
		if (UKBVEFootIKAnimInstance* Anim =
			Mesh ? Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance()) : nullptr)
		{
			Anim->WeaponGrip = WeaponGrip;
		}
		UE_LOG(LogTemp, Display, TEXT("weapon: now %s"), bSS2 ? TEXT("SS2-V5") : TEXT("Mosin"));
	}

	// Reapplied every frame rather than once, so the offset can be dialled in
	// from the details panel while the game is running. It is two compares and a
	// store when nothing has changed.
	if (WeaponMesh)
	{
		// Pitched about the grip rather than translated: the right hand is on the
		// stock's wrist and must stay there, so dropping the fore-end onto the
		// support hand has to pivot around the point the trigger hand holds.
		// The weapon's own attach offset when it carries one, so a second rifle
		// is not hung where the first one's stock happened to sit.
		const FTransform Base = (WeaponGrip && !WeaponGrip->AttachOffset.Equals(FTransform::Identity))
			? WeaponGrip->AttachOffset
			: WeaponAttachOffset;
		FTransform Tuned = FTransform(FRotator(GWeaponPitch, 0.0f, GWeaponRoll), FVector::ZeroVector)
			* Base;
		Tuned.AddToTranslation(FVector(GWeaponOffsetX, GWeaponOffsetY, GWeaponOffsetZ));

		// The mesh follows the fit; the solver keeps being told the untouched
		// tuned offset.
		//
		// Feeding the fitted transform back as the solver's input makes the fit
		// compound on its own output: each frame swings the rifle a little
		// further from a base that already includes the last swing, and it
		// leaves the character's hands entirely within a second.
		FTransform Worn = Tuned;
		if (const UKBVEFootIKAnimInstance* Solved =
			Mesh ? Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance()) : nullptr)
		{
			if (Solved->bFitWeaponToHands && !Solved->FittedWeaponRelativeToHand.Equals(FTransform::Identity))
			{
				Worn = Solved->FittedWeaponRelativeToHand;
			}
		}

		if (!WeaponMesh->GetRelativeTransform().Equals(Worn))
		{
			WeaponMesh->SetRelativeTransform(Worn);
		}

		// The solver is told the same transform, every frame. It was told the
		// untuned offset once at BeginPlay, so pitching or rolling the weapon
		// moved the rifle and left the hands reaching for where it used to be --
		// a grip solved perfectly against a weapon that is no longer there.
		if (UKBVEFootIKAnimInstance* AnimInstance =
			Mesh ? Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance()) : nullptr)
		{
			AnimInstance->WeaponRelativeToHand = Tuned;

			// The socket rides with the bone labels rather than behind DrawBore.
			//
			// It is the whole of the grip now -- one transform the arm is solved
			// to -- and the same argument that put the bone names on by default
			// applies twice over to the point they are all being measured
			// against. The bore and the fore-end box stay behind their own
			// switch: those are the weapon, and the weapon is on screen.
			if (GWeaponDrawBore > 0 || GGripBones > 0)
			{
				const FTransform Weapon = WeaponMesh->GetComponentTransform();

				// The fore-end as the solver models it: a block under the barrel,
				// not a cylinder on the bore. Drawn at its measured section so a
				// glance says whether the two agree.
				//
				// Weapon geometry in grey and the things the hands are aimed at
				// in red, so the two questions a bad hold raises -- is the target
				// in the wrong place, or is the hand failing to reach a right one
				// -- never wear the same colour.
				if (GWeaponDrawBore > 0)
				{
					const float Centre = AnimInstance->ForeEndCentreHeight;
					DrawDebugBox(GetWorld(),
						Weapon.TransformPosition(FVector(AnimInstance->LeftHandTargetLocal.X, 0.0f, Centre)),
						FVector(7.0f, AnimInstance->ForeEndHalfWidth, AnimInstance->ForeEndHalfHeight),
						Weapon.GetRotation(), FColor(130, 130, 130), false, -1.0f, SDPG_Foreground, 0.3f);

					const FVector Breech =
						Weapon.TransformPosition(FVector(-45.0f, 0.0f, AnimInstance->WeaponBoreHeight));
					const FVector Muzzle =
						Weapon.TransformPosition(FVector(10.0f, 0.0f, AnimInstance->WeaponBoreHeight));
					DrawDebugLine(GetWorld(), Breech, Muzzle, FColor(90, 90, 90), false, -1.0f,
						SDPG_Foreground, 0.2f);
				}

				// Where the support hand is actually being sent, and facing which
				// way. The socket is the whole of the grip now, and dialling one
				// blind is what a debug draw exists to stop: a wrist that will
				// not sit right is a different problem from a wrist being aimed
				// at a point off the weapon, and they look alike on a character.
				if (AnimInstance->bResolvedSupportSocketValid)
				{
					const FTransform Socket = AnimInstance->ResolvedSupportSocket * Weapon;
					DrawDebugSphere(GetWorld(), Socket.GetLocation(), 1.5f, 12,
						FColor::Red, false, -1.0f, SDPG_Foreground, 0.3f);
					DrawDebugCoordinateSystem(GetWorld(), Socket.GetLocation(), Socket.Rotator(), 8.0f,
						false, -1.0f, SDPG_Foreground, 0.3f);
					DrawDebugString(GetWorld(), Socket.GetLocation() + FVector(0.0f, 0.0f, 3.0f),
						TEXT("socket"), nullptr, FColor::Red, 0.0f, true, GGripBonesText);

					// Where the wrist was sent, drawn apart from where the palm
					// is meant to land. Orange to the red of the socket, because
					// the gap between the two is the hand's own length and
					// reading it as a miss is exactly the mistake that cost an
					// evening: the line that matters runs from the wrist to the
					// orange point, and it should be short.
					const FVector TargetWorld =
						Weapon.TransformPosition(AnimInstance->ResolvedSupportTarget);
					DrawDebugSphere(GetWorld(), TargetWorld, 1.2f, 12,
						FColor(255, 150, 0), false, -1.0f, SDPG_Foreground, 0.3f);
					DrawDebugLine(GetWorld(), Socket.GetLocation(), TargetWorld,
						FColor(120, 60, 0), false, -1.0f, SDPG_Foreground, 0.2f);

					// Wrist to target, the length of the miss.
					//
					// The one measurement a still frame will not give up: an arm
					// solved short and an arm solved to the wrong place look the
					// same on a character, and this is the line between them.
					if (Mesh)
					{
						DrawDebugLine(GetWorld(), Mesh->GetSocketLocation(TEXT("hand_l")),
							TargetWorld, FColor::Red, false, -1.0f, SDPG_Foreground, 0.35f);
					}
				}
				if (GWeaponDrawBore > 0)
				{
					DrawDebugSphere(GetWorld(), Weapon.TransformPosition(AnimInstance->RightGripLocal),
						1.5f, 12, FColor(140, 0, 0), false, -1.0f, SDPG_Foreground, 0.3f);
				}

				if (GWeaponDrawBore > 0 && Mesh)
				{
					// Which wrist is which, because a screenshot does not say and
					// the two are solved by completely different things: the left
					// is placed by the grip solve, the right is whatever the clip
					// animated and is never touched here.
					DrawDebugSphere(GetWorld(), Mesh->GetSocketLocation(TEXT("hand_l")), 2.0f, 12,
						FColor::White, false, -1.0f, SDPG_Foreground, 0.4f);
					DrawDebugSphere(GetWorld(), Mesh->GetSocketLocation(TEXT("hand_r")), 2.0f, 12,
						FColor(120, 120, 120), false, -1.0f, SDPG_Foreground, 0.4f);
					DrawDebugLine(GetWorld(), Mesh->GetSocketLocation(TEXT("lowerarm_l")),
						Mesh->GetSocketLocation(TEXT("hand_l")), FColor::White, false, -1.0f,
						SDPG_Foreground, 0.4f);
					DrawDebugLine(GetWorld(), Mesh->GetSocketLocation(TEXT("lowerarm_r")),
						Mesh->GetSocketLocation(TEXT("hand_r")), FColor(120, 120, 120), false, -1.0f,
						SDPG_Foreground, 0.4f);
				}
			}
		}
	}

	// A screenshot on the same schedule, so a headless run leaves a picture of
	// what it actually rendered. Asset metadata says a material is wired and a
	// texture is bound; it does not say the surface came out looking right, and
	// that is the only question a missing-texture report can be answered with.
	if (GAutoShot && !bAutoShotTaken && TimeSinceBeginPlay >= GAutoShotDelay)
	{
		bAutoShotTaken = true;
		// The request API rather than the HighResShot console command: the
		// command needs an editor viewport and silently does nothing in a
		// headless -game run, which is exactly where this is wanted.
		FScreenshotRequest::RequestScreenshot(TEXT("rareicon"), false, false);
	}

	// Once, after the pawn has had time to settle onto the ground, so a headless
	// run records it without anyone typing into a console.
	// A series rather than one sample: a capsule still settling and a capsule
	// wedged at the wrong height look identical in a single reading.
	if (FeetReportsDone < FeetReportCount)
	{
		TimeSinceBeginPlay += DeltaSeconds;
		if (TimeSinceBeginPlay >= FeetReportDelay + FeetReportInterval * FeetReportsDone)
		{
			++FeetReportsDone;
			// Once, well after landing: drop the capsule onto the ground a sweep
			// of that same capsule actually finds. If it stays, the landing
			// simply stopped high and nothing holds it there; if it returns to
			// where it was, something is actively holding it up.
			ReportFeet();
		}
	}
}

float ARareIconPlayerPawn::EffectiveDwellTime() const
{
	float BlendTime = 0.0f;
	if (const UKBVEFootIKAnimInstance* AnimInstance =
			Mesh ? Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance()) : nullptr)
	{
		BlendTime = AnimInstance->ClipBlendTime;
	}
	return FMath::Max(MinClipDwellTime, BlendTime);
}

void ARareIconPlayerPawn::UpdateLocomotionAnimation(float DeltaSeconds)
{
	if (!Mesh)
	{
		return;
	}

	// Held on idle so the hands stop moving while they are being looked at.
	if (GGripLab != 0 && IdleAnim)
	{
		if (CurrentAnim != IdleAnim || !FMath::IsNearlyEqual(CurrentLabRate, GGripLabRate))
		{
			CurrentAnim = IdleAnim;
			CurrentLabRate = GGripLabRate;
			if (UKBVEFootIKAnimInstance* Anim = Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance()))
			{
				Anim->SetLocomotionClip(IdleAnim, GGripLabRate);
			}
		}
		return;
	}

	const FVector Velocity = GetAuthoritativeVelocity();
	const float GroundSpeed = Velocity.Size2D();

	UAnimSequence* Desired = IdleAnim;
	float PlayRate = 1.0f;

	// Asked of the mover rather than inferred from vertical speed: at the apex
	// of a jump the vertical speed passes through zero, so a speed threshold
	// picks the run clip while the character is still in the air.
	const UCharacterMoverComponent* Mover = GetMoverComponent();
	const bool bAirborne = Mover
		? Mover->IsAirborne()
		: FMath::Abs(Velocity.Z) > FallSpeedThreshold;

	// Descending close enough to the ground counts as grounded for the purpose
	// of picking a pose, so the legs are already reaching for the floor when the
	// character arrives rather than sweeping down after it.
	const bool bUseGroundPose = !bAirborne
		|| (Velocity.Z < 0.0f && IsAboutToLand(-Velocity.Z));

	if (!bUseGroundPose)
	{
		Desired = FallAnim;
	}
	else
	{
		// Latched rather than compared each frame: entering a run takes the
		// full threshold, leaving it takes a drop well below, so a speed
		// hovering at the boundary does not alternate clips.
		bRunning = bRunning ? GroundSpeed > RunExitSpeedThreshold : GroundSpeed > RunSpeedThreshold;

		if (bRunning)
		{
			// Scaled to the clip's authored speed so the feet slide less. Not
			// foot IK, and no substitute for it -- the cheap half only.
			Desired = RunAnim;
			PlayRate = RunClipSpeed > KINDA_SMALL_NUMBER ? GroundSpeed / RunClipSpeed : 1.0f;
		}
		else if (GroundSpeed > MoveSpeedThreshold)
		{
			Desired = WalkAnim;
			PlayRate = WalkClipSpeed > KINDA_SMALL_NUMBER ? GroundSpeed / WalkClipSpeed : 1.0f;
		}
	}

	if (!Desired)
	{
		return;
	}

	// Landing from a run and stopping happen within a few frames of each other,
	// which without this walks the clip through run, walk and idle in under a
	// tenth of a second -- three blends, each cut short by the next. Going
	// airborne is exempt: a jump has to read immediately.
	TimeInCurrentClip += DeltaSeconds;
	const bool bUrgent = Desired == FallAnim || CurrentAnim == nullptr;
	if (Desired != CurrentAnim && (bUrgent || TimeInCurrentClip >= EffectiveDwellTime()))
	{
		CurrentAnim = Desired;
		TimeInCurrentClip = 0.0f;
	}

	if (UKBVEFootIKAnimInstance* AnimInstance = Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance()))
	{
		AnimInstance->SetLocomotionClip(CurrentAnim, FMath::Clamp(PlayRate, MinClipPlayRate, MaxClipPlayRate));
	}
}


bool ARareIconPlayerPawn::IsAboutToLand(float DescentSpeed) const
{
	const UWorld* World = GetWorld();
	const UCapsuleComponent* PawnCapsule = FindComponentByClass<UCapsuleComponent>();
	if (!World || !PawnCapsule || DescentSpeed <= KINDA_SMALL_NUMBER || LandingAnticipationTime <= 0.0f)
	{
		return false;
	}

	// Only as far as the character can fall in the anticipation window, so a
	// jump that is still high up keeps playing the fall clip.
	const float Reach = DescentSpeed * LandingAnticipationTime;
	const FVector Location = GetActorLocation();
	const float Bottom = Location.Z - PawnCapsule->GetScaledCapsuleHalfHeight();

	FHitResult Hit;
	FCollisionQueryParams Params;
	Params.AddIgnoredActor(this);
	const FVector Start(Location.X, Location.Y, Bottom);
	return World->LineTraceSingleByChannel(Hit, Start, Start - FVector(0.0f, 0.0f, Reach), ECC_Visibility, Params);
}

// Reports every link between the ground that is drawn and the feet that are
// drawn, in one line, because "floating" can be any of them: a collision
// surface that disagrees with the visual one, a capsule resting high, a mesh
// offset, or an animation whose pose does not put the feet at the root.
void ARareIconPlayerPawn::ReportFeet() const
{
	const UWorld* World = GetWorld();
	if (!World)
	{
		return;
	}

	// Whether the weapon is actually on the bone it was asked for. A bone name a
	// mesh does not carry is not an error: the component attaches to the parent's
	// origin instead, which on this pawn is the capsule bottom -- so the rifle
	// ends up lying on the ground, looking like a placement bug rather than a
	// failed lookup.
	if (WeaponMesh && Mesh)
	{
		const int32 BoneIndex = Mesh->GetBoneIndex(WeaponAttachBone);
		const FVector WeaponAt = WeaponMesh->GetComponentLocation();
		const FVector BoneAt = BoneIndex != INDEX_NONE
			? Mesh->GetBoneLocation(WeaponAttachBone) : FVector::ZeroVector;
		UE_LOG(LogRareIcon, Display,
			TEXT("weapon: bone '%s' index=%d exists=%d attachedTo='%s' weaponAt=(%.1f,%.1f,%.1f) boneAt=(%.1f,%.1f,%.1f) gap=%.1f"),
			*WeaponAttachBone.ToString(), BoneIndex, BoneIndex != INDEX_NONE ? 1 : 0,
			*WeaponMesh->GetAttachSocketName().ToString(),
			WeaponAt.X, WeaponAt.Y, WeaponAt.Z, BoneAt.X, BoneAt.Y, BoneAt.Z,
			BoneIndex != INDEX_NONE ? FVector::Dist(WeaponAt, BoneAt) : -1.0f);

		// How far each support-hand joint sits from the barrel's centreline,
		// in the weapon's own space. A closed grip has the fingertips at about
		// the weapon's radius; an open hand lying along it has them further out
		// than the knuckles. Measuring this is what makes the curl tunable
		// against a number instead of against a screenshot.
		// Full local coordinates, not a radius. The bore does not run along the
		// weapon's local X axis -- a rifle's barrel sits above its stock line, by
		// about 5 cm at the fore-end on this model -- so distance from that axis
		// says nothing about distance from the barrel, and a hand hovering a
		// clear 5 cm underneath measures as a tight grip.
		const FTransform WeaponToWorld = WeaponMesh->GetComponentTransform();
		FString Grip;
		for (const TCHAR* Bone : { TEXT("hand_l"), TEXT("index_01_l"), TEXT("middle_01_l"),
				TEXT("middle_03_l"), TEXT("thumb_01_l") })
		{
			const FName BoneName(Bone);
			if (Mesh->GetBoneIndex(BoneName) == INDEX_NONE)
			{
				continue;
			}
			const FVector Local = WeaponToWorld.InverseTransformPosition(Mesh->GetSocketLocation(BoneName));
			Grip += FString::Printf(TEXT(" %s=(%.1f,%.1f,%.1f)"), Bone, Local.X, Local.Y, Local.Z);
		}
		UE_LOG(LogRareIcon, Display, TEXT("grip local (cm):%s"), *Grip);
	}

	const FVector Location = GetActorLocation();
	const UCapsuleComponent* PawnCapsule = FindComponentByClass<UCapsuleComponent>();
	const float HalfHeight = PawnCapsule ? PawnCapsule->GetScaledCapsuleHalfHeight() : 0.0f;
	const float Radius = PawnCapsule ? PawnCapsule->GetScaledCapsuleRadius() : 0.0f;
	const float CapsuleBottom = Location.Z - HalfHeight;

	FCollisionQueryParams Params;
	Params.AddIgnoredActor(this);
	const FVector End = Location - FVector(0.0f, 0.0f, 5000.0f);

	// A patch draws one mesh and collides with another. Querying only the
	// visibility channel measures whichever of the two answers it, which is not
	// necessarily the one the capsule rests on -- so name the component that
	// each query hit, and ask on the pawn's own channel as well.
	auto Describe = [&](ECollisionChannel Channel, bool bSweep) -> FString
	{
		FHitResult Hit;
		const bool bAny = bSweep
			? World->SweepSingleByChannel(Hit, Location, End, FQuat::Identity, Channel,
				FCollisionShape::MakeCapsule(Radius, HalfHeight), Params)
			: World->LineTraceSingleByChannel(Hit, Location, End, Channel, Params);
		if (!bAny)
		{
			return FString(TEXT("MISS"));
		}
		const float Z = bSweep ? Hit.Location.Z - HalfHeight : Hit.Location.Z;
		const FString Component = Hit.GetComponent() ? Hit.GetComponent()->GetName() : TEXT("?");
		return FString::Printf(TEXT("%.1f@%s%s"), Z, *Component,
			Hit.bStartPenetrating ? TEXT("!pen") : TEXT(""));
	};

	float Analytic = 0.0f;
	float PeakAnalytic = 0.0f;
	TActorIterator<AKBVEWorldStreamer> StreamerIt(World);
	if (StreamerIt)
	{
		const int32 Seed = FKBVEWorldHeightfield::SeedFromWorld(StreamerIt->WorldSeed);
		Analytic = FKBVEWorldHeightfield::HeightAt(
			StreamerIt->Shape, Seed, Location.X / 100.0f, Location.Y / 100.0f);

		PeakAnalytic = Analytic;
		for (int32 Step = 0; Step < 16; ++Step)
		{
			const float Angle = (2.0f * PI * Step) / 16.0f;
			PeakAnalytic = FMath::Max(PeakAnalytic, FKBVEWorldHeightfield::HeightAt(
				StreamerIt->Shape, Seed,
				(Location.X + Radius * FMath::Cos(Angle)) / 100.0f,
				(Location.Y + Radius * FMath::Sin(Angle)) / 100.0f));
		}
	}

	// Each foot against the ground directly under that foot, which is the thing
	// foot IK is trying to make zero. The single foot_l reading hides the case
	// the IK exists for: one foot planted and the other hanging.
	float FootZ = 0.0f;
	FString Feet(TEXT("none"));
	if (const USkeletalMeshComponent* MeshComponent = FindComponentByClass<USkeletalMeshComponent>())
	{
		FootZ = MeshComponent->GetSocketLocation(TEXT("foot_l")).Z;

		Feet.Reset();
		for (const TCHAR* Bone : {TEXT("foot_l"), TEXT("foot_r")})
		{
			const FVector Foot = MeshComponent->GetSocketLocation(Bone);
			FHitResult FootHit;
			const bool bFootHit = World->LineTraceSingleByChannel(FootHit,
				Foot + FVector(0.0f, 0.0f, 50.0f), Foot - FVector(0.0f, 0.0f, 100.0f),
				ECC_Visibility, Params);
			Feet += bFootHit
				? FString::Printf(TEXT(" %s: foot=%.1f ground=%.1f gap=%.1f"),
					Bone, Foot.Z, FootHit.Location.Z, Foot.Z - FootHit.Location.Z)
				: FString::Printf(TEXT(" %s: foot=%.1f ground=MISS"), Bone, Foot.Z);
		}
	}

	const FVector Velocity = GetAuthoritativeVelocity();
	const FString Mode = GetMoverComponent()
		? GetMoverComponent()->GetMovementModeName().ToString()
		: FString(TEXT("none"));

	// Which capsule is being measured, and whether it is the one Mover moves. A
	// second capsule, or a half-height that is not what the constructor set,
	// would account for the whole gap on its own.
	FString CapsuleDesc(TEXT("none"));
	if (PawnCapsule)
	{
		int32 CapsuleCount = 0;
		for (const UActorComponent* Component : GetComponents())
		{
			if (Component && Component->IsA<UCapsuleComponent>())
			{
				++CapsuleCount;
			}
		}
		CapsuleDesc = FString::Printf(TEXT("%s h=%.1f r=%.1f count=%d root=%s"),
			*PawnCapsule->GetName(), HalfHeight, Radius, CapsuleCount,
			PawnCapsule == GetRootComponent() ? TEXT("yes") : TEXT("no"));
	}

	const USceneComponent* Updated = GetMoverComponent() ? GetMoverComponent()->GetUpdatedComponent() : nullptr;
	const FString UpdatedDesc = Updated
		? FString::Printf(TEXT("%s z=%.1f"), *Updated->GetName(), Updated->GetComponentLocation().Z)
		: FString(TEXT("none"));

	const FString VisSweep = Describe(ECC_Visibility, true);
	const FString PawnSweep = Describe(ECC_Pawn, true);

	// Every surface under the capsule, named by actor. All 169 patches call
	// their collision component "CollisionMesh", so the component name cannot
	// tell two patches apart -- and two patches overlapping at different
	// heights is exactly what a single hit would hide.
	// Mover's own answer, rather than a reconstruction of it: which surface it
	// believes it is standing on and how far it thinks that surface is.
	FString Floor(TEXT("none"));
	if (UMoverComponent* MoverComp = GetMoverComponent())
	{
		bool bWalkable = false;
		FFloorCheckResult Result;
		UFloorQueryUtils::TryFindFloor(MoverComp, bWalkable, Result);
		Floor = FString::Printf(
			TEXT("blocking=%d walkable=%d dist=%.1f lineTrace=%d lineDist=%.1f hitZ=%.1f impactZ=%.1f on=%s"),
			Result.bBlockingHit ? 1 : 0, Result.bWalkableFloor ? 1 : 0, Result.FloorDist,
			Result.bLineTrace ? 1 : 0, Result.LineDist,
			Result.HitResult.Location.Z, Result.HitResult.ImpactPoint.Z,
			Result.HitResult.GetActor() ? *Result.HitResult.GetActor()->GetName() : TEXT("?"));
		// Where that surface is in XY, and where the patch owning it now sits.
		// Patches are pooled, so a floor remembered from landing can name a
		// patch that has since been recycled to a different chunk.
		const FVector Impact = Result.HitResult.ImpactPoint;
		Floor += FString::Printf(TEXT(" impactXY=(%.0f,%.0f) pawnXY=(%.0f,%.0f)"),
			Impact.X, Impact.Y, Location.X, Location.Y);
		if (const AKBVEWorldHeightfieldActor* Patch =
				Cast<AKBVEWorldHeightfieldActor>(Result.HitResult.GetActor()))
		{
			Floor += FString::Printf(TEXT(" patchOrigin=(%.0f,%.0f) lod=%d colLod=%d"),
				Patch->TileOrigin.X, Patch->TileOrigin.Y, Patch->LODStep, Patch->CollisionLODStep);
		}
	}

	FString Stack;
	{
		TArray<FHitResult> Hits;
		World->SweepMultiByChannel(Hits, Location, End, FQuat::Identity, ECC_Pawn,
			FCollisionShape::MakeCapsule(Radius, HalfHeight), Params);
		for (int32 i = 0; i < FMath::Min(Hits.Num(), 5); ++i)
		{
			Stack += FString::Printf(TEXT(" [%s bottom=%.1f impact=%.1f%s]"),
				Hits[i].GetActor() ? *Hits[i].GetActor()->GetName() : TEXT("?"),
				Hits[i].Location.Z - HalfHeight, Hits[i].ImpactPoint.Z,
				Hits[i].bStartPenetrating ? TEXT(" pen") : TEXT(""));
		}
		if (Hits.Num() == 0)
		{
			Stack = TEXT(" none");
		}
	}

	UE_LOG(LogRareIcon, Display,
		TEXT("feet: mode=%s velZ=%.1f speed2D=%.1f actorZ=%.1f capsuleBottom=%.1f footBoneZ=%.1f "
			"analyticZ=%.1f peakAnalytic=%.1f | capsule=[%s] updated=[%s] "
			"| visSweep=%s pawnSweep=%s | feet:%s | floor=[%s] | stack:%s"),
		*Mode, Velocity.Z, Velocity.Size2D(), Location.Z, CapsuleBottom, FootZ,
		Analytic, PeakAnalytic, *CapsuleDesc, *UpdatedDesc,
		*VisSweep, *PawnSweep, *Feet, *Floor, *Stack);
}

static void RareIconFeetCmd()
{
	UWorld* World = GEngine ? GEngine->GetCurrentPlayWorld() : nullptr;
	APlayerController* PC = World ? World->GetFirstPlayerController() : nullptr;
	if (const ARareIconPlayerPawn* Pawn = PC ? Cast<ARareIconPlayerPawn>(PC->GetPawn()) : nullptr)
	{
		Pawn->ReportFeet();
	}
	else
	{
		UE_LOG(LogRareIcon, Error, TEXT("no RareIcon pawn possessed"));
	}
}

static FAutoConsoleCommand GRareIconFeetCmd(
	TEXT("rareicon.Feet"),
	TEXT("Report capsule, trace, analytic terrain and foot-bone heights at the pawn."),
	FConsoleCommandDelegate::CreateStatic(&RareIconFeetCmd));
