#include "RareIconPlayerPawn.h"

#include "Components/CapsuleComponent.h"
#include "Animation/AnimSequence.h"
#include "DrawDebugHelpers.h"
#include "Components/SkeletalMeshComponent.h"
#include "Engine/SkeletalMesh.h"
#include "InputAction.h"
#include "InputMappingContext.h"
#include "Components/CapsuleComponent.h"
#include "Engine/Engine.h"
#include "Engine/World.h"
#include "GameFramework/PlayerController.h"
#include "HAL/IConsoleManager.h"
#include "UnrealClient.h"
#include "DefaultMovementSet/CharacterMoverComponent.h"
#include "MoveLibrary/FloorQueryUtils.h"
#include "KBVEFootIKAnimInstance.h"
#include "KBVEWeaponGrip.h"
#include "GameFramework/SpringArmComponent.h"
#include "UnrealClient.h"
#include "KBVEWorldHeightfield.h"
#include "KBVEWorldStreamer.h"
#include "KBVEWorldHeightfieldActor.h"
#include "RareIcon.h"
#include "EngineUtils.h"
#include "UObject/ConstructorHelpers.h"

namespace
{
	// Manny ships inside the MoverExamples plugin rather than as engine content,
	// because this install has no feature packs. That makes the player mesh a
	// dependency on an Experimental plugin's sample content -- fine for finding
	// the feel of the game, wrong to ship. Replacing it means changing this path
	// and nothing else.
	const TCHAR* MannyMeshPath = TEXT("/MoverExamples/Characters/Mannequins/Meshes/SKM_Manny_Simple.SKM_Manny_Simple");

	// Epic's Game Animation Sample rifle set, staged and imported by the
	// `import-animations` moon task. Authored on the UE5 mannequin rig, which
	// shares 86 of its 87 bones with this one, so they bind with no retarget.
	//
	// They hold the weapon themselves -- stance, grip and finger pose are all
	// animated -- which is why the procedural weapon hold below is off. A pose
	// an animator authored beats one a solver reconstructs.
	//
	// Individual clips rather than the blendspaces beside them, because playing
	// a blendspace needs an animation graph to evaluate it. Single-node playback
	// is the honest floor: no strafe set and no turn-in-place, both of which are
	// in the source set waiting for a graph that can blend them.
	const TCHAR* IdleAnimPath = TEXT("/Game/Animations/Rifle/A_Rifle_Idle.A_Rifle_Idle");
	const TCHAR* WalkAnimPath = TEXT("/Game/Animations/Rifle/A_Rifle_Walk_F.A_Rifle_Walk_F");
	const TCHAR* RunAnimPath = TEXT("/Game/Animations/Rifle/A_Rifle_Run_F.A_Rifle_Run_F");
	const TCHAR* FallAnimPath = TEXT("/Game/Animations/Rifle/A_Rifle_Jump_Start.A_Rifle_Jump_Start");

	// Generated by the `import-weapons` moon task rather than authored: the
	// PolyHaven source ships as loose rigid parts, and scripts/rig_weapon.py
	// builds the armature from their geometry. See that file for the bolt axis.
	const TCHAR* RifleMeshPath = TEXT("/Game/Weapons/SK_Rifle_BoltAction762.SK_Rifle_BoltAction762");

	// Built by `build-weapon-grips` from scripts/config/weapons.json.
	const TCHAR* RifleGripPath = TEXT("/Game/Weapons/DA_Grip_BoltAction762.DA_Grip_BoltAction762");

	// A second weapon, to find out whether the grip pipeline describes a rifle
	// or just describes the Mosin. Different length, different section, barrel
	// on a different axis in the source -- if the hand lands on both from
	// measurements alone, the data asset is doing its job.
	const TCHAR* SS2MeshPath = TEXT("/Game/Weapons/SK_Rifle_SS2V5.SK_Rifle_SS2V5");
	const TCHAR* SS2GripPath = TEXT("/Game/Weapons/DA_Grip_SS2V5.DA_Grip_SS2V5");

	// Strip the weapon and every pass that touches an arm, leaving the clip.
	//
	// The control this whole grip investigation lacked: if the left wrist still
	// reads as twisted with nothing solving it, the twist is authored into the
	// animation and no solver change was ever going to fix it.
	static int32 GWeaponHide = 0;
	static FAutoConsoleVariableRef CVarWeaponHide(
		TEXT("rareicon.Weapon.Hide"), GWeaponHide,
		TEXT("1 hides the weapon and disables every arm solve, showing the clip alone."),
		ECVF_Default);

	static int32 GWeaponUse = 0;
	static FAutoConsoleVariableRef CVarWeaponUse(
		TEXT("rareicon.Weapon.Use"), GWeaponUse,
		TEXT("0 the bolt-action Mosin, 1 the SS2-V5. Swaps mesh and grip asset live."),
		ECVF_Default);

	template <typename T>
	T* FindAsset(const TCHAR* Path)
	{
		ConstructorHelpers::FObjectFinder<T> Finder(Path);
		return Finder.Succeeded() ? Finder.Object : nullptr;
	}
}

ARareIconPlayerPawn::ARareIconPlayerPawn(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	PrimaryActorTick.bCanEverTick = true;
	if (Mesh)
	{
		if (USkeletalMesh* Manny = FindAsset<USkeletalMesh>(MannyMeshPath))
		{
			Mesh->SetSkeletalMesh(Manny);
			// Manny's origin is at his feet and the capsule's is at its centre,
			// so the mesh has to drop by the half-height or he floats. The yaw
			// is because the skeleton faces -Y and a pawn's forward is +X.
			const float HalfHeight = Capsule ? Capsule->GetUnscaledCapsuleHalfHeight() : 88.0f;
			Mesh->SetRelativeLocationAndRotation(
				FVector(0.0f, 0.0f, -HalfHeight), FRotator(0.0f, -90.0f, 0.0f));
		}

		// A native anim instance rather than an animation blueprint: the one that
		// ships beside this mesh does not compile in 5.8, and this keeps the
		// whole solve in C++ where it shows up in a diff. It plays the one clip
		// the locomotion picks and plants both feet on the ground beneath them.
		Mesh->SetAnimInstanceClass(UKBVEFootIKAnimInstance::StaticClass());
		Mesh->SetAnimationMode(EAnimationMode::AnimationBlueprint);

		// Attached to the chest rather than a hand: the arms are solved onto the
		// weapon, not the other way round. It has no collision of its own -- the
		// capsule is what the world tests against, and a rifle barrel sweeping
		// the geometry would push the character off ledges it stands clear of.
		WeaponMesh = CreateDefaultSubobject<USkeletalMeshComponent>(TEXT("WeaponMesh"));
		WeaponMesh->SetupAttachment(Mesh, WeaponAttachBone);
		WeaponGrip = FindAsset<UKBVEWeaponGrip>(RifleGripPath);
		WeaponMesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);
		WeaponMesh->SetCanEverAffectNavigation(false);
		if (USkeletalMesh* Rifle = FindAsset<USkeletalMesh>(RifleMeshPath))
		{
			WeaponMesh->SetSkeletalMesh(Rifle);
		}
		WeaponMesh->SetRelativeTransform(WeaponAttachOffset);
	}

	InputMappingContext = FindAsset<UInputMappingContext>(TEXT("/Game/Input/IMC_RareIcon.IMC_RareIcon"));
	MoveAction = FindAsset<UInputAction>(TEXT("/Game/Input/IA_Move.IA_Move"));
	LookAction = FindAsset<UInputAction>(TEXT("/Game/Input/IA_Look.IA_Look"));
	JumpAction = FindAsset<UInputAction>(TEXT("/Game/Input/IA_Jump.IA_Jump"));
	SprintAction = FindAsset<UInputAction>(TEXT("/Game/Input/IA_Sprint.IA_Sprint"));
	ZoomAction = FindAsset<UInputAction>(TEXT("/Game/Input/IA_Zoom.IA_Zoom"));
	InteractAction = FindAsset<UInputAction>(TEXT("/Game/Input/IA_Interact.IA_Interact"));
	InventoryAction = FindAsset<UInputAction>(TEXT("/Game/Input/IA_Inventory.IA_Inventory"));

	IdleAnim = FindAsset<UAnimSequence>(IdleAnimPath);
	WalkAnim = FindAsset<UAnimSequence>(WalkAnimPath);
	RunAnim = FindAsset<UAnimSequence>(RunAnimPath);
	FallAnim = FindAsset<UAnimSequence>(FallAnimPath);
}

namespace
{
	// Off by default: this writes a file, and a game that drops a screenshot into
	// Saved/ on every run is a surprise rather than a diagnostic.
	static bool GAutoShot = false;
	// Later than the feet report on purpose: the player start is 1500 units up,
	// so a shot taken as soon as the pawn exists catches it still falling and
	// posed mid-air rather than standing in its idle.
	// Live handles for seating the weapon in the support hand. Both rotate about
	// the trigger-hand grip, because that is the contact that must not move.
	static float GWeaponPitch = 0.0f;
	static float GWeaponRoll = 0.0f;
	static FAutoConsoleVariableRef CVarWeaponPitch(
		TEXT("rareicon.Weapon.Pitch"), GWeaponPitch,
		TEXT("Extra weapon pitch about the trigger-hand grip, degrees."), ECVF_Default);
	static FAutoConsoleVariableRef CVarWeaponRoll(
		TEXT("rareicon.Weapon.Roll"), GWeaponRoll,
		TEXT("Extra weapon roll about the trigger-hand grip, degrees."), ECVF_Default);

	// Draws the weapon as the hand solver believes it to be: the bore it rolls
	// the wrist around and the fore-end it closes the fingers onto. If this
	// cylinder is not lying inside the rendered barrel then every grip number
	// downstream is being measured against a rifle that is not there, and no
	// amount of finger solving converges.
	static int32 GWeaponDrawBore = 0;
	// Frame the support hand and photograph it, so a grip can be looked at
	// instead of inferred from joint angles. Six rounds of this were spent
	// measuring numbers that were all individually correct while the hand
	// still looked wrong, which is a thing only a picture settles.
	static float GGripShotSeconds = -1.0f;
	static float GGripShotYaw = -100.0f;
	static float GGripShotPitch = -15.0f;
	static float GGripShotDist = 42.0f;
	static int32 GGripShotWeapon = 1;
	static FAutoConsoleVariableRef CVarGripShotWeapon(
		TEXT("rareicon.Weapon.GripShotWeapon"), GGripShotWeapon,
		TEXT("1 frames the weapon in world space, 0 frames the support hand in the pawn's frame."),
		ECVF_Default);
	static FAutoConsoleVariableRef CVarGripShotYaw(
		TEXT("rareicon.Weapon.GripShotYaw"), GGripShotYaw,
		TEXT("Camera yaw about the support hand for the grip shot, relative to the pawn."), ECVF_Default);
	static FAutoConsoleVariableRef CVarGripShotPitch(
		TEXT("rareicon.Weapon.GripShotPitch"), GGripShotPitch,
		TEXT("Camera pitch for the grip shot."), ECVF_Default);
	static FAutoConsoleVariableRef CVarGripShotDist(
		TEXT("rareicon.Weapon.GripShotDist"), GGripShotDist,
		TEXT("Camera distance from the support hand for the grip shot, cm."), ECVF_Default);
	static FAutoConsoleVariableRef CVarGripShot(
		TEXT("rareicon.Weapon.GripShot"), GGripShotSeconds,
		TEXT("Seconds to wait, then frame the left hand, screenshot it and quit. -1 off."),
		ECVF_Default);
	static FAutoConsoleVariableRef CVarWeaponDrawBore(
		TEXT("rareicon.Weapon.DrawBore"), GWeaponDrawBore,
		TEXT("Draw the bore and fore-end the grip solver is aiming at."), ECVF_Default);

	static float GAutoShotDelay = 9.0f;
	static FAutoConsoleVariableRef CVarAutoShotDelay(
		TEXT("rareicon.AutoShotDelay"),
		GAutoShotDelay,
		TEXT("Seconds after possession before the automatic screenshot."),
		ECVF_Default);
	static FAutoConsoleVariableRef CVarAutoShot(
		TEXT("rareicon.AutoShot"),
		GAutoShot,
		TEXT("Take one screenshot a few seconds after possession."),
		ECVF_Default);
}

void ARareIconPlayerPawn::BeginPlay()
{
	Super::BeginPlay();

	// Reapplied here as well as in the constructor so that editing the offset on
	// the placed pawn takes effect: the constructor runs once against the class
	// default, and a value changed in the details panel would otherwise never
	// reach the component.
	if (WeaponMesh)
	{
		WeaponMesh->SetRelativeTransform(WeaponAttachOffset);
	}

	// One source of truth for where the weapon is. The component is parented to
	// the chest and the solver places the hands from the same transform, so
	// handing it over here is what keeps the rifle the arms are reaching for and
	// the rifle being drawn in the same place.
	if (UKBVEFootIKAnimInstance* AnimInstance = Mesh ? Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance()) : nullptr)
	{
		// Off, because the rifle clips already hold the weapon. The solver stays
		// in the class for characters without an authored hold; running it over
		// clips that have one would fight them for the same bones.
		AnimInstance->SetHoldWeapon(bUseProceduralWeaponHold);

		// The solver has to find the weapon exactly where the component is, so
		// it is told the same bone and the same offset rather than keeping its
		// own copy that could drift out of step.
		AnimInstance->WeaponHandBone = WeaponAttachBone;
		AnimInstance->WeaponRelativeToHand = WeaponAttachOffset;

		// Without this the grip asset is built and never read, and the support
		// hand keeps whatever fingers the locomotion clip happened to have.
		AnimInstance->WeaponGrip = WeaponGrip;
		StoredLeftHandIKAlpha = AnimInstance->LeftHandIKAlpha;
		StoredFitWeaponToHands = AnimInstance->bFitWeaponToHands;
	}
}

void ARareIconPlayerPawn::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);
	UpdateLocomotionAnimation(DeltaSeconds);

	// A close, fixed view of the support hand, held from the moment play starts
	// so the shot below lands on a settled pose rather than a spawn frame.
	if (GGripShotSeconds >= 0.0f && Mesh && CameraBoom)
	{
		// Framed on the weapon in world space, not on a hand in the pawn's own
		// frame. Aiming at hand_l meant the character turned into the shot and
		// occluded the thing being photographed, which cost several rounds of
		// screenshots that showed a torso and a sliver of wood.
		const FVector Target = (GGripShotWeapon != 0 && WeaponMesh)
			? WeaponMesh->Bounds.Origin
			: Mesh->GetSocketLocation(TEXT("hand_l"));
		CameraBoom->SetWorldLocation(Target);

		// Looking from the character's left and slightly below: the grip is on
		// the underside of the fore-end, and the body hides it from anywhere in
		// front. Yaw follows the pawn so the view holds as the character turns.
		CameraBoom->SetWorldRotation(GGripShotWeapon != 0
			? FRotator(GGripShotPitch, GGripShotYaw, 0.0f)
			: FRotator(GGripShotPitch, GetActorRotation().Yaw + GGripShotYaw, 0.0f));
		CameraBoom->TargetArmLength = GGripShotDist;
		CameraBoom->bDoCollisionTest = false;

		GripShotElapsed += DeltaSeconds;
		if (GripShotElapsed >= GGripShotSeconds && !bGripShotTaken)
		{
			bGripShotTaken = true;
			FScreenshotRequest::RequestScreenshot(false);
			UE_LOG(LogTemp, Display, TEXT("grip shot: requested at %.1fs"), GripShotElapsed);
		}
		else if (bGripShotTaken && GripShotElapsed >= GGripShotSeconds + 1.5f)
		{
			FPlatformMisc::RequestExit(false);
		}
	}

	// Nothing held, nothing solved: the clip as the animator left it.
	if (Mesh)
	{
		if (WeaponMesh && WeaponMesh->IsVisible() == (GWeaponHide != 0))
		{
			WeaponMesh->SetVisibility(GWeaponHide == 0, true);
		}
		if (UKBVEFootIKAnimInstance* Anim = Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance()))
		{
			const bool bHide = GWeaponHide != 0;
			Anim->LeftHandIKAlpha = bHide ? 0.0f : StoredLeftHandIKAlpha;
			Anim->bFitWeaponToHands = bHide ? false : StoredFitWeaponToHands;
			Anim->SetHoldWeapon(bHide ? false : bUseProceduralWeaponHold);
		}
	}

	// Swapped live rather than at spawn, so two weapons can be compared without
	// a relaunch -- which is the whole point of measuring a grip instead of
	// tuning one.
	if (WeaponMesh && GWeaponUse != AppliedWeapon)
	{
		AppliedWeapon = GWeaponUse;
		const bool bSS2 = GWeaponUse != 0;
		if (USkeletalMesh* Swap = LoadObject<USkeletalMesh>(nullptr, bSS2 ? SS2MeshPath : RifleMeshPath))
		{
			WeaponMesh->SetSkeletalMesh(Swap);
		}
		WeaponGrip = LoadObject<UKBVEWeaponGrip>(nullptr, bSS2 ? SS2GripPath : RifleGripPath);
		if (UKBVEFootIKAnimInstance* Anim =
			Mesh ? Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance()) : nullptr)
		{
			Anim->WeaponGrip = WeaponGrip;
		}
		UE_LOG(LogTemp, Display, TEXT("weapon: now %s"), bSS2 ? TEXT("SS2-V5") : TEXT("Mosin"));
	}

	// Reapplied every frame rather than once, so the offset can be dialled in
	// from the details panel while the game is running. It is two compares and a
	// store when nothing has changed.
	if (WeaponMesh)
	{
		// Pitched about the grip rather than translated: the right hand is on the
		// stock's wrist and must stay there, so dropping the fore-end onto the
		// support hand has to pivot around the point the trigger hand holds.
		// The weapon's own attach offset when it carries one, so a second rifle
		// is not hung where the first one's stock happened to sit.
		const FTransform Base = (WeaponGrip && !WeaponGrip->AttachOffset.Equals(FTransform::Identity))
			? WeaponGrip->AttachOffset
			: WeaponAttachOffset;
		const FTransform Tuned = FTransform(FRotator(GWeaponPitch, 0.0f, GWeaponRoll), FVector::ZeroVector)
			* Base;

		// The mesh follows the fit; the solver keeps being told the untouched
		// tuned offset.
		//
		// Feeding the fitted transform back as the solver's input makes the fit
		// compound on its own output: each frame swings the rifle a little
		// further from a base that already includes the last swing, and it
		// leaves the character's hands entirely within a second.
		FTransform Worn = Tuned;
		if (const UKBVEFootIKAnimInstance* Solved =
			Mesh ? Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance()) : nullptr)
		{
			if (Solved->bFitWeaponToHands && !Solved->FittedWeaponRelativeToHand.Equals(FTransform::Identity))
			{
				Worn = Solved->FittedWeaponRelativeToHand;
			}
		}

		if (!WeaponMesh->GetRelativeTransform().Equals(Worn))
		{
			WeaponMesh->SetRelativeTransform(Worn);
		}

		// The solver is told the same transform, every frame. It was told the
		// untuned offset once at BeginPlay, so pitching or rolling the weapon
		// moved the rifle and left the hands reaching for where it used to be --
		// a grip solved perfectly against a weapon that is no longer there.
		if (UKBVEFootIKAnimInstance* AnimInstance =
			Mesh ? Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance()) : nullptr)
		{
			AnimInstance->WeaponRelativeToHand = Tuned;

			if (GWeaponDrawBore > 0)
			{
				const FTransform Weapon = WeaponMesh->GetComponentTransform();

				// The fore-end as the solver models it: a block under the barrel,
				// not a cylinder on the bore. Drawn at its measured section so a
				// glance says whether the two agree.
				const float Centre = AnimInstance->ForeEndCentreHeight;
				DrawDebugBox(GetWorld(),
					Weapon.TransformPosition(FVector(AnimInstance->LeftHandTargetLocal.X, 0.0f, Centre)),
					FVector(7.0f, AnimInstance->ForeEndHalfWidth, AnimInstance->ForeEndHalfHeight),
					Weapon.GetRotation(), FColor::Cyan, false, -1.0f, 0, 0.3f);

				const FVector Breech = Weapon.TransformPosition(FVector(-45.0f, 0.0f, AnimInstance->WeaponBoreHeight));
				const FVector Muzzle = Weapon.TransformPosition(FVector(10.0f, 0.0f, AnimInstance->WeaponBoreHeight));
				DrawDebugLine(GetWorld(), Breech, Muzzle, FColor::Blue, false, -1.0f, 0, 0.2f);
				DrawDebugSphere(GetWorld(),
					Weapon.TransformPosition(AnimInstance->LeftHandTargetLocal), 1.5f, 12,
					FColor::Yellow, false, -1.0f, 0, 0.3f);
				DrawDebugSphere(GetWorld(), Weapon.TransformPosition(AnimInstance->RightGripLocal), 1.5f, 12,
					FColor::Red, false, -1.0f, 0, 0.3f);

				if (Mesh)
				{
					// Which wrist is which, because a screenshot does not say and
					// the two are solved by completely different things: the left
					// is placed by the grip solve, the right is whatever the clip
					// animated and is never touched here.
					DrawDebugSphere(GetWorld(), Mesh->GetSocketLocation(TEXT("hand_l")), 2.0f, 12,
						FColor::Green, false, -1.0f, 0, 0.4f);
					DrawDebugSphere(GetWorld(), Mesh->GetSocketLocation(TEXT("hand_r")), 2.0f, 12,
						FColor::Magenta, false, -1.0f, 0, 0.4f);
					DrawDebugLine(GetWorld(), Mesh->GetSocketLocation(TEXT("lowerarm_l")),
						Mesh->GetSocketLocation(TEXT("hand_l")), FColor::Green, false, -1.0f, 0, 0.4f);
					DrawDebugLine(GetWorld(), Mesh->GetSocketLocation(TEXT("lowerarm_r")),
						Mesh->GetSocketLocation(TEXT("hand_r")), FColor::Magenta, false, -1.0f, 0, 0.4f);
				}
			}
		}
	}

	// A screenshot on the same schedule, so a headless run leaves a picture of
	// what it actually rendered. Asset metadata says a material is wired and a
	// texture is bound; it does not say the surface came out looking right, and
	// that is the only question a missing-texture report can be answered with.
	if (GAutoShot && !bAutoShotTaken && TimeSinceBeginPlay >= GAutoShotDelay)
	{
		bAutoShotTaken = true;
		// The request API rather than the HighResShot console command: the
		// command needs an editor viewport and silently does nothing in a
		// headless -game run, which is exactly where this is wanted.
		FScreenshotRequest::RequestScreenshot(TEXT("rareicon"), false, false);
	}

	// Once, after the pawn has had time to settle onto the ground, so a headless
	// run records it without anyone typing into a console.
	// A series rather than one sample: a capsule still settling and a capsule
	// wedged at the wrong height look identical in a single reading.
	if (FeetReportsDone < FeetReportCount)
	{
		TimeSinceBeginPlay += DeltaSeconds;
		if (TimeSinceBeginPlay >= FeetReportDelay + FeetReportInterval * FeetReportsDone)
		{
			++FeetReportsDone;
			// Once, well after landing: drop the capsule onto the ground a sweep
			// of that same capsule actually finds. If it stays, the landing
			// simply stopped high and nothing holds it there; if it returns to
			// where it was, something is actively holding it up.
			ReportFeet();
		}
	}
}

float ARareIconPlayerPawn::EffectiveDwellTime() const
{
	float BlendTime = 0.0f;
	if (const UKBVEFootIKAnimInstance* AnimInstance =
			Mesh ? Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance()) : nullptr)
	{
		BlendTime = AnimInstance->ClipBlendTime;
	}
	return FMath::Max(MinClipDwellTime, BlendTime);
}

void ARareIconPlayerPawn::UpdateLocomotionAnimation(float DeltaSeconds)
{
	if (!Mesh)
	{
		return;
	}

	const FVector Velocity = GetAuthoritativeVelocity();
	const float GroundSpeed = Velocity.Size2D();

	UAnimSequence* Desired = IdleAnim;
	float PlayRate = 1.0f;

	// Asked of the mover rather than inferred from vertical speed: at the apex
	// of a jump the vertical speed passes through zero, so a speed threshold
	// picks the run clip while the character is still in the air.
	const UCharacterMoverComponent* Mover = GetMoverComponent();
	const bool bAirborne = Mover
		? Mover->IsAirborne()
		: FMath::Abs(Velocity.Z) > FallSpeedThreshold;

	// Descending close enough to the ground counts as grounded for the purpose
	// of picking a pose, so the legs are already reaching for the floor when the
	// character arrives rather than sweeping down after it.
	const bool bUseGroundPose = !bAirborne
		|| (Velocity.Z < 0.0f && IsAboutToLand(-Velocity.Z));

	if (!bUseGroundPose)
	{
		Desired = FallAnim;
	}
	else
	{
		// Latched rather than compared each frame: entering a run takes the
		// full threshold, leaving it takes a drop well below, so a speed
		// hovering at the boundary does not alternate clips.
		bRunning = bRunning ? GroundSpeed > RunExitSpeedThreshold : GroundSpeed > RunSpeedThreshold;

		if (bRunning)
		{
			// Scaled to the clip's authored speed so the feet slide less. Not
			// foot IK, and no substitute for it -- the cheap half only.
			Desired = RunAnim;
			PlayRate = RunClipSpeed > KINDA_SMALL_NUMBER ? GroundSpeed / RunClipSpeed : 1.0f;
		}
		else if (GroundSpeed > MoveSpeedThreshold)
		{
			Desired = WalkAnim;
			PlayRate = WalkClipSpeed > KINDA_SMALL_NUMBER ? GroundSpeed / WalkClipSpeed : 1.0f;
		}
	}

	if (!Desired)
	{
		return;
	}

	// Landing from a run and stopping happen within a few frames of each other,
	// which without this walks the clip through run, walk and idle in under a
	// tenth of a second -- three blends, each cut short by the next. Going
	// airborne is exempt: a jump has to read immediately.
	TimeInCurrentClip += DeltaSeconds;
	const bool bUrgent = Desired == FallAnim || CurrentAnim == nullptr;
	if (Desired != CurrentAnim && (bUrgent || TimeInCurrentClip >= EffectiveDwellTime()))
	{
		CurrentAnim = Desired;
		TimeInCurrentClip = 0.0f;
	}

	if (UKBVEFootIKAnimInstance* AnimInstance = Cast<UKBVEFootIKAnimInstance>(Mesh->GetAnimInstance()))
	{
		AnimInstance->SetLocomotionClip(CurrentAnim, FMath::Clamp(PlayRate, MinClipPlayRate, MaxClipPlayRate));
	}
}


bool ARareIconPlayerPawn::IsAboutToLand(float DescentSpeed) const
{
	const UWorld* World = GetWorld();
	const UCapsuleComponent* PawnCapsule = FindComponentByClass<UCapsuleComponent>();
	if (!World || !PawnCapsule || DescentSpeed <= KINDA_SMALL_NUMBER || LandingAnticipationTime <= 0.0f)
	{
		return false;
	}

	// Only as far as the character can fall in the anticipation window, so a
	// jump that is still high up keeps playing the fall clip.
	const float Reach = DescentSpeed * LandingAnticipationTime;
	const FVector Location = GetActorLocation();
	const float Bottom = Location.Z - PawnCapsule->GetScaledCapsuleHalfHeight();

	FHitResult Hit;
	FCollisionQueryParams Params;
	Params.AddIgnoredActor(this);
	const FVector Start(Location.X, Location.Y, Bottom);
	return World->LineTraceSingleByChannel(Hit, Start, Start - FVector(0.0f, 0.0f, Reach), ECC_Visibility, Params);
}

// Reports every link between the ground that is drawn and the feet that are
// drawn, in one line, because "floating" can be any of them: a collision
// surface that disagrees with the visual one, a capsule resting high, a mesh
// offset, or an animation whose pose does not put the feet at the root.
void ARareIconPlayerPawn::ReportFeet() const
{
	const UWorld* World = GetWorld();
	if (!World)
	{
		return;
	}

	// Whether the weapon is actually on the bone it was asked for. A bone name a
	// mesh does not carry is not an error: the component attaches to the parent's
	// origin instead, which on this pawn is the capsule bottom -- so the rifle
	// ends up lying on the ground, looking like a placement bug rather than a
	// failed lookup.
	if (WeaponMesh && Mesh)
	{
		const int32 BoneIndex = Mesh->GetBoneIndex(WeaponAttachBone);
		const FVector WeaponAt = WeaponMesh->GetComponentLocation();
		const FVector BoneAt = BoneIndex != INDEX_NONE
			? Mesh->GetBoneLocation(WeaponAttachBone) : FVector::ZeroVector;
		UE_LOG(LogRareIcon, Display,
			TEXT("weapon: bone '%s' index=%d exists=%d attachedTo='%s' weaponAt=(%.1f,%.1f,%.1f) boneAt=(%.1f,%.1f,%.1f) gap=%.1f"),
			*WeaponAttachBone.ToString(), BoneIndex, BoneIndex != INDEX_NONE ? 1 : 0,
			*WeaponMesh->GetAttachSocketName().ToString(),
			WeaponAt.X, WeaponAt.Y, WeaponAt.Z, BoneAt.X, BoneAt.Y, BoneAt.Z,
			BoneIndex != INDEX_NONE ? FVector::Dist(WeaponAt, BoneAt) : -1.0f);

		// How far each support-hand joint sits from the barrel's centreline,
		// in the weapon's own space. A closed grip has the fingertips at about
		// the weapon's radius; an open hand lying along it has them further out
		// than the knuckles. Measuring this is what makes the curl tunable
		// against a number instead of against a screenshot.
		// Full local coordinates, not a radius. The bore does not run along the
		// weapon's local X axis -- a rifle's barrel sits above its stock line, by
		// about 5 cm at the fore-end on this model -- so distance from that axis
		// says nothing about distance from the barrel, and a hand hovering a
		// clear 5 cm underneath measures as a tight grip.
		const FTransform WeaponToWorld = WeaponMesh->GetComponentTransform();
		FString Grip;
		for (const TCHAR* Bone : { TEXT("hand_l"), TEXT("index_01_l"), TEXT("middle_01_l"),
				TEXT("middle_03_l"), TEXT("thumb_01_l") })
		{
			const FName BoneName(Bone);
			if (Mesh->GetBoneIndex(BoneName) == INDEX_NONE)
			{
				continue;
			}
			const FVector Local = WeaponToWorld.InverseTransformPosition(Mesh->GetSocketLocation(BoneName));
			Grip += FString::Printf(TEXT(" %s=(%.1f,%.1f,%.1f)"), Bone, Local.X, Local.Y, Local.Z);
		}
		UE_LOG(LogRareIcon, Display, TEXT("grip local (cm):%s"), *Grip);
	}

	const FVector Location = GetActorLocation();
	const UCapsuleComponent* PawnCapsule = FindComponentByClass<UCapsuleComponent>();
	const float HalfHeight = PawnCapsule ? PawnCapsule->GetScaledCapsuleHalfHeight() : 0.0f;
	const float Radius = PawnCapsule ? PawnCapsule->GetScaledCapsuleRadius() : 0.0f;
	const float CapsuleBottom = Location.Z - HalfHeight;

	FCollisionQueryParams Params;
	Params.AddIgnoredActor(this);
	const FVector End = Location - FVector(0.0f, 0.0f, 5000.0f);

	// A patch draws one mesh and collides with another. Querying only the
	// visibility channel measures whichever of the two answers it, which is not
	// necessarily the one the capsule rests on -- so name the component that
	// each query hit, and ask on the pawn's own channel as well.
	auto Describe = [&](ECollisionChannel Channel, bool bSweep) -> FString
	{
		FHitResult Hit;
		const bool bAny = bSweep
			? World->SweepSingleByChannel(Hit, Location, End, FQuat::Identity, Channel,
				FCollisionShape::MakeCapsule(Radius, HalfHeight), Params)
			: World->LineTraceSingleByChannel(Hit, Location, End, Channel, Params);
		if (!bAny)
		{
			return FString(TEXT("MISS"));
		}
		const float Z = bSweep ? Hit.Location.Z - HalfHeight : Hit.Location.Z;
		const FString Component = Hit.GetComponent() ? Hit.GetComponent()->GetName() : TEXT("?");
		return FString::Printf(TEXT("%.1f@%s%s"), Z, *Component,
			Hit.bStartPenetrating ? TEXT("!pen") : TEXT(""));
	};

	float Analytic = 0.0f;
	float PeakAnalytic = 0.0f;
	TActorIterator<AKBVEWorldStreamer> StreamerIt(World);
	if (StreamerIt)
	{
		const int32 Seed = FKBVEWorldHeightfield::SeedFromWorld(StreamerIt->WorldSeed);
		Analytic = FKBVEWorldHeightfield::HeightAt(
			StreamerIt->Shape, Seed, Location.X / 100.0f, Location.Y / 100.0f);

		PeakAnalytic = Analytic;
		for (int32 Step = 0; Step < 16; ++Step)
		{
			const float Angle = (2.0f * PI * Step) / 16.0f;
			PeakAnalytic = FMath::Max(PeakAnalytic, FKBVEWorldHeightfield::HeightAt(
				StreamerIt->Shape, Seed,
				(Location.X + Radius * FMath::Cos(Angle)) / 100.0f,
				(Location.Y + Radius * FMath::Sin(Angle)) / 100.0f));
		}
	}

	// Each foot against the ground directly under that foot, which is the thing
	// foot IK is trying to make zero. The single foot_l reading hides the case
	// the IK exists for: one foot planted and the other hanging.
	float FootZ = 0.0f;
	FString Feet(TEXT("none"));
	if (const USkeletalMeshComponent* MeshComponent = FindComponentByClass<USkeletalMeshComponent>())
	{
		FootZ = MeshComponent->GetSocketLocation(TEXT("foot_l")).Z;

		Feet.Reset();
		for (const TCHAR* Bone : {TEXT("foot_l"), TEXT("foot_r")})
		{
			const FVector Foot = MeshComponent->GetSocketLocation(Bone);
			FHitResult FootHit;
			const bool bFootHit = World->LineTraceSingleByChannel(FootHit,
				Foot + FVector(0.0f, 0.0f, 50.0f), Foot - FVector(0.0f, 0.0f, 100.0f),
				ECC_Visibility, Params);
			Feet += bFootHit
				? FString::Printf(TEXT(" %s: foot=%.1f ground=%.1f gap=%.1f"),
					Bone, Foot.Z, FootHit.Location.Z, Foot.Z - FootHit.Location.Z)
				: FString::Printf(TEXT(" %s: foot=%.1f ground=MISS"), Bone, Foot.Z);
		}
	}

	const FVector Velocity = GetAuthoritativeVelocity();
	const FString Mode = GetMoverComponent()
		? GetMoverComponent()->GetMovementModeName().ToString()
		: FString(TEXT("none"));

	// Which capsule is being measured, and whether it is the one Mover moves. A
	// second capsule, or a half-height that is not what the constructor set,
	// would account for the whole gap on its own.
	FString CapsuleDesc(TEXT("none"));
	if (PawnCapsule)
	{
		int32 CapsuleCount = 0;
		for (const UActorComponent* Component : GetComponents())
		{
			if (Component && Component->IsA<UCapsuleComponent>())
			{
				++CapsuleCount;
			}
		}
		CapsuleDesc = FString::Printf(TEXT("%s h=%.1f r=%.1f count=%d root=%s"),
			*PawnCapsule->GetName(), HalfHeight, Radius, CapsuleCount,
			PawnCapsule == GetRootComponent() ? TEXT("yes") : TEXT("no"));
	}

	const USceneComponent* Updated = GetMoverComponent() ? GetMoverComponent()->GetUpdatedComponent() : nullptr;
	const FString UpdatedDesc = Updated
		? FString::Printf(TEXT("%s z=%.1f"), *Updated->GetName(), Updated->GetComponentLocation().Z)
		: FString(TEXT("none"));

	const FString VisSweep = Describe(ECC_Visibility, true);
	const FString PawnSweep = Describe(ECC_Pawn, true);

	// Every surface under the capsule, named by actor. All 169 patches call
	// their collision component "CollisionMesh", so the component name cannot
	// tell two patches apart -- and two patches overlapping at different
	// heights is exactly what a single hit would hide.
	// Mover's own answer, rather than a reconstruction of it: which surface it
	// believes it is standing on and how far it thinks that surface is.
	FString Floor(TEXT("none"));
	if (UMoverComponent* MoverComp = GetMoverComponent())
	{
		bool bWalkable = false;
		FFloorCheckResult Result;
		UFloorQueryUtils::TryFindFloor(MoverComp, bWalkable, Result);
		Floor = FString::Printf(
			TEXT("blocking=%d walkable=%d dist=%.1f lineTrace=%d lineDist=%.1f hitZ=%.1f impactZ=%.1f on=%s"),
			Result.bBlockingHit ? 1 : 0, Result.bWalkableFloor ? 1 : 0, Result.FloorDist,
			Result.bLineTrace ? 1 : 0, Result.LineDist,
			Result.HitResult.Location.Z, Result.HitResult.ImpactPoint.Z,
			Result.HitResult.GetActor() ? *Result.HitResult.GetActor()->GetName() : TEXT("?"));
		// Where that surface is in XY, and where the patch owning it now sits.
		// Patches are pooled, so a floor remembered from landing can name a
		// patch that has since been recycled to a different chunk.
		const FVector Impact = Result.HitResult.ImpactPoint;
		Floor += FString::Printf(TEXT(" impactXY=(%.0f,%.0f) pawnXY=(%.0f,%.0f)"),
			Impact.X, Impact.Y, Location.X, Location.Y);
		if (const AKBVEWorldHeightfieldActor* Patch =
				Cast<AKBVEWorldHeightfieldActor>(Result.HitResult.GetActor()))
		{
			Floor += FString::Printf(TEXT(" patchOrigin=(%.0f,%.0f) lod=%d colLod=%d"),
				Patch->TileOrigin.X, Patch->TileOrigin.Y, Patch->LODStep, Patch->CollisionLODStep);
		}
	}

	FString Stack;
	{
		TArray<FHitResult> Hits;
		World->SweepMultiByChannel(Hits, Location, End, FQuat::Identity, ECC_Pawn,
			FCollisionShape::MakeCapsule(Radius, HalfHeight), Params);
		for (int32 i = 0; i < FMath::Min(Hits.Num(), 5); ++i)
		{
			Stack += FString::Printf(TEXT(" [%s bottom=%.1f impact=%.1f%s]"),
				Hits[i].GetActor() ? *Hits[i].GetActor()->GetName() : TEXT("?"),
				Hits[i].Location.Z - HalfHeight, Hits[i].ImpactPoint.Z,
				Hits[i].bStartPenetrating ? TEXT(" pen") : TEXT(""));
		}
		if (Hits.Num() == 0)
		{
			Stack = TEXT(" none");
		}
	}

	UE_LOG(LogRareIcon, Display,
		TEXT("feet: mode=%s velZ=%.1f speed2D=%.1f actorZ=%.1f capsuleBottom=%.1f footBoneZ=%.1f "
			"analyticZ=%.1f peakAnalytic=%.1f | capsule=[%s] updated=[%s] "
			"| visSweep=%s pawnSweep=%s | feet:%s | floor=[%s] | stack:%s"),
		*Mode, Velocity.Z, Velocity.Size2D(), Location.Z, CapsuleBottom, FootZ,
		Analytic, PeakAnalytic, *CapsuleDesc, *UpdatedDesc,
		*VisSweep, *PawnSweep, *Feet, *Floor, *Stack);
}

static void RareIconFeetCmd()
{
	UWorld* World = GEngine ? GEngine->GetCurrentPlayWorld() : nullptr;
	APlayerController* PC = World ? World->GetFirstPlayerController() : nullptr;
	if (const ARareIconPlayerPawn* Pawn = PC ? Cast<ARareIconPlayerPawn>(PC->GetPawn()) : nullptr)
	{
		Pawn->ReportFeet();
	}
	else
	{
		UE_LOG(LogRareIcon, Error, TEXT("no RareIcon pawn possessed"));
	}
}

static FAutoConsoleCommand GRareIconFeetCmd(
	TEXT("rareicon.Feet"),
	TEXT("Report capsule, trace, analytic terrain and foot-bone heights at the pawn."),
	FConsoleCommandDelegate::CreateStatic(&RareIconFeetCmd));
