// <auto-generated/>
// Source: packages/data/codegen/gen-itemdb-atlas.mjs
// Regenerate: npx nx run astro-kbve:sync:itemdb-atlas

export const ATLAS_URL = '/assets/items/itemdb-atlas.png';
export const ATLAS_SIZE = 2048;
export const TILE_SIZE = 64;
export const TILES_PER_ROW = 32;
export const MAX_SLOTS = 1024;

/** Atlas cell (column,row) for an item key. Slot index == item key;
 * key 0 and out-of-range fall back to the atlas's slot-0 marker tile. */
export function atlasCell(key: number): { col: number; row: number } {
	if (key <= 0 || key >= MAX_SLOTS) return { col: 0, row: 0 };
	return { col: key % TILES_PER_ROW, row: Math.floor(key / TILES_PER_ROW) };
}

/** Phaser spritesheet frame index for an item key (row-major). */
export function atlasFrame(key: number): number {
	return key > 0 && key < MAX_SLOTS ? key : 0;
}
