/**
 * Placeholder memes shown when the API returns no data.
 * Separated from the component to keep the island thin.
 */

import type { FeedMeme } from '../memeService';

export const PLACEHOLDER_MEMES: FeedMeme[] = [
	{
		id: 'placeholder-1',
		title: 'Welcome to Meme.sh',
		format: 1,
		asset_url: 'https://picsum.photos/seed/msh1/1200/675',
		thumbnail_url: 'https://picsum.photos/seed/msh1/600/338',
		width: 1200,
		height: 675,
		tags: ['welcome', 'featured'],
		view_count: 2400,
		reaction_count: 187,
		comment_count: 12,
		save_count: 45,
		share_count: 23,
		created_at: new Date().toISOString(),
		author_name: 'memesh',
		author_avatar: null,
	},
	{
		id: 'placeholder-2',
		title: 'When the code finally compiles',
		format: 1,
		asset_url: 'https://picsum.photos/seed/msh2/600/800',
		thumbnail_url: 'https://picsum.photos/seed/msh2/300/400',
		width: 600,
		height: 800,
		tags: ['dev', 'relatable'],
		view_count: 1280,
		reaction_count: 95,
		comment_count: 8,
		save_count: 31,
		share_count: 14,
		created_at: new Date().toISOString(),
		author_name: 'coder42',
		author_avatar: null,
	},
	{
		id: 'placeholder-3',
		title: 'Monday mood',
		format: 1,
		asset_url: 'https://picsum.photos/seed/msh3/800/800',
		thumbnail_url: 'https://picsum.photos/seed/msh3/400/400',
		width: 800,
		height: 800,
		tags: ['mood'],
		view_count: 856,
		reaction_count: 62,
		comment_count: 4,
		save_count: 18,
		share_count: 9,
		created_at: new Date().toISOString(),
		author_name: 'vibes',
		author_avatar: null,
	},
	{
		id: 'placeholder-4',
		title: 'This hits different at 3am',
		format: 1,
		asset_url: 'https://picsum.photos/seed/msh4/700/500',
		thumbnail_url: 'https://picsum.photos/seed/msh4/350/250',
		width: 700,
		height: 500,
		tags: ['latenight', 'deep'],
		view_count: 3200,
		reaction_count: 234,
		comment_count: 19,
		save_count: 67,
		share_count: 41,
		created_at: new Date().toISOString(),
		author_name: 'nightowl',
		author_avatar: null,
	},
	{
		id: 'placeholder-5',
		title: 'POV: your deploy succeeded first try',
		format: 1,
		asset_url: 'https://picsum.photos/seed/msh5/500/700',
		thumbnail_url: 'https://picsum.photos/seed/msh5/250/350',
		width: 500,
		height: 700,
		tags: ['devops', 'rare'],
		view_count: 4100,
		reaction_count: 312,
		comment_count: 27,
		save_count: 89,
		share_count: 55,
		created_at: new Date().toISOString(),
		author_name: 'sre_life',
		author_avatar: null,
	},
	{
		id: 'placeholder-6',
		title: 'The Stack Overflow experience',
		format: 1,
		asset_url: 'https://picsum.photos/seed/msh6/900/600',
		thumbnail_url: 'https://picsum.photos/seed/msh6/450/300',
		width: 900,
		height: 600,
		tags: ['stackoverflow'],
		view_count: 1500,
		reaction_count: 110,
		comment_count: 6,
		save_count: 22,
		share_count: 15,
		created_at: new Date().toISOString(),
		author_name: 'debugger',
		author_avatar: null,
	},
	{
		id: 'placeholder-7',
		title: 'CSS centering in 2026',
		format: 1,
		asset_url: 'https://picsum.photos/seed/msh7/600/900',
		thumbnail_url: 'https://picsum.photos/seed/msh7/300/450',
		width: 600,
		height: 900,
		tags: ['css', 'webdev'],
		view_count: 920,
		reaction_count: 73,
		comment_count: 11,
		save_count: 28,
		share_count: 8,
		created_at: new Date().toISOString(),
		author_name: 'frontend',
		author_avatar: null,
	},
	{
		id: 'placeholder-8',
		title: 'Me explaining my side project',
		format: 1,
		asset_url: 'https://picsum.photos/seed/msh8/800/800',
		thumbnail_url: 'https://picsum.photos/seed/msh8/400/400',
		width: 800,
		height: 800,
		tags: ['sideproject'],
		view_count: 640,
		reaction_count: 48,
		comment_count: 3,
		save_count: 15,
		share_count: 7,
		created_at: new Date().toISOString(),
		author_name: 'builder',
		author_avatar: null,
	},
	{
		id: 'placeholder-9',
		title: 'How to center a div (2026 edition)',
		format: 3,
		asset_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
		thumbnail_url: null,
		width: 1280,
		height: 720,
		tags: ['video', 'tutorial'],
		view_count: 8900,
		reaction_count: 520,
		comment_count: 42,
		save_count: 130,
		share_count: 88,
		created_at: new Date().toISOString(),
		author_name: 'webdev',
		author_avatar: null,
	},
	{
		id: 'placeholder-10',
		title: 'When production goes down on Friday',
		format: 3,
		asset_url: 'https://youtu.be/dQw4w9WgXcQ?t=42',
		thumbnail_url: null,
		width: 1280,
		height: 720,
		tags: ['friday', 'incidents'],
		view_count: 5600,
		reaction_count: 389,
		comment_count: 31,
		save_count: 95,
		share_count: 67,
		created_at: new Date().toISOString(),
		author_name: 'oncall',
		author_avatar: null,
	},
];
