apiVersion: v1
kind: ConfigMap
metadata:
    name: firecracker-pip-packages
    namespace: firecracker
    labels:
        app: firecracker-ctl
        kbve.com/category: virtualization
        kbve.com/stack: core
        kbve.com/managed-by: argocd
data:
    packages.txt: 'kbve

        fudster

        requests

        httpx

        pydantic

        click

        rich

        beautifulsoup4

        python-dateutil

        pyyaml

        toml

        orjson

        tabulate

        jmespath

        fastapi

        uvicorn

        starlette

        python-multipart

        email-validator

        websockets

        '
