apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: firecracker-ctl-ingress
    namespace: firecracker
spec:
    podSelector:
        matchLabels:
            app: firecracker-ctl
    policyTypes:
        - Ingress
    ingress:
        - from:
              - namespaceSelector:
                    matchLabels:
                        app: kilobase
                podSelector:
                    matchLabels:
                        app: functions
          ports:
              - protocol: TCP
                port: 9001
