apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: firecracker-ctl-net
    namespace: firecracker
    labels:
        app: firecracker-ctl-net
        release: prometheus
spec:
    selector:
        matchLabels:
            app: firecracker-ctl-net
    endpoints:
        - port: api
          interval: 30s
          path: /metrics
          scrapeTimeout: 10s
