apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: firecracker-rootfs
    namespace: firecracker
    labels:
        app: firecracker-ctl
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 2Gi
