fullnameOverride: sealed-secrets-controller
secretName: sealed-secrets-key
existingSecret: sealed-secrets-key
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi