---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: palworld-credentials
    namespace: palworld
spec:
    encryptedData:
        server_password: PLACEHOLDER_RESEAL_AGAINST_CLUSTER
    template:
        metadata:
            name: palworld-credentials
            namespace: palworld
