---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: palworld-credentials
  namespace: palworld
spec:
  encryptedData:
    server_password: AgCqWf1Cu8rg5ioQhdHc8PKnrwpNeDb0lxFsmBysxwa5a+3QZ/zdwX7he/ACbjiCLRufEQhMkaCeOcUB8JI/Q/EZr6jXzTVkMNuTZMncD6ZO+3vvodeKd+AzwcmTIuSIbRPwXUDZP5g96Skk23p+UHE47hQV9Rl4fe+TyO+2pERN/5ARZA/tg4gQzW7mB6y6xaFYyz1yLaLj8FZRgwezPPkHH5iFJ21kqxZdcui/iOM2pmPj9Vsdn84GvRlhbK0EGLQeH7X3lWM8PFfZ9lH1EQF+QX4OzijOrONIbcWqwPuWke9Oh7uVJoOVIrHQ4g8YaSrQfgBnJ5oHT/VxrfBoAClxpcnk0jPBYYM3cd0BUzzFqE6Fz8zTSTsqPF0mKROaTUmSZ2B5SJg0kCSb8DsPWHYIwOmiv+t78399bT1LD+dY8v0zBv6y4ppJdJJ2iIVNm/e9WsFigqbf0NYXJnVC8rk0PCauoQp+B1ITzZR6cMURwpYMeDmMAN5kPHhA91EyRaBL9phAPYLnTOg5InqhsJeG2w31FeALjL9Ntp5n733n5BlgsdU0p1HU+QxmVfo++WxGQpjgAP86uftk6LGV5VpLa/dkzbv4ysGVfF5smxppxK/vNcaddXhVgCe1irBi6X1Gmi/cqxIb/ttvYX7P6G/mnSuwJANna720jEEE1MNOhgTfQMN8q0qJ1SKJYdndeEU=
  template:
    metadata:
      name: palworld-credentials
      namespace: palworld
