---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: palworld-rcon
  namespace: palworld
spec:
  encryptedData:
    admin_password: AgBUBPZ49V2g152sk2nCZrRN6e4q234Knq16TrWCkTpSxNszueyURblq5jtobj1TI9akcI2Z3mrNTqqcX7Qizu+ZMCd6fOusPf/Vgk3QazyrcvcR4bEprKd3WNSskTvfVtj6xack3+vZ92P4iRR+4/B83oV8cD8D4yZAGqB1U0IQi1J9kb8X7YnGokRgR8AoLYnEP5ZGkKZHZ6dGLecFW7b1UJoS8IhWnw03BdMrJg6sWWcooe965eGiDy6RQV6YAfvxVUAEqujdYoAYEmr1ATKznWoQC5gjPIhSpiWoWAGVJ6y6MTDy8Aim50qbGTlREr1DN1OytxLd+MJVJuiiH4T4b3aAWdpg/NRjwSRb8nI9DXdtYXaLO9uGfVO1dMGCzWp3oF4gxm05M3myOjSYjQ4BqsgkmHmm/SIb6eLGIiTe4Umm3cao+4x9Oqe33eS/iP01SR27AD+8rErVVuLU9rkKZkweWSLMHpZQJe/LHHK3Oxf4MreLF7OGMG574/DFOrfBBILtg7D6IvURYzPkMnjqEli0SnQOf8n7GW6yTaw1IT3VthKdH7rlqJLqgQZ389DaGwxzsWPMoGUVuQbFryG87Vqx7mhFmKHRGmz24OKqTmo0qEB0LFYqumepvJyJg52JRkGevEMz5uhdo9vRK0VfjYnlbmp/kd6uE7YD4mBRWGxN2cuQD49omNbaD+hK9HfbnBT7YDuBqOSF4JOd9oOoAO7Up4MTg/fb9hANy8CdlFd+s88dKKE6ZYlcvueYXKo=
    rcon_password: AgB76TkG3tF7NAzTgitN1l0zN6jcZIu1R5B3P+JYDxAQewxaia2V37QvSWXnd+iDw+bRksMouaM0z4GV2zjhE6NxJeG3yt/QK6NmDL9dSSshabvv8MR4TNCS+6bAB60aO50EKfPy8ZNpsO0pxK7puPizdazmqWcgTgMUrORNcCrqIjdbSCBY2FlN7HxGfsn54Lan6UbOo6BEIzEub4oGPyUhW55Sfs1i+Y9vfMEjwFBQpH9LUpx2Uhvyd3DWJR7tQDm1xXWJrUojmFqGbQgLA+Pq8iQDw0Q4iVqIhBFB4L8sVtZz0Bqzi1SmaNQDeBtmc3L3q/khrj2zXNtN6loCjGgc2ySZ4JEY6n65PoYpGgYtqIHuz0dEs3GgCQRB2QRMA2/9LHYOsHVJKnuCYxRijRB+sDu4PgidDbs4xrzKrg0DBeu7GiYw843JWkDVoXY7slEpHTOigIBnfD6hD87u5lSf4cJMfDIiX6UQxNHGEqCqV+ZmRmohxffzjrweTinoNEeAN40psdg7vWGPeuOdv8yDn/yf2wl5dLQiGazmVd8Rq0Y5JO9zwp81p7a/p+crbB6mNzvSmwutBse0drrzDnWqzHnRy3cWpe+zMBPJncg0LKYdNTsq4jVvlQD6jpwb28ubDVRZoKqSVYM8ZzfOa4Q3KMf880DaDwkvN6KdDCr6o+kP/7wDde7O7Tc5NwzSCuvJvDZKeg0wdx83YbQq6yoAH5tEapSA3pzf7rEOJ+LfOGKROlXRJxq+kzwfOPGcLoc=
  template:
    metadata:
      name: palworld-rcon
      namespace: palworld
