---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: ows-encryption-key
    namespace: rows
spec:
    encryptedData:
        encryption-key: AgAohwAj/BuxMw+FtBaeyPkKasEmbCSWTwGZcRcZg3ie5E2L2VB5vZGChLD2tMzaKphdmscbbOocqrH/Be+Jdp0UnPS/laWE1u8FR6M1klIdRcPNwZ7Oj4uT1CHbu0rv1RvWddndmx0rzKPHXKHGtjzf/DhtrFaHLUTVUQdiKn9QuXvlxSOyECxpcoDyB5Z9/ny80BNHh7ydI900JPTABW+AqNxUtn81boKpGp4wVWvzSc1706brLGrbKYiswg4GcZkcBV+phG69GK7m5e8b4iGK7sB+RETmw9MkJ1sWcLzIK6SF50SHo0HQovqKRePpp0xpKVNZRS36Ke7nzFKAn0uhkLycs5x+h0rPcjQS7RKPjCwCHEDquA1bhU5/PQzWIUi+Ug7fh0n6eXRMgPEtRbItndpO1Mmv/zVtVWWxJo+HaCkS+dAghlwHv+Cygu48O2l2b0Ns44EKcI6Ewj/gJG+WMP9wwokvn6M0ZtvZ2GjP+7btjQx5jQLlindhFqlE48cWAKcMK2xSCBK0cNBa7OnGOVKliEJev470EFpf0oNSUCwvk/oBLXSefh8+FrWvNiX67k/sBG3mpyLJJWIN50RzSpGEXeWqfNDY5aipy8ur0LPidsJBx1HlWjWEP5tvpe4+/yoJ+ZRyPMdbgTHxtfPK+lE0BK0y522AMZfP59hdaV7JjxOG1HhyusSJ7yLsSMwn/kqlOatwo7Iqh+wyVbRs/J9b3S+s2vgbYcc2dkS+g6WKmNid7/s0mg0PAAgp+Lwgs2cM4sZwnDX67Evx/5gV
    template:
        metadata:
            name: ows-encryption-key
            namespace: rows
