#!/bin/bash

echo "[STARTING] : Fudster"
echo "[ACTION] : AutoStart | Home -> $HOME Display -> $DISPLAY"

if [ ! -f $HOME/.Xauthority ]; then
    touch $HOME/.Xauthority
    chown abc:abc $HOME/.Xauthority
fi

export DISPLAY=${DISPLAY:-:1}

python3 /usr/local/bin/app/main.py --host 0.0.0.0 --port 8086 --ws-ping-interval 25 --ws-ping-timeout 5 | tee -a /usr/local/bin/app/uvicorn.log &

# Wait for 5 seconds before sending the curl request
sleep 5

# Make a GET request to start Runelite
curl -X GET "http://localhost:8086/start-runelite"