#!/bin/bash

echo "[STARTING] : kbveATLASv1.42"
echo "[ACTION] : AutoStart | Home -> $HOME Display -> $DISPLAY"

if [ ! -f $HOME/.Xauthority ]; then
    touch $HOME/.Xauthority
    chown abc:abc $HOME/.Xauthority
fi

# Set the DISPLAY environment variable to :1 if it's not already set
export DISPLAY=${DISPLAY:-:1}

. ~/.venv/bin/activate && DISPLAY=$DISPLAY poetry run uvicorn main:app --host 0.0.0.0 --port 8086 --ws-ping-interval 25 --ws-ping-timeout 5 | tee -a uvicorn.log &
