[package]
name = "agones-palworld-relay"
authors = ["kbve", "h0lybyte"]
version = "0.0.1"
edition = "2021"
rust-version.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
axum = { version = "0.8", default-features = false, features = [
    "http1",
    "json",
    "tokio",
] }
thiserror = "2"
tokio = { workspace = true, features = ["default", "macros", "rt-multi-thread", "fs", "io-util", "sync", "time", "signal", "net"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["default", "env-filter"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
    "json",
] }
chrono = { workspace = true, features = ["clock", "serde"] }
jedi = { path = "../../../../packages/rust/jedi", features = ["clickhouse"] }
tokio-rustls = { workspace = true, features = ["ring"] }
webpki-roots = { workspace = true }
rustls = { workspace = true, features = ["ring", "std", "tls12"] }
