apiVersion: v1
kind: ServiceAccount
metadata:
    name: angelscript-external-secrets
    namespace: angelscript
    labels:
        app: angelscript
        component: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: angelscript-read-github-token
    namespace: arc-systems
rules:
    - apiGroups: ['']
      resources: ['secrets']
      resourceNames: ['github-arc-token']
      verbs: ['get']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: angelscript-read-github-token
    namespace: arc-systems
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: angelscript-read-github-token
subjects:
    - kind: ServiceAccount
      name: angelscript-external-secrets
      namespace: angelscript
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
    name: arc-systems-secret-store
    namespace: angelscript
    labels:
        app: angelscript
        component: external-secrets
spec:
    provider:
        kubernetes:
            auth:
                serviceAccount:
                    name: angelscript-external-secrets
            remoteNamespace: arc-systems
            server:
                url: 'https://kubernetes.default.svc'
                caProvider:
                    key: ca.crt
                    name: kube-root-ca.crt
                    namespace: kube-system
                    type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: github-arc-token
    namespace: angelscript
    labels:
        app: angelscript
        component: external-secrets
spec:
    refreshInterval: 1h
    secretStoreRef:
        kind: SecretStore
        name: arc-systems-secret-store
    target:
        name: github-arc-token
        creationPolicy: Owner
        template:
            engineVersion: v2
            data:
                github_token: '{{ .token }}'
    data:
        - secretKey: token
          remoteRef:
              key: github-arc-token
              property: github_token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: angelscript-read-vpn-wireguard
    namespace: kasm
rules:
    - apiGroups: ['']
      resources: ['secrets']
      resourceNames: ['vpn-wireguard']
      verbs: ['get']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: angelscript-read-vpn-wireguard
    namespace: kasm
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: angelscript-read-vpn-wireguard
subjects:
    - kind: ServiceAccount
      name: angelscript-external-secrets
      namespace: angelscript
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
    name: kasm-secret-store
    namespace: angelscript
    labels:
        app: angelscript
        component: external-secrets
spec:
    provider:
        kubernetes:
            auth:
                serviceAccount:
                    name: angelscript-external-secrets
            remoteNamespace: kasm
            server:
                url: 'https://kubernetes.default.svc'
                caProvider:
                    key: ca.crt
                    name: kube-root-ca.crt
                    namespace: kube-system
                    type: ConfigMap
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: vpn-wireguard
    namespace: angelscript
    labels:
        app: angelscript
        component: external-secrets
spec:
    refreshInterval: 1h
    secretStoreRef:
        kind: SecretStore
        name: kasm-secret-store
    target:
        name: vpn-wireguard
        creationPolicy: Owner
    dataFrom:
        - extract:
              key: vpn-wireguard
