apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: angelscript-network
    namespace: angelscript
    labels:
        app: angelscript
spec:
    podSelector:
        matchLabels:
            app: angelscript
    policyTypes:
        - Ingress
        - Egress
    ingress:
        - ports:
              - port: 7777
                protocol: UDP
              - port: 7777
                protocol: TCP
              - port: 27015
                protocol: UDP
              - port: 15000
                protocol: UDP
    egress:
        - ports:
              - port: 53
                protocol: UDP
              - port: 53
                protocol: TCP
        - ports:
              - port: 443
                protocol: TCP
        - ports:
              - port: 80
                protocol: TCP
        - to:
              - podSelector:
                    matchLabels:
                        app: gluetun-builder-egress
          ports:
              - port: 8888
                protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: gluetun-builder-egress
    namespace: angelscript
    labels:
        app: gluetun-builder-egress
spec:
    podSelector:
        matchLabels:
            app: gluetun-builder-egress
    policyTypes:
        - Ingress
        - Egress
    ingress:
        - from:
              - podSelector:
                    matchLabels:
                        app: angelscript
          ports:
              - port: 8888
                protocol: TCP
        - ports:
              - port: 9999
                protocol: TCP
    egress:
        - ports:
              - port: 51820
                protocol: UDP
              - port: 443
                protocol: UDP
              - port: 1194
                protocol: UDP
        - ports:
              - port: 53
                protocol: UDP
              - port: 53
                protocol: TCP
        - ports:
              - port: 443
                protocol: TCP
