apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: windows-builder-rootdisk
    namespace: angelscript
    labels:
        app: angelscript
        component: windows-builder
        kbve.com/category: application
        kbve.com/stack: core
        kbve.com/managed-by: argocd
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 300Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
    name: windows-builder
    namespace: angelscript
    labels:
        app: angelscript
        component: windows-builder
spec:
    runStrategy: Manual
    template:
        metadata:
            labels:
                app: angelscript
                component: windows-builder
                kubevirt.io/domain: windows-builder
        spec:
            evictionStrategy: LiveMigrate
            domain:
                cpu:
                    cores: 8
                    sockets: 1
                    threads: 1
                devices:
                    disks:
                        - name: rootdisk
                          disk:
                              bus: virtio
                          bootOrder: 1
                        - name: iso
                          cdrom:
                              bus: sata
                          bootOrder: 2
                        - name: shared-storage
                          disk:
                              bus: virtio
                    interfaces:
                        - name: default
                          masquerade: {}
                    inputs:
                        - type: tablet
                          bus: usb
                          name: tablet
                features:
                    acpi: {}
                    hyperv:
                        relaxed: {}
                        vapic: {}
                        spinlocks:
                            spinlocks: 8191
                clock:
                    utc: {}
                    timer:
                        hpet:
                            present: false
                        pit:
                            tickPolicy: delay
                        rtc:
                            tickPolicy: catchup
                        hyperv: {}
                machine:
                    type: q35
                memory:
                    guest: 16Gi
                resources:
                    requests:
                        memory: 16Gi
                        cpu: '8'
                    limits:
                        memory: 20Gi
                        cpu: '10'
            networks:
                - name: default
                  pod: {}
            terminationGracePeriodSeconds: 60
            volumes:
                - name: rootdisk
                  persistentVolumeClaim:
                      claimName: windows-builder-rootdisk
                - name: iso
                  dataVolume:
                      name: windows-server-builder-iso
                - name: shared-storage
                  persistentVolumeClaim:
                      claimName: builder-shared-storage
