apiVersion: batch/v1
kind: Job
metadata:
    name: ingress-nginx-admission-create
    namespace: ingress-nginx
    annotations:
        'helm.sh/hook': pre-install,pre-upgrade
        'helm.sh/hook-weight': '-5'
        'helm.sh/hook-delete-policy': before-hook-creation,hook-succeeded
        'argocd.argoproj.io/hook': Skip
