apiVersion: v1
kind: Service
metadata:
  name: discordsh-service
  namespace: discordsh
  labels:
    app: discordsh
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: discordsh
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4321
