apiVersion: v1
kind: ServiceAccount
metadata:
    name: discordsh-external-secrets
    namespace: discordsh
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
    name: discordsh-supabase-secret-store
    namespace: discordsh
spec:
    provider:
        kubernetes:
            remoteNamespace: kilobase
            auth:
                serviceAccount:
                    name: discordsh-external-secrets
                    namespace: discordsh
            server:
                url: https://kubernetes.default.svc
                caProvider:
                    type: ConfigMap
                    name: kube-root-ca.crt
                    key: ca.crt
                    namespace: kube-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: discordsh-supabase-secrets
    namespace: discordsh
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: discordsh-supabase-secret-store
        kind: SecretStore
    target:
        name: discordsh-supabase-shared
        creationPolicy: Owner
        template:
            engineVersion: v2
            data:
                service-role-key: '{{ .servicekey }}'
    data:
        - secretKey: servicekey
          remoteRef:
              key: supabase-jwt
              property: service-key
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
    name: discordsh-n8n-hmac-store
    namespace: discordsh
spec:
    provider:
        kubernetes:
            remoteNamespace: n8n
            auth:
                serviceAccount:
                    name: discordsh-external-secrets
                    namespace: discordsh
            server:
                url: https://kubernetes.default.svc
                caProvider:
                    type: ConfigMap
                    name: kube-root-ca.crt
                    key: ca.crt
                    namespace: kube-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: discordsh-n8n-hmac
    namespace: discordsh
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: discordsh-n8n-hmac-store
        kind: SecretStore
    target:
        name: discordsh-n8n-hmac
        creationPolicy: Owner
        template:
            engineVersion: v2
            data:
                N8N_HMAC_SECRET: '{{ .hmac }}'
    data:
        - secretKey: hmac
          remoteRef:
              key: discordsh-n8n-hmac
              property: N8N_HMAC_SECRET
