apiVersion: v1
kind: ServiceAccount
metadata:
    name: discordsh-sa
    namespace: discordsh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: discordsh-redis-access
    namespace: redis
rules:
    - apiGroups: ['']
      resources: ['services', 'endpoints']
      verbs: ['get', 'list']
    - apiGroups: ['']
      resources: ['secrets']
      resourceNames: ['redis-auth']
      verbs: ['get']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: discordsh-redis-access-binding
    namespace: redis
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: discordsh-redis-access
subjects:
    - kind: ServiceAccount
      name: discordsh-external-secrets
      namespace: discordsh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: discordsh-supabase-access
    namespace: kilobase
rules:
    - apiGroups: ['']
      resources: ['secrets']
      resourceNames: ['supabase-jwt']
      verbs: ['get']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: discordsh-supabase-access-binding
    namespace: kilobase
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: discordsh-supabase-access
subjects:
    - kind: ServiceAccount
      name: discordsh-external-secrets
      namespace: discordsh
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: allow-discordsh-to-redis
    namespace: redis
spec:
    podSelector:
        matchLabels:
            app.kubernetes.io/name: redis
    policyTypes:
        - Ingress
    ingress:
        - from:
              - namespaceSelector:
                    matchLabels:
                        name: discordsh
              - podSelector:
                    matchLabels:
                        app: discordsh
          ports:
              - protocol: TCP
                port: 6379
