apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: arc-runners
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-wave: '1'
        kbve.com/source-path: kube/github/runners
        kbve.com/manifest-path: kube/github/runners
        kbve.com/application-file: kube/github/runners/application.yaml
        kbve.com/managed-by: argocd
        kbve.com/schema-version: v1
        kbve.com/category: ci-cd
        kbve.com/stack: github-actions
spec:
    project: default
    sources:
        - repoURL: ghcr.io/actions/actions-runner-controller-charts
          targetRevision: 0.9.3
          chart: gha-runner-scale-set
          helm:
              releaseName: arc-runner-set
              valueFiles:
                  - $values/apps/kube/github/runners/manifests/values.yaml
        - repoURL: ghcr.io/actions/actions-runner-controller-charts
          targetRevision: 0.9.3
          chart: gha-runner-scale-set
          helm:
              releaseName: arc-runner-set-kbve
              valueFiles:
                  - $values/apps/kube/github/runners/manifests/values-kbve.yaml
        - repoURL: ghcr.io/actions/actions-runner-controller-charts
          targetRevision: 0.9.3
          chart: gha-runner-scale-set
          helm:
              releaseName: arc-runner-ue
              valueFiles:
                  - $values/apps/kube/github/runners/manifests/values-ue.yaml
        - repoURL: ghcr.io/actions/actions-runner-controller-charts
          targetRevision: 0.9.3
          chart: gha-runner-scale-set
          helm:
              releaseName: arc-runner-ue-win
              valueFiles:
                  - $values/apps/kube/github/runners/manifests/values-ue-win.yaml
        - repoURL: ghcr.io/actions/actions-runner-controller-charts
          targetRevision: 0.9.3
          chart: gha-runner-scale-set
          helm:
              releaseName: arc-runner-ue-mac
              valueFiles:
                  - $values/apps/kube/github/runners/manifests/values-ue-mac.yaml
        - repoURL: https://github.com/kbve/kbve
          targetRevision: main
          ref: values
        - repoURL: https://github.com/kbve/kbve
          targetRevision: main
          path: apps/kube/github/runners/manifests
    destination:
        server: https://kubernetes.default.svc
        namespace: arc-runners
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
        syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
        retry:
            limit: 3
            backoff:
                duration: 5s
                factor: 2
                maxDuration: 3m
