apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: mail
    namespace: argocd
    annotations:
        kbve.com/source-path: kube/mail
        kbve.com/manifest-path: apps/kube/mail/manifest
        kbve.com/application-file: kube/mail/application.yaml
        kbve.com/managed-by: argocd
        kbve.com/schema-version: v1
        kbve.com/category: application
        kbve.com/stack: core
spec:
    project: default
    source:
        repoURL: https://github.com/KBVE/kbve
        targetRevision: HEAD
        path: apps/kube/mail/manifest
    destination:
        server: https://kubernetes.default.svc
        namespace: mail
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
            - PrunePropagationPolicy=foreground
            - PruneLast=true
            - RespectIgnoreDifferences=true
            - Replace=false
