use bevy::prelude::*;

use super::scene_objects::{FlowerArchetype, MushroomKind, RockKind};

// Re-export bevy_inventory types that the rest of the game uses.
pub use bevy_inventory::{
    Inventory, InventoryFullEvent, InventoryPlugin, ItemStack, LootEvent,
    get_inventory_snapshot_json,
};

// Re-export the proto-driven item type as the game's canonical ItemKind.
pub use bevy_items::inventory_adapter::ProtoItemKind as ItemKind;

// Re-export ItemDb and init for startup.
pub use bevy_items::inventory_adapter::init_item_db;
pub use bevy_items::{BevyItemsPlugin, ItemDb};

// ── Baked itemdb ───────────────────────────────────────────────────────
// Generated by `node scripts/sync-itemdb.mjs` before each build.
// Contains all item definitions from the Astro itemdb content collection.
const BAKED_ITEMDB_JSON: &str = include_str!("../data/itemdb.json");

/// Startup system: parse the baked itemdb JSON, insert it as a Bevy resource,
/// and initialize the global reference so ProtoItemKind can resolve names/stacks.
pub fn load_baked_itemdb(mut commands: Commands) {
    match ItemDb::from_json(BAKED_ITEMDB_JSON) {
        Ok(db) => {
            let count = db.len();
            // Leak into 'static so the global OnceLock reference stays valid
            // for ProtoItemKind lookups across the entire app lifetime.
            let db_static: &'static ItemDb = Box::leak(Box::new(db));
            init_item_db(db_static);
            info!("[itemdb] loaded {count} items from baked itemdb.json");
        }
        Err(e) => {
            warn!(
                "[itemdb] failed to parse baked itemdb.json: {e:?} — inventory will use fallback names"
            );
        }
    }
    // Note: BevyItemsPlugin already inserted an empty ItemDb resource.
    // ProtoItemKind resolves via the global static ref, not the Bevy resource.
}

// ── Item ref constants ─────────────────────────────────────────────────
// These match the `ref` field in the itemdb MDX files.

pub const ITEM_LOG: &str = "log";
pub const ITEM_STONE: &str = "stone";
pub const ITEM_MOSSY_STONE: &str = "mossy-stone";
pub const ITEM_COPPER_ORE: &str = "copper-ore";
pub const ITEM_IRON_ORE: &str = "iron-ore";
pub const ITEM_CRYSTAL_ORE: &str = "crystal-ore";
pub const ITEM_TULIP: &str = "tulip";
pub const ITEM_DAISY: &str = "daisy";
pub const ITEM_LAVENDER: &str = "lavender";
pub const ITEM_BELLFLOWER: &str = "bellflower";
pub const ITEM_WILDFLOWER: &str = "wildflower";
pub const ITEM_SUNFLOWER: &str = "sunflower";
pub const ITEM_ROSE: &str = "rose";
pub const ITEM_CORNFLOWER: &str = "cornflower";
pub const ITEM_ALLIUM: &str = "allium";
pub const ITEM_BLUE_ORCHID: &str = "blue-orchid";
pub const ITEM_PORCINI: &str = "porcini";
pub const ITEM_CHANTERELLE: &str = "chanterelle";
pub const ITEM_FLY_AGARIC: &str = "fly-agaric";

// ── Conversion helpers ─────────────────────────────────────────────────
// Map game-world object types to their proto item ref.

pub fn item_from_rock_kind(kind: &RockKind) -> ItemKind {
    ItemKind::from_ref(match kind {
        RockKind::Boulder => ITEM_STONE,
        RockKind::MossyRock => ITEM_MOSSY_STONE,
        RockKind::OreCopper => ITEM_COPPER_ORE,
        RockKind::OreIron => ITEM_IRON_ORE,
        RockKind::OreCrystal => ITEM_CRYSTAL_ORE,
    })
}

pub fn item_from_flower_archetype(arch: &FlowerArchetype) -> ItemKind {
    ItemKind::from_ref(match arch {
        FlowerArchetype::Tulip => ITEM_TULIP,
        FlowerArchetype::Daisy => ITEM_DAISY,
        FlowerArchetype::Lavender => ITEM_LAVENDER,
        FlowerArchetype::Bell => ITEM_BELLFLOWER,
        FlowerArchetype::Wildflower => ITEM_WILDFLOWER,
        FlowerArchetype::Sunflower => ITEM_SUNFLOWER,
        FlowerArchetype::Rose => ITEM_ROSE,
        FlowerArchetype::Cornflower => ITEM_CORNFLOWER,
        FlowerArchetype::Allium => ITEM_ALLIUM,
        FlowerArchetype::BlueOrchid => ITEM_BLUE_ORCHID,
    })
}

pub fn item_from_mushroom_kind(kind: &MushroomKind) -> ItemKind {
    ItemKind::from_ref(match kind {
        MushroomKind::Porcini => ITEM_PORCINI,
        MushroomKind::Chanterelle => ITEM_CHANTERELLE,
        MushroomKind::FlyAgaric => ITEM_FLY_AGARIC,
    })
}
