import { test, expect } from '@playwright/test';
import { ALL_ROUTES } from './helpers/routes';
import { getMeta, getMetaProperty } from './helpers/env';

test.describe('SEO metadata', () => {
	for (const route of ALL_ROUTES) {
		test(`${route.label} has a non-empty title and description`, async ({
			page,
		}) => {
			await page.goto(route.path);
			await expect(page).toHaveTitle(/.+/);
			const description = await getMeta(page, 'description');
			expect(description ?? '').not.toHaveLength(0);
		});
	}

	test('homepage exposes Open Graph tags', async ({ page }) => {
		await page.goto('/');
		expect(await getMetaProperty(page, 'og:title')).toBeTruthy();
		expect(await getMetaProperty(page, 'og:type')).toBeTruthy();
	});

	test('homepage declares a canonical URL', async ({ page }) => {
		await page.goto('/');
		await expect(page.locator('link[rel="canonical"]')).toHaveAttribute(
			'href',
			/https?:\/\//,
		);
	});

	test('document declares a language', async ({ page }) => {
		await page.goto('/');
		await expect(page.locator('html')).toHaveAttribute('lang', /.+/);
	});

	test('sitemap index is served (production build only)', async ({
		page,
	}) => {
		const response = await page.goto('/sitemap-index.xml');
		test.skip(
			response?.status() === 404,
			'sitemap is only generated by the production build, not astro dev',
		);
		expect(response?.status()).toBe(200);
		expect(await response?.text()).toMatch(/sitemapindex|urlset/);
	});
});
