// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
#[derive(Queryable, Debug)]
pub struct Apikey {
    pub id: u64,
    pub uuid: Option<i32>,
    pub permissions: Option<String>,
    pub keyhash: Option<String>,
    pub label: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct Appwrite {
    pub id: u64,
    pub uuid: Option<i32>,
    pub appwrite_endpoint: Option<String>,
    pub appwrite_projectid: Option<String>,
    pub apppwrite_api_key: Option<String>,
    pub version: Option<String>,
    pub created_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Auth {
    pub id: u64,
    pub uuid: Option<i32>,
    pub email: Option<String>,
    pub hash: String,
    pub salt: String,
    pub password_reset_token: Option<String>,
    pub password_reset_expiry: Option<NaiveDateTime>,
    pub verification_token: Option<String>,
    pub verification_expiry: Option<NaiveDateTime>,
    pub status: Option<i32>,
    pub last_login_at: Option<NaiveDateTime>,
    pub failed_login_attempts: Option<i32>,
    pub lockout_until: Option<NaiveDateTime>,
    pub two_factor_secret: Option<String>,
    pub recovery_codes: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct N8n {
    pub id: u64,
    pub uuid: Option<i32>,
    pub webhook: Option<String>,
    pub permissions: Option<String>,
    pub keyhash: Option<String>,
    pub label: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct Profile {
    pub id: u64,
    pub name: Option<String>,
    pub bio: Option<String>,
    pub unsplash: Option<String>,
    pub github: Option<String>,
    pub instagram: Option<String>,
    pub discord: Option<String>,
    pub uuid: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: u64,
    pub username: Option<String>,
    pub role: Option<i32>,
    pub reputation: Option<i32>,
    pub exp: Option<i32>,
    pub created_at: NaiveDateTime,
}

