apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-bot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kbve/kbve
    targetRevision: HEAD
    path: apps/kube/notification-bot/manifests
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: discord
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true