apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: forgejo-redis
    namespace: forgejo
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: kubernetes-secret-store
        kind: ClusterSecretStore
    target:
        name: forgejo-redis
        creationPolicy: Owner
    dataFrom: []
    data:
        - secretKey: password
          remoteRef:
              key: redis-auth
              namespace: redis
              property: redis-password
              metadataPolicy: None
