apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: forgejo-db
    namespace: forgejo
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: kubernetes-secret-store
        kind: ClusterSecretStore
    target:
        name: forgejo-db
        creationPolicy: Owner
    dataFrom: []
    data:
        - secretKey: password
          remoteRef:
              key: supabase-cluster-app
              namespace: kilobase
              property: password
              metadataPolicy: None
