apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - httproute.yaml
    - sealed-admin.yaml
    - rbac.yaml
    - forgejo-externalsecret.yaml
    # Future: actions-runner.yaml
