apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ows-server-build
    namespace: arc-runners
    labels:
        app.kubernetes.io/part-of: ows
        app.kubernetes.io/component: dedicated-server
        kbve.com/category: ci-cd
        kbve.com/stack: github-actions
        kbve.com/managed-by: argocd
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: longhorn
    resources:
        requests:
            storage: 50Gi
